### ISSUE TITLE
XQFO Code in the Rules sections

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#1000]
In #978, it’s being discussed what is the best language for presenting code in the Rules sections of the XQFO specification. Currently, XPath is used for compact equivalencies, for example…

```xquery
(: array:size :)
count(array:members($array))

(: fn:remove :)
$input[not(position() = $positions)].
```

...while XQuery is used for more complex expressions, including function declarations, or when the XPath representation would be syntactically more complex. Examples:

```xquery
(: fn:deep-equal :)
declare function equal-strings(
  $string1   as xs:string,
  $string2   as xs:string, 
  $collation as xs:string,
  $options   as map(*)
) as xs:boolean {
  let $n1 := if ($options?whitespace = "normalize"))
             then normalize-unicode(?, $options?normalization-form) 
             else identity#1
  let $n2 := if ($options?normalize-space)
             then normalize-space#1 
             else identity#1               
  return compare($n1($n2($string1)), $n1($n2($string2)), $collation) eq 0    
}

(: fn:index-where :)
for $item at $pos in $input
where $predicate($item, $pos)
return $pos

(: …flatten, fold-left, while-do, others :)
```

Finally, we have many cases in which XPath/XQuery code is omitted, either because the presented feature is basic enough, because the equivalent code would get too complicated, or (e.g., for `fn:doc`) because it does not provide means to express the feature.

We should strive for consistency and decide which language(s) the majority of us believes is the best choice…

1. XPath & XQuery (what we currently have)
2. XPath only
3. XPath, XQuery and XSLT (whatever seems most appropriate)
4. Other pseudocode
5. Don’t use pseudocode at all  if it is too complex to be represented with moderately simple XPath code

**Comment by ChristianGruen** [comment]
Thanks to @dnovatchev's discussion, I had the honor of opening issue #1000.

**Comment by michaelhkay** [comment]
I think it might be useful, if only for our own editorial sanity, if we classified functions, and perhaps syntactic constructs, as intrinsic or extrinsic. Extrinsic functions and constructs should be specified in terms of a "lexical" equivalence that relies only on intrinsic constructs. For example, `node-name()` is intrinsic; `local-name()`, namespace-uri()`, and `name()` are extrinsic.

To avoid too much discontinuity from current practice, extrinsic functions should be defined as follows in order of preference:

(a) where possible, an XPath expression that can be used as the body of the function: for example `local-name($node)` is `local-name-from-QName( node-name($node))`.

(b) if that's not possible or convenient, use an XQuery expression.

(c) if the equivalent is recursive or requires supporting functions, express the equivalence using XQuery function declarations. Unless we can come up with a more readable way of expressing recursive functions in XPath, we should avoid them.

We should ideally have some way of checking that we haven't introduced any circularity into the specification.

**Comment by dnovatchev** [comment]
> I think it might be useful, if only for our own editorial sanity, if we classified functions, and perhaps syntactic constructs, as intrinsic or extrinsic. Extrinsic functions and constructs should be specified in terms of a "lexical" equivalence that relies only on intrinsic constructs. For example, `node-name()` is intrinsic; `local-name()`, namespace-uri()`, and `name()` are extrinsic.
> 
> To avoid too much discontinuity from current practice, extrinsic functions should be defined as follows in order of preference:
> 
> (a) where possible, an XPath expression that can be used as the body of the function: for example `local-name($node)` is `local-name-from-QName( node-name($node))`.

👍 

> 
> (b) if that's not possible or convenient, use an XQuery expression.


> 
> (c) if the equivalent is recursive or requires supporting functions, express the equivalence using XQuery function declarations. Unless we can come up with a more readable way of expressing recursive functions in XPath, we should avoid them.

Convenience is a rather subjective term.

We could have an introductory section which explains how XPath code is used in the Rules and which provides a simple example of recursion in XPath.

We can precede a recursive function definition with a suitable comment, such as:

```xq
(: Recursive function $factorial defined with the help of $factorial-inner :)
```


We shouldn't suppose that all implementors know XQuery well and any such assumption may really discriminate and be unfair to some potential implementors.

Some implementors may even have no XQuery processor available, not to speak about an XQuery 4.0 processor.

**Comment by ChristianGruen** [comment]
> We shouldn't suppose that all implementors know XQuery well and any such assumption may really discriminate and be unfair to some potential implementors.

Until someone proves me wrong, I feel safe to say that everyone who’s smart enough to write an XPath 4.0 implementation will certainly be smart enough to understand some basic XQuery or XSLT code – let alone function declarations that basically have the same syntax as the function signatures in the XQFO spec.

No matter which language or pseudo-code we use, we should avoid syntactical constructs that don’t focus on the actual task, such as self-referencing function arguments.

**Comment by dnovatchev** [comment]
> Until someone proves me wrong, I feel safe to say that everyone who’s smart enough to write an XPath 4.0 implementation will certainly be smart enough to understand some basic XQuery or XSLT code – let alone function declarations that basically have the same syntax as the function signatures in the XQFO spec.
> 
> No matter which language or pseudo-code we use, we should avoid syntactical constructs that don’t focus on the actual task, such as self-referencing function arguments. Just because something can be done doesn’t mean it should be done.

Said the author of an XQuery processor ...

**Comment by ChristianGruen** [comment]
> Said the author of an XQuery processor ...

…who included XSLT in the reply, and added a second comment on conciseness, which is more important than the used language.

The discussion is getting absurd. This is the current XQuery code for `fn:flatten` in the spec:

```xquery
declare function flatten(
  $input as item()*
) as item()* {
  for $item in $input
  return if ($item instance of array(*)) then flatten(array:values($item)) else $item
};
```

An equivalent XPath version would be:

```xquery
let $flatten-inner := function(
  $input as item()*,
  $self  as function(*)
) as item()* {
  for $item in $input
  return if ($item instance of array(*)) then $self(array:values($item), $self) else $item  
}
let $flatten := function(
  $input as item()*
) as item()* {
  $flatten-inner($input, $flatten-inner)
}
return ...
```

Only a minority of users would be able to judge that the second version is XPath at all.

**Comment by ChristianGruen** [comment]
I’ve added another suggestion, as a fallback if we shouldn’t manage to agree on one of the other alternatives:

> 5. Don’t use pseudocode at all  if it is too complex to be represented with moderately simple XPath code

**Comment by dnovatchev** [comment]
> I’ve added another suggestion, as a fallback if we shouldn’t manage to agree on one of the other alternatives:
> 
> > 5. Don’t use pseudocode at all  if it is too complex to be represented with moderately simple XPath code

Quite a few issues with this:

1. Such a rule is obviously subjective - what is "too-complex" for one person may be "normal" for another one.

2. This will in certain cases prohibit the provision of **_executable code_** - that is an [**_oracle_**](https://en.wikipedia.org/wiki/Test_oracle) for the results of the function. Having an oracle is immensely better than not having one. It simply eliminates the possibility of one implementor understanding and interpreting the rules in a different way than other implementors, resulting in different implementations of the function producing different results for some calls with the same arguments. Even if we have a thousand of tests, having an oracle is much better, as it covers **_all_** infinite number of possible tests

3. When the provided code is considered "too-complex", its readability can always be enhanced by providing comments within the code, or adding additional explanation in the Rules text. The code still remains the same - authoritative and precise. Which cannot be said at all about **verbal-only rules that can be interpreted in a different way by different readers**, and whose correctness, completeness and lack of ambiguity or of controversial statements cannot be proven at all.

I think point 3. above is especially important. It tells us that we can always add more explanations without sacrificing the oracle code.

**Comment by michaelhkay** [comment]
I think my experience is that if the "oracle" requires more than about 10 lines of code, there's a strong danger of it being incorrect or imprecise: for example, making unwarranted assumptions about overflow behaviour. In addition, the primary purpose of the specification is to communicate clearly and precisely, and there comes a point where you can do that better in English than in complex code. So yes, it absolutely has to be subjective: deciding whether you're communicating clearly is a judgement call.

Generally my experience over my career has been that formalism, if taken to extremes, is counter-productive. The XQuery formal semantics was a good example of that. You end up with the situation where only a small elite tries to read the specification, which means it doesn't get widespread review, which means it has bugs. Oracles are useful, but only if they are sufficiently simple that the bugs stare out at you. They also need to be tested.

**Comment by dnovatchev** [comment]
> I think my experience is that if the "oracle" requires more than about 10 lines of code, there's a strong danger of it being incorrect or imprecise: for example, making unwarranted assumptions about overflow behaviour. In addition, the primary purpose of the specification is to communicate clearly and precisely, and there comes a point where you can do that better in English than in complex code. So yes, it absolutely has to be subjective: deciding whether you're communicating clearly is a judgement call.
> 
> Generally my experience over my career has been that formalism, if taken to extremes, is counter-productive. The XQuery formal semantics was a good example of that. You end up with the situation where only a small elite tries to read the specification, which means it doesn't get widespread review, which means it has bugs. Oracles are useful, but only if they are sufficiently simple that the bugs stare out at you. They also need to be tested.

Yes, so let us try to define "sufficiently simple"?

Some people say that the code should be contained in a single screen with no need for scrolling.

Other advise that the number of lines should not exceed 30 or 50.

There are also objective code complexity metrics and some are already used in popular IDEs - for example Visual Studio issues an error message if the [**_cyclomatic complexity_**](https://en.wikipedia.org/wiki/Cyclomatic_complexity) exceeds 50.

In all cases having such precise and objective criteria is better and more truly indicative than having the case someone tell you that they cannot understand the code.

Pupils at school need encouragement to learn, not acknowledgements that they cannot.

**Comment by dnovatchev** [comment]
> Generally my experience over my career has been that formalism, if taken to extremes, is counter-productive. The XQuery formal semantics was a good example of that. You end up with the situation where only a small elite tries to read the specification, 

We are not talking about that kind of formalism - rather about having a few lines - XPath expression that everybody can readily execute - even in their existing XPath processors. 

So it is not "only a small elite" - it is **_everyone_** can execute and test - with as many (unlimited number of) tests as they can come independently with.

>which means it doesn't get widespread review, which means it has bugs. Oracles are useful, but only if they are sufficiently simple that the bugs stare out at you. They also need to be tested.

Very good point. In case the results of some proposed tests are not what the Oracle produces, then we have immediately discovered a discrepancy - either in the proposed tests, or in the Oracle, or in our understanding of what the function does - and thus we can immediately rectify the problem, as opposed to the case where we do not have an Oracle and the problem remains unnoticed indefinitely.

**Comment by ChristianGruen** [comment]
I don’t think we’ll make any further progress here (unless someone wants to prepare a PR that unifies all existing code snippets), so I propose to close the issue.

**Comment by ndw** [comment]
The CG agreed to close this issue without further action at [meeting 079](https://qt4cg.org/meeting/minutes/2024/05-28.html).
