### ISSUE TITLE
Reinstate subsequence-before

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#1002]
There's a question on StackOverflow today:

https://stackoverflow.com/questions/77944304/

that makes me think dropping `subsequence-before` might have been a mistake (the replacement, `subsequence-where`, doesn't allow the end condition to be exclusive).

The question is how to find all the consecutive `list` elements that follow a given `para` element. That would be solved with `subsequence-before(following-sibling::*, fn{not(self::list)})`. Doing it with `subsequence-where` is much harder - you need to drop the final element in the result if it is not a `list` element, while also taking into account that the result might be empty.

I would like to propose reinstating subsequence-before; or perhaps inverting the predicate and naming it `subsequence-while()`, so it becomes `subsequence-while(following-sibling::*, fn{self::list})` assuming we accept the proposal in issue #919 to allow a callback predicate to use EBV.

**Comment by ChristianGruen** [comment]
…which reminds me again of the `take-while` and `drop-while` duo, which are offered by many other languages (and also in the proposal on generators, #716). `subsequence-while` and `subsequence-after` could be our alternatives.

I’d definitely prefer not to introduce the full range of 4 functions (with possibly 4 more array functions).
