### ISSUE TITLE
[XSLT] Need to say what happens when a capturing accumulator rule matches a non-element node

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#1013]
The option capture="yes" has been added to `xsl:accumulator-rule`; its purpose is to indicate that the entire subtree under an element is to be captured during streamed processing of the document, and is made available as an in-memory tree once the element end tag has been processed.

We need to say what happens when such a rule matches a node other than an element. I think it makes sense for the capture="yes" to be ignored, optionally with a warning.

**Comment by ndw** [comment]
Why is that better than just making the node available?

**Comment by michaelhkay** [comment]
The node is available anyway; saxon:capture is logically a no-op. The only question is, its presence suggests some kind of misunderstanding on the users' part, so should we flag it?

**Comment by Arithmeticus** [comment]
Someone who writes `<xsl:accumulator-rule match="node()[string-length(.) lt 5]" phase="end" capture="yes">` would not appreciate an error for matches on a text node, no?
