### ISSUE TITLE
Editorial comments on fn:parse-csv()

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#1016]
(a) The spec says:

> The first argument is CSV data, as defined in ..., in the form of a sequence of xs:string values.

But in fact, the argument is a single (optional) xs:string value, not a sequence.

(b) The spec says:

> If $csv is the empty sequence, implementations must return a parsed-csv-structure-record whose rows entry is the empty sequence.
> 
> If $csv is the empty sequence, but column name extraction has been requested, or explicit column names have been supplied, then the parsed-csv-structure-record returned by implementations must have a rows entry whose value is the empty sequence.

The second paragraph seems to add nothing to the first.

(c) And the phrase "_implementations must return XXX_" is unidiomatic. The normal form of words is "_the function returns XXX_".

(d) The grammar of the sentence "Handling of delimiters, and whitespace trimming, are handled using..." is inelegant.

(e) References to the record type names (such as parsed-csv-structure-record) should be hyperlinked.

**Comment by michaelhkay** [comment]
`csv-to-simple-rows()` seems a very clumsy name. Wouldn't `csv-to-array()` be clearer?

**Comment by ChristianGruen** [comment]
Related (#748):

1. The input argument should be named `$value` (in alignment with `fn:parse-xml`).
2. The input argument could be enhanced to `union(xs:string, xs:hexBinary, xs:base64Binary)?`
3. I would suggest adding `fn:csv-doc`.

**Comment by michaelhkay** [comment]
Also: with scan-left() and scan-right() we chose to return a sequence of arrays rather than an array of sequences. I don't feel strongly that one form is better than the other, but there is merit in consistency. The sequence-of-arrays is certainly easier to process for some use cases, for example to get all the distinct values in the second column you can write `distinct-values($result?2)` whereas with an array of sequences it would have to be something like `distinct-values(array:for-each($result, fn(){.[2])))`
