### ISSUE TITLE
Make argument of fn:void optional

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#1029]
If you want to supply a function that always returns an empty sequence, fn:void#0 would be useful; but currently there is no arity-zero variant.

Example: `map:build(...., combine:=fn:void#0)` returns a map in which any key that occurs more than once in the input is mapped to an empty sequence.

The first argument of `fn:void` should default to an empty sequence.

**Comment by apb2006** [comment]
I  have sometimes wanted a function that always returns true or false regardless of it's argument(s). Perhaps while struggling to debug something "HOF" y . 
If there is to be a `fn:void#0`, why not a `true#1` and `false#1`?

**Comment by michaelhkay** [comment]
>why not a true#1 and false#1

Because with the new arity-reducing function coercion, you can supply `true#0` or `false#0` in this situation.

**Comment by ChristianGruen** [comment]
> I have sometimes wanted a function that always returns true or false regardless of it's argument(s). Perhaps while struggling to debug something "HOF" y . If there is to be a `fn:void#0`, why not a `true#1` and `false#1`?

Good news: With the new [function coercion rules](https://qt4cg.org/specifications/xquery-40/xpath-40.html#id-function-coercion), it’s possible to pass on functions with a lower arity, making function calls like `filter(1 to 10, true#0)` legal.

**Comment by dnovatchev** [comment]
> If you want to supply a function that always returns an empty sequence, fn:void#0 would be useful; but currently there is no arity-zero variant.

Why would one need a function rather than just writing: `fn(){()}` ? Or just `empty-sequence#0` - assuming that this is the constructor function for the `empty-sequence()`  type? I think the last alternative is superior in readability and understandability than using fn:void#0

**Comment by dnovatchev** [comment]
In regards with the comment above, should we re-open this issue, or create a new issue?

**Comment by michaelhkay** [comment]
As a matter of process, I think that opening a new issue is generally better than reopening one that has already been closed. But if we're going to move this spec forwards to a conclusion, proposing to remove something that we have added solely on the grounds that you think it isn't needed isn't especially helpful. It's very hard to gather evidence about whether a feature is needed or not, but generally, an argument to add something should be based on evidence that it is needed, while an argument to remove something should be based on evidence that it causes a problem.

**Comment by dnovatchev** [comment]
> As a matter of process, I think that opening a new issue is generally better than reopening one that has already been closed. But if we're going to move this spec forwards to a conclusion, proposing to remove something that we have added solely on the grounds that you think it isn't needed isn't especially helpful. It's very hard to gather evidence about whether a feature is needed or not, but generally, an argument to add something should be based on evidence that it is needed, while an argument to remove something should be based on evidence that it causes a problem.

Yes, and the existing of **empty-sequence#0** tells us that **another function is not needed**.

Based on this, we shouldn't be tweaking another function to fill in this case, as this case already has a better solution.

**Comment by ChristianGruen** [comment]
> Yes, and the existing of **empty-sequence#0** tells us that **another function is not needed**.

Existing in what way?

**Comment by dnovatchev** [comment]
> > Yes, and the existing of **empty-sequence#0** tells us that **another function is not needed**.
> 
> Existing in what way?

Don't we have in XPath a constructor function for any existing type?

And `empty-sequence()` is one such type. Existing.

**Comment by ChristianGruen** [comment]
> Don't we have in XPath a constructor function for any existing type?

I’m not aware of those. Could you provide a pointer to the spec?

**Comment by dnovatchev** [comment]
> > Don't we have in XPath a constructor function for any existing type?
> 
> I’m not aware of those. Could you provide a pointer to the spec?

**https://qt4cg.org/pr/1027/xpath-functions-40/Overview.html#constructor-functions**

For all XML Schema types, and even for user-defined types there is a constructor-function with the same name as the type.

**Comment by michaelhkay** [comment]
empty-sequence() is not a schema type, nor is it a user-defined type, and it has no constructor function. We could change that, of course. However, using exactly the same syntax `empty-sequence()` as both a type name and a call on a constructor function could be syntactically problematic - note that none of the types ending in "()" such as `node()`, `item()`, `text()` currently have constructor functions.

**Comment by dnovatchev** [comment]
> empty-sequence() is not a schema type, nor is it a user-defined type, and it has no constructor function. We could change that, of course. However, using exactly the same syntax `empty-sequence()` as both a type name and a call on a constructor function could be syntactically problematic - note that none of the types ending in "()" such as `node()`, `item()`, `text()` currently have constructor functions.

We will not be writing `empty-sequence()` (which is said to be problematic) but just **`empty-sequence#0`**.

There is no syntactical problem here.

**Comment by michaelhkay** [comment]
The construct `empty-sequence#0` only works if there is a function named `empty-sequence` with arity zero (with namespace equal to the default function namespace) in the static context , and if there is such a function then `empty-sequence()` automatically becomes a legal function call.

**Comment by dnovatchev** [comment]
> The construct `empty-sequence#0` only works if there is a function named `empty-sequence` with arity zero (with namespace equal to the default function namespace) in the static context , and if there is such a function then `empty-sequence()` automatically becomes a legal function call.

Maybe we could think of adding constructor functions for the types ending in "()" such as node(), item(), text() that currently have no constructor functions.

Something like:

**`fn:make-node()`** , **`fn:make-empty-sequence()`**

**Comment by michaelhkay** [comment]
See also issue #573

**Comment by dnovatchev** [comment]
If we did have a function:

```xq
fn:const($val, $anyArg) { $val }
```
then a function that produces the empty sequence is simply:

**fn:const#2((), ?)**

Similarly:

**fn:const#2([], ?)**

or

**fn:const#2(map{}, ?)**

Do we have any other case for a function that must produce something empty?
