### ISSUE TITLE
allow pattern matches in axis expression

### ISSUE THREAD

**Issue by MarkNicholls** [qt4cg/qtspecs#1030]
There's a danger that this already exists, and that i dont know about it, but i dont think it does.

Consider this SO question.

https://stackoverflow.com/questions/78027093/selecting-preceding-cousins-inclusing-siblings

the questioner is writing this

`/root/level1/level2[@id='6']/preceding::level2[parent::level1[parent::root]][1]`

eeek...look at the nasty nested predicates

when he/she wants to write this

`/root/level1/level2[@id='6']/preceding::(root/level/level2)[1]`

there is an answer on the question which sort of shows how horrific the problem is in general.

(its a problem that crops up quite a lot for me)

**Comment by MarkNicholls** [comment]
maybe lets wait for the SO question to run its course, but it does strike me that the current axis syntax only really matches on 'leaves' not 'paths'

**Comment by michaelhkay** [comment]
I've put my solution to the "last preceding cousin" problem on StackOverflow as:

```
    let $this := .
    let $precedingCousins := (../../*/*)[. << $this]
    return $precedingCousins[last()]
```

One feature that has sometimes been mooted is "used-defined axes". An axis is really just a function from one node to a sequence of nodes, so in principle any function with signature `function(node()) as node()*` could be used as an axis, allowing

```
let $precedingCousins := fn($this){(../../*/*)[. << $this]}
return $x/precedingCousins::*[last()]
```

But it's not really very useful syntactic sugar, given the complexity.

**Comment by michaelhkay** [comment]
On the proposal to introduce XSLT pattern matching capability to XPath, that's certainly something I have considered from time to time, but it's a lot of heavy machinery and I'm not sure the benefits repay the costs.

**Comment by MarkNicholls** [comment]
to be honest I dont really use axes except for ancestor really...I find preceding mind boggling when you have a sequence order and a seperate document order, and whilst preceding-sibling is too narrow for most purposes, preceding (and following) are too broad.

**Comment by MarkNicholls** [comment]
let me use this opportunity for a bit of training...
I dont understand 

`$x/precedingCousins::*[last()]`

$x is some sequence

`precedingCousins::`

is?
you've mangled a function into an axis name

and `*[last()]` is the obvious

**Comment by michaelhkay** [comment]
>I dont understand

Not surprising, it's just a sketch, not a specification. The basic reasoning is that an axis is just a special kind of function, and you should therefore be able to use any suitable function as if it were an axis.

**Comment by ndw** [comment]
The CG decided to close this issue without further action at [meeting 067](https://qt4cg.org/meeting/minutes/2024/02-27.html).
