### ISSUE TITLE
Add default values for parameters in constructor functions for records

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#1035]
We have added implicit constructor functions for named record types; we should allow the parameters in these functions to take explicit default values.

For example

`declare item type my:complex as record(r as xs:double, i as xs:double := 0)`

At the same time we might consider introducing fixed values, for example

`declare item type my:rectangle as record(height, width, area ::= function($rect){$rect?height * $rect?width))`

in which (a) the area function must NOT be supplied as an argument to the constructor function call, and (b) a map in which the area field is different from this fixed value is not a valid instance of the `my:rectangle` record type.

**Comment by ChristianGruen** [comment]
Looks good and simple.

Do you think that it would make sense to change the syntax to…

```xquery
declare record my:rectangle(
  height,
  width,
  area ::= fn { ?height * ?width }
)
```

…or should we look at this in a separate issue?

> (b) a map in which the area field is different from this fixed value is not a valid instance of the `my:rectangle` record type.

The challenge could be how to decide when a field is equal (or equivalent or identical). If we apply the deep-equal semantics (and compare the identity of function items), the following assignment may either be successful or fail, depending on the way how a processor optimizes the function item:

```xquery
let $r as my:rectangle := map {
  'height': 0,
  'width': 0,
  'area': fn { .?height * .!?width }
}
```

An alternative could be to use type annotations (as has been prepared before), i.e., assign the record type to maps that have been created with the record constructor (and to propagate this type when `map:remove` or `map:put` is invoked), but to disallow the coercion from untyped maps to records. By adhering to this principle, the `let` binding from the example would fail. Instead, you would need to write:

```xquery
let $r as my:rectangle := my:rectangle(0, 0)
```

**Comment by michaelhkay** [comment]
Yes, I think the "declare record" syntax is a good idea.

I've been toying with the idea that a map created using a record constructor should be labeled with the record type, and should lose its label if a fixed field is updated. Details to be worked out. Basically, a shift away from duck typing to constructive typing (or from Aristotelean typing to Platonic typing), such as we already have for atomic values.

**Comment by MarkNicholls** [comment]
an aside...in principle equals on functions is equivalent to the halting problem.....i dont understand the details of the proposal or its motivation, so ignore if irrelevant.

**Comment by michaelhkay** [comment]
Closed as completed.
