### ISSUE TITLE
parse-json: liberal parsing

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#1036]
I noticed that some new test cases ([`fn-parse-json-712`](https://github.com/qt4cg/qt4tests/blob/1859042e97f5d2ce4917bd3eef7beae4e5f64171/fn/parse-json.xml#L960-L973), `fn-parse-json-716`, possibly others) rely on specific liberal parsing rules.

@michaelhkay Do you think that it could make sense to formalize some of those rules, or should we rather fix the test cases?

**Comment by michaelhkay** [comment]
Yes, sorry, I intended to review these tests before committing them. In the case of number-parser, we explicitly say that the value is validated against JSON rules prior to calling the user-supplied number-parser if liberal=no, but not if liberal=yes. However that doesn't make liberal=yes completely interoperable, because it has to look something like a number for the number-parser to be invoked in the first place.

**Comment by michaelhkay** [comment]
I agree, these tests are not interoperable and should be withdrawn.

Perhaps we should also clarify the sentence:

> Before calling the supplied number-parser, the value is first checked to ensure that it conforms to the JSON grammar (for example, a leading plus sign and redundant leading zeroes are not allowed); these checks are disabled if the liberal option is set to true.

It might be better to write:

> If the liberal option is set to false, then the supplied number-parser is called if and only if the value conforms to the JSON grammar for numbers (for example, a leading plus sign and redundant leading zeroes are not allowed). If the liberal option is set to true, then it is also called if the value conforms to an implementation-defined extension of this grammar.

**Comment by michaelhkay** [comment]
I believe that the tests in question all allow the option of rejecting the JSON as invalid.

I guess this leaves the possibility that the JSON parser accepts something like `+1.21` as a "liberal" extension to the JSON grammar, but doesn't recognize it as an extension to the grammar for numbers. That seems a bit implausible to me. I think the only results that a practical implementation is likely to return are (a) FOJS0001 (invalid JSON), or (b) the result of calling the supplied number-parser.

**Comment by michaelhkay** [comment]
So, I've created a pull request on the spec that adds the clarification noted, and I'ev created a PR on the tests that simply annotates tests with the PR that they relate to.

**Comment by ChristianGruen** [comment]
> I believe that the tests in question all allow the option of rejecting the JSON as invalid.

I agree: The commit https://github.com/qt4cg/qt4tests/commit/9483a9683e328aa520ad843fa2260747a54dba93 seems to have resolved the issue.
