### ISSUE TITLE
fn:json-to-xml: 'number-parser' option

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#1037]
A function supplied via the `number-parser` option of `fn:json-to-xml` is now allowed to return zero or <del>more</del> **one** items. Analogous to the `action` argument of `fn:replace`, the result should be converted to a string by invoking `fn:string` on the result. An example:

```xquery
json-to-xml('-1', map { 'number-parser': abs#1 })
→ <fn:number>1</fn:number>

json-to-xml('1', map { 'number-parser': fn { true#0 } })
→ err:FOTY0013
```

No change is required for `fn:parse-json`.

**Comment by michaelhkay** [comment]
>A function supplied via the number-parser option of fn:json-to-xml is now allowed to return zero or more items

I think it's actually zero-or-one.

**Comment by ChristianGruen** [comment]
> I think it's actually zero-or-one.

Thanks, true; has been fixed in the initial comment.
