### ISSUE TITLE
Backwards incompatibility caused by use of EBV in callback functions

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#1038]
Changing fn:filter and similar functions that existed in 3.1 to use the EBV of the callback function's result has introduced a backwards incompatibility. In 3.1, the function conversion rules were used to convert the callback function's result to `xs:boolean`. This involves atomization. If the callback returned the untyped node `<a>false</a>`, this is atomised as `false()`, but its EBV is `true()`.

Revealed by test case fn:filter-006.

I think it's unlikely to happen much in practice, but it's a bit nasty. Perhaps we shouldn't make the change to use EBV for functions that existed in 3.1?

Perhaps we should even consider reverting the change entirely. It's not exactly essential.

**Comment by ChristianGruen** [comment]
> Perhaps we should even consider reverting the change entirely. It's not exactly essential.

Yes, I believe consistency should be our primary goal.

Maybe we can offer more flexibility by allowing empty sequences as return types, i.e. changing `xs:boolean` to `xs:boolean?`. Another suggestion would be to change the return type to `xs:anyAtomicType?` and to compute the EBV from this value.

**Comment by michaelhkay** [comment]
I think the only real use case for EBV is to allow nodes, in particular the self::x construct which people think of as being boolean; and it's the node case that creates the backwards incompatibility.

**Comment by ndw** [comment]
I think we should remove the change entirely.

**Comment by michaelhkay** [comment]
We resolved to drop the EBV change, thereby resolving this issue.
