### ISSUE TITLE
name of map:replace/array:replace

### ISSUE THREAD

**Issue by benibela** [qt4cg/qtspecs#104]
The name of map:replace/array:replace is easily confused with fn:replace. One might think that map:replace applies a regular expression to all the keys of a map (which might be a quite useful replacement for JSON object). 

It might also be confused with the replace function of Java's hashmap, which only inserts a new value if the key already exists in the map.

One could name it map:put-with-function or map:put-f or map:putf  or map:puf for short

Or something else: map:change, map:modify, map:alter

**Comment by michaelhkay** [comment]
Perhaps `map:selective-change()`?

**Comment by ChristianGruen** [comment]
In the current XQFO4 specification, `fn:replace` was augmented with additional arguments. I think we should proceed similarly with `map:put` and `array:put`:

```xquery
map:put(
  $map     as map(*),
  $key     as xs:anyAtomicType,
  $value   as item()*,
  $action  as (function(item()*) as item()*
) as map(*)

array:put(
  $array     as array(*),
  $position  as xs:integer,
  $member    as item()*,
  $action    as (function(item()*) as item()*
) as array(*)
```

And I would propose to change and unify the rules of all three functions:

> The replacement is determined by the value of the `$...` or `$action` argument:
> * If the $action argument is present, then the value obtained by calling the function.
> * If the $... argument is present, then the value.
> * If no argument is present, the value will be the empty sequence.

For `fn:replace`, the string value of the result can then be applied as replacement string.

**Comment by michaelhkay** [comment]
Shame that we can't do fn:put for a similar function on sequences, the name was taken by XQuery Update. But we could do fn:put-item.

**Comment by ChristianGruen** [comment]
I’m closing this in favor of #583.
