### ISSUE TITLE
CSV parsing - "blank" rows

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#1043]
The CSV parsing specification states "A blank row is represented as an empty array.".

1. It's not clear what "blank" means here. Does it depend on the whitespace-trimming option?

2. It would be more logical to return an array containing a single zero-length string, since any other line containing no field delimiter is considered to contain one field.

3. Alternatively, it might make sense to ignore the row entirely.

**Comment by fidothe** [comment]
In most CSV implementations the answer does indeed depend on whitespace trimming. For example, from the CSV stdlib module in Ruby:

```ruby
irb(main):001> CSV.parse("a,b\n  \nc,d")
=> [["a", "b"], ["  "], ["c", "d"]]
irb(main):002> CSV.parse("a,b\n  \nc,d", strip: true)
=> [["a", "b"], [], ["c", "d"]]
```

`CSV.parse` here returns arrays-of-arrays-of-strings, the inner arrays representing the rows.

As far as point 2 goes, I think we'd be going against accepted practice. Here, again, from the Ruby stdlib CSV module:

```ruby
irb(main):001> CSV.parse("a,b\n\nc,d")
=> [["a", "b"], [], ["c", "d"]]
```

As for point 3, there is an option in most CSV libraries to do just that - 

```ruby
irb(main):010> CSV.parse("a,b\n  \nc,d", strip: true, skip_blanks:true)
=> [["a", "b"], ["c", "d"]]
```

But it's optional behaviour, not the default.

**Comment by michaelhkay** [comment]
Related to this is the question of 

(a) what should happen if the supplied $value is a zero-length string. Do we treat this as being zero rows, or as one blank row? If it's one blank row, then how do you supply zero rows?

(b) what should happen if the input is an empty sequence. Should we allow it at all (currently some of the functions do and others don't)? If we allow it, what should it mean? Options are to treat it the same as supplying a zero length string, to treat it as supplying zero rows, or to just return the empty sequence.

**Comment by ChristianGruen** [comment]
> (a) what should happen if the supplied $value is a zero-length string.

I would tend to ignore rows with 0 characters; I can’t imagine obvious use cases for treating them differently.

> (b) what should happen if the input is an empty sequence. 

We should do the same what `fn:parse-xml` and `fn:parse-json` do (i.e., return an empty sequence).
