### ISSUE TITLE
CSV row delimiter - allowed values

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#1044]
Section 15.4.2.1 says:

> The row delimiter defaults to matching any of CRLF (&#x0D;&#x0A;), LF (&#x0A;), or CR (&#x0D;). Valid values for the row delimiter are a single Unicode character, or one of CRLF, LF, or CR, that has not been marked for use as the column delimiter. Implementations must raise [[err:FOCV0002](] if the row-delimiter option is set to a multi-character string other than CRLF (&#x0D;&#x0A;)

1. It's not entirely clear to me what this is saying. Are alternative row delimiters other than newline delimiters allowed (`row-delimiter:('|','/')`? 
2. The statement in this section doesn't align with the error conditions appearing in the actual function specs, which says: "A dynamic error [[err:FOCV0002] occurs if one or more of the values for field-delimiter or quote-character are specified and are not a single character." - no mention here of the row-delimiter.

**Comment by fidothe** [comment]
Alternative row delimiters are allowed. It's primarily complicated by the fact that existing implementations generally require user-specified delimiters to be a single character, with CRLF special-cased because it's a two-character sequence.

The FOCV0002 error text sounds like an omission on my part when I originally wrote that.

**Comment by ChristianGruen** [comment]
PS: The CSV implementation of Python seems to have gone a similar direction: The CSV parser ignores the 
[Dialect.lineterminator](https://docs.python.org/3/library/csv.html#dialects-and-formatting-parameters) option, it is only used for generating CSV (which is something we would rather control with our serialization parameters, see https://github.com/qt4cg/qtspecs/issues/101).

**Comment by michaelhkay** [comment]
Perhaps we should split it into two options: (a) `normalize-line-endings=true/false`, and (b) `row-delimiter` as a single character.  And perhaps we don't need `normalize-line-endings` if `unparsed-text()` already does it.

**Comment by ChristianGruen** [comment]
> And perhaps we don't need `normalize-line-endings` if `unparsed-text()` already does it.

Thanks for the correction (instead of `file:read-text`, I should have referred to this function).
