### ISSUE TITLE
Incorrect note for `fn:some` and `fn:every`

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#1047]
`fn:some` and `fn:every` state (non-normatively): 

> "If the second argument is omitted or an empty sequence, the first argument must be a sequence of xs:boolean values.". 

I don't think this note is correct. If the default predicate `identity#1` is used, it is coerced to the required type `function(item()) as xs:boolean`, so the effective predicate is `fn($x as item()) as xs:boolean {identity($x)}`. This atomises the result of calling `identity($x)` and casts the result to `xs:boolean`. Therefore expressions such as `some([true()])` and `some(<a>true</a>)` return true, not an error.

**Comment by ChristianGruen** [comment]
…which is strange enough, but I agree.

**Comment by michaelhkay** [comment]
We could change the default from `identity#1` to `fn($x){$x treat as xs:boolean}` if that's what we want to do.

**Comment by ChristianGruen** [comment]
> We could change the default from `identity#1` to `fn($x){$x treat as xs:boolean}` if that's what we want to do.

…or `boolean#1`?

**Comment by ChristianGruen** [comment]
…accepted.

I’ve revised various `fn:every`/`fn:some` test cases, which I believe were wrong:
https://github.com/qt4cg/qt4tests/commit/af7640a513bd7bda9f301a0cc8334a58bb5ea78e#diff-df371a354e84b8d2323836483adafbd66f138762e7d7fd414875ce185862f112
