### ISSUE TITLE
Simplifying match templates

### ISSUE THREAD

**Issue by MarkNicholls** [qt4cg/qtspecs#1056]
I like match templates a lot, I think they are a USP for XSLT, but I find using them quite clumsy e.g.

- priority rules are quite subtle (I couldn't tell you what they are not, and I tend to make them explicit)
- because each match sits in a different template they tend to sort of drift around in the spaghetti of the code
- they don't naturally extend to nested local matches....everything exists at the top level.

If you compare this with main stream functional match expressions then they are quite syntactically different, and I think the mainstream syntax is probably a bit simpler (and much more familiar)
(I can see this potentially extending to lots of subsequent things but I'll keep it to the headline)

I think something like

    <xsl:template mode="foo" as="xs:string">
        <xsl:match select="Foo">
            <xsl:sequence select="'this is a foo'"/>
        </xsl:match>
        <xsl:match select="Bar">
            <xsl:sequence select="'this is a bar'"/>
        </xsl:match>
        <xsl:match>
            <xsl:sequence select="'this is something else'"/>
        </xsl:match>
    </xsl:template>

- templates are matched in sequence (as is the norm), no opaque priority rules
- if nothing is matched then nothing is returned...I have effectively a catchall match above.
- everything is cohesive, the template contains all matches....no secret ones hidden at the bottom of the file.

there's lots of holes here, 
- how does this interact with existing match templates? 
- are the a different syntax for the same thing?
- how do they work with includes and imports?

my guesses are...they ARE just different syntax for the existing infrastructure...because thats the smallest change.
and then the other questions are answered by how the above syntax maps into "priority" but tbh, as I barely know how the current priority rules work, I can't really give a sensible guess. 

tbh, if this is just different syntax then secret matches CAN exist elsewhere in the spaghetti, but at least the programmer does have a construct to not do that, rather than the default contract to lack cohesion from the outset.

**Comment by MarkNicholls** [comment]
a slightly more radical suggestion is to have a match as a local expression rather than a template e.g.

```
    <xsl:template mode="makeFoo" match="bar" as="xs:string">
        <xsl:match select="Foo[@wibble = '23']">
            <xsl:when select="Foo[@bar]">
                <xsl:sequence select="'Foo with a bar'"/>
            </xsl:when>
            <xsl:otherwise>
                <xsl:sequence select="'no bar'"/>
            </xsl:otherwise>
        </xsl:match>            
    </xsl:template>

```

this is basically a mainstream FP match but with xpath style cases...(I think thats pretty nice).

this has the benefit of from the ground up being local, and nestable etc....quite nice (I prefer it to the headline suggestion) but I suspect a much bigger ask.

**Comment by MarkNicholls** [comment]
> Basically you seem to be asking for the model available since xslt 1 as xsl:choose
> 
> ```
>  <xsl:choose>
>     <xsl:when select="self::Foo">
>         <xsl:sequence select="'this is a foo'"/>
>     </xsl:when
>     <xsl:when select="self::Bar">
>         <xsl:sequence select="'this is a bar'"/>
>     </xsl:when>
>     <xsl:otherwise>
>         <xsl:sequence select="'this is something else'"/>
>     </xsl:xsl:otherwise>
> </xsl:choose>     
> ```

yes but you cant put complex matches in a self axis can you?

**Comment by davidcarlisle** [comment]
`self::*[@foo='wibble'  and (self::abc or self::xyz) and exists(.//hmm)]`

**Comment by MarkNicholls** [comment]
you can't put

`match="Foo/Wibble/Bar[@bar]"
`
easily in an axis expression

**Comment by michaelhkay** [comment]
I have no idea what you mean by "mainstream". One thing we learn in this game is that everyone comes to it from a different direction and tends to believe that the design of previous languages they have used is the only natural way of doing things; they often fail to appreciate how much diversity there is out there. 

Also please be aware that sketching out proposed syntax for a feature isn't helpful unless you tell us what the new syntax is supposed to mean. You might have a clear idea in your own head, but that doesn't mean we can read your mind. I can only guess what you intend by nesting `xsl:match` within `xsl:template`, and I'm probably guessing wrong, especially when you then nest `xsl:when` inside `xsl:match`.

In 4.0 we have tried to tackle the problem of scoped template rules by the use of **enclosing modes**: please take a look at the spec at https://qt4cg.org/specifications/xslt-40/Overview.html#enclosing-modes and comment on it, as there is certainly room to change the detail at this stage.

The rather simplistic mechanism for allocating default priorities to rules based on the syntactic form of the pattern is not a design I would passionately defend today, but it's the kind of thing that is extremely difficult to change.

**Comment by MarkNicholls** [comment]
If I could put a match template style expression in a "choose" style expression, I'd choose a "choose".

I get more cohesive code and local/nested logic

**Comment by MarkNicholls** [comment]
@michaelhkay 

> I have no idea what you mean by "mainstream"

lets just take these three - I accept that there are many nuances in different languages.

https://www.haskell.org/tutorial/patterns.html

https://docs.scala-lang.org/overviews/scala-book/match-expressions.html

https://learn.microsoft.com/en-us/dotnet/fsharp/language-reference/match-expressions

but these 3 are basically the same.

you "select' a value, and then you pattern match on it in turn by decomposiing it.

actually @davidcarlisle 's answer highlights how to similate this in the current choose expression, but as discussed somewhere else , you cant use match expressions in XPath axis, you have to sort of invert them to work backwards.

(I seem to remember you inventing some syntax in a response to me the other day!....which to be fair completely confused me).

The problem with sketching out formal semantics of a syntax requires an understanding of formal semantics (which I have the tiniest knowledge) and is a lot of work to do based on a hunch.

So...I've doubly confused this by putting 2 suggestions in.

suggestion a is simply syntactic sugar on the same current semantics.

from this

```
<xsl:template mode="foo" as="xs:string">
    <xsl:match select="Foo">
        <xsl:sequence select="'this is a foo'"/>
    </xsl:match>
    <xsl:match select="Bar">
        <xsl:sequence select="'this is a bar'"/>
    </xsl:match>
    <xsl:match>
        <xsl:sequence select="'this is something else'"/>
    </xsl:match>
</xsl:template>

```

we construct this

```
<xsl:template match= "Foo" mode="foo" as="xs:string" priority="0">
        <xsl:sequence select="'this is a foo'"/>
</xsl:template>

<xsl:template match= "Bar" mode="foo" as="xs:string" priority="-1">
        <xsl:sequence select="'this is a bar'"/>
</xsl:template>

<xsl:template match= "@*|node()" mode="foo" as="xs:string" priority="-2">
        <xsl:sequence select="'this is something else'"/>
</xsl:template>

```

take the origin of the priority with a pinch of salt for the moment...I suspect doing the above would interact weirdly with existing templates.

So broadly why do I prefer the former syntax to the latter?

because its all in 1 place, and the priority of each "rule" is obvious, its simple the order they are laid out (as per a choose expression).

Again, as a newcomer to the language, priority rules are baffling (I spend many months thinking the order in the file mattered).

(the 2nd suggestion we can park).

**Comment by MarkNicholls** [comment]
I'll read the enclosing mode spec

**Comment by MarkNicholls** [comment]
ah ok, its covered by enclosing modes
