### ISSUE TITLE
Formatting XPath/XQuery

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#1060]
I got reminded today that the specification documents are kind of “wild”, because all code snippets use a different formatting:

* The indentation is inconsistent (the tendency seems to be 2 spaces, in accordance with the function signatures). Repeatedly, indentations are used that don’t seem to follow any conventions at all.
* Sometimes, `function`, `map` and `array` keywords are followed by a space, sometimes not. My preference would be not be too stingy; we have enough space.
* Sometimes, the `return` keyword starts in a new line, sometimes it’s attached to the previous line.

This is certainly something we cannot finalize too early, but I think we shouldn’t be too erratic in an official document, even though it’s “just code”.

Related: #1000.

**Comment by michaelhkay** [comment]
I actually find it very difficult to adopt a consistent indentation style for XQuery; I have yet to find a set of conventions that consistently gives good reasons. An example is how to write a multi-line inline function as a function argument. So even if we only had one author, it wouldn't be easy.

Another problem is the XML markup of `<eg>` and `<CDATA` tags, and another is the tendency of Oxygen to reformat fragments when you copy-and-paste.

**Comment by ChristianGruen** [comment]
I may be difficult to get 100% consistency, but I think we could definitely do better. Oxygen should hopefully not stop us here ;)

I’d be ready to unify the status quo (provided, of course, that the result won’t lead to too much discussion).
