### ISSUE TITLE
deep-equal() - option to compare functions liberally

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#1063]
We have changed deep-equal() so it no longer automatically treats functions as not equal.

However, it is still in practice infeasible to use deep-equal() for comparison of test results that include function items because it is not in general possible to supply an expected result that compares true to the function item actually returned. Since comparison of test results is an important use case for deep-equal, this is a serious limitation. It affects our own process that checks that output from examples in the spec is correct: the examples for parse-csv, for example, are artificially adjusted to make test comparison feasible by eliminating the function items in the result, which reduces the pedagogical value of the examples.

There should be an option such as `strict-function-comparison=true|false`. If set to false, then the function properties such as name, arity, and signature are compared, but the function body is ignored and assumed equal.

**Comment by ChristianGruen** [comment]
I’m not sure whether test cases should be a driving factor to add more features to a specification. Can we provide other use cases for which the proposed option would be helpful?

Next, if the function body is ignored, will this mean that test case results are really correct?

**Comment by michaelhkay** [comment]
It's not just our testing that uses deep-equal: anyone testing their stylesheets using the XSpec framework is likely to hit the same problem.

To test that the results are really correct, you need both a test that the function exists and has the right signature, which can be done with the proposed change to deep-equal(), and a test that calling the function returns the expected result.

For example,

```
<x:expect test="deep-equal(map'x':1, 'y':2, 'z':function($p as xs:integer){9999}}, 
                                 map{'strict-function-comparison':false()})"/>
<x:expect test="?z(22)=32"/>
```

**Comment by ChristianGruen** [comment]
> There should be an option such as `strict-function-comparison=true|false`. If set to false, then the function properties such as name, arity, and signature are compared, but the function body is ignored and assumed equal.

If an additional test is required to call the function anyway, we could define an option that ignore function items in the comparison; it may be closer to what we have for comments and processing instructions.

Otherwise, we may be limited to only comparing the arity of the function. For example (and if I got it right), processors are currently allowed to return `true` for all of the following expressions…

```xquery
deep-equal(fn($x) { count($x) }, fn($x) { count($x) }),
deep-equal(fn($x) { count($x) }, fn($y) { count($y) }),
deep-equal(fn($x) { count($x) }, count(?)),
deep-equal(fn($x) { count($x) }, count#1)
```

…as the compared functions return the same output for the same input. In all cases, `true` should also be returned if `strict-function-comparison` is disabled.

In the long term, it would certainly be most appealing to extend function comparisons to include the function body (and possibly the closre and/or static context), but I know it’s challenging to specify it in a way that will be suitable for all processors.

**Comment by michaelhkay** [comment]
>isn't this impossible in principle?

There are three cases: (a) we know the functions are different, (b) we know they are the same, (c) we don't know and can't tell.

Currently in case (c) we return "not equal", The proposal here is to have an option to return "equal" instead; that is, to give it the benefit of the doubt.

**Comment by MarkNicholls** [comment]
ok, feels scary....but I wont ask you to revisit it.

**Comment by MarkNicholls** [comment]
is it worth changing the signature to true/false/dont know?

(a test that returns true, when the answer should be false is a nasty thing).

**Comment by ChristianGruen** [comment]
@MarkNicholls If you interested, you can read through #520 and #908 to learn more about the current solution, and reasons for the decisions that have been taken.

**Comment by ChristianGruen** [comment]
> > isn't this impossible in principle?
> 
> There are three cases: (a) we know the functions are different, (b) we know they are the same, (c) we don't know and can't tell.
> 
> Currently in case (c) we return "not equal", The proposal here is to have an option to return "equal" instead; that is, to give it the benefit of the doubt.

I think a simple `functions` option would be more self-explanatory, and similar to `comments` and `processing-instructions`:

* `functions`: Determines whether functions are significant.<br/>Type: `xs:boolean`<br/>Default: `true`

It will give us more freedom if we decide later on to improve the detection of equal/equivalent/identical functions.

**Comment by MarkNicholls** [comment]
I've skimmed those things, looks like a mine field to me.
I'll go away.

**Comment by MarkNicholls** [comment]
This is nagging me, sorry.

I think this is problematic, extensionally comparing functions is the halting problem, and intensionally comparing them requires a unique normal form, that I think doesn't always exist. 

OK, you can sidestep this (like OOers do) by ensuring that "methods" are immutable by definition so if are comparing "objects" in a "type" you don't need to compare the methods....but you need an explicit mechanism to do that, i.e. you can label them, but trying to look inside a label I think is problematic in principle.

for me these

```
deep-equal(fn($x) { count($x) }, fn($x) { count($x) }),
deep-equal(fn($x) { count($x) }, fn($y) { count($y) }),
deep-equal(fn($x) { count($x) }, count(?)),
deep-equal(fn($x) { count($x) }, count#1)

```

are all "maybe", as soon as you try to write rules to reduce them to a normal form (which may not exist), I think you are on a never ending journey doomed to be incomplete, and with every iteration you will get a new set of functions that you now consider are equal, which the previous version of software didnt.

 Using object identity in the underlying implementation may seem convenient you MAY be able to guarentee that

let y$ = x$
deep-equal($x,$y)

is true, where $x is a function,

but it would wake me up in the middle of the night every now and then, am I now just moving the problem to ensure that the function before the call to deep-equal is equivalent to assignment.....hurts my head.

dont feel like you have to respond, I expect you are aware of this, and have accepted it.

**Comment by michaelhkay** [comment]
Mark, I'm not trying to reduce the number of cases where the answer is "maybe" which indeed is a hopeless goal. Rather I'm proposing to change how deep-equal handles the situation where there are "maybe's" in the result. At the moment we treat maybe as false, but I'm seeing use cases where it would be more convenient to treat maybe as true. It's very like the situation where you want to ignore whitespace differences; when writing test assertions people want to focus on selected aspects of the result that must be as expected, and allow differences in other aspects.

**Comment by MarkNicholls** [comment]
Sorry, I'm answering the question i want to answer and not the one you are asking.

If you want to have an option that completely ignore function comparison in deep equal explicitly always, then that makes sense in a practical sense (i.e. you ignore all cases always).

I don't like the the use of function comparison in any use case though, and I cant mentally get beyond that.

I WILL go away now though, you can move on.

**Comment by MarkNicholls** [comment]
I completely understand and sympathise with the motivation.

**Comment by michaelhkay** [comment]
I'm now thinking of satisfying this requirement with a more general and powerful capability: a callback function that allows any two items to be deemed equal.

For example

```
deep-equal($actual, $expected, options := map{
  "deem-equal": fn($x, $y){$x instance of attribute(@last-updated) and $y instance of attribute(@last-updated)}
})
```

deems two node trees to be deep-equal even though the values for the @last-updated attribute differ.

For a "smoke test" of function items, you might write

"deem-equal": fn($x, $y) {$x instance of function(*) and $y instance of function(*) and $x(22) = $y(22)}

Another use case would be treating floating point numbers as equal if they differ by a very small amount.

**Comment by michaelhkay** [comment]
The callback also has diagnostic value, on the assumption that it is only called when two items would otherwise cause deep-equal to return false:

```
"deem-equal": fn($x, $y) {
    trace(false(), `{serialize($x)} and {serialize($y} are not equal`)
}
```

**Comment by ChristianGruen** [comment]
I had to read it twice to spot that `deem-equal` is not `deep-equal` ;)

I assume the function will be invoked for every item, and all other options will be ignored (except for `ordered`)?

And I assume it will be up to the user to handle different item types?

```xquery
deep-equal($actual, $expected, (), map {
  "deem-equal": fn($x, $y) {
    if($x instance of function(*) and $y instance of function(*)) then (
      function-arity($x) = function-arity($y)
    ) else (
      deep-equal($x, $y)
    )
})
```

**Comment by michaelhkay** [comment]
We did agree on a definition of function identity, so there are cases where we definitely know that two functions are equivalent, and other cases where we don't.

This is issue not re-opening this question.  Rather it's pointing out that for one of the important use-cases for deep-equal(), which is comparing test results against expected results, we want to "give the benefit of the doubt", that is, if there are parts of the result that we can't meaningfully compare, we don't want the test case to report a failure.

**Comment by dnovatchev** [comment]
> We did agree on a definition of function identity, so there are cases where we definitely know that two functions are equivalent, and other cases where we don't.
> 
> This is issue not re-opening this question. Rather it's pointing out that for one of the important use-cases for deep-equal(), which is comparing test results against expected results, we want to "give the benefit of the doubt", that is, if there are parts of the result that we can't meaningfully compare, we don't want the test case to report a failure.

As someone noted, testing by implementors should be opaque to the outside world.

Maybe this deserves a special function, that will not be exposed to everyone?

Again as someone noted, implementing a 3-valued logic result-type (or returning a pair of results) seems very appropriate.
I imagine a tester's IDE that will display a warning if the result is "Maybe".

**Comment by benibela** [comment]
>This is issue not re-opening this question. Rather it's pointing out that for one of the important use-cases for deep-equal(), which is comparing test results against expected results, we want to "give the benefit of the doubt", that is, if there are parts of the result that we can't meaningfully compare, we don't want the test case to report a failure.

one could remove these parts before doing the comparison

**Comment by michaelhkay** [comment]
>As someone noted, testing by implementors should be opaque to the outside world.

And as I replied, this is not just for testing by implementors: it's for anyone who wants to test their stylesheets or queries and use deep-equal in doing so. XSpec users make heavy use of deep-equal for this purpose.

>one could remove these parts before doing the comparison

Yes, and proposals for deep update might eventually make that rather easier than it is today.

**Comment by dnovatchev** [comment]
> > one could remove these parts before doing the comparison
> 
> Yes, and proposals for deep update might eventually make that rather easier than it is today. But in defining test assertions, you don't just want to remove things that can't be equality-compared, you want to sanity-check them.

It seems from this conversation that it would be best to provide a new, special function, to be used for comparing test results.

And I completely agree with @benibela that functions should have been excluded from day one. Why they arbitrarily decided that NaN should be equal to itself (whatever that means ???) but didn't do the same for functions?

On the other side, if someone is interested in function "equality", then we need to provide a new function exactly for these users - let us tentatively name it:

**`functions-equal`**  

And this function can return three values: 

- **`0`** - for (definitely) equal
- **`-1`** - for (definitely) unequal
- **NaN** - for **_unknown_**.

Now, for the people who decided that _NaN_ equals _NaN_, the fact that such a function comparison returned _NaN_ probably should mean that all such functions should be considered "_equal_".

For other people, like myself - _NaN_ equal to _NaN_ is more like an immature teenagers dream. Trying to explain and label more that can be explained is a sure path to delusion. Let us leave hallucinating to AI only.
