### ISSUE TITLE
fn:format-number: further notes

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#1065]
This issue summarizes suggestions for `fn:format-number` from the [QT4 Meeting 068](https://qt4cg.org/meeting/minutes/2024/03-05.html) that have not yet been incorporated into the current draft:

1. The [Unicode Common Locale Data Repository](https://cldr.unicode.org/translation/number-currency-formats/number-and-currency-patterns) (CLDR) should be referenced; it has recommendations for all of the languages in Unicode and some variants.
2. We could consider introducing an options map so that we can just add more things later (such as e.g. an option for using the default decimal format for parsing the picture string, see https://github.com/qt4cg/qtspecs/issues/1048#issuecomment-1978869499).

**Comment by michaelhkay** [comment]
Note that item 2 has been done.

I'm somewhat sceptical about locale-based number formatting. My impression is that publishing conventions depend as much on what discipline you are in (e.g. accountancy versus engineering) as on what country you are in. In any event, anything locale-based leads to serious complications in getting interoperable tests. I don't see a great deal of user pressure for this.

**Comment by ndw** [comment]
At [meeting 095](https://qt4cg.org/meeting/minutes/2024/10-22.html), the CG agreed to close this issue with no further action.
