### ISSUE TITLE
fn:deep-equal: significant children

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#1067]
The current rules of [fn:deep-equal](https://qt4cg.org/specifications/xpath-functions-40/Overview.html#func-deep-equal) are:

> e. Let `significant-children($parent)` be the sequence of nodes obtained by applying the following steps to the children of `$parent`, in turn:
>   i. Comment nodes are discarded if the option `comments` is false.
>   ii. Processing instruction nodes are discarded if the option `processing-instructions` is false.
>   iii. Adjacent text nodes are merged.
> …
>  …the sequence `significant-children($i1)` is deep-equal to the sequence `significant-children($i2)`.

If my interpretation is correct, the following expression is now expected to return `true`…

```xquery
deep-equal(
  <e>A<!---->B</e>,
  <e>AB</e>
)
```

…and we need to update various test cases (e.g. [K2-SeqDeepEqualFunc-22](https://github.com/qt4cg/qt4tests/blob/af7640a513bd7bda9f301a0cc8334a58bb5ea78e/fn/deep-equal.xml#L2390-L2398)).

**Comment by ChristianGruen** [comment]
I observed that my observation is a duplicate from https://github.com/qt4cg/qtspecs/issues/934#issuecomment-1905775961. I’ll keep this one open as the other issue has a different focus.

**Comment by michaelhkay** [comment]
Yes, I believe that the correct interpretation of the new rules.
