### ISSUE TITLE
Allow self::(a|b|c)

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#107]
After an explicit axis specifier (including the abbreviated axis specifier "@", but not including the default axis specifier), allow a composite NodeTest that consists of a |-separated list of NodeTest's in parentheses. For example

`@(id|name)`

`ancestor::(section|chapter)`

`child::(comment()|processing-instruction())`

The composite NodeTest matches a node if any of its constituent NodeTest's matches.

**Comment by joewiz** [comment]
This would be great! This would be a far more natural way to express NodeTests like these.

**Comment by michaelhkay** [comment]
Here's the detail.

`AbbrevForwardStep  ::= "@"?  NodeTest
`
changes to 

```
AbbrevForwardStep  ::= "@"  NodeTest | SimpleNodeTest
NodeTest ::= SimpleNodeTest | ParenthesizedNodeTest
ParenthesizedNodeTest ::= "(" SimpleNodeTest ("|" SimpleNodeTest)* ")"
SimpleNodeTest ::= NameTest | KindTest
```

(Note, I've chosen not to allow `child::(A | (B|C) )` - no nesting allowed or needed.

In 4.6.2.2 we need to add "A ParenthesizedNodeTest matches a node if any of its constituent SimpleNodeTests matches the node".

Apart from that it's just a case of adding examples and notes.

XSLT needs to pick up the change in the syntax for patterns. A pattern that uses a ParenthesizedNodeTest has a default priority of +0.5.

**Comment by michaelhkay** [comment]
Note that most of the time, this construct is just syntactic sugar: `@(A|B)` is equivalent to `@A|@B`.

However, with a reverse axis, it does add expressive power. `ancestor::(div1|div2)[2]` is not easily expressed any other way, because `(ancestor::div1|ancestor::div2)[2]` has a different meaning (the union operator sorts nodes into document order before applying the predicate).

**Comment by michaelhkay** [comment]
This proposal overlaps issue #23. It's wider than issue #23 in that it allows unions of NodeTests, not just NameTests. But it's narrower in that it doesn't allow multiple names in an elementTest (for example `element(A|B|C)`).

**Comment by michaelhkay** [comment]
This change has been implemented.
