### ISSUE TITLE
Editorial: XSLT, Applying Template Rules, Examples

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#1079]
This guy is all around. Do we really need him in our specs as well? 😏 

https://qt4cg.org/pr/1078/xslt-40/Overview.html#applying-templates

```xquery
  "Title": "How to Win Elections",
  "Authors": [ "...
```

**Comment by michaelhkay** [comment]
Perhaps I should change the book title to "How to be a bad loser".
