### ISSUE TITLE
Inconsistency in underscore in numeric literal grammar

### ISSUE THREAD

**Issue by johnlumley** [qt4cg/qtspecs#1082]
[Numeric Literals](https://qt4cg.org/specifications/xquery-40/xpath-40.html#id-numeric-literals) describes permitting underscores to be used as separators in sequences of digits within long numbers. The first interpretation rule says underscores are first stripped out.

But the grammar provided appears to me to be inconsistent. 

```
IntegerLiteral	   ::=   	Digits
DecimalLiteral	   ::=   	("." Digits) | (Digits "." [0-9]*)
DoubleLiteral	   ::=   	(("." Digits) | (Digits ("." [0-9]*)?)) [eE] [+-]? Digits
Digits	           ::=   	DecDigit ((DecDigit | "_")* DecDigit)?
DecDigit	   ::=   	[0-9]
```

`Digits` permits underscores in the grammar, which works in the integer portion of the numeric literal, but when the value exceeds 1 the fractional part is described as `[0-9]*`. If underscore stripping is a 'pre-parsing' step, then `Digits` need not mention it at all.

On the other hand if the grammar is defining the sequence of characters that are permitted, then the fractional section in the grammar should also permit underscores, which it plainly does not in the presence of an integer part. (The test `seconds-010` uses such in an expansion of π.) 

An alternative formulation that I think does describe underscores in fractional parts might be:

```
 DecimalLiteral	   ::=   	("." Digits) | (Digits "." Digits?) 
```

and similarly for `DoubleLiteral`. I know this isn't a game-changer, but for those generating grammars, consistency certainly helps.

**Comment by michaelhkay** [comment]
Looking at the history (see #433 and #456) I'm persuaded that this was an oversight, and that the intention of the CG was to allow underscores in the fractional part of the number. I will raise a PR to that effect.
