### ISSUE TITLE
Incorrect rendition of option defaults

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#1084]
In the F&O spec, when rendering the default value of an option, code font is being used for narrative prose: see for example defaults for the `delivery-format` and `base-output-uri` options of `fn:transform`

**Comment by ndw** [comment]
I think what we have here is semantic drift. Most occurrences of `fos:default` contain a single value that is to be taken as the default. For example `true()`, `default-language()` or `()`. Mixing in a prose description doesn't seem like it was the original intent.[*] In any event, as a consequence of this drift, not typesetting the value as "code" looks worse in most places.

One obvious hack is to say that if the default includes a `code` element, assume that it also has prose. That won't help for `base-output-uri` on `fn:transform` though. That's just a prose description.

There are only a dozen or so places where additional prose appears to be added. I propose that we add a `fos:default-description` element to support this.

[*] The type of `fos:default` is `xs:anyType` which is a little weird too. A hack to allow elements, maybe?

**Comment by michaelhkay** [comment]
That looks like the right solution.

**Comment by ndw** [comment]
Right. That's what PR #1149 does, but I'm not going to merge it now. It feels like it might introduce merge conflicts and I might as well be the victim. I've marked it "merge without discussion" so if no one objects, I'll merge any PRs we approve on Tuesday, then merge that one. That will limit the impact, I think.
