### ISSUE TITLE
Convenience function to construct a collation URI

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#1091]
I propose a convenience function to construct a collation URI: for example

collation({'lang':'fr'})

returns a collation URI suitable for French.

If the property names supplied are those that are defined for UCA collation names, the result will be the corresponding UCA collation URI; alternatively, implementation-defined property names can be included.

**Comment by Arithmeticus** [comment]
This new function will be greatly appreciated by those who have to deal with collations.
