### ISSUE TITLE
Collation: caseblind → Standardize or replace with `html-ascii-case-insensitive`?

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#1095]
Various test cases use the artificial `http://www.w3.org/2010/09/qt-fots-catalog/collation/caseblind` collation. It seems that most (all) of them could also be written with the `http://www.w3.org/2005/xpath-functions/collation/html-ascii-case-insensitive`.

Could we replace the tests with the standardized collation, or should we rather try to standardize the caseblind variant?

**Comment by michaelhkay** [comment]
I didn't realise the `http://www.w3.org/2010/09/qt-fots-catalog/collation/caseblind` was still used in test cases. This predates the introduction of standard collation URIs in 3.0/3.1 and it should be possible to get rid of it now.

**Comment by ChristianGruen** [comment]
> I didn't realise the `http://www.w3.org/2010/09/qt-fots-catalog/collation/caseblind` was still used in test cases. This predates the introduction of standard collation URIs in 3.0/3.1 and it should be possible to get rid of it now.

Thanks; I’ll give it a try.
