### ISSUE TITLE
TypeTest expressions

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#1104]
Our current status quo text allows the result of a lookup expression to be filtered by type:

`[[1,2], [3,4], 5, 6]?*::array(*)?1`

and issue #859 points out that this doesn't work because of a syntax ambiguity involving occurrence indicators ('?' is both an occurrence indicator and a lookup operator).

This issue addresses that problem by re-examining the requirements, and pulling in a number of other issues at the same time.

In path expressions we have a shorthand syntax for selecting nodes, called the node test, and the proposed syntax `::array(*)` was modelled on this. Node tests have a considerable overlap with types, but there are limitations. For example the `self` axis is often used to turn a node test into a general predicate, but `[self::XX]` can only be used to test elements, not attributes. However, the popularity of node tests and the self axis illustrates the need for a concise filtering operation.

Of course it's always possible to write `[. instance of array(*)]` but this gets extremely verbose.

In XSLT 3.0, template rules matching maps and arrays could only be written as `match=".[. instance of array(*)]"`, which gets really ugly, so we have proposed an alternative in 4.0. Specifically, you can match any type using `match="type(ItemType)"`, and for many types such as arrays and maps you can abbreviate this to, for example `match="array(*)"`. But this feels clumsy because the type() wrapper is sometimes needed and sometimes not.

I would like to propose an expression that has concise syntax, whose effect is equivalent to `. instance of T`. I propose to use the `~` symbol. This is available as both a binary and unary operator, so we can define a binary form `$z ~ T` which is syntactic shorthand for `$z instance of T`, and a unary form `~T` which is shorthand for `. ~ T`.

First, in the case of lookup expressions, we can now write:

`[[1,2], [3,4], 5, 6]?*[~array(*)]?1`

TypeTests will often be used within predicates in this way, and of course the usage is completely general.

Here's an example used for array:filter: `array:filter($array, fn{~xs:integer+})` which selects all members of the array comprising one or more integers.

In XSLT 4.0 the syntax `~T` replaces the current TypePattern, giving a much more uniform way of matching items by type.

In XPath and XSLT conditionals the construct can be used as an equivalent to XQuery's TypeswitchExpr:

```
<xsl:choose>
  <xsl:when test="~xs:integer">...</xsl:when>
  <xsl:when test="~xs:string">...</xsl:when>
  ...
</xsl:choose>
```

The choice of tilde for this operator is motivated by:

- There are not many symbols available
- Tilde has many different uses in mathematics and computing, some of which represent a boolean test applied to a value (for example testing whether it is similar to another value or whether it matches some pattern), which is not dissimilar to this proposed usage
- The alliteration between "tilde" and "type" has some mnemonic value (cf. the use of `@` for the attribute axis).

**Comment by ChristianGruen** [comment]
One feedback we got on a prototype implementation for the tilde in #755…

```xquery
(1 to 5) ~ count(.)
```

…that the syntax reminds of the bitwise not operator. With reference to, it could mean that some developers may interpret `test="~xs:integer"` as `test="not(. instance of xs:integer)"`.

**Comment by michaelhkay** [comment]
Unfortunately our users come from many different programming or non-programming traditions, and any operator symbol that we introduce from one of those traditions is going to feel alien to users accustomed to a different tradition. There's not much we can do about that. Yes, tilde has been used to mean "logical not" - mainly because of a historical accident where tilde and logical not were assigned to the same codepoint position in different character sets - and some users will have to readjust. Fortunately, we know that they are able to do so - using "/" to mean something other than division being the most obvious example.

**Comment by dnovatchev** [comment]
My immediate first reaction was that `~` is the bit-negation operator in C# and probably in other languages such as C++, C, and Java.

Thus using this particular `~` symbol may be really confusing to lots of people.

Also, using this one-character symbol is cryptic, requires effort to read, recognize and understand, and is easy to mistype and introduce an error, that sometimes could result in other, completely correct syntactically expression, and thus would not be caught and reported by an IDE. 

What about adding a new test:

**_`of-type(T)`_**

**Comment by ChristianGruen** [comment]
I wonder whether there are enough use cases to justify a dedicated operator for instance matches. I wouldn’t call `. instance of array(*)` extremely verbose; but maybe I’ve just gotten used to it. I think we should rather nail down a solution for the related requirement in #148.

If we think that `instance of` is too verbose , I agree with Dimitre that a function-like syntax or a keyword will be the more intuitive choice.

**Comment by michaelhkay** [comment]
Withdrawing this one; PR #1125 proposes an alternative solution.
