### ISSUE TITLE
Casting to numerical type from strings with underscores

### ISSUE THREAD

**Issue by johnlumley** [qt4cg/qtspecs#1105]
The [Digits](https://qt4cg.org/specifications/xquery-40/xpath-40.html#prod-xpath40-Digits) production now permits underscores as separators in long numerical character sequences.
However in casting to numerical types, either by operator or by function:
```
'12_345_678' as xs:integer
number('12.345_678')
```
am I correct that this should fail according to [Casting from xs:string and xs:untypedAtomic](https://qt4cg.org/specifications/xpath-functions-40/Overview.html#casting-from-strings), even though a static resolution/rewrite would be possible?

**Comment by michaelhkay** [comment]
Yes, that's correct. Casting strictly follows the XSD validation rules, so the input has to be in a form that XSD would validate.

**Comment by michaelhkay** [comment]
I'm going to propose closing with no action. The desired effect can be achieved, at least for integers, using parse-integer(), and I don't think we should change the casting rules to depart from XSD.

**Comment by johnlumley** [comment]
Is it worth adding a note in the spec emphasising that this only applies to constants and `parse-integer()`?

**Comment by michaelhkay** [comment]
The WG resolved to close this with no action on 2024-04-09.
