### ISSUE TITLE
Discrepancies in fn:hash() published examples

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#1109]
In the third example:

`hash("") `

the expected result has a spurious trailing letter "o". That's trivial and I will fix it.

In the seventh example:

`hash(serialize($doc), map{"algorithm": "sha-1"}) `

I am getting a completely different result, which I suspect is because I am getting a different result from `serialize()`. Perhaps the difference is something like a trailing newline, I don't know.

In my case the result of `serialize($doc)` is the 14-character string `"<doc>abc</doc>"`, which I believe is correct, but I suspect there might be other results of `serialize($doc)` that would also be conformant with the spec.

**Comment by ChristianGruen** [comment]
As I’ve edited the formatting of some `fn:hash` examples in #1078, I’ve just incorporated the correct test results into that PR to avoid conflicts.

**Comment by Arithmeticus** [comment]
Confirm fix in @ChristianGruen 's commit.
