### ISSUE TITLE
FLWOR tracing

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#111]
I've been developing a complex query involving grouping, windowing, and sorting, and finding it very hard to debug.

I propose a new clause that can be included anywhere in a FLWOR expression

`TraceClause ::= "trace" Expr`

for example

```
for $item in //items
trace "input: ", $item/@id
group by $sku := $item/sku
trace "group: ", data($sku), " items: ", data($item/@id)
return count($item) 
```

As with fn:trace(), the precise output is implementation-dependent.

The trace clause passes the incoming tuple stream unchanged to the next clause in the pipeline, with the side effect of evaluating an expression in the context of the variables defined in that tuple stream and displaying the value of the expression in an implementation-defined way.

**Comment by ChristianGruen** [comment]
I believe a more general solution would be to introduce a function that outputs items without returning them:

```xquery
for $item in //items
group by $sku := (fn:dump($item/@id), $item/sku)
return (
  fn:dump(data($sku), 'group: '),
  fn:dump(data($item/@id), 'items: '),
  count($item)
)
```

**Comment by michaelhkay** [comment]
Certainly it's a problem with trace(). I sometimes resort to things like

`return (trace((), data($sku)), count($item)`

where the useful content of the message is a computed label, and the value returned is (), which doesn't affect the result.

But this is addressing a different requirement, the ability to trace tuples as the pass through the tuple stream. A trace clause is much easier to insert and remove into a multi-line FLWOR expression, and it causes less problem to the optimiser than a function called for its side-effects.

**Comment by dnovatchev** [comment]
Why not a `monitor()` function that can internally access all variables and do whatever the developer needs: 

- Just dump them, or 
- validate a number of developer-specified condition and raise error(s) whenever any of these conditions is violated?

Something as unit tests that are executed in real time.

**Comment by ChristianGruen** [comment]
We could…

1. use `message` instead of `trace`, as FLWOR tracing will swallow the output results, whereas `fn:trace` passes items unchanged to the next expression.
2. use the same parameter order as for `fn:trace`/`fn:message`, with the 2nd parameter being optional. This way, we could still output items and labels differently:

```xquery
for member $m in [ (), 'a', ('b', 'c') ]
message $m, "• "
return $m

(: implementation-specific :)
• ()
• "a"
• "b", "c"
```

On the other hand…

1. `trace` would be shorter, and
2. maybe I’ve just become used too much to `fn:trace`.

**Comment by ndw** [comment]
Addressed adequately by `fn:message`

**Comment by ndw** [comment]
The CG agreed to close this issue without further action at [meeting 081](https://qt4cg.org/meeting/minutes/2024/06-11.html#close-without-action)
