### ISSUE TITLE
New error codes

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#1110]
The XQFO spec includes various “[TODO: error code]” comments. Should we add error codes when finalizing PRs, or does a master plan exist to add them at the very end?

**Comment by michaelhkay** [comment]
Best to add them now as they need to appear in tests.

**Comment by ChristianGruen** [comment]
It seems there are only 3 codes missing at the moment. Feel free to correct my suggestions (I’ve never understood the semantics behind the error codes…).

* [fn:hash](https://qt4cg.org/specifications/xpath-functions-40/Overview-diff.html#func-hash): `FOHA0001` ?
* [fn:op](https://qt4cg.org/specifications/xpath-functions-40/Overview-diff.html#func-op): `FOOP0001` ?
* [XQuery, Map Test](https://qt4cg.org/specifications/xquery-40/xquery-40-diff.html#id-map-test): …

**Comment by michaelhkay** [comment]
>I’ve never understood the semantics behind the error codes

Not so much semantics, as culture and tradition: they were introduced to the spec by an IBM old-timer, for whom 8 character alphanumeric codes are the instinctively natural way of distinguishing error conditions.

**Comment by ChristianGruen** [comment]
> The only tricky design decision is whether to allocate a new code or re-use an existing one. The current spec offers very little guidance on that. The key question to ask yourself is: if an application wanted to catch this error, how specific would it want it to be?

True. A custom error code for `fn:hash` seems appropriate; for `fn:op`, an existing code should work as well.

Newer EXPath modules use codes like `file:is-dir`, which are probably more intuitive, but I guess it’s too late to initiate that for XQFO as long as we don’t offer aliases for the existing codes.
