### ISSUE TITLE
XSLT - ability to call a function from xslt (not just xpath)

### ISSUE THREAD

**Issue by MarkNicholls** [qt4cg/qtspecs#1115]
I don't think this is possible in 3.0 and I don't think its yet suggested (whats the easiest way to find out)....if it has then close.

I wonder in passing many times why I ever use 

`<xsl:call-template.../>`

when functions exist?
I never use the data context inside a named template...feels dangerous.

So the only reason I do it, is because I can embed literal XML elements e.g.

```
<xsl:call-template name='foo'>
   <xsl:with-param name='barElement' as='element(barElement)'>
     <barElement/>
   <xsl:with-param/>


```
but if I could do

```
<xsl:call-function name='foo'>
   <xsl:with-param name='barElement' as='element(barElement)'>
     <barElement/>
   <xsl:with-param/>

```
then i would use functions always in preference to named templates.

motivation
- language simplification (though you'd have to keep named templates for legacy)
- you explicitly remove the data context (which I think is error prone in practice).
- if people used functions in preference to named templates then you would be able to use more of your code directly from x-path expressions.

**Comment by michaelhkay** [comment]
The fact that XSLT instructions can't be embedded within XPath expressions has already led to a lot of duplication of flow-of-control constructs between XSLT and XPath, so this wouldn't be unprecedented. but I'm not convinced that

```
<xsl:call-function name='foo'>
   <xsl:with-param name='barElement' as='element(barElement)'>
     <barElement/>
   <xsl:with-param/>
</xsl:call-function> 
```

is a significant improvement over

```
<xsl:variable name='barElement' as='element(barElement)'>
     <barElement/>
<xsl:variable/>
<xsl:sequence select='foo($barElement)'/>
```

**Comment by MarkNicholls** [comment]
Tbh using the context inside a named template I'd see at best as a warning. its effectively an implicit, untyped, global, mutable variable....it doesnt get much worse than that in my world, unless of course if it was concurrent, then I'd need a lie down.

Its not a ground breaking suggestion, I personally would never use named templates, and at least twice a week, I wouldn't have to do a minor 5 minute somersault to get code that is in a template referenced from some XPath map expression.

I'll leave it at that, lets see if anyone else has the same recurring ephemeral thought every time they type `<xslt:template name="....`

**Comment by michaelhkay** [comment]
It's implicit, yes, but it's not global and it's not mutable, and it's only untyped if you don't declare a type for it using xsl:context-item.

**Comment by MarkNicholls** [comment]
Ok, its not mutable....a stylesheet is effectively a state monad where the state is the data context, point taken.

In my book it is global though.

`'.'` is global (inside the templates).

If we were to write it as a state monad there would be a global function 

`getDataContext :: State -> (DataContext,State)`

and similarly when you set the DataContext

`setDataContext :: DataContent -> State -> ((),State)
`
`'.'` is simply shorthand for 

`(context,newState) =  getDataContext(state)`

so "state" is global too, its just implicit, because there is only 1 stylesheet state.

but this is all academic, and u may well disagree, some immutable global state is inevitable, from a practical point of view I want the language to be.

- as simple as possible
- as comprehensible as possible (not quite the same thing as simple)
- makes it hard to get something wrong by accident.

I think 
- functions are simpler
- implicit parameters aren't as comprehensible as explicit ones
- its very very very easy to get the wrong data context.

Tbh I'm more interested in making today's code simpler and friendly, not tomorrows code more powerful.
This suggestion isn't a breaking change, so it at least has that merit.

I'll get me coat.
P.S.

I'll look at `xsl:context-item`.

**Comment by dnovatchev** [comment]
> I don't think this is possible in 3.0 and I don't think its yet suggested (whats the easiest way to find out)....if it has then close.
> 
> I wonder in passing many times why I ever use
> 
> `<xsl:call-template.../>`
> 
> when functions exist? I never use the data context inside a named template...feels dangerous.
> 
> So the only reason I do it, is because I can embed literal XML elements e.g.
> 
> ```
> <xsl:call-template name='foo'>
>    <xsl:with-param name='barElement' as='element(barElement)'>
>      <barElement/>
>    <xsl:with-param/>
> ```
> 
> but if I could do
> 
> ```
> <xsl:call-function name='foo'>
>    <xsl:with-param name='barElement' as='element(barElement)'>
>      <barElement/>
>    <xsl:with-param/>
> ```
> 
> then i would use functions always in preference to named templates.
> 
> motivation
> 
> * language simplification (though you'd have to keep named templates for legacy)
> * you explicitly remove the data context (which I think is error prone in practice).
> * if people used functions in preference to named templates then you would be able to use more of your code directly from x-path expressions.

Why use XSLT at all, when all the processing could be done completely in XPath?

To me using `<xsl:call-template/>` , when the same can be presented as a much simpler XPath expression (just a function call),  seems strange and not justified.

And even in XSLT 2.0 there is the `<xsl:function>` declaration that people use to create their own (XSLT) functions that can be accessed just as regular functions from XPath expressions.

**Comment by MarkNicholls** [comment]
> Why use XSLT at all, when all the processing could be done completely in XPath?

For me XSLT has 2 USPs
- its convenient to embed the literal xml in it, but I'm open to other suggestions (I can do this in scala and visual basic).
- I find pattern matching a convenient mechanism to process/pipeline XML

So that's whats this stems from, I want to use XSLT in the most convenient way to embed literal xml, but for functions parameters I cant do that in XPath (?) and bizarrely I cant do that directly in XSLT, for me that's almost foundational, yes I can assign them to variables and then select them, but I can also do that for apply templates, but I largely don't, is it a habit? or is it inconvenient? probably a bit of both,

Data context are inherent in apply-templates pattern matching, in an analogous way to 'this' being inherent to OO dispatch, or the typeclass is to typeclass binding.....but they aren't inherent to named templates, and in my opinion, bad practice.

There is also a simple practical observation that I can debug XSLT code line by line in oxygen, but it doesn't really work for the xpath expressions....but again I'm open to suggestions, but I must admit, as I gain proficiency my XSLT code is getting thinner and my XPath expressions fatter, sometimes I wish that wasn't the case but the language is encouraging me to work like that.

**Comment by Arithmeticus** [comment]
I think an `xsl:call-function` would slightly confuse me. And I appreciate the asymmetry, which reminds me that (for my own coding style) a named template is usually less desirable than a function.

It looks like your main question/problem concerns not XSLT but XPath. That is, if you get some way to construct XML natively within XPath, problem solved, no?

**Comment by gimsieke** [comment]
> I think an `xsl:call-function` would slightly confuse me. And I appreciate the asymmetry, which reminds me that (for my own coding style) a named template is usually less desirable than a function.

I [made a case for preferring named templates over functions](https://subversion.le-tex.de/common/presentations/2020-07_Balisage_XSLT_Class-Attributes/slides/index.html#/34/2) (unless you need to call them in XPath expressions) since you can use tunnel parameters in named templates.

**Comment by MarkNicholls** [comment]
@Arithmeticus 

I have asked that question before, i.e. can I construct 'literal' elements inside xpath, thats useful but no, the USP for me is I can take an xml document and simply copy/paste it into an XSLT stylesheet, the fact that XSLT is XML makes this a natural embedding, doing that in XPath I think would always be clunky because XPath is just a string.

but I'm pleased you agree that 

functions > named templates

**Comment by MarkNicholls** [comment]
@gimsieke 

I'm not a fan of tunnel parameters, if you like them, then yes, I can see why you'd get to that conclusion.

ideally you could be able to call named templates from xpath (maybe you can) something like a function where you go

`<xsl:sequence select="fn:call-template('mytemplate',.,map {'param1' : 'value1','param2' : 'value2'})"/>
`

i.e. a function to be able to invoke a named template explicitly passing the data context and separately pass the params in a map.

(maybe it already exists?)

If you had tunnel params in functions, would you then be happy to let named templates go? (for new code)

then you get the best of both worlds, a simplification to the language, more operability between your code (if everything is a function, then the problem of calling named templates evaporates).

and the XSLT world is a very slightly simpler, more interoperable, slightly safer world.

sounds nice to me.

**Comment by Arithmeticus** [comment]
The advantage of `xsl:call-function` and its tunnel parameters has to do with preserving existing tunnel parameters. If I'm in mode A, with an unknown number of tunnel parameters, I can call template B and all tunnel parameters are preserved. But if I invoke a function from mode A, all tunnel parameters are lost. It's a very powerful feature of the language, that has been critically important in several business use cases. Thanks to @gimsieke for helping me appreciate that point a few years back. A corollary: always think twice before making a non-tunnel parameter, because 4 times out of 5, it's more useful as a tunnel parameter.

The other requirement I have for named templates is writing output via `xsl:result-document`. Can't do that in an XPath function, for security reasons (I presume).

**Comment by dnovatchev** [comment]
> > Why use XSLT at all, when all the processing could be done completely in XPath?
> 
> For me XSLT has 2 USPs
> 
> * its convenient to embed the literal xml in it, but I'm open to other suggestions (I can do this in scala and visual basic).
> * I find pattern matching a convenient mechanism to process/pipeline XML

It is quite easy to "embed" literal XML within XPath code - just use the **[`fn:parse-xml`](https://qt4cg.org/pr/1062/xpath-functions-40/Overview.html#func-parse-xml)** (or `fn:parse-xml-fragment`)

Not sure why people aren't aware of these functions - were in the F&O 3.0 Spec more than 10 years ago.

**Comment by michaelhkay** [comment]
Sadly, simplifying the language can only really be achieved by removing things, not by adding things. We can try and make the language more orthogonal, which is a kind of simplification, and that might mean making functions and templates more interchangeable:

* both could allow tunnel parameters
* both could allow passing the context item
* both could be called from XPath expressions
* both could be called from XSLT instructions
* both could allow named and positional parameters
* both could allow optional parameters

but that involves new syntax, new rules, new tests; and that's not simplification in my book.

**Comment by michaelhkay** [comment]
>Can't do that in an XPath function, for security reasons (I presume).

More to do with optimisation. Many of the "restrictions" on what you can do in functions are to keep them functionally pure, so for example a function can safely be moved out of a loop if the arguments don't depend on anything that changes in the loop. That can't be done if the function can have side-effects like creating result documents.

**Comment by michaelhkay** [comment]
>It is quite easy to "embed" literal XML within XPath code

Literal XML, yes. XML that's constructed on the fly, less so.

**Comment by dnovatchev** [comment]
> > It is quite easy to "embed" literal XML within XPath code
> 
> Literal XML, yes. XML that's constructed on the fly, less so.

It can be done exactly in the same way and as easily, but the XML string is not self-visualized as in the literal case.

**Comment by dnovatchev** [comment]
> The other requirement I have for named templates is writing output via `xsl:result-document`. Can't do that in an XPath function, for security reasons (I presume).

This can be done from within an XPath expression that contains a call to [**`fn:transform`**](https://www.w3.org/TR/xpath-functions-31/#func-transform). Thus one can write their own XPath library function that has the same functionality as `xsl:result-document`

**Comment by Arithmeticus** [comment]
In my experiments, the secondary results of `fn:transform` are not written to disk, but rather returned to the caller in a map as a result document. It's up to the caller to save those results to disk.

I'm pretty sure vendor-supplied functions do not have strictures on result documents.

**Comment by MarkNicholls** [comment]
> Sadly, simplifying the language can only really be achieved by removing things, not by adding things. We can try and make the language more orthogonal, which is a kind of simplification, and that might mean making functions and templates more interchangeable:
> 

absolutely, I've accepted your backwards compatibility argument, but that still doesnt stop us from defining a subset of these languages that span behaviour we want in a simpler more uniform way, and "deprecate" all the stuff we require to keep the wheels oiled on legacy.

> * both could allow tunnel parameters

I've never used them, they feel like "inheritance" and is too implicit for my tastes, but if this is required then absolutely consider it.

> * both could allow passing the context item

I personally wouldnt, you can explicitly pass a 'context' by defining a parameter, it is the implicit context I object to.
ok, you could have a 'special' param instruction to indicate the data context is passed (a bit like extension methods in C#), but the invisible nature of the data-context is what I think is unnecessary (just pass it).

> * both could be called from XPath expressions

if functions subsume templates, and we are only interested in preserving legacy, then is isn't required, that's explicitly not in the proposal.

> * both could be called from XSLT instructions

i.e. the original request, yes

> * both could allow named and positional parameters

again why? your constraint up to now has been that legacy must be preserved, now you seem to insist that legacy must be extended. If XPath doesnt require named templates, then why does XSLT except for legacy?

> * both could allow optional parameters

as above

> but that involves new syntax, new rules, new tests; and that's not simplification in my book.

I think you've misinterpreted (or I've communicated it poorly) the underlying intention (maybe due to my psuedo code example of how to call a template via a function), I've explicitly NOT suggested enhancing named templates, but to make them redundant by replacing them with a single language construct is more interoperable, more composable, safer (in my opinion), more explicit and comprehensible alternative that already exists, the function.

In a sense they are already partially deprecated because they aren't directly addressable from XPath expressions.

**Comment by MarkNicholls** [comment]
> > It is quite easy to "embed" literal XML within XPath code
> 
> Literal XML, yes. XML that's constructed on the fly, less so.

I think this is a USP of XSLT.

**Comment by dnovatchev** [comment]
> In my experiments, the secondary results of `fn:transform` are not written to disk, but rather returned to the caller in a map as a result document. It's up to the caller to save those results to disk.
> 
> I'm pretty sure vendor-supplied functions do not have strictures on result documents.

I think one needs to specify a value for this:

**_["base-output-uri (defaults to absent)"](https://www.w3.org/TR/xpath-functions-31/#func-transform)_**

**Comment by michaelhkay** [comment]
>As for "tunnel-parameters" ... very similar functionality is available in XPath by using ...

The motivating use case for tunnel parameters was the recursive-descent rule-based apply-templates pattern, where the essential characteristic is that as the stylesheet author you only have partial information about what the XML structure will look like, and therefore only have partial information about what templates will be invoked while walking the tree. This is particularly the case when you're overriding template rules to modify the behaviour of code that you can't directly change. If you want to change the way that citation/author is displayed, but you don't want to change all the template rules that might be invoked en route to citation/author, then tunnel parameters are a godsend.

There's nothing in conventional function calls that allow you to pass additional information through a stack of function calls without changing the source code of those functions.

**Comment by dnovatchev** [comment]
> There's nothing in conventional function calls that allow you to pass additional information through a stack of function calls without changing the source code of those functions.

The same way there is nothing in the chain of the "apply-templates stack" templates, that allows the templates to access the tunnel parameters or add additional tunnel parameters, without modifying the source code of those templates.

Thus, if we have the tunnel-data specified in a globally-accessible map (or quite similarly, in a conventional `$this` variable), then no function in the call stack (except the one that uses this data) needs to be aware of the existence of this map.

Indeed, there might be a lot happening behind the scenes in order to provide this feature, but the developer is not concerned in any such implementation details - exactly as we want them to be - comfortable and unconcerned.

**Comment by michaelhkay** [comment]
@dnovatchev No, you've missed the point.

Tunnel parameters differ from global variables in that they don't have to be constant for the duration of a transformation, and they differ from local parameters in that they don't need to be explicitly passed through every function/template on the call stack. You've clearly never used this feature in anger -- it can be a life-saver.

**Comment by MarkNicholls** [comment]
@michaelhkay 

> The motivating use case for tunnel parameters was the recursive-descent rule-based apply-templates pattern, where the essential characteristic is that as the stylesheet author you only have partial information about what the XML structure will look like, and therefore only have partial information about what templates will be invoked while walking the tree. This is particularly the case when you're overriding template rules to modify the behaviour of code that you can't directly change. If you want to change the way that citation/author is displayed, but you don't want to change all the template rules that might be invoked en route to citation/author, then tunnel parameters are a godsend.
> 
> There's nothing in conventional function calls that allow you to pass additional information through a stack of function calls without changing the source code of those functions.

this is quite interesting, can you give me a reference to an specific example? it doesnt need to be XSLT (though that helps).

**Comment by MarkNicholls** [comment]
> @dnovatchev No, you've missed the point.
> 
> Tunnel parameters differ from global variables in that they don't have to be constant for the duration of a transformation, and they differ from local parameters in that they don't need to be explicitly passed through every function/template on the call stack. You've clearly never used this feature in anger -- it can be a life-saver.

I'm interested in this, but to be clear, the proposal and motivation is not about removing or even deprecating match templates.

**Comment by michaelhkay** [comment]
Tunnel parameters only really come into their own when the stylesheet becomes fairly complex, so simple examples tend to be rather artificial.

There's a reasonably simple use at https://github.com/qt4cg/qtspecs/blob/master/specifications/xslt-40/src/xml-to-json.xsl It's simple enough to show how the feature works, but not complex enough to show why the feature is needed.

More complex examples can be found in Phil Fearon's syntax highlighter at https://github.com/qt4cg/qtspecs/blob/master/lib/xmlspectrum/xsl/highlight-file.xsl

and in the code for handling diff markup at https://github.com/qt4cg/qtspecs/blob/master/style/xsl-query-2016.xsl

**Comment by MarkNicholls** [comment]
this is very off topic so feel free to ignore, I've looked at those and still not really got it, I cant see how it does anything more than save typing? so I cant see the life saving? (Maybe RSI saving).

It feels like object inheritance but here its parameters, so you save typing but you lose transparency.

so this

> This is particularly the case when you're overriding template rules to modify the behaviour of code that you can't directly change. If you want to change the way that citation/author is displayed, but you don't want to change all the template rules that might be invoked en route to citation/author, then tunnel parameters are a godsend.

is the equivalent of saying (with hand waving) in OO, if I want to change the behaviour of some subclass that requires  a new parameter, I can add it to the subclass as a new field, and it is effectively invisible to to all superclass (its automatically passed through on "this").

So in the OO case the claim is you can 'extend' some behaviour in isolation? and this is the same?

without it you have to change all the templates in the call chain?

in a closure the parameter is embedded in the closure, but as stylesheets can't be nested in a closure I see how that applies to XPath but not to XSLT.
and this is similar?

**Comment by michaelhkay** [comment]
Don't try to cast this into the metaphor of object-oriented programming. XSLT is rule-based processing, the paradigm is completely different.

**Comment by MarkNicholls** [comment]
I was attempting and failing to introduce a lingua franca

hmmmm...ok...I'll just have to believe you, I cant envisage a specific scenario that you're describing.

mapping an XML to html and someone wanting to pass say, the colour of the a heading in, would be a painful experience if you had to pass it from root to tip...and I can see tunnelling being a convenient mechanism to do that (though that's basically analogous to my OO example)

youre describing something more subtle than that....anyway this isnt training for me....so lets leave it...I am intrigued though.

**Comment by michaelhkay** [comment]
I'm going to propose closing with no action. There's been an interesting discussion, but I don't think the proposed feature (an XSLT instruction to call functions) has sufficient benefit to justify itself.

**Comment by ndw** [comment]
The CG agreed to close this issue without further action at [meeting 073](https://qt4cg.org/meeting/minutes/2024/04-16.html).
