### ISSUE TITLE
unparsed-text() end-of-line normalization

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#1116]
I'm uncomfortable with the backwards-incompatible change we have made to `unparsed-text()` which now normalizes line endings.

I think it's unlikely that there are many users who care about the difference between LF and CRLF line endings and want to preserve that difference; but I think it's very likely that there are users who have written application code that expects the line ending to be CRLF, where the application will break if the line ending changes.

I would be more comfortable with the change if there were an option setting to revert to the 3.1 behaviour. But my preference would be to add the option and keep the default compatible with 3.1.

Also, for users who want to treat the file as a sequence of lines, we already introduced `unparsed-text-lines()` so they don't have to worry about different representations of line endings.

**Comment by MarkNicholls** [comment]
as per a recent SO question about handling this sort of thing, this is horribly difficult when creating things like spreadsheet xmls, where you need to know where the wrinkles are to get it all coming out in the correct formatting.
I don't know whether this would break it, but it would upset a lot of people if it did.

**Comment by michaelhkay** [comment]
I've proposed an options parameter with `'normalize-newlines' : true`.

Note that a custom option to normalize newlines while reading the data is likely to be a lot more efficient than reading all the data and then post-processing it with a regular expression.

**Comment by cedporter** [comment]
FWIW, there's an expectation that when you release a new X major version there may be breaking changes. If normalization is the desired behavior for the vast majority of use cases, defaulting to that with an option to toggle off normalization makes sense to me.
