### ISSUE TITLE
Abbreviate `map:function($someMap)` to `$someMap?function()`

### ISSUE THREAD

**Issue by dnovatchev** [qt4cg/qtspecs#112]
The title says it all.

We already have a proposal to be able to have (when `$m` is a map and `$x` is a variable of type `xs:string`):

```xq
$m?$x
```
instead of: `map:get($m, $x)`

The next logical step is to allow the RHS of the `?` operator to be any of the standard functions in the namespace "http://www.w3.org/2005/xpath-functions/map" (with the standard prefix "map:".

Thus, instead of `map:keys($m)`  or `$m => map:keys()`

One would simply write:

`$m?keys()`

**Comment by ChristianGruen** [comment]
I think the proposed expression would introduce an ambiguity, as the following expression is already valid (it returns `SUCCESS`):

```xquery
let $m := map { 'keys': function() { 'SUCCESS' } }
return $m?keys()
```

Next, we would you need to clarify what is going to happen if an array is provided as LHS (or any other function item, as proposed in #51).

**Comment by dnovatchev** [comment]
@ChristianGruen, Yes, if an existing key happens to be a function with exactly the same name and signature, then getting the key from the map will have a higher precedence.

As for any overlap with #51, the current proposal allows on the RHS _only standard Xpath functions that are in the `map` namespace_.

Maybe it would be good if you could provide a specific example?

**Comment by dnovatchev** [comment]
> I think the proposed expression would introduce an ambiguity, as the following expression is already valid (it returns `SUCCESS`):
> 
> ```xq
> let $m := map { 'keys': function() { 'SUCCESS' } }
> return $m?keys()
> ```
> 
> Next, we would you need to clarify what is going to happen if an array is provided on the LHS (or any other function item, as proposed in #51).

@ChristianGruen,

The above will call the function `map:keys()` on the map `$m`

On the other side, this expression gets the value of the key `"keys"` and then call it as a function, producing `"SUCCESS"`:

```xq
let $m := map { 'keys': function() { 'SUCCESS' } }
return ($m?keys)()
```

**There is absolutely no ambiguity!**

**Comment by dnovatchev** [comment]
> Maybe it would be good if you could provide a specific example?
> 
> ```xq
> array { }?keys()
> ```

@ChristianGruen,

Sorry, but what is the problem here? Please, help me understand.

What are the two different ways to interpret this expression?

Thanks,
Dimitre

**Comment by ChristianGruen** [comment]
> There is absolutely no ambiguity!

Sorry, I can't follow you. What will be returned by `$m?keys()` if the value of `$m` is unknown at compile time?

> `array { }?keys()`

Which error will be raised by this expression?

**Comment by michaelhkay** [comment]
I don't think there's a syntactic ambiguity here, because in 3.1 the RHS of "?" has to be one of

`KeySpecifier	::=   NCName | IntegerLiteral | ParenthesizedExpr | "*"`

and we're already used to the idea that if an NCName is followed by "(" then it's treated differently.

What there is, however, is a significant semantic overloading of the "?" operator. Currently all the different forms of "?" indicate lookup of entries in the map; using the same operator to apply a function to the map as a whole seems very confusing to me.

Of course, it would be great to get rid of the ugly `map:` prefix in calls like `map:keys($m)` (or `$m => map:keys()`). I've explored ways of doing that by having some kind of "namespace search list" for unprefixed function names but I can't say I've found a good solution along those lines. Another approach would be for the function name resolution after "=>" to be polymorphic based on the type of the LH operand, but again it quickly gets very complicated.

It's worth remembering that the problem we're trying to solve here is fairly cosmetic, and while cosmetics matter, we don't want to impose a lot of new semantic complexity that people have to master in order to achieve it.

**Comment by dnovatchev** [comment]
> Of course, it would be great to get rid of the ugly `map:` prefix in calls like `map:keys($m)` (or `$m => map:keys()`). I've explored ways of doing that by having some kind of "namespace search list" for unprefixed function names but I can't say I've found a good solution along those lines. Another approach would be for the function name resolution after "=>" to be polymorphic based on the type of the LH operand, but again it quickly gets very complicated.

This is exactly the intent of this proposal. There would be no need to use `?`, instead we could use `->` or some other string that is not overloaded with different meanings. But the main thing is to get read of the namespace, as correctly noticed above!

> 
> It's worth remembering that the problem we're trying to solve here is fairly cosmetic, and while cosmetics matter, we don't want to impose a lot of new semantic complexity that people have to master in order to achieve it.

Here I disagree. This feature closely resembles how objects in the OOP world have a set of methods (and generally members). So it would be extremely useful to be able to specify: "All functions of the `map:` namespace are the (standard/given) methods of the `map object` "

These can even be the key-value pairs of a map, that is the value of special, standard key (something like "hidden directories" in a file-system. 

Different programming languages do have such features. For example in Python every object has special (system / default / given) properties whose names start and end with "__" (double underscore), and there is even a convention that a name "\_\_name\_\_" is pronounced as "dunder-name".

Javascript has `Object.fromEntries()`, `Object.prototype`, etc.

C# provides syntax for adding "extension methods" to any object and these can be invoked with the same syntax as invoking the original, own methods of the object.

Similarly, we could alter the map constructor, by adding a new argument that is a namespace, and this would mean that all things (functions, constants etc.) living under this namespace automatically become key-value pairs of its special "hidden/system" sub-map.

One of the goals of this proposal is to provoke discussion. 

Let us all contribute with our feedback so that we could gradually produce an elegant and useful result.

**Comment by michaelhkay** [comment]
I'd like to suggest that we use the syntax

`*:local-name(arg0, arg1, ....)`

or

`arg0 => *:local-name(arg1, arg2, ...)`

for a polymorphic function call. A polymorphic function call makes a decision which function to call based on the dynamic type of the first item in arg0. Based on this dynamic type, there is a **candidate namespace list**, and the function that is chosen is found by searching the candidate namespace list for a namespace N such that (a) a function with namespace N and matching local name exists, (b) the function has suitable arity, and (c) the actual dynamic type of arg0 satisfies the type required by the function signature; the function chosen is the first one that meets these criteria.

- If arg0 is an empty sequence, then the candidate namespace list is (math, fn, xs)
- If arg0[1] is a map, then the candidate namespace list is (map, fn)
- If arg0[1] is an array, then the candidate namespace list is (array, fn)
- If arg0[1] is an atomic value or a node, then the candidate namespace list is (math, fn, xs)
- In all other cases, the candidate namespace list is (fn)

The net practical effect for most users is simply that you can call map and array functions using (for example) `*:remove(...)` in place of `map:remove(...)` - with the additional benefit (especially in XSLT) that you don't have to declare the map namespace. (Declaring extra namespaces is not just noisy and verbose, it also creates bloat in the static context that has to be carried around even at run-time, just in case someone does a cast-to-QName using that namespace prefix).

**Comment by ChristianGruen** [comment]
If I get it right, this would trigger `map:remove` for the first function call and `fn:remove` for the second one:

```xquery
let $seq := (map { 1: 2 }, map { 3: 4 }, map { 5: 6 })
return (
  *:remove(head($seq)),
  *:remove(tail($seq))
)
```

Isn’t this a bit fishy? I see similarities to the problematic dynamic type dependency of predicates, or the proposal I made in https://github.com/qt4cg/qtspecs/issues/50#issuecomment-761759550 for the lookup operator (which got rejected, and I understand why).

> Declaring extra namespaces is not just noisy and verbose, it also creates bloat in the static context that has to be carried around even at run-time, just in case someone does a cast-to-QName using that namespace prefix.

I can understand that this is an implementation issue for XSLT that seems to be hard to resolve economically. From a user perspective, though, I would clearly vote for having statically defined namespaces.

**Comment by dnovatchev** [comment]
> If I get it right, this would trigger `map:remove` for the first function call and `fn:remove` for the second one:
> 
> ```xq
> let $seq := (map { 1: 2 }, map { 3: 4 }, map { 5: 6 })
> return (
>   *:remove(head($seq)),
>   *:remove(tail($seq))
> )
> ```
> 
> Isn’t this a bit fishy?

Not even a little bit. 

Both function calls must raise an error, because both **`fn:remove`** and **`map:remove`** require a second argument, but only one argument is supplied in each function call.

If the example was:

```xq
let $seq := (map { 1: 2 }, map { 3: 4 }, map { 5: 6 })
return (
  *:remove(head($seq), 1),
  *:remove(tail($seq), 1)
)
```

then strictly following the rules provided by his last comment:



> * f arg0 is an empty sequence, then the candidate namespace list is (math, fn, xs)
> * If arg0[1] is a map, then the candidate namespace list is (map, fn)
> * If arg0[1] is an array, then the candidate namespace list is (array, fn)
> * If arg0[1] is an atomic value or a node, then the candidate namespace list is (math, fn, xs)
> * In all other cases, the candidate namespace list is (fn)

The processor would correctly produce the expected result:

`( map{}, map{5:6} )`

Or did I accidentally do something wrong here?

**Comment by ChristianGruen** [comment]
> Both function calls must raise an error,  […]

You are obviously right, I intercepted the second argument in the example.

> The processor would correctly produce the expected result:

The rules are unambiguous, true. I wanted to imply that users are easily confused if a polymorphic function call is evaluated differently when the supplied input changes. Think of `*:remove(tail($seq), 1)`:

* If `$seq` happens to have 1 or 3 items, `fn:remove` is chosen.
* If `$seq` has 2 items, `map:remove` will be chosen.

**Comment by dnovatchev** [comment]
> The rules are unambiguous, true. I wanted to imply that users are easily confused if a polymorphic function call is evaluated differently when the supplied input changes. Think of `*:remove(tail($seq), 1)`:
> 
> * If `$seq` happens to have 1 or 3 items, `fn:remove` is chosen.
> * If `$seq` has 2 items, `map:remove` will be chosen.

Yes, the edge case, if I understand it well, is when we have a sequence of one item and this item is a map. In this case, shall we consider the argument to **`*:remove()`** to be a map or to be a sequence, and correspondingly, resolve this to a call to **`map:remove`** or to **`fn:remove`** ?

I think that such ambiguities arise in many similar cases. We may need to introduce a **_sequence constructor_**, something like **`fn:sequence($arg1 as item()) as sequence`**, and an explicit **_sequence_** type.

While this would be cleaner, I think that one may even now, with the currently available syntax, indicate that a single argument is to be treated as a sequence, by just enclosing it in `()`, like this:

`*:remove(($arg), 1)`

or like this:

`*:remove(($arg, ()), 1)`

And in a case when we know that we want to remove the only item from a single-item sequence, calling `fn:remove` wouldn't be necessary, as we could simply write `()` and avoid the unnecessary overhead.

**Comment by michaelhkay** [comment]
Propose to close with no action. While there is support for the aspiration of introducing some kind of polymorphism, the discussion here has not come up with a consensus proposal. If we still want to do this, we're going to have to start with a clean slate with some new ideas.

**Comment by ndw** [comment]
At [meeting 039](https://qt4cg.org/meeting/minutes/2023/06-20.html#open-pull-requests) the CG agreed to close this issue without further action.
