### ISSUE TITLE
let clause: function coercion

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#1139]
@michaelhkay I should be careful (as I regularly miss changes and additions in the 4.0 drafts), but it seems that the application of the function coercion rules for typed `let` clauses (https://qt4cg.org/specifications/xquery-40/xquery-40.html#id-binding-rules) is not mentioned in the list of substantive changes at the end of the document. Would it be useful to add it, or does this change fall into a different category?

**Comment by michaelhkay** [comment]
I stopped routinely adding to the changes appendix with each PR on the grounds that it was leading to a large number of GIT conflicts. Instead I was proposing to do a periodic review and update of the list.

Appendix L1 of the XQuery spec does however list this change in list item 16:

> In XQuery, the coercion rules are now used when binding values to variables (both global variable declarations and local variable bindings). This aligns XQuery with XSLT, and means that the rules for binding to variables are the same as the rules for binding to function parameters.

**Comment by ChristianGruen** [comment]
Thanks.
