### ISSUE TITLE
fn:deep-equal: items-equal

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#1142]
The current spec says about `items-equal` that…

> If this option is present then the `ordered` option MUST be `true` and the `unordered-elements` option MUST be an empty sequence.

I doesn’t say what is going to happen if `ordered` is `false` or if `unordered-elements` is non-empty.

My preference would be to allow all combinations; we could then do things like:

```xquery
deep-equal(
  (1, 2, 3),
  (3.1, 2.1, 1.1),
  { 'ordered': false(), 'items-equal': fn($a, $b) { xs:integer($a) = xs:integer($b) } }
)
```

It may imply O(n²), but it’s very simple to formulate other XPath expressions with the same complexity, such as `$huge1[. = $huge2]`.

**Comment by michaelhkay** [comment]
> it’s very simple to formulate other XPath expressions with the same complexity, such as `$huge1[. = $huge2]`.

The semantics of `=` are known, so it's easy enough to implement this with a hash join. That isn't true when you have an equality operator with opaque semantics.

**Comment by ChristianGruen** [comment]
> The semantics of `=` are known, so it's easy enough to implement this with a hash join.

Maybe it is, in theory, but in many cases you won’t experience it in the wild. Just run a query as basic as the following one with Saxon:

```xquery
count(
  let $seq := (1 to 100000) ! string()
  return $seq[. = $seq]
)
```

This specific query is certainly made up, but it is simple to find real use cases with the same runtime, for example, if you want to find the intersection of two sequences of strings; if you want to use items that only occur in one list, using `$seq1[not(. = $seq2)]`; etc.

An advanced user can always generate a map or something else to speed this up. The same is true for `deep-equal`, as I believe: Whenever you notice that the processor you use won’t rewrite your quadratic runtime, you can do it on your own.

**Comment by michaelhkay** [comment]
OK, I'll remove the restriction. I agree, it's a bit paternalistic. Orthogonality wins.
