### ISSUE TITLE
[xsl:item-type] error in sample

### ISSUE THREAD

**Issue by cmarchand** [qt4cg/qtspecs#1154]
Here : https://qt4cg.org/specifications/xslt-40/Overview-diff.html#named-item-types

First sample is
```
<xsl:item-type name="cx:complex" as="record(r as xs:double, i as xs:double)"/>

<xsl:variable name="i" as="cx:complex" select="cx:number(0, 1)"/>
```

`xsl:variable/@select` should probably be `cx:complex(0, 1)` instead of `cx:number`

**Comment by michaelhkay** [comment]
Thanks for reporting it. (It resulted from an incomplete rewrite of the example when constructor functions for records were introduced). PR raised.
