### ISSUE TITLE
Maps & Arrays: Consistency & Terminology

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#1169]
After the introduction of #1094 and #1159, and before adding more map/array operations, I think it’s time to get more serious about consistency and terminology. The current drafts employ a variety of terms that are not clearly defined, or separated from each other. We now have at least…

> items, members, pairs, keys, values, entries

…which are sometimes used for maps, for arrays, or for both data structures. A first attempt to clean up, with reducing the overall effort:

1. A minor one: The modifier for lookups should be in singular form, analagous to node axes: `item`, `key`, `value`, `pair`.

2. While I first advocated the orthogonality principle for axes in lookup expressions, I now think we should stick to the existing terminology. Otherwise, we would need to revise many other existing parts of the spec. My suggestion would be to:

* introduce `member` for arrays
* only allow `key`, `value` and `pair` for maps
* allow `items` for both maps and arrays

This would make it symmetric with a) the current terminology for maps and arrays, and b) enhanced `for` clauses, i.e. `for member $m` and `for key $k value $v`.

The reverse approach would be to drop `for member $m` and to also allow `for key $k value $v` for arrays (with `for value` replacing `for member`). In addition, we could have `for pair`.

3. With the introduction of the `item` axis, `map:values` and `arrays:values` should be renamed to `map:items` and `array:items`. → `map:contents` and `array:contents`, see [#1179](https://github.com/qt4cg/qtspecs/issues/1179)

4. I would suggest dropping `array:members` and `array:of-members`. The names don’t imply we’ll deal with records, and it’s not in line with `for member $m` either. If we want to keep these functions, we could rename them to `array:pairs` and `array:of-pairs` and add the integer positions as keys, and we should introduce and consistently use the term `pair` for maps and arrays.

Closely related: #826

**Comment by michaelhkay** [comment]
>A minor one: The modifier for lookups should be in singular form, analagous to node axes: item, key, value, pair.

I'm fine with that.

>introduce member for arrays
>only allow key, value and pair for maps
>allow items for both maps and arrays
>This would make it symmetric with a) the current terminology for maps and arrays, and b) enhanced for clauses, i.e. for member $m and for key $k value $v.

The minimal set would probably be 

* item (or content) for both maps/arrays
* pair for maps
* members for arrays

>With the introduction of the item axis, map:values and arrays:values should be renamed to map:items and array:items.

Can't say I like the effect much. But I'm not happy with our over-use of `value` either. Perhaps `content` is better.

>I would suggest dropping array:members and array:of-members. The names don’t imply we’ll deal with records, and it’s not in line with for member $m either. If we want to keep these functions, we could rename them to array:pairs and array:of-pairs and add the integer positions as keys, and we should introduce and consistently use the term pair for maps and arrays.

Yes that seems feasible.

Now the other thing in my mind is to try and unify this with labels. If we deliver the results of a lookup as maps containing key + value, why shouldn't the result also contain accessor functions equivalent to the fields in a label: specifically parent() and ancestors()? The two features definitely have significant overlap.

**Comment by ChristianGruen** [comment]
> Now the other thing in my mind is to try and unify this with labels. If we deliver the results of a lookup as maps containing key + value, why shouldn't the result also contain accessor functions equivalent to the fields in a label: specifically parent() and ancestors()? The two features definitely have significant overlap.

Sounds reasonable (I haven’t spent time on/with pins and labels yet, I should do so soon). Would `$map?pin::*` or `$map?label::*` make sense? Regarding the naming, I felt similar to @cmsmcq that I would tend to associate “labels” with plain strings. Alternative terms for pins and labels that show their correlation could possibly be beneficial, now that we confront our poor (or brave) users with so many new concepts.

**Comment by michaelhkay** [comment]
>I would suggest dropping `array:members` and `array:of-members`.

The main benefit of these functions is probably as primitives that can be used to define the semantics of all the other functions concisely. 

For example we currently define array:join rather concisely as 

`array:of-members($arrays ! array:members(.))`

Perhaps private functions could serve the same purpose. But if these functions are so useful as primitives, one feels that they would be useful tools for end-users as well.

**Comment by ChristianGruen** [comment]
If we drop `array:members`, we could rename `array:split` to `array:members`:

```xquery
map:merge(map:entries($map))
array:join(array:members($array))
```

This would feel intuitive to me, as the current spec terminology (as far as I can judge) regards array members as the counterparts of map entries.

**Comment by michaelhkay** [comment]
Indeed, the two function pairs `array:split/join` and `array:members/of-members` differ only in the way that they represent a "parcel", that is, the way they package a sequence as a single item. There's not a big difference, and although the latter pair seems a little more "type-safe" to me (converting an array of sequences to a sequence of arrays can be a bit confusing...), it's probably true that the first pair have a wider range of application, meaning that if either pair goes, it should be the second.

**Comment by michaelhkay** [comment]
Actually, I'm a bit confused about the spec of array:split.

What is the result of `array:split([ (1,2), (3,4) ])`?

The notes say

> The function call array:split($array) produces the same result as the expression `for member $m in $array return [ $m ].`

Which makes the result `( [(1, 2)], [(3, 4)] )`.

But this is only in the notes, and the actual rules are very informal; and none of the examples makes this clear. The only example that touches on it is the fourth example, and that one would work equally well if the result were `( [1,2], [3,4] )` -- which is probably the result many users would expect.

More examples are needed, and the first note should be moved into the normative rules.

**Comment by ChristianGruen** [comment]
> What is the result of `array:split([ (1,2), (3,4) ])`?
> ...
> Which makes the result `( [(1, 2)], [(3, 4)] )`.

Yes, that's supposed to be the result. Otherwise, the result could not be reversed (which is what I wanted to point out with “This function is the inverse of `array:join`.”):

```xquery
(: [ 1, 2, 3, 4 ] :) 
array:join([ 1, 2 ],[ 3, 4 ])
```

> But this is only in the notes, and the actual rules are very informal; and none of the examples makes this clear.

True; sorry for that, and thanks for the hints. I still fail to understand what information is required to make the rules comprehensive enough (there are various functions, like `array:fold-left`, which don't have informal rules at all, possibly due to historical reasons?). I’ll be glad to revise the presentation once we decide which functions we want to keep.

**Comment by ndw** [comment]
At [meeting 095](https://qt4cg.org/meeting/minutes/2024/10-22.html), the CG agreed to close this issue with no further action.
