### ISSUE TITLE
Predicates returning xs:boolean vs. xs:boolean?

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#1171]
In [4.13.4  Filter Expressions for Maps and Arrays](https://qt4cg.org/specifications/xquery-40/xquery-40.html#id-filter-maps-and-arrays), the type of the predicate expression `FILTER` is `xs:boolean?`.

To be consistent, we should either relax the types of the predicate/filter functions (for `fn:filter`, etc.) or stick with `xs:boolean`.

**Comment by michaelhkay** [comment]
Closed by #1182
