### ISSUE TITLE
array:build, map:build: Positional access

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#1173]
`array:build` seems to be the only function (for iterating over ordered input) for which the HOF parameters lacks a positional parameter:

```xquery
array:build(
  $input   as item()*,	
  $action  as function(item()) as item()*  := fn:identity#1
) as array(*)

(: should be :)
array:build(
  $input   as item()*,	
  $action  as function(item(), xs:integer) as item()*  := fn:identity#1
) as array(*)
```

**Comment by MarkNicholls** [comment]
As a comparison

The idiomatic functional way to 'build' an array is 'unfold' (actually the idiomatic way to build any non trivial data type is in a sense 'unfold')

see [origami](https://www.cs.ox.ac.uk/jeremy.gibbons/publications/origami.pdf)

(this is adopted pretty widely, Haskell, Scala, F# etc)

**Comment by MarkNicholls** [comment]
for comparison:

1. build is almost bind.

bind would be

```
array:bind(
   $input as array(*),
   $binder as function(item()) as array(*)
) as array(*)
```

bind is a way to query a data structure rather than to build it, you would usually 'unfold' it, 'bind'/'map'/'apply' it to the same structure, and 'fold' it into other structures.

**Comment by ChristianGruen** [comment]
I’ve just had an interesting use case where I created an inverted index with `map:merge` as simple as that:

```xquery
map:merge(for-each($data, map:entry#2))
```

Maybe there are use cases for which the `position` argument would also be helpful for the function parameters of `map:build`?
