### ISSUE TITLE
Editorial: `array:values`, `map:values`

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#1179]
Triggered by #1087:

1. Align `map:values` with `array:values`
2. Revise notes.
3. Rename the functions.

@michaelhkay You suggested that `content` might be a better name – rather than `item` – for retrieving the sequence-concatenation of values in map lookups in https://github.com/qt4cg/qtspecs/issues/1169#issuecomment-2074378446. Should we rename the functions to `array:contents`, `map:contents` or use `array:items` and `map:items`?

**Comment by michaelhkay** [comment]
"content" does seem a better name than "values". The current name "values" suggests that it simply returns the values that are already present, without any hint of a flattening operation.
