### ISSUE TITLE
Function: distinct document order

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#1189]
The nodes resulting from path traversals are normalized by restoring document order and removing duplicates. There are use cases where this operation needs to be enforced, for which people do things like…

```xquery
$nodes/.
$nodes/self::node()
$nodes union ()
$nodes except ()
```

…which all look arcane to occasional readers, and are prone to be accidentally optimized away.

It would be sensible to have a helper function that makes this operation explicit, so that users have some clue that something intentional is going on. Some articles called this postprocessing step *distinct document order*, which is why we added `util:ddo` in the past – but I would love to find a both canonical and catchier name for it.

**Comment by michaelhkay** [comment]
Indeed, I would be in favour of having such a function, but it's hard to find a good name for it. The best I can come up with is `ordered-nodes`.

(But if accidentally mis-optimizing these expressions is the problem, then creating this function won't solve it...)

**Comment by ChristianGruen** [comment]
> (But if accidentally mis-optimizing these expressions is the problem, then creating this function won't solve it...)

True, we won’t have a guarantee that this concept will be understood by everyone. In a current case, I had to debug code that originally included a `$data/.` expression, and which was rewritten to `$data` as “`/.` seemed completely pointless”. Took me quite a while. A `fn:ordered-nodes` (or `fn:distinct-order` ?) function call might have stopped the human optimizer.

**Comment by ChristianGruen** [comment]
…or `fn:distinct-nodes`. Maybe the name does not matter too much, as long as the behavior is documented somewhere (it won’t be used very frequently).

**Comment by michaelhkay** [comment]
Perhaps just spell it out in full: `distinct-ordered-nodes()`. Sometimes there's no harm in verbosity.

**Comment by ChristianGruen** [comment]
> Perhaps just spell it out in full: `distinct-ordered-nodes()`. Sometimes there's no harm in verbosity.

+1 (and still 1 character shorter than `fn:random-number-generator`).

**Comment by dnovatchev** [comment]
> The nodes resulting from path traversals are normalized by restoring document order and removing duplicates. There are use cases where this operation needs to be enforced, for which people do things like…
> 
> ```xq
> $nodes/.
> $nodes/self::node()
> $nodes union ()
> $nodes except ()
> ```
> 
> …which all look arcane to occasional readers, and are prone to be accidentally optimized away.
> 
> It would be sensible to have a helper function that makes this operation explicit, so that users have some clue that something intentional is going on. Some articles called this postprocessing step _distinct document order_, which is why we added `util:ddo` in the past – but I would love to find a both canonical and catchier name for it.

Let us not forget that for a sequence of nodes belonging to 2 or more documents, the ordering is unpredictable.

People may need to know the exact sequences of nodes from each of the documents - something that is lost with the proposed function.

Maybe return a map, whose keys are all the document nodes, and the value for each key is the ordered nodes from that document.

Probably this needs to be a separate function. I am not sure if we can specify a union type for the result-type of a function, and even if this is possible, it seems create problems rather than solve problems.

**Comment by michaelhkay** [comment]
People may need to know the exact sequences of nodes from each of the documents

That would be 

```
let $is-different-doc := fn($m, $n) { not ( root($m) is root($n) }
return distinct-ordered-nodes($nodes) => 
    partition( split-when := fn($group, $next){ $is-different-doc( foot($group), $next )})
```

**Comment by ChristianGruen** [comment]
Accepted at [meeting 077](https://qt4cg.org/meeting/minutes/2024/05-14.html).
