### ISSUE TITLE
Allow "fn" as abbreviation for "function" in ItemType syntax

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#1192]
The syntax for inline functions is, by design, similar to the syntax for function tests. So it's confusing that you can abbreviate "function" to "fn" in the first case but not the second.

Open question: what about "declare function" in the XQuery prolog? My instinct is to leave that as it is.

**Comment by ChristianGruen** [comment]
> The syntax for inline functions is, by design, similar to the syntax for function tests. So it's confusing that you can abbreviate "function" to "fn" in the first case but not the second.

Sounds good.

> Open question: what about "declare function" in the XQuery prolog? My instinct is to leave that as it is.

I agree; we shouldn’t trigger the desire for other abbrv.s like `decl(are) var(iable)`.

**Comment by michaelhkay** [comment]
Closed by #1197
