### ISSUE TITLE
XQFO: Rendering of new/updated functions

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#1202]
It’s not always clear in the XQFO draft what has been updated when a function is marked as such. In the attached examples (there are several cases), either the `Changed` section is missing, or the renderer fails to detect that the function has not actually changed:

----

![image](https://github.com/qt4cg/qtspecs/assets/196589/0c616f31-278a-4147-9266-8d8f5d51378d)

**Comment by michaelhkay** [comment]
Having dealt change markings on all the other documents that link changed sections directly to the PRs that affected them, doing the same for F&O is on my TODO list.
