### ISSUE TITLE
Detailed comments on math:e, sinh(), cosh(), tanh()

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#1216]
I should have made these comments before we accepted the proposal, but it's only minor details.

In the example given for `math:e`, the explanation of the example as a compound interest calculation seems a bit simplistic. There are all sorts of assumptions here about the initial investment, the frequency at which interest is calculated, etc. It might be better just to give the expression and the result and not attempt an interpretation.

According to IEEE 754-2008 table 9.1, `sinh()` can produce overflow or underflow, `cosh()` can produce overflow, and `tanh()` can produce underflow. We seem to be catering for exceptions that cannot occur?

The example results should perhaps be tagged as approximate to ensure that they pass automated testing.

We should perhaps be referencing IEEE 754-2019 (though I'm reluctant to purchase a copy...)

**Comment by ChristianGruen** [comment]
> In the example given for `math:e`, the explanation of the example as a compound interest calculation seems a bit simplistic. There are all sorts of assumptions here about the initial investment, the frequency at which interest is calculated, etc. It might be better just to give the expression and the result and not attempt an interpretation.

True; I wasn’t happy about it anyway.

> According to IEEE 754-2008 table 9.1, `sinh()` can produce overflow or underflow, `cosh()` can produce overflow, and `tanh()` can produce underflow. We seem to be catering for exceptions that cannot occur?

The link to 9.1 was helpful; I now understand better how to interpret the exceptions of the existing functions.

> The example results should perhaps be tagged as approximate to ensure that they pass automated testing.

Will be added.

> We should perhaps be referencing IEEE 754-2019 (though I'm reluctant to purchase a copy...)

Happy to do so (…when it comes to the reference).

**Comment by ChristianGruen** [comment]
@michaelhkay In the existing examples, `approx="true"` is sometimes used and sometimes not. Is there something to consider that may not be obvious? See e.g.  [function-catalog.xml#L2713 ff.](https://github.com/qt4cg/qtspecs/blob/master/specifications/xpath-functions-40/src/function-catalog.xml#L2713):

```xml
<fos:test>
   <fos:expression>math:exp(1)</fos:expression>
   <fos:result approx="true">2.7182818284590455e0</fos:result>
</fos:test>
<fos:test>
   <fos:expression>math:exp(2)</fos:expression>
   <fos:result>7.38905609893065e0</fos:result>
</fos:test>
```

**Comment by michaelhkay** [comment]
I think it's likely that approx="true" was only added to tests where someone (like me) got a failure if it was left out, due to the results being slightly different between implementations.
