### ISSUE TITLE
QT4CG-078-01 fn:unparsed-text-lines, normalize newlines

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#1236]
I think we should offer `normalize-newlines` only for `fn:unparsed-text`:

* It should never affect the result of `fn:unparsed-text-available`.
* I doubt (after further consideration) that it’s really helpful for `fn:unparsed-text-lines`. The default should work just fine for nearly all users. If someone really needs to do more sophisticated string processing, it’s still possible to use `fn:unparsed-text` and modify the result.

I have commited some test that (more or less) reflect the status quo: https://github.com/qt4cg/qt4tests/commit/68d40455f2404c379fdccddc1d524648ae4c8803

**Comment by ChristianGruen** [comment]
I think we should change `PRG-optional` as the current solution in the specification is backward-incompatible.

**Comment by ndw** [comment]
What's the incompatibility? Happy to make it required, but the issue doesn't describe an incompatibility AFAICT.

**Comment by ChristianGruen** [comment]
True, my comment is misleading. I mostly created the issue for Mike’s `QT4CG-078-01` action. Feel free to close the issue if you believe it should better be handled differently.

**Comment by michaelhkay** [comment]
I think PR #1279 handles this adequately.

**Comment by michaelhkay** [comment]
I think we can close this, the position after applying PR #1279 is fine.
