### ISSUE TITLE
XSLT xsl:next-match with select attribute

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#1239]
The ability of `xsl:next-match` to apply a sequence of template rules to the same item is limited by the fact that the item in question cannot be changed in any way. For example, if I want a template rule that matches an array to sort the array and then continue processing using the next rule for arrays, it's not possible; applying templates to the new array will sort it again, ad infinitum, while doing next-match is only possible on the original array, not the new sorted version.

I propose that xsl:next-match should have a select attribute. The effect is to process the selected items using the current mode, considering only the template rules that are lower in ranking order than the current template rule.

Alternatively or in addition, we could drop the rule that instructions that change the context item also clear the current mode. This would enable, for example, xsl:next-match to be used within xsl:for-each. However, it's possible that the results here could be confusing: we need to look at use cases.

**Comment by Arithmeticus** [comment]
I support this development. The point raised in the third paragraph seems to deserve its own separate issue, not only because it's different but because it might need more discussion.
