### ISSUE TITLE
[XPath] [XQuery] Incorrect subtype-itemtype rules for pure and local union types

### ISSUE THREAD

**Issue by rhdunn** [qt4cg/qtspecs#124]
Looking at https://github.com/qt4cg/qtspecs/issues/122, I've identified a possible gap in the logic for pure union types and `LocalUnionTypes`. Specifically, the rules are defined for when `A` is one of these union types but not when `B` is one of these union types.

That is, under the current 4.0 draft rules:
1. `subtype-itemtype(union(xs:string, xs:integer), xs:string)` is defined and will return false (`xs:integer` is not a subtype of `xs:string`).
2. `subtype-itemtype(xs:string, union(xs:string, xs:integer))` is not defined and will return false even though the union type supports `xs:string` as one of its member types.

Note that in the earlier standard versions, the pure union type case is handled by `derives-from(AT, ET)`:
1. `ET` is a pure union type of which `AT` is a member type 

With `derives-from(AT, ET)` only being applied in the case when both are atomic types 

## Draft Wording

2. *Conditions for atomic and union types:*
    a. `A` and `B` are `AtomicOrUnionType`s, and `derives-from(A, B)` returns true.
    b. `A` is a `LocalUnionType` in the form `union(T1, T2, ...)` and every type `T` in (`T1`, `T2`, ...) satisfies `subtype-itemType(T, B)`.
    c. `B` is a `LocalUnionType` in the form `union(T1, T2, ...)` and any type `T` in (`T1`, `T2`, ...) satisfies `subtype-itemType(A, T)`.

> Design Note: There is no need for a rule when `A` is a pure union type as that is covered by the "There is a type MT such that derives-from( AT, MT ) and derives-from( MT, ET )" rule for `derives-from`.

**Comment by michaelhkay** [comment]
I believe that `subtype-itemtype(xs:string, union(xs:string, xs:integer))`  is true under rule 2.a -

> A and B are [generalized atomic types], and `derives-from(A, B)` returns true.

Section 3.5 says that `derives-from( AT, ET )` returns true if ET is a pure union type of which AT is a member type

But it took me a while to get there and these rules could certainly be more helpful. (I hope that my re-factoring of this section helps, but it's only a beginning.)

**Comment by michaelhkay** [comment]
I've done a substantial reworking of the subtype rules to include a lot more explanations and examples. I hope it's correct; please review it.

**Comment by michaelhkay** [comment]
The section has been rewritten, so the issue can be closed.
