### ISSUE TITLE
array:partition → fn:partition: empty results; examples

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#125]
1. I think that an empty sequence should be returned if `array:partition` is invoked with an empty array. See e.g. `fn:tokenize('')`, which also returns an empty sequence and no zero-character string.

2. The last two example queries need to be revised, e.g. as follows:

```xquery
array:partition(
  tokenize("In the beginning was the word"),
  function($previous, $current) { sum(($previous, $current) ! string-length()) gt 10 }
)

array:partition(
  (1, 2, 3, 6, 7, 9, 10),
  function($seq, $new) { not($new = $seq[last()] + 1) }
)
```

Maybe an affirming `$add-when` function is more intuitive than `$break-when`, in particular for function bodies with sequence operations and general comparisons.

**Comment by michaelhkay** [comment]
I believe that PR #454 has addressed the problems identified, and am therefore closing the issue.
