### ISSUE TITLE
[XPath] [XQuery] Mathematical Operator Unicode Symbols

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#126]
As [programming fonts with ligatures](https://www.hanselman.com/blog/monospaced-programming-fonts-with-ligatures) get more and more common, we should ensure that Unicode symbols that are defined as equivalents for ASCII operators will not be mixed up with ligatures.

In particular, it’s the aliases for value comparisons that I believe should be used for general comparison operators instead:

* `≤` → `<=` (instead of`le`)
* `≥` → `>=` (instead of`ge`)
* `≠` → `!=` (instead of `ne`)
* `≐`, `⋖`, `⋗` …drop them?

The full list of the currently defined aliases: https://qt4cg.org/branch/master/xquery-40/xquery-40-diff.html#id-math-symbols

**Comment by ChristianGruen** [comment]
> If <= ligatures to a ≤ glyph, that isn't so much of a problem is it?

Yes, that’s fine. I would rather be confused if it’s legal to write `le` as `≤`.

> NFD normalisation could make xpath gramatically incorrect 

An interesting observation.

**Comment by davidcarlisle** [comment]
> Yes, that’s fine. I would rather be confused if it’s legal to write le as ≤.

Ah sorry, yes  see what you mean. Given `<=` and `le` already exist, even without a ligature my brain associated ≤ with `<=` which is wrong according to the draft you linked to. That's going to be confusing....

**Comment by rhdunn** [comment]
What I'm trying to understand about this section is how the mapping is done.

I would personally prefer the mappings to be done in the grammar to avoid issues with keywords being used in different contexts like LocalUnionType getting incorrectly handled. I've descibed my thoughts about that in https://github.com/qt4cg/qtspecs/issues/30. It also avoids complications of having a separate preprocessing step or having that intermixed in the parsing process that complicates the implementation of the language.

**Comment by ChristianGruen** [comment]
I agree that the alternative symbols will need to be added to the grammar (provided that they survive the draft stage).

Additional symbols could be added for the thin and fat arrows (→, ⇒)

**Comment by michaelhkay** [comment]
A problem with arrow symbols is that Unicode has so many of them, people would have great difficulty finding the right one.

But perhaps the practical scenario is that they would continue to type "->" or "=>" and an syntax-aware XPath editor would do a smart substitution?

**Comment by rhdunn** [comment]
It shouldn't be difficult to add that smart substitution to an XPath/XQuery editor like my plugin/IntelliJ. IntelliJ supports that editing capability for things like adding `};` when you type `{` after a function declaration, and performing more advanced auto-complete functionality.

The editor would know the exact codepoint(s) to use in the arrow replacement/substitution, so it would just need some preferences to indicate which operators the user wants to use Unicode symbols for in the contexts where that Unicode symbol is supported by the grammar.

**Comment by ChristianGruen** [comment]
For further discussion, see #204.
