### ISSUE TITLE
[XPath] [XQuery] Function items: Align "function" and "->" 

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#127]
I think that `function` and `->` should be 100% interchangeable:

```
Current Rule:
[83] InlineFunctionExpr  ::=  (("function" FunctionSignature) | ("->" FunctionSignature?)) FunctionBody

Proposed:
[83] InlineFunctionExpr  ::=  (("function" | "->") FunctionSignature?) FunctionBody
```

And an editorial note: In https://qt4cg.org/branch/master/xquery-40/xquery-40-diff.html#id-inline-func, the expanded syntax needs to be changed from

```
function($x as item()} as item()* {$x -> {EXPR}}
```

to 

```
function($x as item()} as item()* { $x ! EXPR }
```

**Comment by rhdunn** [comment]
Isn't this a duplicate of https://github.com/qt4cg/qtspecs/issues/53?

**Comment by ChristianGruen** [comment]
Definitely. Thank you, Reece, it’s finally time to read the existing issues again (and stop creating new ones).
