### ISSUE TITLE
Generalize for-each-pair to work with any number of input sequences

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#1273]
Inspired by https://stackoverflow.com/questions/78614003

fn:for-each-pair is great when you want to select corresponding items from two input sequences. But what if there are more than two?

We could provide 

`for-corresponding-items($input-sequences as array(item*)), $action as function(item()*))`

For example 

```
for-corresponding-items([(1,2,3), ("a","b","c"), (true(), false(), true())],
       fn{ array{.} }
)
```

returns `[1, "a", true()], [2, "b", false()], [3, "c", true()]`

**Comment by michaelhkay** [comment]
Perhaps it's best to offer a pure array operation, without any modification of the items

`array:invert($input as array(array(item()))) as array(array(item()))`

and any changes to item values can be done separately (before or after the inversion)

The previous example would become:

```
let $input := [(1,2,3), ("a","b","c"), (true(), false(), true())]
let $inverse := array:invert($input !! array{.})
return $inverse?*
```

The specification is essentially that `$result($i)($j) = $input($j)($i)` for all $i, $j, with some rules for how ragged arrays are handled.

**Comment by MarkNicholls** [comment]
its doesn't seem very long winded to write it from scratch

`array:fold-left(array:tail($xs),array:head($xs),local:zip#2)`

where

```
declare function local:zip($array1 as array(*),$array2 as array(*)) as array(*) {
    array:for-each-pair($array1,$array2,function($x,$y) { ($x,$y) })
};
```

(this is the monoidal pattern)

its values seems to be analogous to having `sum` even though you already have `+`

**Comment by michaelhkay** [comment]
Dropping this suggestion, I haven't been able to come up with a convincing proposal.
