### ISSUE TITLE
Declare named record types

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#1277]
Raised in response to action QT4CG-063-06.

Currently named item types are simply an alias - except when they declare a record type, in which case they have some magic properties by allowing the record type to be recursive, and by the fact that they implicitly create constructor functions.

We would also like to refine these constructor functions for example by allowing default values for fields to be defined.

It might therefore make sense to define a separate construct for declaring named record types (in both XQuery and XSLT), and perhaps putting these in a separate category in the static context.

We might also consider introducing some built-in named record types, for example for key-value pairs, so that users can conveniently construct instances of these record types without explicitly declaring them. These would presumably be in the fn namespace.

**Comment by ChristianGruen** [comment]
It has been mentioned before: The current term ”Record test” is a bit misleading, as it can result in a conversion/coercion of the processed map, and the result is a map again. Maybe we could…

1. Introduce a record constructor (related: #917):

```xquery
declare record geo:coord(
  x  as xs:double,
  y  as xs:double,
  z  as xs:double := 0
);
```

As we don’t want to introduce new types, the result of calling the record constructor could be a map annotated with the `geo:coord` type.

2. Drop current “record tests” and replace them with named tests:

```xquery
declare function geo:product($c as geo:coord) as xs:double {
  $c?x * $c?y * $c?z
};
```

If the input is annotated with the required type, no further checks are necessary. If not, the input map could be matched against the record type definition; if successful, it could be annotated with the expected type.

When updating a map, the type of the original map could be propagated to the new map if it still matches its definition.

At least in XQuery, this would make code with records much more intuitive.

I’ve somewhat deliberately ignored the `declare item-type` declaration. In the test suite (as far as I can see), there are no test cases for this construct yet that create records, but if we decide to keep it, we could try to combine it with the proposed record constructor:

```xquery
declare item-type geo:coord as record(
  x  as xs:double,
  y  as xs:double,
  z  as xs:double := 0
);
geo:coord(1, 2)
```

If we do so, we should probably introduce constructors for all other types, too:

```xquery
declare item-type xs:int-or-string as (xs:integer | xs:string);
xs:int-or-string("one")
```
