### ISSUE TITLE
invisible-xml() return type

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#1281]
It has been pointed out that the return type of `fn:invisible-xml()`, currently `fn(xs:string) as item()`, could be more precisely given as `fn(xs:string) as document-node()`.

**Comment by ndw** [comment]
Yes, that's my `QT4CG-081-04: NW to update the function signature of fn:invisible-xml` I believe.

**Comment by michaelhkay** [comment]
Fixed by #1282
