### ISSUE TITLE
Record Test Subtype Relationship

### ISSUE THREAD

**Issue by GuntherRademacher** [qt4cg/qtspecs#1317]
For a subtype relationship between record tests, `A ⊆ B`, I am trying to understand the impact of the extensibility of `A`, where `B` is extensible, but I can't spot any.

The cases of extensible and non-extensible `A` are distinguished in [3.3.2.10 Record Tests](https://qt4cg.org/specifications/xquery-40/xquery-40.html#id-item-subtype-records), points 5 and 6. The only difference between those, apart from `A`'s extensibility, is the first one saying

> For every field that is declared in B but not in A, the declared type in B is item()*.

while the second one has

> Every field that is declared in B with a type other than item()* is also declared in A.

So the first one asks for a type of `item(*)` when a declaration is missing, and the second one allows a missing declaration only for a type of `item(*)`. How can that not be the same?

**Comment by GuntherRademacher** [comment]
On second thought, I now believe that the requirement under 6.d. of [3.3.2.10 Record Tests](https://qt4cg.org/specifications/xquery-40/xquery-40.html#id-item-subtype-records) should be dropped:

> Every field that is declared in B with a type other than item()* is also declared in A.

Since `A` here is non-extensible, an `A` record can never present fields not declared in `A`, so it might not be necessary to restrict their type. It should be sufficient to ask for them to be optional in `B`, as implied by 6.c.:

> Every mandatory field in B is also declared in A.

In contrast to this, the corresponding restriction in 5.e. is needed for extensible `A`s, in order to cover `A` records with arbitrary types for the fields in question:

> For every field that is declared in B but not in A, the declared type in B is item()*.

**Comment by michaelhkay** [comment]
Yes, I agree, rule 6.d seems unnecessary.

**Comment by GuntherRademacher** [comment]
Another remark on the subtype rules for RecordTests, concerning the formulation used in 4.d, 5.c, and 6c:

> Every mandatory field in B is also declared in A.

As I read it, it remains open whether the respective field should be mandatory in A. But I think it should, otherwise A records without that field would not match B. I would thus propose to change it into:

> Every mandatory field in B is also declared as mandatory in A.

**Comment by michaelhkay** [comment]
Yes, I think you are right.
