### ISSUE TITLE
Clarify if redirects should be followed

### ISSUE THREAD

**Issue by ndw** [qt4cg/qtspecs#132]
If a user requests a document (using doc, document, unparsed-text, etc) with an HTTP(S) URI, and a redirect response is returned, what should the processor do?

**Comment by ChristianGruen** [comment]
My assumption is that following redirects would probably be what most users would expect today.

**Comment by ndw** [comment]
I agree completely. It came up on the XML.com Slack that the specs aren't explicit. I think this is a minor editorial issue, but unlikely to be a convtroversial one.

**Comment by michaelhkay** [comment]
The specs for functions like `doc()` abstract away all the HTTP machinery - we don't even acknowledge the existence of the web, except as a mapping from URIs to documents that's present in the dynamic context of the query.

The only way to provide an answer to this question would be to provide some kind of non-normative appendix called something like "Guidelines for implementation of fn:doc" that gives a potential interpretation of how HTTP(S) Uri's should be handled. Drafting that is a fairly signfiicant exercise. Moreover, if the text makes recommendations that conflict with existing practice of some products then it's likely to be controversial, but if it sits on the fence on such questions then it serves no useful purpose.

**Comment by ndw** [comment]
If it isn't practical to encourage implementations to follow redirects, then I suggest we should call it out explicitly as an implementation-defined detail. In practice, it matters a lot, as we've seen recently.

**Comment by michaelhkay** [comment]
We currently say, for the doc() function:

> One possible processing model for this function is as follows. The resource identified by the URI Reference is retrieved. If the resource cannot be retrieved, a dynamic error is raised [[err:FODC0002](https://qt4cg.org/specifications/xpath-functions-40/Overview-diff.html#ERRFODC0002)].

We could expand this to say, for example, 

> One possible processing model for this function is as follows. The URI is first looked up in a catalog to see if a local copy of the resource is available. If not, the resource identified by the URI Reference is retrieved. If an HTTP redirect response is received, then a new request is made. If the resource still cannot be retrieved, a dynamic error is raised [[err:FODC0002](https://qt4cg.org/specifications/xpath-functions-40/Overview-diff.html#ERRFODC0002)]....

But then what about fn:unparsed-text?

Perhaps it would be better if 14.6 had a general subsection about retrieval of resources covering all the functions, and move the notes in there? And who would be better qualified than you to draft it...?

**Comment by ndw** [comment]
Right. I'll give it a think and try to draft some text.

**Comment by ChristianGruen** [comment]
@ndw Do you think we should keep this one open?

**Comment by ndw** [comment]
All this resolution stuff is complicated. I've made myself a "todo" item locally. If I haven't made a PR in a week or two, I'll declare defeat and close this.

**Comment by michaelhkay** [comment]
The WG agreed to close this with no action on 2024-04-09.
