### ISSUE TITLE
Drop unordered mode

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#1339]
Is there any evidence that unordered mode is useful, or that any implementations actually take note of it (by delivering a different result if unordered mode is set)?

If not, could we drop it? I would suggest continuing to recognize the syntax, marking it deprecated, and saying it has no effect.

It's not doing a great deal of harm, but there are a lot of places where our examples in the spec assume ordered mode, but the examples don't explicitly call out this assumption. Similarly, a great many QT3 test cases would fail on an implementation that sets unordered mode by default.

**Comment by ChristianGruen** [comment]
I would like to see it dropped.
