### ISSUE TITLE
Drop the static typing feature

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#1343]
Since XQuery 3.0, the effect of the static typing feature has been almost entirely implementation defined. Since there is no interoperability when this feature is in effect, there seems very little point leaving it as an optional feature in the spec. In any case, I think user experience of processors that attempt to implement the static typing feature has been rather negative, and most of the processors that implemented it have been left to languish and are unlikely to be upgraded to 4.0.

**Comment by ChristianGruen** [comment]
I agree. We do a lot of static typing, but we’ve never followed the Static Typing Feature instructions given in the spec as it only covers a small number of all cases that are interesting.
