### ISSUE TITLE
Bare brace ambiguity resolution in practice

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#1345]
I have applied the new bare brace grammar rules to two existing projects, and (if I’m correct) all of the the following constructs cannot be parsed anymore (with the order reflecting my sense of urgency):

1. Simple maps: `$data ! {}`
2. Sequence arrow: `{} => map:size()` 
3. Predicates: `{ 'x': 1 }[map:keys(.) = 'x']`
4. Return clause: `let $x := ... return {}`
5. Paths: `<a/>/{}`
6. Instance of: `{} instance of record(x)` 
7. If expression: `if($x) then { $x: $y } else {}`

I think we should try hard to tweak the grammar for some of these.

I didn’t manage to construct an ambiguous example with `return` and `{}`; could someone help me?

Related: #1309

**Comment by michaelhkay** [comment]
I think it would be possible without too much difficulty to allow binary operators (such as  => , `?`, instance of) after a bare brace constructor but it makes the rules more complicated. It would also be possible to allow non-verbal operators before the constructor, such as "!" and "/".

Most of the cases that cause difficulty involve a keyword preceding the constructor, for example

`let $x := $a/element return {}`

`if ($x) then $a/element else {}`

But I wouldn't be confident that all cases are known. (Some research using a parser generator might yield extra insights.)

**Comment by ChristianGruen** [comment]
Thanks. – I noticed that some more test cases need to be updated to do justice to the new grammar rules (I would tend to update those after we have fine-tuned the grammar).

**Comment by ChristianGruen** [comment]
In practice, empty map constructors are a rare sight. Would it be possible to only disallow empty bare brace constructors after keywords?

I think/hope that this would make the following constructs unambiguous:

```xquery
let $_ := element return { } return { }
let $_ := element return { xml:xml }
let $_ := element return { 1: 2 }
let $_ := element return map {}
let $_ := element return ({})
```

**Comment by michaelhkay** [comment]
While empty map constructors demonstrate the ambiguity problem very starkly, non-empty map constructors can also be problematic, in that it takes unbounded lookahead to tell whether you're in a map constructor or not. Consider for example

`let $x := element return {1+2+3+4+5+6.... : 42}`

We really don't want to have to look ahead to the ":" in order to decide what "return" means here - quite apart from the difficulty for parser-writers, the diagnostics for users would probably be awful.

It might be possible to formulate an XGC to deal with it, especially if we're prepared to contemplate edge-case incompatibilities: for example, if the element/attribute name in a computed element/attribute constructor is a language keyword that is a valid continuation of the expression, then it must be written in quotes.

**Comment by ChristianGruen** [comment]
> It might be possible to formulate an XGC to deal with it, especially if we're prepared to contemplate edge-case incompatibilities: for example, if the element/attribute name in a computed element/attribute constructor is a language keyword that is a valid continuation of the expression, then it must be written in quotes.

This way out appears more and more attractive to me: It is not counterintuitive at all that `let $m := {}` is legal while `for $m in {}` or `return {}` isn’t.

**Comment by michaelhkay** [comment]
I would certainly be happy to require `element return {}` to be changed to `element "return" {}` if it solved the problem. But are we 100% confident this is sufficient? Do we have any tools to allow us to check this?

**Comment by ChristianGruen** [comment]
> I would certainly be happy to require `element return {}` to be changed to `element "return" {}` if it solved the problem. But are we 100% confident this is sufficient? Do we have any tools to allow us to check this?

True. @johnlumley, @rhdunn Do you have an opinion on this?

**Comment by rhdunn** [comment]
So we are proposing making `return` a reserved computed node constructor keyword like is done for function calls? I think that makes sense.

Thus, we are proposing:
1. making StringLiteral an option for computed node constructor names along with `EQName` and `"{" Expr "}"` -- I like this, especially with the proposed change; (Q: Should the string be an NCName only or should QNames be allowed?)
2. defining a set of reserved computed node constructor keywords (after the A.4 Reserved Function Names section);
3. adding a new "constraint: reserved-computed-node-constructor-names" to disallow the keywords in (2) to appear in the name position of a computed node constructor.

I would also add notes to e.g. the *Computed Attribute Constructors* "If the keyword attribute is followed by an EQName," section to include a note stating something like:
> If the EQName is an NCName and the NCName is in the Reserved Computed Node Constructor Names then the XPath/XQuery processor will not treat the expression as being a *Computed Attribute Constructor*. Instead, it will be treated as a `PathExpr` with a single `attribute` element step.

**Comment by michaelhkay** [comment]
@rhdunn Yes, that's the essence of it. Question is, can we be sure this is sufficient to eliminate bare-brace ambiguities?

My other main concern is with braced if/then/else.

**Comment by johnlumley** [comment]
My initial reaction was 'so sometimes the `return` keyword has to be quoted?' but of course I hadn't realised that it was in the context of element node construction (I've never programmed in XQuery, so never used the construct.) If so, then it seems reasonable to require some node names to require quoting in that circumstance hinted at by an XGC, or as Mike says, by a subtraction. 

Does that imply:
```
CompElemConstructor	   ::=   	"element" (EQName | StringLiteral | ("{" Expr "}")) EnclosedContentExpr
```
I don't think that would cause an issue, but haven't tried running something through my iXML grammar - will try to in the next few days. I assume use of a `StringTemplate` would be in the immediately braced expression.

**Comment by johnlumley** [comment]
I think this is related, but QT4 tests `fo-test-array-of-members-00[34]` fail to parse the expression
```
array:of-members((1 to 5) ! { 'value': . })
```
as `BareMapConstructor` is not a valid `PrimaryExpr` which would be needed for either of the arguments of `SimpleMapExpr`, via a route through `PathExpr` to `PostfixExpr`. 

`MapConstructor` of course uses `BareMapConstructor`, but whilst making `BareMapConstructor` a valid `PrimaryExpr` does allow this expression to parse, it also makes:
```
{ 'value': . }
```
ambiguous, permitting either of the `ExprSingle` or `BareMapConstructor` parse routes from `StandaloneExpr`.

**Comment by johnlumley** [comment]
My exploration above of the position of `BareMapConstructor` (where it can be unambiguous against constructs such as `BracedActions` if made solely a production of `PrimaryExpr`) is only in the context of **XPath**. In **XQuery** the problem of interference with node constructors still remains, I think.

**Comment by johnlumley** [comment]
The migration of `BareMapConstructor` from `StandaloneExpr` to `PrimaryExpr`, discussed above, appears to introduce a case of potential ambiguity between `NodeConstructor` and `MultiplicativeExpr`.

Test `K2-ComputeConAttr-62` shows this and contains the subexpression:
```
attribute div {}
```
which can be parsed in two ways:
```
<Module xmlns:ixml="http://invisiblexml.org/NS" ixml:state="ambiguous">
   <MainModule>
      <Prolog/>
      <MultiplicativeExpr MultiplicativeOps="div">
         <AxisStep>
            <QName local="attribute"/>
         </AxisStep>
         <BareMapConstructor/>
      </MultiplicativeExpr>
   </MainModule>
</Module>
<Module xmlns:ixml="http://invisiblexml.org/NS" ixml:state="ambiguous">
   <MainModule>
      <Prolog/>
      <NodeConstructor>
         <CompAttrConstructor>
            <QName local="div"/>
            <EnclosedExpr/>
         </CompAttrConstructor>
      </NodeConstructor>
   </MainModule>
</Module>
```
Of course the first should fail a static type check, but the initial ambiguous parse would be the case for any of the 'word' form binary operators. 

With `BareMapConstructor` a production of `StandaloneExpr` this ambiguity disappears, but some of the parses given earlier now fail..

**Comment by ChristianGruen** [comment]
> The migration of `BareMapConstructor` from `StandaloneExpr` to `PrimaryExpr`, discussed above, appears to introduce a case of potential ambiguity between `NodeConstructor` and `MultiplicativeExpr`.
> 
> Test `K2-ComputeConAttr-62` shows this and contains the subexpression:
> 
> ```
> attribute div {}
> ```

Thanks for your analysis. This reminds me of some of the cases that had been discussed in https://github.com/qt4cg/qtspecs/issues/1241.

**Comment by michaelhkay** [comment]
`attribute div {}`

I think we know about that issue. The question we need an answer to is: if we disallowed reserved keywords in computed element and attribute constructors, would that be sufficient to solve the problem and allow a `BareMapConstructor` as a `PrimaryExpr`?

**Comment by johnlumley** [comment]
I can certainly experiment - the iXML parser and my grammar generator has sufficient power to make disallowing pretty simple. I'll try it (though the full test suite takes some 40 minutes to process.)

**Comment by johnlumley** [comment]
### Ambiguity with `BareMapConstructor` in `StringTemplate`:
[4.9.2 String Templates](https://qt4cg.org/specifications/xquery-40/xquery-40.html#id-string-templatesl) states:
>Currently no XPath expression starts with an opening curly bracket, so the use of `{{` creates no ambiguity. If an enclosed expression ends with a closing curly bracket, no whitespace is required between this and the closing delimiter.

But of course `BareMapConstructor` breaks that, so `"{{}}"`` within backticks (can't work out how to escape!) can parse as:
```
<StringTemplate>
      <StringTemplateFixedPart>"{{}}"</StringTemplateFixedPart>
   </StringTemplate>
```
or
```
<StringTemplate>
      <StringTemplateFixedPart>"</StringTemplateFixedPart>
      <StringTemplateVariablePart>
         <EnclosedExpr>
            <BareMapConstructor/>
         </EnclosedExpr>
      </StringTemplateVariablePart>
      <StringTemplateFixedPart>"</StringTemplateFixedPart>
   </StringTemplate>
```

**Comment by johnlumley** [comment]
> `attribute div {}`
> 
> I think we know about that issue. The question we need an answer to is: if we disallowed reserved keywords (such as `div`) in computed element and attribute constructors, would that be sufficient to solve the problem and allow a `BareMapConstructor` as a `PrimaryExpr`?

I've done some preliminary exploration using the XQuery testset, and so far it appears that there is no ambiguity introduced by that migration using minor changes to some of the computed node constructors (in iXML notation):
```
CompElemConstructor: -"element", s, (NodeEQName; -"{", s, Expr, -"}", s), EnclosedContentExpr.
CompAttrConstructor: -"attribute", s, (NodeEQName; -"{", s, Expr, -"}", s), EnclosedExpr.
...
        -NodeEQName: EQName ¬ (reservedNodeNames, s) .
 -reservedNodeNames: "and"; "div"; "eq"; "except"; "ge"; "gt"; 
                     "is"; "le"; "lt"; "mod"; "ne"; 
                     "or"; "otherwise"; "union" .
```
(`s` denotes optional whitespace, `A ¬ B` means `A` matches unless `B` also matches over the same characters - an unofficial iXML extension.). A similar change is needed for the `NCName` in `CompPIConstructor`.

I'll carry on checking.

**Comment by michaelhkay** [comment]
I think that with StringTemplate (and attribute value templates and their XQuery analogue), we have to treat `{{` as effectively a single token that is matched and interpreted as an escaped literal `{`, not as an unescaped `{` followed by an expression starting with `{`. Although we're not strictly tokenising in this situation, the situation is very closely analogous to the "longest token" rule - `{{` when processing a StringTemplate is handled as a unit.

**Comment by johnlumley** [comment]
> I think that with StringTemplate (and attribute value templates and their XQuery analogue), we have to treat `{{` as effectively a single token that is matched and interpreted as an escaped literal `{`, not as an unescaped `{` followed by an expression starting with `{`. ...

In which case I think it's worth moving `BareMapConstructor` to `PrimaryExpr`  and adding 'word' binary operator exclusions from the direct name fields of `CompElemConstructor`, `CompAttrConstructor` and `CompPIConstructor`, noting that they can still be constructed using enclosed expressions, e.g.:
```
element {'div'} {}
```
We could eventually remove `StandaloneExpr`, but it might be prudent to leave that until the next 'tidying' pass on the overall grammar. Something unforseen might still 'break' :-)
