### ISSUE TITLE
Names of private functions in XQuery library modules

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#1356]
Is there any good reason for the rule that the name of a private function or variable declared in a library module must be in the target namespace of the module? I think it makes sense to allow:

* private functions to be in any non-reserved namespace
* private variables to be in any non-reserved namespace or in no namespace

The reason I ask is that I'm looking at what the rule should be for item type declarations.

**Comment by ChristianGruen** [comment]
> Is there any good reason for the rule that the name of a private function or variable declared in a library module must be in the target namespace of the module? 

For variables, it would be convenient to allow functions in no namespace, but I think we shouldn’t allow other namespaces. It feels like a bad design choice without obvious advantages.

Also for functions, it would rather be confusing if the rules for private and public functions differed. I would still love to see support for functions without namespace (but this is another topic).

> The reason I ask is that I'm looking at what the rule should be for item type declarations.

It assume it would be intuitive to use the same rules for variables and types (no prefix = no namespace), unless unprefixed types get a default namespace.

**Comment by michaelhkay** [comment]
>It assume it would be intuitive to use the same rules for variables and types (no prefix = no namespace),

The problem is that an unprefixed reference to a named item type will use the default namespace for elements and types but an unprefixed call of the corresponding constructor function will use the default namespace for functions. That's sufficiently confusing that it seems a good idea to insist that named item types should be in a namespace. But constraining it to be the module namespace, especially for private declarations, seems to be imposing a restriction for no good reason. Which is why I asked if there is any reason for the corresponding restriction on functions and variables. It makes no sense to me (perhaps because of my background in XSLT where namespaces and modules are completely orthogonal).

**Comment by ChristianGruen** [comment]
> Which is why I asked if there is any reason for the corresponding restriction on functions and variables. It makes no sense to me

Maybe the reason is purely historical, since the `%private` annotation was only introduced with XQuery 3.0. Apart from that, while I motivate users to make parts of the XQuery code private, I rarely see it in practice.

**Comment by michaelhkay** [comment]
Closing with no action.
