### ISSUE TITLE
Rendering of new vs. updated features

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#1357]
In previous versions of the XQFO drafts, it was possible to differentiate between NEW and UPDATED functions. It would be nice if this distinction could be preserved:

<img width='300' src='https://github.com/user-attachments/assets/dbb7f726-55de-4a6a-9eaa-c39c50689776'/>    <img width='300' src='https://github.com/user-attachments/assets/074b4863-481d-482a-b608-ce24184e159f'/>

**Comment by michaelhkay** [comment]
It may be worth noting that the choice of icon was sometimes wrong. It was based on rough heuristics. If we're going to do it, we should do it properly, by examining the 3.1 version of the function catalog.

**Comment by ChristianGruen** [comment]
> It may be worth noting that the choice of icon was sometimes wrong. It was based on rough heuristics.

True; that will certainly take some time. Before we do that, I would propose to use 3 categories:

1. New feature
2. Major update
3. Minor update

…and to visually suppress 3. Minor Updates in the table of contents. I know it won’t make things easier (deciding what’s major and minor), but I’m sure no one will care too much about changes like…

> `fn:subsequence`: The optional third argument can now be supplied as an empty sequence.

…and it will be difficult to find the interesting changes otherwise. – In addition, we should probably drop "Update" information on features that are being added as new features.

For the symbols, here are some alternatives (in different colors, although this depends on the rendering)…

* Added: 🆕➕🎉
* Updated: ✨★

If we use the same symbol, we could choose custom colors.

**Comment by ndw** [comment]
I'm at Balisage this week, but I'll take a look at this when I can. I am hoping to carve out some time for QT4 work over the next couple of weeks.
