### ISSUE TITLE
Occurrence indicator meaning "exactly one"

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#1365]
There are several reasons it would be good to have an occurrence indicator meaning "exactly one".

1. It's generally a good idea if there is explicit syntax that's equivalent to the default: it enables you to write code that is more explicit about the fact that you have chosen the default option; it makes code generation easier.
2. Sometimes you need to write an ItemType in parentheses to avoid a following `?` or `*` being interpreted as an occurrence indicator. Having an explicit occurrence indicator for "exactly one" would avoid this need.
3. It makes it clear that you are writing a SequenceType, not an ItemType.

I don't expect this to be used very often, but I think it would be useful to allow it. I propose using U+00B9, superscript 1.

For example, `as="xs:integer¹"`

We can now write:

`function($a, $b) as xs:integer¹ *`

to mean a sequence of functions each returning a single integer; while writing

`array(xs:integer¹ )`

just serves to remind the reader that  the array entries must be single integers.

**Comment by ndw** [comment]
Honestly, I prefer `(function($a, $b) as xs:integer)*` and I find the superscript `¹` awfully hard to read. 

If we think it's sufficiently uncommon that it can be relegated to a Unicode character, I might prefer `➀`.

**Comment by ChristianGruen** [comment]
> If we think it's sufficiently uncommon that it can be relegated to a Unicode character, I might prefer ➀.

Please let us stick with ASCII. Would `!` or `=` be parseable?

```
fn() as xs:integer!*
array(xs:integer=)
```


Similar to Norm, I tend to prefer the existing syntax with additional parens. It would have been different if the occurrence indicator had been mandatory from the beginning.

**Comment by michaelhkay** [comment]
I think any ASCII character here would be likely to cause as many problems as it solves, and the meaning would be entirely unclear to a reader who hasn't encountered it before, which I don't think is true of the superscript 1. The superscript 1 also has the advantage that we're used to superscript digits being used as a suffix, they obviously relate to the thing that they immediately follow.

**Comment by benibela** [comment]
>It's generally a good idea if there is explicit syntax that's equivalent to the default

I think in general that is a rather bad idea





Regex has occurrence indicator. Those could be used

Then one can write

   function($a, $b) as xs:integer{1} *

to mean a sequence of functions each returning a single integer; while writing

       array(xs:integer{1})


But you could also write

       array(xs:integer{2})

for an array of pairs of integers


And `xs:integer?` could be replaced by `xs:integer{0,1}`,  `xs:integer*` by `xs:integer{0,}` and `xs:integer+` by `xs:integer{1,}`

**Comment by michaelhkay** [comment]
> function($a, $b) as xs:integer{1} *

Interesting suggestion, both (a) as suggested syntax for the "exactly one" occurrence indicator, and (b) as extended functionality for constraining the cardinality of sequences.

I can't see any immediate reason why the syntax shouldn't work, but we know from experience that ambiguities aren't always obvious at first sight.

**Comment by ChristianGruen** [comment]
> the meaning would be entirely unclear to a reader who hasn't encountered it before, which I don't think is true of the superscript 1.

Superscript 1 lets me think of a reference note. I think I would not have guessed that it has something to do with counting things (and we don’t have ², ³, etc.). But maybe that’s just me.

If we chose `!` (I’m not convinced we should), it would be complimentary to `?`: does it exist? yes, it exists!

+1 for @benibela’s proposal for using existing syntax.

**Comment by michaelhkay** [comment]
Well, you immediately hit a problem with

```
declare function f:the-answer-to-everything() as xs:integer {
   42
}
```

which means it's probably a non-starter. Shame.

**Comment by michaelhkay** [comment]
Closing due to lack of consensus.
