### ISSUE TITLE
In the EBNF, use explicit separator syntax

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#1366]
We could pick up the `++` and `**` operators from Invisible XML for defining "a sequence of [one|zero] or more Xs separated by Ys".

So for example

`Annotation ::= "%"  EQName ("("  AnnotationValue ("," AnnotationValue)* ")")?`

changes to

`Annotation ::= "%"  EQName ("("  (AnnotationValue ++ ",") ")")?`

and 

`TypedFunctionTest ::= ("function" | "fn") "(" (SequenceType ("," SequenceType)*)? ")" "as" SequenceType`

becomes

`TypedFunctionTest ::= ("function" | "fn") "(" (SequenceType ** ",") ")" "as" SequenceType`

Note that there is an impact on anyone who uses the machine-readable XML version of our grammar. However, the current version could easily be generated by preprocessing.

**Comment by michaelhkay** [comment]
I've spent half an hour looking at this and decided it's not a task to be undertaken lightly.

Apart from anything else, there's an awful lot of code both in our project and elsewhere that's driven by the grammar file, and a lot of it would break.

So I'm going to close this with no further action.

**Comment by michaelhkay** [comment]
Reopening because it turned out to be rather easier. Anyone using the grammar file, for example to generate a parser, can easily preprocess the grammar into a different form.

**Comment by johnlumley** [comment]
A preliminary test, using the XPath test suite, doesn't seem to add any additional ambiguities or errors by using the repeat/separator form. 

At present the use seems to be only where the separator is always a constant string. It might be possible to extend to nonterminal or compound separators, though whether this is worthwhile is a moot point.

**Comment by michaelhkay** [comment]
For simplicity the representation of the grammar in the XML currently only allows a constant string as the separator; I made that choice deliberately as (a) it's the 99% use case, and (b) I think other cases would probably be confusing if presented this way.
