### ISSUE TITLE
Unknown option: FORG0013 → XPTY0004

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#1372]
I would suggest dropping https://qt4cg.org/specifications/xpath-functions-40/Overview.html#ERRFORG0013 and replacing it with a type error, `XPTY0004`. This way, it can be perfomed during the type checks (which may also be the best solution if we define options as records).

I’ll be glad to create the PR for the spec and the tests.

**Comment by michaelhkay** [comment]
FORG0013 is already classified as a type error, so I don't see what changing the error code would achieve. Unless we do actually start to define the options as a record type in the function type signature, in which case it would probably make sense.

**Comment by ChristianGruen** [comment]
> FORG0013 is already classified as a type error, so I don't see what changing the error code would achieve. 

In our case, we would have to put additional effort into our option checks to determine what kind of checks are performed to raise either FORG0013 or XPTY0004. Of course it can be done, but I do not see any real benefit. I don't think people will explicitly catch `FORG00013` – and it would not be possible with records anymore.
