### ISSUE TITLE
XQFO: Editorial

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#1373]
* Wrong example: `hash("password123" || $salt, "sha-1234567")`
* The following test lacks a `use="v-deep-equal-at"` attribute:

```xquery
deep-equal(
  $at//name[@first="Bob"], 
  $at//name[@last="Barker"],
  options := { 'items-equal': op('is') } 
)
```
* `graphemes($crlf)`: Result should be `char('\r') || char('\n')` instead of `$crlf` (otherwise, test doesn’t work)
* fix `fn:unix-time` example: `1969-12-31T23:59:59.999Z` (thanks @johnlumley)
* TODO for `fn:replicate` can be dropped
* `fn:parse-uri`: Remove example for `FOUR0002`.

…to be continued

**Comment by michaelhkay** [comment]
fn:function-annotations is missing change markup
