### ISSUE TITLE
Duplicate keys in map constructor

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#1374]
We say (concerning map constructors)

If two or more entries have the [same key value] then a dynamic error is raised [[err:XQDY0137].

I think we should say:

if every MapKeyExpr is a Literal then this error SHOULD be reported as a static error.

**Comment by benibela** [comment]
This is like the static type checking all over again. 

What if it the query is:

      if (false()) then {"a": 1, "a": 2} else ()

**Comment by ChristianGruen** [comment]
Isn’t it already the case that an implementation may raise dynamic errors statically? For example, we raise FOAR0002 at parse time when an integer literal cannot be represented in 64 bits.

**Comment by michaelhkay** [comment]
The general rule is 

`An implementation can raise a [dynamic error] for a [QueryBody] statically only if the query can never execute without raising that error, as in the following example:`

We tend to make specific exceptions to that rule for specific dynamic errors where problems are obviously detectable statically and it doesn't make sense even if put in a conditional.
