### ISSUE TITLE
Circular dependencies: XQDY0054 vs. XPST0008 vs. optional errors

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#1379]
It remains a challenge (for me) to understand how the specification expects implementations to handle circular dependencies. Sorry in advance for mixing up the specification, tests and the behavior of Saxon (it basically demonstrates my confusion):

### Error Codes

The definition of `err:XPST0008` is:

> It is a [static error](https://qt4cg.org/specifications/xquery-40/xquery-40.html#dt-static-error) if an expression refers to an element name, attribute name, schema type name, namespace prefix, or variable name that is not defined in the [static context](https://qt4cg.org/specifications/xquery-40/xquery-40.html#dt-static-context), except for an ElementName in an [ElementTest](https://qt4cg.org/specifications/xquery-40/xquery-40.html#doc-xquery40-ElementTest) or an AttributeName in an [AttributeTest](https://qt4cg.org/specifications/xquery-40/xquery-40.html#doc-xquery40-AttributeTest).

The definition of `err:XQDY0054` is:

> It is a [dynamic error](https://qt4cg.org/specifications/xquery-40/xquery-40.html#dt-dynamic-error) if a cycle is encountered in the definition of a module’s dynamic context components, for example because of a cycle in variable declarations.

### Queries

The following test case [K-InternalVariablesWith-15b](https://github.com/qt4cg/qt4tests/blob/4659dfdcc92ac57c9a7f482a1ec9f3f509020f52/prod/VarDecl.xml#L1527C21-L1537) expects `XPST0008` as error:

```xquery
declare variable $var1 := $var1;
true()
```

I would expect `XQDY0054` as error, and `true()` to be a valid alternative, as `$var1` is indeed defined in the static context. Think of a similar query (for which I would as well expect `XQDY0054` or `true()` to be correct results):

```xquery
declare variable $var1 := $var2;
declare variable $var2 := $var1;
true()
```

Saxon outputs  the following error for the first query…

> [XPST0008] Circular definition of global variable: $var1 uses $var1.

…which is confusing in itself, as the error code and the message do not really match. The output of the second query is consistent:

> [XQDY0054] Circular definition of global variable: $var2 uses $var1, which uses $var2.

Another test case that expects `XQDY0054` is [K-InternalVariablesWith-17a](https://github.com/qt4cg/qt4tests/blob/4659dfdcc92ac57c9a7f482a1ec9f3f509020f52/prod/VarDecl.xml#L1582-L1591):

```xquery
declare variable $var := local:func1();
declare function local:func1() { local:func2($var) };
declare function local:func2($arg2) { 1 };
true()
```

Again, I would expect `true()` to be a valid alternative, in `K-InternalVariablesWith-17` (the original XQuery 1.0 test), the rational for reporting an error was…

> A prolog variable having a circular dependency, by having a variable reference in a call site argument. This is an error even though the variable isn't used, because implementations cannot skip reporting static errors.

…but we now have a dynamic error.

### Suggestions

1. `XPST0008` should only be raised if no declaration exists for that variable in the query prolog.
2. `XQDY0054` should be optional for cases in which the affected code is never evaluated.

I would like to hear some feedback on this, and I will be happy to move the corresponding questions to `qt4tests` and/or the Saxon bug tracker if we believe that the spec is comprehensive enough.

**Comment by michaelhkay** [comment]
With

`declare variable $var := $var;`

It's not true that `$var` is present in the static context, because of the rule:

[Definition: If a variable declaration includes an expression (VarValue or VarDefaultValue), the expression is called an initializing expression. The static context for an initializing expression includes all functions, variables, and namespaces that are declared or imported anywhere in the Prolog, other than the variable being declared.]

A self-reference is a static error even if it's dynamically masked, for example

`declare variable $var := fn($x){if ($x) then $var else 42};`

That's a stronger constraint than we have for cyclic references, such as 

```
declare variable $var1 := fn($x){if ($x) then $var2 else 42};
declare variable $var2 := fn($x){if ($x) then $var1 else 42};
```
which only becomes an error if the dependency exists at evaluation time.

Where the cycle exists but the variables aren't referenced, as in

```
declare variable $var1 := $var2;
declare variable $var2 := $var1;
true()
```
then I think "errors and optimization" allows the query to return true() on the basis that it's not required to do extra work to detect errors if the query result can be computed without it.

**Comment by ChristianGruen** [comment]
Thanks for the swift reply on a non-trivial issue.

> A self-reference is a static error even if it's dynamically masked, for example
> 
> `declare variable $var := fn($x){if ($x) then $var else 42};`

This one does not raise an error in Saxon EE 12.5 (`$var(0)` yields `42`). Is it a bug or something that should be clarified in the spec?

> then I think "errors and optimization" allows the query to return true() on the basis that it's not required to do extra work to detect errors if the query result can be computed without it.

Good to know. I will fix the tests.

**Comment by ChristianGruen** [comment]
It would actually be pretty fancy if we could make Saxon’s current behavior legal. We could get rid of explicit self references and, thus, further align global variables and functions:

```xquery
declare variable $f := fn($n) { if($n) then $f($n - 1) else $n };
$f(100)
```

I have browsed some bugs in the old W3 tracker, and my impression is that the current specification makes somewhat outdated assumptions on the underlying implementation. One indication for that is that the former error code `XQST0054` was made dynamic with version 3.0 (https://www.w3.org/Bugs/Public/show_bug.cgi?id=15791, https://www.w3.org/Bugs/Public/show_bug.cgi?id=17272).

**Comment by michaelhkay** [comment]
>I will fix the tests.

Please fix them so that the processor has to detect the circularity, not so that it can avoid doing so!

>t would actually be pretty fancy if we could make Saxon’s current behavior legal

I think you just have to take out the rule that a variable isn't in scope within its own initialiser, and just treat this as a special case of the circularity rules.

**Comment by ChristianGruen** [comment]
> I think you just have to take out the rule that a variable isn't in scope within its own initialiser, and just treat this as a special case of the circularity rules.

Maybe it’s already sufficient to drop the condition “, other than the variable being declared”. I don’t know what we need a special case for?

> Please fix them so that the processor has to detect the circularity, not so that it can avoid doing so!

I think I’ll wait. If we relax the rule above, I don’t think an error will be raised for [K-InternalVariablesWith-17a](https://github.com/qt4cg/qt4tests/blob/4659dfdcc92ac57c9a7f482a1ec9f3f509020f52/prod/VarDecl.xml#L1582-L1591) anymore:

```xquery
declare variable $var := local:func1();
declare function local:func1() { local:func2($var) };
declare function local:func2($arg2) { 1 };
```

No matter whether the main expression is `$var`, `local:func1()` or `loca;:funcs2(0)`: In all cases, `1` would be a reasonable result.
