### ISSUE TITLE
Quantifier expressions: optional positional argument

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#1385]
This has been requested multiple times before (albeit not in this repository): What about adding a positional argument to quantifier expressions? It it simple to implement, and it would allow us to do things like…

```xquery
every $item at $pos in $input satisfies $item = $pos * 2
```

…which would be equivalent to…

```xquery
every($input, fn($item, $pos) { $item = $pos * 2 })
```

…and much better to read than e.g.…

```xquery
not((for $item at $pos in $input return $item = $pos * 2) = false())
```

**Comment by michaelhkay** [comment]
I've never seen a need for it and there seem to be plenty of ways of doing it if needed, for example

`every(for $item at $pos in $input return $item = $pos * 2)`

**Comment by ndw** [comment]
The CG agreed to close this issue without further action at [meeting 089](https://qt4cg.org/meeting/minutes/2024/09-10.html)
