### ISSUE TITLE
fn:build-uri: Observations

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#1387]
@ndw I’ll again start with a single test case, [fn-build-uri-from-parse-020](https://github.com/qt4cg/qt4tests/blob/b5c9431b6e5c7e24729a4de19aac1754b0b34c4a/fn/build-uri.xml#L296-L314):

```xml
<test-case name="fn-build-uri-from-parse-020">
    <description>Builds an example from the specification</description>
    <created by="Norm Tovey-Walsh" on="2023-03-10"/>
    <test>fn:build-uri(map {
  "uri": "ldap://[2001:db8::7]/c=GB?objectClass?one",
  "scheme": "ldap",
  "authority": "[2001:db8::7]",
  "host": "[2001:db8::7]",
  "path": "/c=GB",
  "query": "objectClass?one",
  "query-parameters": map {
    "": "objectClass?one"
  },
  "path-segments": ("", "c=GB")
})</test>
    <result>
      <assert-eq>"ldap://[2001:db8::7]/c=GB?objectClass?one"</assert-eq>
    </result>
  </test-case>
```

I would expect `ldap://[2001:db8::7]/c=GB?=objectClass%3Fone` as result, as the spec says…

> If the `query-parameters` key exists in the map, its value must be a map. A sequence of strings is constructed from the values in the map. For each key and each *value* associated with that *key* in turn:
> * If the *key* is the empty string, the string constructed is the *value* encoded with `encode-for-uri`.

…and `encode-for-uri('?')` gives us `%3F`. How do you handle that in your code?

**Comment by ndw** [comment]
I'm using the same encoding function for `query-parameters` that we describe for `path-segments`. I expect that's what we should do for the same reasons outlined under `path-segments`.

If you agree, I'll update the spec.

**Comment by ChristianGruen** [comment]
> If you agree, I'll update the spec.

Absolutely.

**Comment by ChristianGruen** [comment]
…however (sorry for yet another comment) the rules for `path-segments` say:

> The encoding performed replaces any control characters (code points less than 0x20) and exclusively the following characters with their percent-escaped forms: ` ` (space) `%` (percent sign), `/` (solidus), `?` (question mark), `#` (number sign), `+` (plus sign), `[` (left square bracket), and `]` (right square bracket).

…so we still get `%3F` for `?`. Maybe I have overlooked something?

**Comment by ndw** [comment]
Yes. I spoke too soon. The rules for query parts have to be slightly different because of `=` and `&`. Not encoding `/` and `?` seems reasonable too.

**Comment by ndw** [comment]
I think the note about not using the compromise for query parameters is misguided. And we need special rules for fragment identifiers as well. Bah, say it with me, humbug!

**Comment by ChristianGruen** [comment]
Here are the characters that Spring’s `UriUtils` class adopts as literals in the various components of a URI:

https://github.com/spring-projects/spring-framework/blob/974dec262ccb3f5bb0de8310514bed0167357c11/spring-web/src/main/java/org/springframework/web/util/HierarchicalUriComponents.java#L577-L660

No real fun to define all of that.

**Comment by ChristianGruen** [comment]
@ndw Thanks for the new PR.

Could you please update the tests with your latest implementation? Many test cases don’t seem to match the current spec (with and without this PR). See [`fn-build-uri-from-parse-023`](https://github.com/qt4cg/qt4tests/blob/b5c9431b6e5c7e24729a4de19aac1754b0b34c4a/fn/build-uri.xml#L342-L352), for example:

```xquery
build-uri(map {
  "path": "+1-816-555-1212",
  "scheme": "tel",
  "path-segments": "+1-816-555-1212",
  "uri": "tel:+1-816-555-1212"
})
```

It’s expected to return `tel:+1-816-555-1212`, but the path segment encoding rules require `+` to be encoded.

**Comment by ndw** [comment]
I haven't updated the tests. That's on my list for today. I. meant to have the PR ready to go but...life, ya know?

**Comment by ndw** [comment]
Nice catch. I think the trick here is that the path segments only need to be encoded if the URI is hierarchical. I think something like the following is the solution. A solution. Intertwisted indeed!

> * If the path-segments key exists in the map, then the path is constructed from the segments.
>   To construct the path, **If the scheme is hierarchical,** each segment is encoded, then they are joined together, separated by / (solidus) characters, to form the path. The encoding performed ... . 
>  **If the scheme is not hierarchical, the path is the string value of the first segment, without encoding.**

**Comment by ChristianGruen** [comment]
Sounds fine! I had similar thoughts.

**Comment by ChristianGruen** [comment]
I’ve just added a comment to the PR; maybe we will need to tweak it a little.

**Comment by ChristianGruen** [comment]
Norm, I believe we can call this a great achievement. All test cases are now succeeding!

**Comment by ndw** [comment]
👍 Now I wonder if mine all still pass ... 😄
