### ISSUE TITLE
fn:while-do: Optional error: will not terminate

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#1389]
In many cases, a compiler may detect that a `fn:while-do` or `fn:do-until` function call will not terminate. Trivial examples:

```xquery
while-do((), true#0, identity#1)
while-do((), exists#1, fn($c) { $c, $c }
```

We should add a fixed error code that an implementation sʜᴏᴜʟᴅ (or ᴍᴀʏ?) raise when it encounters such a case. The error can be raised statically (e.g., as the result of type checks) or dynamically (when the input is not known at compile time). We could reuse `XQDY0054`.

In principle, the error code could also be used to reject non-terminating recursive functions:

```xquery
declare function local:rec() { local:rec() };
local:rec()

declare function local:duplicate($input) {
  if(exists($input)) then $input else local:duplicate(($input, $input))
};
local:duplicate(())

let $oh := fn($my) { $my($my) }
return $oh($oh)

(: if we legalize this, see #1379 :)
declare variable $rec := fn() { $rec };
$rec()
```

**Comment by MarkNicholls** [comment]
is it better if such a thing is a warning, I may not intend it to terminate.

**Comment by ChristianGruen** [comment]
True; it may be too protective to prevent users from doing that.

**Comment by ndw** [comment]
The CG agreed to close this issue without further action at [meeting 090](https://qt4cg.org/meeting/minutes/2024/09-17.html).
