### ISSUE TITLE
Annotations: duplicate names

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#1391]
The function `fn:function-annotations` returns a map from QNames to values, which rather assumes that a function cannot have two annotations with the same name. But there is nothing in either the data model or the XQuery language spec that imposes this restriction.

**Comment by michaelhkay** [comment]
I propose that (a) two annotations cannot have the same name, and (b) writing `%a(v1) %a(v2)` is deemed equivalent to writing `%a(v1, v2)`

Further observation: XQuery says "If the namespace URI of an annotation is not recognized by the implementation, then the annotation is ignored." I propose changing this so that the annotation has no effect other than to retain the value and make it visible via the `fn:function-annotations` function.

**Comment by ChristianGruen** [comment]
I’m ashamed to have overlooked that: It’s indeed fairly common for annotations to have the same name, and it’s important to not throw the values together. The most prominent example may be RESTXQ with its query and form parameters: 

https://exquery.github.io/exquery/exquery-restxq-specification/restxq-1.0-specification.html#example-query-parameter-annotation-with-a-default-value

I think we’ll need to change the function definition and return the annotation values as array(s).
