### ISSUE TITLE
`element(a|b)` vs `(element(a)|element(b))`

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#1392]
We have introduced two syntax extensions which achieve the same effect:

`element(a|b)` vs `(element(a)|element(b))`

Do we actually want both?

If we do, I would suggest that we define `element(a|b)` as a shorthand for `(element(a)|element(b))`.

Are they actually equivalent? I think it's fairly clear that they match the same items. It's less clear what the subtyping rules have to say. I think each is a subtype of the other, which means they are substitutable for each other in a function signature, but it needs a lot of digging in the spec to demonstrate this. Are they equivalent from the point of view of coercion rules? I think they probably are, because no coercion actually takes place when the required type is a node type.

So I think there's no technical bug here just a lack of clarity. It would be easier (assuming we want to retain the syntax at all) if we defined `element(a|b)` as a shorthand for `(element(a)|element(b))`.

Minor editorial issues:

- In 3.2.7.2 example 5 is incorrect -- `element(xhtml:*|svg:*|mathml|*)` - the last `|` should be `:`. 
- In the changes section of 3.2.7.2, the `element(A|B)` syntax is not mentioned.

**Comment by ChristianGruen** [comment]
> Do we actually want both?

I’d say yes. It’s simpler and shorter to write `/element(a|b)`, and we need the other syntax to write things like `/(element()|text())`.

Our optimizer rewrites `/(element(a)|element(b))` to `/element(a|b)` (i.e., an element union test).

**Comment by rhdunn** [comment]
I agree that we want both.

This also applies to the `attribute(a|b)` constructs.

**Comment by michaelhkay** [comment]
It gets a bit complicated with XSLT match patterns.

We have special rules for union patterns such as A|B - we split it into two patterns that can have different default priority.

In 4.0 we have extended this rule so it also applies to `child::(A|B)`, which seems reasonable since "child::" is the default axis, so including it shouldn't make any difference.

The same logic suggests that this should also apply to `element(A|B)` - but that is not what I have proposed in PR #1442.

The rules get more and more complicated, and I suggest that we apply the special rules only where the union operator is strictly at the top level of the pattern (which we have to do for backwards compatibility).

**Comment by michaelhkay** [comment]
OK, I've changed PR #1442 so that `match="element(a|b)"` is now handled in the same way as `match="element(a)|element(b)"`.

**Comment by michaelhkay** [comment]
Looking at the subtyping rules, and considering

(a) `element(p|q) ⊆ (element(p)|element(q))`
(b) `(element(p)|element(q)) ⊆ element(p|q)`

Case (b) is true because both alternatives of the choice on the LHS are subtypes of `element(p|q)`.

Case (a) is more tricky. I don't think this is currently true.

**Comment by michaelhkay** [comment]
I've extended the scope of PR #1442 to cover this issue.

**Comment by michaelhkay** [comment]
I think this is effectively closed by virtue of PR #1442 (which suffered some scope creep as it developed).
