### ISSUE TITLE
Casting from duration to string

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#1401]
We've just been examining the rules for casting from duration / dayTimeDuration / yearMonthDuration to string (F+O section 20.1.1) and they are fairly impenetrable: I think we could do better.

* We use the phrase "canonical representation as defined in XSD 1.1 part 2"; a more specific reference would be helpful. Mentioning the function `·durationCanonicalMap·` would take readers straight to the right place.
* The actual XSD spec has one or two typos, and uses some notations that might not be immediately obvious to every reader, for example `|m|` to mean `abs(m)`.

I think the best answer to this is to add non-normative examples, which are badly missing from this whole section.

This would probably require splitting of 20.1.1 into subsections. Alternatively, we could add examples to the string() function, which would have the benefit that we have validation machinery to check that the examples under a specific function are correct; we could point to these examples from 20.1.1.

**Comment by michaelhkay** [comment]
I'm doing a general clean-up of the section, and note a few minor points in passing.

> If ST is xs:string or a type derived from xs:string, TV is SV.

That implies that when casting an `xs:NCName` to `xs:string`, the result should retain the type annotation of `xs:NCName`. I'm not sure that's intended; certainly we don't have a similar rule, for example that casting an `xs:integer` to `xs:decimal` should return an `xs:decimal`. 

In fact there's generally rather too little said about the type annotation of the result of a cast. Perhaps it's assumed that it's the same as the target of the cast. But like any other expression, we should allow it to be a subtype.

For casting dates and times to xs:string the sentence "TV is the local value" is fairly impenetrable. In fact the term "local value" is defined in 9.2 (as "the value with its original timezone"). A hyperlink is needed. But this also raises the question why we have very specific rules for date, time, and dateTime, but not for the 5 gXY types, which are handled simply by the catch-all "in other cases uses the canonical lexical representation" rule.

**Comment by michaelhkay** [comment]
I'm wondering how to tackle the problem that the term "primitive type" is used with two different meanings (and indeed, definitions). In some places it's the 19 atomic primitive types of XSD plus `xs:untypedAtomic`. In other places it's these 19 plus `xs:integer`, `xs:dayTimeDuration`, and `xs:yearMonthDuration`. Really, if we have two different concepts then we should have two different names.

I'm inclined to refer to `xs:integer`, `xs:dayTimeDuration`, and `xs:yearMonthDuration` as _quasi-primitive_, and then say that in section 20, the term primitive includes both the true primitive types and the quasi-primitive types.

**Comment by ChristianGruen** [comment]
What would it mean if someone says that “`xs:integer` is a quasi-primitive type”? Not-quite-a-primitive? Pardon for my ignorance, I never really dived into XSD.

**Comment by michaelhkay** [comment]
The prefix "quasi-X" refers to something that isn't really an X but can be treated for the present purposes as if it were an X.

In XSD, `xs:integer` is a derived type, not a primitive type. Some sections of F+O say that they're going to treat it as if it were primitive. I think we can do better than that.

**Comment by michaelhkay** [comment]
I note that the cross-references to XSD for things like "canonical lexical representation" are to the XSD 1.0 specs. But the way this concept is presented has changed considerably (and is much improved) in XSD 1.1. I propose to change these references to the XSD 1.1 rules (the technical effect is the same).

**Comment by michaelhkay** [comment]
So, why do we spell out how xs:date, xs:time, and xs:dateTime are converted to strings, while simply referring to the XSD specification for gYear, gMonth, etc? As far as I can see, we could happily refer to XSD for all of them, and we would get the same result. But it's a bit hard to prove that, given the obscurity of the XSD notation.

The answer seems to be that in XSD 1.0, timezones were normalized, they were not part of the value space. The seven-property model was introduced in XSD 1.1; but the change was already anticipated in XPath 2.0 F+O. So the fact that we define the algorithm directly rather than by reference to XSD 1.1 seems to be entirely historic.

**Comment by michaelhkay** [comment]
I note that section 20.1.4 talks of durations having six components (year, month, day, hour, minute second) whereas §8.1 makes it clear that we are using a two-component model, months plus seconds.
