### ISSUE TITLE
Align AnyMapTest, AnyArrayTest and with ElementTest

### ISSUE THREAD

**Issue by line-o** [qt4cg/qtspecs#1403]
I always wondered why ElementTests for _any element_ can be written as `element()` which is equivalent to `element(*)` but `as map()` and `as array()` are not permitted and always have to include the asterisk (`map(*)`) .

This is still the case even in XPath4 and I think we should have a look, if this can be omitted.
It does not add any value IMHO, but maybe I am overlooking something important.

https://qt4cg.org/specifications/xquery-40/xquery-40.html#doc-xquery40-ElementTest
https://qt4cg.org/specifications/xquery-40/xquery-40.html#doc-xquery40-ArrayTest
https://qt4cg.org/specifications/xquery-40/xquery-40.html#doc-xquery40-MapTest

The "fix" would be as simple as

```
[255]   AnyMapTest   ::=  "map" "(" "*"? ")"
```

```
[265]   AnyArrayTest ::=  "array" "(" "*"? ")"
```

-- update after comment from @michaelhkay --

The same does _not apply_ to FunctionTest as `as function()` specifies a zero-arity function wheras `as function(*)` matches functions of any arity.

**Comment by ChristianGruen** [comment]
Sounds reasonable to me. We should also allow `fn()` and `function()`.

**Comment by michaelhkay** [comment]
Yes, I agree, this would be more logical.

**Comment by line-o** [comment]
I'll prepare a PR

**Comment by michaelhkay** [comment]
I don't think `function()` is a good idea because it's easily confused with `function() as item()*` which only matches a zero-arity function.

**Comment by line-o** [comment]
I agree `function()` _is_ different from `function(*)`

**Comment by line-o** [comment]
@michaelhkay do I read the EBNF correctly that `function()` is only allowed in combination with the return type (`function() as <some-type>`)?

**Comment by ChristianGruen** [comment]
> @ChristianGruen Sadly, we cannot do that.

Just fine, makes sense, thanks.

**Comment by line-o** [comment]
Not sure how I feel about your idea @ChristianGruen. Trading three characters at the end with three characters at the beginning and having to educate users what this means when they see it in other people's code.
Having all common types in one namespace seems valuable, though.

**Comment by michaelhkay** [comment]
>function() is only allowed in combination with the return type ("function" "(" ")" "as" SequenceType)?

Correct. You can either omit all the types, so `function(*)` matches any function, or you have to include all the argument types AND the return type.

**Comment by ChristianGruen** [comment]
Thanks. Yes, it’s too late for such fantasies.

**Comment by michaelhkay** [comment]
The WG decided not to make the proposed change. The reasoning was, I think, that there was no benefit in introducing synonyms especially as `function()` and `function(*)` mean different things, similarly `record()` and `record(*)`
