### ISSUE TITLE
`fn:unix-time`: Revisions

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#1421]
In yesterday’s meeting, [`fn:unix-time`](https://qt4cg.org/specifications/xpath-functions-40/Overview.html#func-unix-time) was added to the spec. It was proposed to…

1. drop support for negative values and
2. change the function name to `fn:unix-dateTime`.

I sympathize with both suggestions. What do others think?

**Comment by michaelhkay** [comment]
I'm happy with those changes.

**Comment by ndw** [comment]
To answer the question that I asked (perhaps clumsily) during the call, you might consider adding a note to point out that it's easy to go the other way. To find out the Unix time associated with a date, the current dateTime, for example, you can do this:

```
let $epoch := xs:dateTime('1970-01-01T00:00:00Z'),
    $delta := current-dateTime() - $epoch
return days-from-duration($delta) * 3600 * 24
       + hours-from-duration($delta) * 3600
       + minutes-from-duration($delta) * 60
       + seconds-from-duration($delta)
```

I wouldn't object to adding a `dateTime-unix()` function, I guess, but it doesn't seem necessary.

**Comment by ChristianGruen** [comment]
Thanks. I remember it was rather me as your audience who was clumsy.
As Michael noted, a simple `div` is sufficient indeed; I’ll add it as well.

**Comment by ndw** [comment]
*blush* I was sure there was an easier way, but didn't recall what it was when I wrote that comment. I guess that's more evidence that a note would be useful!
