### ISSUE TITLE
Typo in XQuery spec: expresssions

### ISSUE THREAD

**Issue by galtm** [qt4cg/qtspecs#1424]
The XQuery 3.1 spec and XQuery 4.0 draft spec both have an extra "s" in the word expressions, showing it as `expresssions`. The typo occurs in the C.1 Static Context Components section.

I know this repo is only for 4.0 work. Should I make a separate issue in the https://github.com/w3c/qtspecs repo?

**Comment by ndw** [comment]
There's no process by which the 3.x specs can be updated. W3C has closed the WG and the Activity. But we can fix it in 4.0. Thanks.

**Comment by michaelhkay** [comment]
For serious technical errors in 3.1, it's worth noting it in the w3c/qtspecs; even if the base spec never gets updated, it's somewhere to point people to if they hit the issue. But it's not worth bothering for simple typos, I think.

**Comment by galtm** [comment]
Thanks for fixing it in 4.0. I agree with not bothering with 3.1 if the page on w3.org can't be updated. This is neither serious nor a technical error.
