### ISSUE TITLE
fn:xml-to-json: `number-formatter` option

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#1445]
I try to, but I don’t get happy with the `number-formatter` option of `fn:xml-to-json`. It results in a lot of special-casing at serialization time for a very special case. More generally, …

* The option would be much more helpful for outputting maps and arrays as JSON with at serialization time, but it is not available as standard serialization parameter. 
* `fn:xml-to-json` represents numbers as text nodes, so numbers already have a string representation. If needed, they could easily be preprocessed before being serialized as JSON.

I imagine that the major use cases for the option will be:

* to avoid scientific representation for doubles, and
* to be able to serialize `INF` and `NaN`.

Couldn’t we simply allow numeric string values (i.e., the children of `fn:number` elements) to be output without changes?

```xquery
'1000000' => json-to-xml() => xml-to-json()  (: 1000000 instead of 1.0E6 :)
xml-to-json(<fn:number>INF</fn:number>)      (: INF instead of error :)
```

We already have the `number-parser` option, which allows us to generate a string representation for numbers that will be suitable for being converted back with `fn:xml-to-json`. For other cases, the XML source can easily be updated before being passed to `fn:xml-to-json`.

If we really want to keep the option, …

1. We should add examples for its usage in the spec.
2. We need more tests.
3. I would suggest using the function type `(fn(xs:untypedAtomic) as xs:untypedAtomic)?`, similar as for `fn:replace` and `fn:json-to-xml` (this would allow things like `xml-to-json($input, { 'number-formatter': fn { . + 1 } })`).
4. We should also add it as a general serialization parameter to be able to write:

```xquery
serialize(xs:double('NaN'), {
  'method': 'json',
  'number-formatter': fn($n) { if(is-NaN($n)) then '"NaN"' else $n }
})
```

If it’s too much hassle to introduce it as a general serialization parameter, we should at least provide it for `fn:serialize`.

**Comment by michaelhkay** [comment]
The main thing that users asked for was a way of avoiding the XPath 3.1 behaviour where exponential notation is used outside the range 1e-6 to 1e+6. We tried to do this in a generalised way that (a) provided as much flexibility as possible, and (b) retained backwards compatibility.

An alternative would be a boolean option `retain-number-format` that causes the XML representation of the number to be retained unchanged; the user could then preprocess the data to achieve whatever format is desired.

The problem for the JSON serialization method is different, because there we are starting with a number, not with a string.

**Comment by ChristianGruen** [comment]
Usually, additional options make life more difficult. Would it really compromise backwards compatibility too much if we just returned the text value unchanged, so that the following query returns `1000000`?

```xquery
<fn:number>1000000</fn:number>
=> xml-to-json()
```

* For integers, the result would certainly be closer to the original JSON input (and I assume that the reported problems were caused by integer input).
* If the XML is created without JSON source, I would expect people to want a JSON representation that is as close as possible to their text representation.
* It would easily be possible to write things like `<fn:number>"NaN"</fn:number>`. One could argue that this allows for the creation of invalid JSON, or that it introduces the risk of code injection – but this is also true for the current `number-formatter` option.

**Comment by michaelhkay** [comment]
OK, I think that's reasonable.

Note that the rules require the input to be valid against the schema, and the schema for `fn:number` disallowed NaN and ±INF.

**Comment by michaelhkay** [comment]
It would be possible to relax the schema, but I don't particularly think it would be a good idea.

We could perhaps allow `<xsl:number liberal="yes">NaN</xsl:number>`

**Comment by ChristianGruen** [comment]
Yes, it’s probably better to it keep strict. A `{ "n": NaN }` JSON result is not very helpful.
Better results would be things like `{ "n": "NaN" }`, `{ "n": null }` or `{}`, but this makes it a bottomless pit.

**Comment by benibela** [comment]
>The main thing that users asked for was a way of avoiding the XPath 3.1 behaviour where exponential notation is used outside the range 1e-6 to 1e+6. 

And for 64-bit integers

People write `9223372036851234567` in the input, and expect `9223372036851234567` as output, but if it is casted to double, you get `9.223372036851235E18`
