### ISSUE TITLE
fn:deep-equal: default option

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#1462]
The default value for the option parameter of `fn:deep-equal` is:

```xquery
{ 'collation': fn:default-collation() }
```

Can we simply use `{}`, or is there a particular reason for mentioning the `collation` and no other option?

**Comment by michaelhkay** [comment]
The particular reason is an attempt (I don't know if it's entirely successful) to ensure that all dependencies of functions on the static and dynamic context are captured in default values for function parameters.

**Comment by michaelhkay** [comment]
There are certainly plenty of examples of functions that have dependencies on the static context that are NOT made explicit in the default values of parameters, so I think this can be changed.

**Comment by michaelhkay** [comment]
Closed by #1462
