### ISSUE TITLE
fn:element-number: Feedback

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#1463]
1. All other XQFO functions that have `.` as the default value for a node parameter (`fn:name`, etc.) return an empty sequence if the passed argument is an empty sequence. Could we use the same rule for `fn:element-number`?
2. The last example is incomplete; it must be `$e//section...`
3. The last example should return `1.2` instead of `1.1`. If the given result is correct, the equivalent XPath expression needs to be revised.

While it was a no-brainer to implement the function, its specification seems overwhelming to me. I eventually read all the notes, but at the end I was more confused than in the beginning ;·) It could be one of those functions that are more accessible to users than to implementors, though.

Still, maybe at least 1, 2 more examples could be provided? The last example goes into that direction, but it could be a bit cryptic for non-experts (e.g. it expects users to know that the result of `$s/ancestor-or-self::section` is returned in document order).

As this function seems to be mostly targeted to XSLT users, maybe we should offer XSLT examples. I assume that XQuery developers may rather be tempted to enumerate all children/descedants of a node, and write recursive code like…

```xquery
declare function enumerate($element, $numbers) {
  for $child at $pos in $element/*
  let $n := $numbers || '.' || $pos
  return ($n, enumerate($child, $numbers || $n))
};
```

In general, if we were able to generalize the function in one way or another, that would be great.

**Comment by ChristianGruen** [comment]
4. I suggest generalizing the type of `$root` from `(document-node() | element())?` to `node()?`, and instead raise an error if the supplied node is not an ancestor-of-self node of `$element`. An error message like `$root must be ancestor-or-self of $element` is more self-explaining than something like `The type of $root must be (document-node() | element())`.

**Comment by michaelhkay** [comment]
As regards the usability of the function, I think the main use cases are when rendering document-oriented XML into output formats such as HTML or XSL-FO, and it's certainly true that these use cases are more likely to be encountered by XSLT users than by XQuery users. I don't personally feel that a great deal more tutorial material is needed. The problem in providing better examples is that the F+O style is to keep examples very short and simple, whereas showing how to number the clauses of a piece of legislation and then use the clause numbers in an index at the end of the document requires a rather more expansive style.

**Comment by michaelhkay** [comment]
After doing a bit more work on examples, I don't think that specifying $root=".." is adequate for achieving single-level numbering. The problem is that given a structure like this:

```
<chap>
   <section id="a">
      <section id="a1"/>
      <section id="a2"/>
   </section>
   <section id="b"/>
</chap>
```

when $root is set to "..", the section with id="b" is going to be given an element number of 4. Restricting the numbering to sibling elements by using the `predicate` argument doesn't seem an adequate solution.

I'm going to try and draft something that mimics `xsl:number` with `level="single|any|multi"` a bit more closely.

**Comment by Arithmeticus** [comment]
I think there are many practical XQuery uses of `element-number`. For example, supposing an HTML page with tables at arbitrary levels, one could write `/html/body//table[element-number(.) mod 2 eq 1]` to grab every other table.

**Comment by ChristianGruen** [comment]
> For example, supposing an HTML page with tables at arbitrary levels, one could write `/html/body//table[element-number(.) mod 2 eq 1]` to grab every other table.

@Arithmeticus Just to be sure: Isn’t your query equivalent to `(/html/body//table)[position() mod 2 eq 1]`?

**Comment by Arithmeticus** [comment]
Yes, it is equivalent. Perhaps a nudge further might make its advantage a bit clearer, e.g., 
`/html/body//div[hr[element-number() eq 4]]//table[element-number() mod 2 eq 1]` -- gets odd-numbered tables, but only those in the div that is the parent of the fourth hairline.

**Comment by ChristianGruen** [comment]
6. We should move the function from »13.5
Functions on node identifiers« to »2
Functions on nodes and node sequences«
7. After further testing, I think we should generalize the function to accept any node type (even though the formal rules may get more complex: the predicate should only be called if the compared nodes have the same type).

**Comment by michaelhkay** [comment]
I've been working hard to try to produce a specification that (a) is functionally a subset of xsl:number with the options `single` or `any`, and (b) cuts out some of the awkward edge cases that make xsl:number so difficult to implement correctly and so difficult for users to understand in its full complexity. It's challenging to meet both objectives at the same time. In the XSLT 1.0 specification of xsl:number, a lot of edge cases were underspecified, and the 2.0 specification was only produced after a survey of the behaviour of 1.0 implementations on these edge cases.

I'm coming to the conclusion that this exercise was over-ambitious, and I'm going to propose dropping the function. The simple cases are easy to achieve (ignoring performance) using combinations such as `count(preceding-sibling::x[condition])` or `count(preceding::x)[condition][ancestor::x[condition]]`.

One thing that makes such expressions difficult to write is the absence of a convenient and efficient way to get all preceding nodes within a specified subtree. The take-while function helps here: the most common use case for `xsl:number` with level="any", numbering figures within a chapter, can be achieved using 

`1 + count(take-while($fig/preceding::fig, fn{. >> $chapter}))`

[which in turn makes me wonder why we don't have `-or-self` variants of all the axes...]
