### ISSUE TITLE
Inconsistent spelling: implementer or implementor?

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#1464]
We use both spellings.

oxfordreference.com says: Although the variant spelling implementor predominated for much of the late 20th century, today implementer is considered standard.

Personally, being a late 20th century kind of guy, I prefer "implementor", but we should be consistent.

**Comment by dnovatchev** [comment]
Perhaps: **implementœr** ?

Don't want to start an argument here, but we use spellings such as "_auth**or**_" and "_creat**or**_" and not "creat**er**", neither "auth**er**".

One certainly could argue that the choice of spelling for "implementor" has nothing to do with the subject of the documents - the definition of the X* languages and their standard functions. Let us leave this as it is and hope/pray 🙏 this would be the greatest inconsistency in our specifications.

As someone said: " questions about "-er" vs "-or" are the acts of a **_tormenter_** or a **_tormentor_**. "

![image](https://github.com/user-attachments/assets/944fe20c-d480-41b0-a5df-2f340280059f)

**Comment by ChristianGruen** [comment]
German readors, usors and developors will get along with both, but consistency rules.
