### ISSUE TITLE
fn:identity: make it variadic

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#1473]
…see https://github.com/qt4cg/qtspecs/pull/1437#issuecomment-2346599503.

**Comment by michaelhkay** [comment]
I'm not convinced. What should `fn:identity((1,2), (3,4))` return, and why? Whatever it returns, the result doesn't seem to be "identical" to the input.

`fn:void` is another matter. Since that ignores all its arguments, it might as well ignore a variable number of them.

**Comment by MarkNicholls** [comment]
I'd find this very confusing, identity for me, by definition, is not variadic.

**Comment by michaelhkay** [comment]
In the use case given, doesn't `fn:identity#1` serve equally well?

**Comment by ChristianGruen** [comment]
> In the use case given, doesn't `fn:identity#1` serve equally well?

I would assume that `identity#1($value, $old-value)` raises an error, but I may be wrong?

**Comment by michaelhkay** [comment]
The function coercion rules say _If F has lower arity than T, then F is wrapped in a new function that declares and ignores the additional argument_, so supplying `identity#1` is equivalent to supplying `fn($x, $y){identity#1($x)}`.

**Comment by ChristianGruen** [comment]
> The function coercion rules say _If F has lower arity than T, then F is wrapped in a new function that declares and ignores the additional argument_, so supplying `identity#1` is equivalent to supplying `fn($x, $y){identity#1($x)}`.

So I got it right. `fn($a, $b) { $a }` is probably still easier to read than `fn($x, $y){identity#1($x)}`. If `fn:identity` was variadic, though, we could replace `fn($a, $b) { $a }` with `fn:identity#2`.

**Comment by ChristianGruen** [comment]
While I could see some use for a variadic `fn:identity`, it will be hard to teach how it works (the mere existence of `fn:identity` is already a miracle to almost everyone). Maybe it’s better to drop too esoteric endeavors.
