### ISSUE TITLE
Drop variadic functions

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#1478]
We've made a decision -- for good reasons of maintaining extensibility -- not to make any of the functions in the system function library variadic.

I think this raises the question of whether the feature is worth retaining. And we already had the situation that many functions that were obvious candidates for variadicity (min, max, distinct-values, sum) couldn't use the feature because they already had additional optional arguments.

If it's not a good design principle for system-defined functions, then the same applies equally to user-defined functions.

We could drop the feature and just revert to defining concat() as a special case. It would remove a significant amount of complexity.

**Comment by ChristianGruen** [comment]
I think that use cases for variadic functions do exist (see e.g. John Snelson’s [`functional.xq`](https://github.com/jpcs/functional.xq/blob/master/functional.xq) library), but I wouldn’t insist on keeping them.

The feature would certainly be more helpful if function parameters in our languages had static types.
