### ISSUE TITLE
Type `none`

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#1483]
The function `fn:error` uses `none` as return type. This type is only defined in the outdated [XQuery 1.0 and XPath 2.0 Formal Semantics](https://www.w3.org/TR/xquery-semantics/) specification:

1. Do we want to live with the current state?
2. Should we include a better definition in the current specifications?
3. Should we simply use `item()*` as return type, even if the function never returns anything?

If we keep `none`, the test case generator should be revised for [Keywords-fn-error-1](https://github.com/qt4cg/qt4tests/blob/b0d8df63d57ab0ab9f985217178811487f0b74ae/misc/BuiltInKeywords.xml#L74C21-L82).

**Comment by michaelhkay** [comment]
I would be inclined to use `item()*`. That's what we use internally; it has the advantage that it means the optimizer avoids making any assumptions.

**Comment by ChristianGruen** [comment]
> I would be inclined to use `item()*`. That's what we use internally; it has the advantage that it means the optimizer avoids making any assumptions.

+1 That’s what we do as well.

**Comment by michaelhkay** [comment]
Another possibility is to define the return type as `xs:error`. This is a type that has no instances.
