### ISSUE TITLE
Functions for splitting a sequence (or array) based on predicate matching 

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#149]
This is concerned with use cases like "How do I select all the paragraphs before the first H2?" or "How do I select items between <start-milestone/> and <end-milestone/>?".

Currently in the draft spec we have proposals for:

`range-from($input, $predicate)`: Returns a sequence containing items from an input sequence, starting with the first item that matches a supplied predicate.

`range-to($input, $predicate)`: Returns a sequence containing items from an input sequence, ending with the first item that matches a supplied predicate.

These both include the matching item, on the theory that it's easier to drop it if it's not wanted, than to add it if its needed.

I've also proposed (as an alternative) a family of four functions `items-before`, `items-to`, `items-from`, `items-after` giving four combinations of taking the subsequence before/after the first match of the predicate, and including or not including the matched item.

It's worth pointing out that these can all be defined in terms of index-where. For example range-to (assuming at least one item matches the predicate) is subsequence($input, 1, index-where($input, $predicate).

These functions all treat the first match of the predicate as special: they partition the sequence before or after the first item that matches the predicate. An alternative, inspilred by XSLT's for-each-group group-ending|starting-with, would be to partition the sequence breaking immediately before or after every item that matches the predicate:

```
group-breaking-after($input, $predicate)
group-breaking-before($input, $predicate)
```

But these logically return a sequence of sequences, which would typically be presented either as an array of sequences or a sequence of arrays, neither of which is ideal. (An alternative would be to return a sequence of arity-0 functions)

Having reviewed the options, I think my preferance remains having a family of four functions which I have called  items-before, items-to, items-from, items-after. But I'm certainly open to other options. The logical names would probably be subsequence-before etc, but that's a bit of a mouthful.

Whatever family of functions we decide upon, there's logically a requirement to offer the same for arrays.

Michael Kay

**Comment by dnovatchev** [comment]
What about just adding to the two functions a boolean argument: **_`$inclusive as xs:boolean`_** ?

Or having "inclusive" or "exclusive" in the name of the function:

```xq
items-to-inclusive()
items-to-exclusive()
items-from-inclusive()
items-from-exclusive()
```

**Comment by michaelhkay** [comment]
The problem with boolean arguments is that someone reading the code `items-to($input, ->{boolean(self::h2)}, true())` has to either remember or read up on what the semantics of the third argument are. There's almost a case for using a string argument that must be set to "inclusive" or "exclusive".

These suggestions are all possible, but I think my preference is for having four functions rather than two functions with options.

There's always a fine balance between making the semantics of a function evident from its name, and keeping it short. We do know from experience that naming is really important; there's an awful lot of incorrect XPath code written because people jump to wrong conclusions about what contains() does.

Michael Kay

**Comment by ChristianGruen** [comment]
I’d be happy to see only 2 functions (items-from, items-from), as it feels like overkill to have 4 functions that are pretty similar. Or we manage to define a single function with additional options for it. I believe this has been discussed before, I just can't find the sources.

**Comment by ChristianGruen** [comment]
Maybe `items-to` → `items-until` ?

**Comment by michaelhkay** [comment]
I've pushed a proposal that uses the function names

- items-before
- items-after
- items-starting-where
- items-ending-where

**Comment by ChristianGruen** [comment]
I’ll add the examples from https://github.com/qt4cg/qtspecs/issues/80#issuecomment-1253466179 to document possible alternative writings.

`fn:items-starting-where`…

```xquery
items-starting-where(
  1 to 10000,
  function($item) { $item <= 5000 }
)
```

…can also be realized as follows (provided that the condition is only met once):

```xquery
while(
  function($seq) { head($seq) <= 5000 },
  function($seq) { tail($seq) },
  1 to 10000
)
```

Or, taking advantage of various new proposals:

```xquery
while(=> { head(.) <= 5000 }, => { tail(.) }, 1 to 10000)
```

The alternative writing of `fn:items-ending-where` looks similar:

```xquery
items-starting-where(1 to 10000, -> { . <= 5000 }
while(=> { foot(.) >= 5000 }, => { init(.) }, 1 to 10000)
```

If we decide to add a predicate for aborting a loop to `fn:fold-left` and `fn:fold-right`, as proposed in https://github.com/qt4cg/qtspecs/issues/80#issuecomment-1268270809, the following two function calls would be equivalent:

```xquery
items-before(1 to 10000, -> { . = $5 })
fold-left(1 to 10000, (), ->($seq, $curr) { $seq, $curr }, -> { . = 5 })
```

**Comment by ndw** [comment]
I'm all for reuse rather than reinvention, but unless I'm being more than usually thick, `take-while` and `drop-while` aren't semantically the same as any of our functions. "Take while" is "items until not" and "drop while" is "items after not" (or something like that). Can we get a nice set of four functions that include take-while and drop-while?

**Comment by ChristianGruen** [comment]
It's true, the functions are not equivalent. I'm just wondering if our requirements are really that different from those of Scala, Python, C#/F#, Kotlin, Java, and other languages? The main difference I can see is that we have sequences, but apart from some specific and cool features such as implicit flattening, the data structure pretty much resembles lists and arrays.

**Comment by ChristianGruen** [comment]
Accepted and resolved (https://github.com/qt4cg/qtspecs/pull/199#issuecomment-1311487973)
