### ISSUE TITLE
Empty record?

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#1491]
Even if the use cases may be limited: Shouldn’t we allow empty record types and declarations for the sake of completeness?

```xquery
(: check for empty map :)
if($map instance of record()) then ...
```

```xquery
declare record empty();

let $empty as empty := {}
return $empty
```

**Comment by michaelhkay** [comment]
Yes, I think it makes sense.

I wish there were a better syntax than `(( A ("," A)* )?)` for a list-of-A-separated-by-commas (see issue #1366)
