### ISSUE TITLE
Editorial: reduce noise in serialization spec for unused options

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#1499]
I suggest that instead of the repetitive use of paragraphs like "The json-lines serialization parameter is not applicable to the XML output method.", we should have a general statement that serialization parameters are not applicable unless otherwise specified; perhaps accompanied by a chart showing which parameters apply to which methods.

**Comment by ChristianGruen** [comment]
+1 just my thought today!
