### ISSUE TITLE
higher order function group-by or gather-by for grouping

### ISSUE THREAD

**Issue by fsteimke** [qt4cg/qtspecs#1515]
xpath 4 offers a new function `fn:partition`: "_Partitions a sequence of items into a sequence of non-empty arrays containing the same items, starting a new partition when a supplied condition is true_". Looks like an equivalent to XSLT `xsl:for-each-group`with `@group-starting-with`.

I would appreciate another new HOF as an equivalent to XSLT `xsl:for-each-group`with `@group-by`, that is _Partitions a sequence of items into a sequence of non-empty arrays containing the same items, where all items in a partition give the same value when a function f is applied_. This is called `gather-by` in _Mathematica_.

**Comment by michaelhkay** [comment]
I think this is what `map:build()` is designed for. It delivers a map rather than a sequence of arrays because this allows the grouping keys to be retained.

See the example:

```
map:build(
  ("January", "February", "March", "April", "May", "June",
   "July", "August", "September", "October", "November", "December"),
  substring(?, 1, 1)
)
```
Result:	
```
{
  "A": ("April", "August"),
  "D": ("December"),
  "F": ("February"),
  "J": ("January", "June", "July"),
  "M": ("March", "May"),
  "N": ("November"),
  "O": ("October"),
  "S": ("September")
}
```

**Comment by fsteimke** [comment]
Yes, that's what i was looking for. Thanks for the hint.

Perhaps the summary could emphasize this aspect a little more clearly. I would not expect grouping functionality when reading _"Returns a map that typically contains one entry for each item in a supplied input sequence"_.
