### ISSUE TITLE
Test failures in app-spec-examples

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#1516]
I'm getting the following test failures (exluding ones where the Saxon implementation is known to be incomplete).

  **fo-test-fn-csv-to-xml-004 to -010**

These are failing because the results are formatted with whitespace which the example expression does not actually generate.

**fo-test-fn-format-number-005**

Error on line 3 at column 16 (in expression on line 1116) of ... qt4tests/app/fo-spec-examples.xml 
  FODF1310  format-number picture: Digit sign must not appear after a zero-digit sign in the
  integer part of a sub-picture

The test is format-number(12345, '0,###^0', {
  'percent': '%:pc'
})
Result:	
"14pc"

which seems to be a complete aberration.

**fo-test-fn-format-number-008, -009, -010**

fail saying decimal-format 'de' is not defined. The dependency is documented in narrative prose, but is not codified so that the test generator knows about it.

**fo-test-fn-function-annotations-*** **

failing because the examples use a non-existant function xs:QName#2. Probably fn:QName#2 is intended.

** fo-test-fn-highest-005 **
Error 
  XPST0142  Keyword key does not match the name of any declared parameter of function fn:highest

Possible Saxon bug ??

**fo-test-fn-hours-from-dateTime-007**

Example is incorrect - it calls year-from-dateTime not hours-from-dateTime

**fo-test-map-build-007**

Results are not deep-equal to the stated result -haven't established why. Possible whitespace issue.

**fo-test-map-pairs-001**

Getting "assert-permutation failed" from the Saxon test driver. Possible problem with the test driver?

**Comment by michaelhkay** [comment]
fo-test-fn-csv-to-xml - changed the fos:result element to specify `@normalize-space=true`. Necessary but may not be sufficient.

fo-test-fn-format-number-005 - rewrote the example.

fo-test-fn-format-number-008, -009, -010 - needs further thought how to fix this.

fo-test-fn-highest-005 - this was indeed a Saxon bug.

fo-test-fn-hours-from-dateTime-007 - fixed

fo-test-map-build-007 - added @normalize-space="true"

fo-test-map-pairs-001 - this is a known limitation of the Saxon test driver implementation of assert-permutation - for non-atomic results it compares the serialization of the individual items, which in the case of maps is unpredictable.

**Comment by ChristianGruen** [comment]
Some more:

#### fo-test-fn-element-number-005

`let $s := //section` should be `let $s := $e//section`

#### fo-test-map-build-007

> Results are not deep-equal to the stated result -haven't established why. Possible whitespace issue.

It uses `assert-xml`, but the string value is a map: `{ "Java": (...`.

#### fo-test-fn-id-00[12], fo-test-fn-element-with-id-00[12], fo-test-fn-idref-00[12]

`XQST0075` (Validation not supported) should be an alternative result.

#### fo-test-fn-collation-003

The order of the query parameters may be implementation-dependent:

```
http://www.w3.org/2013/collation/UCA?lang=de;strength=primary
http://www.w3.org/2013/collation/UCA?strength=primary&amp;lang=de
```

**Comment by michaelhkay** [comment]
Some of these problems are going to be a bit challenging; we don't have the mechanisms to inject dependencies and publish alternative results when generating test cases.

Perhaps the answer is to allow a full environment and/or results element (in test suite format) to be included in the fos:example element in the function catalog?

**Comment by michaelhkay** [comment]
For functions whose return type is a named record type, we are generating an invalid test, for example (note the missing return type):

```
<test-case name="Keywords-fn-atomic-type-annotation-1">
      <description>Test of keyword arguments in fn:atomic-type-annotation</description>
      <created by="generate-keyword-test-set.xsl" on="2024-11-06"/>
      <environment ref="ka"/>
      <test>fn:atomic-type-annotation(value := ?) instance of function(xs:anyAtomicType) as </test>
      <result>
         <assert-true/>
      </result>
   </test-case>
```
