### ISSUE TITLE
Ambiguity in XSLT Pattern Grammar

### ISSUE THREAD

**Issue by johnlumley** [qt4cg/qtspecs#1522]
I've tested the grammar against the ~500 distinct patterns in the stylesheets of the `attr/match` test sets (which is the largest collection I can find). As far as I can tell, there is one ambiguity inherent in the current grammar, which is not covered by notes, in that the pattern
```
id()
``` 
(and similar for `element-with-id()`, `key()` and `root()`) can parse (in reduced form) in two ways:
```
<Pattern40 xmlns:ixml="http://invisiblexml.org/NS" ixml:state="ambiguous">
   <RootedPath>
      <FunctionCallP>
         <OuterFunctionName>id</OuterFunctionName>
         <ArgumentListP/>
      </FunctionCallP>
   </RootedPath>
</Pattern40>
<Pattern40 xmlns:ixml="http://invisiblexml.org/NS" ixml:state="ambiguous">
   <PostfixExprP>
      <FunctionCallP>
         <OuterFunctionName>id</OuterFunctionName>
         <ArgumentListP/>
      </FunctionCallP>
   </PostfixExprP>
</Pattern40>
```
that is, there are two paths, via `RootedPath` and `RelativePathExprP/StepExprP/PostfixExprP` to get from `PathExprP` to `FunctionCallP`

**Comment by michaelhkay** [comment]
This problem was caused by issue #1375 / PR #1378.

**Comment by michaelhkay** [comment]
I think we can solve it simply by removing the FunctionCallP option from RootedPath, that is:


`RootedPath ::= VarRef  Predicate* (("/" | "//") RelativePathExprP)?`
