### ISSUE TITLE
document-uri of xslt transformation primary output

### ISSUE THREAD

**Issue by fsteimke** [qt4cg/qtspecs#1536]
When using XSLT transformations, it would be helpful in many cases to know the transformation target, that is the base-uri of the primary result document. This would allow, for example,

- to make the uri of secondary result documents relative to the primary base-uri to ensure that all output is in the same target directory
- to copy media files from transformation source directory into transformation target directory
- to generate a transformation report as secondary output, which informs and links to the primary result document

I am pretty sure that there are situations where the URI of the primary result document is undefined or unknown. The XPath function `fn:document-uri` is decribed as "Returns the URI of a resource where a document can be found, if available.". So maybe we could have a new function `fn:primary-result-document-uri` as "Returns the URI of the primary result document, if available.".

**Comment by michaelhkay** [comment]
Dod you overlook current-output-uri?

https://www.w3.org/TR/xslt-30/#func-current-output-uri

**Comment by fsteimke** [comment]
Yes, i did. Never seen before ... sorry

**Comment by michaelhkay** [comment]
No problem!
