### ISSUE TITLE
Managing indentation parameters for serialization

### ISSUE THREAD

**Issue by ndw** [qt4cg/qtspecs#1548]
In the [discussion](https://qt4cg.org/meeting/minutes/2024/10-29.html#pr-1497) of PR #1497 at [meeting 096](https://qt4cg.org/meeting/minutes/2024/10-29.html), some concern was expressed that the default value for indentation might be problematic in testing.

It was observed that all of the serialization parameter settings are defined by the host language, not by the serialization specification, but that did not resolve the concerns.

Can we/should we/would we mandate that indentation is disabled by default? (Is that not already the case in XQuery and XSLT?)

**Comment by michaelhkay** [comment]
I don't think there's any harm in allowing a client of the serializer to make indent="yes" the default; it might be appropriate for some scenarios, and in any case, there's nothing we can do to prevent it.

XSLT specifies that the default for `indent` is `false` for the XML output method, `true` for HTML and XHTML It makes no statement for JSON, which is an omission we should rectify.

XQuery specifies a default of indent=no irrespective of output method, as does the fn:serialize function.
