### ISSUE TITLE
XQFO: Formal Specification

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#1554]
In the XQFO, the “Formal Specification” sections present XPath/XQuery expressions that are equivalent to the introduced function.

In a previous meeting, it has been noted that “Equivalent Expression” may be a better term for these sections.

Would it be sufficient to simply rename the section, and adapt the wording in [1.5.5 Formal Specification](https://qt4cg.org/specifications/xpath-functions-40/Overview.html#id-function-signatures-formal-specification)?

**Comment by michaelhkay** [comment]
Note that in some cases we give an equivalent XPath expression, in others we give an equivalent XQuery function. It's all controlled by markup and stylesheet rules, so it's easily changed.
