### ISSUE TITLE
Grammar productions missing spec conditionality

### ISSUE THREAD

**Issue by johnlumley** [qt4cg/qtspecs#1574]
The XPath grammar currently projects the following productions, which appear to be only relevant to XQuery, are not reachable from the `XPath` root, and either lack an `if="xquery40"` condition, or wrongly have `xpath40` in the condition:

`ExtendedFieldDeclaration`, `ParamListWithDefaults`,`ParamWithDefault`

In fact, the grammar doesn't allow default values for arguments of inline functions.  Is this the case?

**Comment by michaelhkay** [comment]
>the grammar doesn't allow default values for arguments of inline functions
Correct. Issue #1175 proposes the feature, but it's not currently in the spec.
