### ISSUE TITLE
Allow $key in map:contains to be empty

### ISSUE THREAD

**Issue by Arithmeticus** [qt4cg/qtspecs#1579]
I wonder if we could relax the 3rd line of the current signature...
```
map:contains(
   $map	as map(*),	
   $key	as xs:anyAtomicType	
) as xs:boolean
```
...to:
```
   $key	as xs:anyAtomicType?	
```

It hit me tonight, as I was running a lengthy operation, and some nulls were passed to `key`. I expected the function to return false, not raise an error.

**Comment by ChristianGruen** [comment]
The empty sequence is already allowed for `fn:contains` and `fn:contains-subsequence`. Ironically, both return `true` in that case, so we might need to clarify whether the semantics of `map:contains($map, ())` is obvious enough.

If we generalize the key, we could also generalize `fn:contains-token`.

**Comment by michaelhkay** [comment]
I'm inclined to keep the status quo. 

One day we might generalize maps to allow arbitrary sequence (or perhaps arbitrary atomic sequences) as keys, and then `()` would have a different meaning.

And I suspect that passing `()` is more likely to be an error than not. It's not too much of a hardship to write `if (exists($key) and map:contains($map, $key))`

**Comment by Arithmeticus** [comment]
In this particular I don't think the `()` was an error, but I get your point about not changing things without thinking about long-term development. I'll close this issue.
