### ISSUE TITLE
typos: dependant and repeated word

### ISSUE THREAD

**Issue by galtm** [qt4cg/qtspecs#1594]
I spotted two typos in the XSLT 3 spec, and I'm reporting them here because they are in the XSLT 4 spec as well, in https://raw.githubusercontent.com/qt4cg/qtspecs/refs/heads/master/specifications/xslt-40/src/xslt.xml

- dependant, in "versions of the packages on which this package is dependant."
- "the the ", in "appears in the the initializing expression"

**Comment by ChristianGruen** [comment]
Maybe it should even be `dependent` (BE → AE; I’ll let natives judge).
