### ISSUE TITLE
Editorial: wording in https://qt4cg.org/specifications/xpath-functions-40/Overview.html#func-concat misses "be" in "and the arguments can sequences of strings "

### ISSUE THREAD

**Issue by martin-honnen** [qt4cg/qtspecs#1595]
I think there is a slight wording/grammar issue in https://qt4cg.org/specifications/xpath-functions-40/Overview.html#func-concat saying 

> The function can now take any number of arguments (previously it had to be two or more), and the arguments can sequences of strings rather than single strings.

It it probably meant to say

> The function can now take any number of arguments (previously it had to be two or more), and the arguments be can sequences of strings rather than single strings.

**Comment by ChristianGruen** [comment]
…or “can be” (what a smartass reply)

**Comment by ChristianGruen** [comment]
I’ve create a little PR (to be not just a smartass). Thanks for the observation.
