### ISSUE TITLE
XQuery version number

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#1628]
In XQuery 1.0 and 3.0 the version number was simply a string.

XQuery version 3.1 specified that 

> An XQuery version number consists of two integers separated by a dot. 

In 4.0 we have taken this rather literally, and have spelled out the consequences in a note:

> The version numbers 4.01 and 4.1 are equivalent: both have a major number of 4 and a minor number of 1. Version 4.10 by the same reasoning has a higher minor number than version 4.2.

This is completely counter-intuitive. 

I propose that we eliminate the confusion by requiring the version number to consist of two single-digit integers separated by a dot.

**Comment by michaelhkay** [comment]
The syntax of the version declaration seems convoluted. It allows you to omit the version number or the encoding but not both. I don't see any sense in that. Why not simplify it to: 

`VersionDecl ::=  "xquery"  ("version"  StringLiteral)? ("encoding"  StringLiteral)? Separator`

**Comment by MarkNicholls** [comment]
its usual to disallow leading zeros in versions, and simply compare based on interpreting each dimension as a natural number.

(though i accept people do complicated things nowadays, this isnt the case here)

> Version 4.10 ... has a higher minor number than version 4.2

yes, thats the usual case, I think

**Comment by ChristianGruen** [comment]
In addition, we could clarify what (we believe) is the rationale behind the version declaration.

The spec says:

> Similarly, the version number “1.0” indicates the intent that the module be processed by an XQuery 1.0 processor, “3.0” an XQuery 3.0 processor, and “3.1” an XQuery 3.1 processor.

Currently, Saxon, eXist, BaseX and presumably other processors return a result for an XQuery 1.0-tagged query even if the actual expression is a 3.0 one, or later:

```xquery
xquery version '1.0';
1 ! 2
```

Personally, I never use query declarations. Their use in the wild seems pretty random to me.

**Comment by michaelhkay** [comment]
There are three reasons I wrote the rules to disallow 4.10.

- It might be read by some users as synonymous with 4.1
- In XSLT, it **is** synonymous with 4.1 (the version number is interpreted as an `xs:decimal`)
- It's very unlikely we will ever want to define a language spec with a minor version of 10

**Comment by benibela** [comment]
>The syntax of the version declaration seems convoluted. It allows you to omit the version number or the encoding but not both. I don't see any sense in that. Why not simplify it to:

I guess the point was that if you want to omit both, you can just omit he entire declaration

>    Version 4.10 ... has a higher minor number than version 4.2

>yes, thats the usual case, I think

always on Linux

on Windows I have seen 4.10 being below 4.2


>Currently, Saxon, eXist, BaseX and presumably other processors return a result for an XQuery 1.0-tagged query even if the actual expression is a 3.0 one, or later:

not all of them

```
$  xidel -e -
xquery version '1.0';
1 ! 2
Error:
err:XPST0003:  requires XPath/XQuery 3.0

```

**Comment by benibela** [comment]
>Process the module using the specification of the XQuery version identified in the version declaration.

That is what it does

and then ` 1 ! 2` throws  an error
