### ISSUE TITLE
Keyword arguments: ":=" or ":"?

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#165]
In function calls using keyword arguments, should we use the syntax `name := value`, or `name : value`?

Regarding `:=`:

* Function declarations in XQuery will presumably use the syntax `name := value` to define the default value for a parameter,  by analogy with initial values in global variable declarations, so it seems consistent to use `name := value` in function calls as well
* The syntax `name := value` is also used in XPath `let` expressions to bind a value to a variable name.

Regarding `:`:

* It matches the use in map constructors
* It's used this way in C#
* There is a need to use whitespace to prevent ambiguity, for example in a construct like `f:display(first: first, last: last)`; moreover, if the space is omitted, there is a danger that the expression will still be valid but will have an unintended meaning.
* Map constructors also require the disambiguating whitespace, but with map constructors, use of a bare name on the LHS is unusual (more common is a string literal in quotes), and failure to include the whitespace is almost certain to lead to a syntax error.

My feeling is that `:=` is the better choice.

Note: `=` (as used in Python) is not an option, because a call like `not(x = y)` already has a well-defined meaning.

**Comment by ndw** [comment]
The possible ambiguity of `first:last` vs `first: last` is a showstopper IMHO. We should use `:=`.

**Comment by ChristianGruen** [comment]
In practice, ambiguities are rare, as parsing can only succeed if the first NCName is also declared as a namespace prefix.
But I agree we shouldn’t necessarily introduce ambiguities if there is no urgent need to do so.

**Comment by dnovatchev** [comment]
**`:=`** is fine

**Comment by michaelhkay** [comment]
We might also like to consider including a "$" with the keyword:

`local:f(12, option := 'foo')`

vs

`local:f(12, $option := 'foo')`

The rationale is that although the $ is redundant, it is already used redundantly in the XQuery function declaration

`declare function local:f($input, $value := 'bar');`

so this gives better consistency between XQuery function declarations and function calls.

**Comment by ChristianGruen** [comment]
I had similar thoughts. At last, I thought it would imply that an RHS value is assigned to an LHS variable, which is not the case here.

If we omit the dollar character, it may be more obvious that we are working with names of _parameters_, not _variables_.

**Comment by ChristianGruen** [comment]
Using quotes followed by a single colon may be another variant. It would resemble the map syntax, and the parameter name would not be limited to NCName characters:

```xquery
fn:serialize($node, 'method': 'xml')

(: as a shortcut for :)
fn:serialize($node, map { 'method': 'xml' })
```

**Comment by michaelhkay** [comment]
That raises the thought that we could use `$input := $node` when binding a declared parameter of the function, and `'method': 'xml'` when binding an entry in the options map. (But my current thinking is that map-variadic functions are a step too far: the complexity outweighs the convenience.)

**Comment by ndw** [comment]
Given how prevalent `$` is when referring to variables in XPath, I think users will expect:

```
local:f(12, $param := 'value')
```

Remembering that it's `param` (without a `$`) when the value is a keyword parameter feels like a burden that doesn't add any value. Isn't that also going to lead to cleaner error messages? If the name has no `$` then doesn't it introduce the  possibility that it's a (child::)`param` that's out of place? (I mean, obviously, not with the `:=` after it, but I can imagine cases where multiple syntax errors compound in an ugly way.)

**Comment by ndw** [comment]
I hypothesize that the amount of cognative effort required to remember where `$` is required for a variable/parameter names and where it isn't plus the amount of time spent finding and inserting or removing the necessary `$` when users get it wrong will outweigh the amount of time required to strike one additional key by at least several orders of magnitude. 

How does requiring a leading `$` on the parameter name make `${name}` valid? Isn't that possibility the same regardless of whether or not a leading `$` is required on parameter names?

**Comment by michaelhkay** [comment]
In general, redundancy tends to benefit readers of the code over writers of the code, which is a win unless it becomes extreme (and one character isn't extreme). Also, redundancy tends to make it possible to produce better error messages, and tends to make it easier to extend the language in the future.

I think that the consistent visual pattern `$name := 'value'` as used in XQuery variable declarations, let expressions, and now function declarations, with essentially the same semantics of binding a name to a value, makes a good case for including the "$" in function calls also.

**Comment by ChristianGruen** [comment]
There’s one bigger concern I have, and it’s the entirely different semantics we’d be introducing here:

```xquery
(: Existing syntax: The value of a variable called `$input` is supplied
   as first parameter value (no matter how the parameter is named). :)
fn:tail($input)

(: Proposed enhanced syntax: A value `abc` is assigned
   to a parameter named `input`. :)
fn:tail($input := 'abc')
```

The following expression would get legal, and even get a common pattern…

```xquery
(: Assign the value of a variable called `$input` to
  as parameter named `input`. :)
fn:tail($input := $input)
```

…but it doesn’t feel very intuitive to me. It rather looks as if we wanted to do something like re-assigning a value to the same variable, and then pass on the result to the function.

Next, I doubt that most people think of “assigning values to variables” when they call functions, in particular built-in ones. Instead, the usual notion rather is to “supply arguments” to a function, and it’s a new concept to give meaning to the names of parameters.

I believe we could avoid confusion by using a dedicated syntax for the assignment of parameters (as proposed above):

```xquery
fn:tail('input': $input)
```

If we choose to support map-variadic functions in a next step, I would choose the same syntax to keep things simple.

**Comment by ndw** [comment]
It doesn't feel especially different to me. When I first started writing XQuery, I'd write things like:

```xquery
let $t1 := ...some complicated expression...
let $t2 := $t1[...some complicated expression...]
let $result := $t2[...predicate...]
return
   <r>{$result}</r>
```

Eventually, I learned that I could just write it with one variable name, even though it looked a bit weird at first:

```xquery
let $result := ...some complicated expression...
let $result := $result[...some complicated expression...]
let $result := $result[...predicate...]
return
   <r>{$result}</r>
```

I fact, `let $x := $x` is perfectly legitimate, I think.

Am I failing to grasp the thing that's different?

**Comment by benibela** [comment]
>…but it doesn’t feel very intuitive to me. It rather looks as if we wanted to do something like re-assigning a value to the same variable, and then pass on the result to the function.

That is my concern, too

Especially if there is a scripting extension with mutable variables where you can write `$x := 123; $x := $x + 1` and get `124`. Or something with loops like `$x := 0; while ($x < 100) { $x := $x + 1 }`.  Then you could debug the loop by adding trace   `$x := 0; while ($x < 100) { trace($x := $x + 1) }`  (which should print 1..100)

**Comment by benibela** [comment]
It could use some other prefix for parameters

E.g. `local:f(12, §param : 'value')`

or 

E.g. `local:f(12, €param : 'value')`

**Comment by michaelhkay** [comment]
We decided to use `:=`, with no $ sign.
