### ISSUE TITLE
JSON maps

### ISSUE THREAD

**Issue by benibela** [qt4cg/qtspecs#1655]
Now that we are discussing different types of maps, there could also be JSON maps. Then each map would have a property `json`, that can be false or true. If it is false, it is an ordinary map like now. If it is true, it is a "JSON map".

A JSON map can only have string keys, and all map functions would enforce that constraint by casting the key to string.

Parse-json and json-doc would return a JSON map. As would the bare brace `{}` constructor for compatibility with Javascript.

For example

    let $json := parse-json('{"1": 234}')
    return map:put($json, 1, 456)

would return a JSON map `{"1": 456}`.

    let $json := parse-json('{"1": 234}')
    return map:contains($json, 1)

would return true.

**Comment by Arithmeticus** [comment]
Would there also be constraints on a JSON map's values?

**Comment by michaelhkay** [comment]
If there are properties of maps that we think are currently missing, then we should find a way to add those properties without tying them to a particular way of creating the maps. I think that's basic to orthogonal design.

Constraining a map to only have string-valued keys (and to drop the type annotation if the key is a subtype of xs:string) could certainly be a handy optimisation (having to retain the type annotation is an overhead that delivers almost no value). But I see no reason to tie it to JSON. And as @Arithmeticus  points out, calling it a "JSON map" might also suggest that, for example, the value cannot be a multi-item sequence.

**Comment by michaelhkay** [comment]
I don't think there's anything viable here; propose closing with no action.

**Comment by ndw** [comment]
The CG agreed to close this issue without further action at [meeting 103](https://qt4cg.org/meeting/minutes/2024/12-17.html).
