### ISSUE TITLE
List-valued options represented as arrays

### ISSUE THREAD

**Issue by GuntherRademacher** [qt4cg/qtspecs#1659]
The specification of the of the [option parameter conventions](https://qt4cg.org/specifications/xpath-functions-40/Overview.html#option-parameter-conventions) contains this:

> In cases where an option is list-valued, by convention the function should accept either a sequence or an array: but this rule applies only if the specification of the option explicitly accepts either. Accepting a sequence is convenient if the value is generated programmatically using an XPath expression; while accepting an array allows the options to be held in an external file in JSON format, to be read using a call on the fn:json-doc function.

In particular, it says

> ...this rule applies only if the specification of the option explicitly accepts either...

However I could not find any option that explicitly makes use of "accepts either" in the specification. In the tests, I found two cases where arrays are passed as option values: [`numberformat-510`](https://github.com/qt4cg/qt4tests/blob/8be46fb7e7e22164dd9005d9c53e7d2f585bbb90/fn/format-number.xml#L3757-L3770) (here the option isn't even list-valued), and [`serialize-xml-106a`](https://github.com/qt4cg/qt4tests/blob/master/fn/serialize.xml#L1332-L1349).

I am wondering whether the above paragraph might be superfluous. The text preceding it says that option values are coerced to the required type, and that implies converting an array to its member sequence, doesn't it?

**Comment by michaelhkay** [comment]
>the function should accept either a sequence or an array

I thought we had dropped that, but it seems not. Thanks for pointing it out.

**Comment by GuntherRademacher** [comment]
Fixed by #1664.
