### ISSUE TITLE
XSLT Conditional Instructions

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#167]
These changes are already present in the draft specification: this issue is being raised to seek WG endorsement of the changes.

See section 8 of the specification.

1. In `xsl:if`, add optional `then` and `else` attributes
2. In `xsl:when` and `xsl:otherwise`, add an optional `select` attribute which can be used in place of the sequence constructor
3. Add a new `xsl:switch` instruction

Justification: these changes do not add any functional capability to the language, they simply provide a small improvement in usability. The changes are self-contained with no dependencies on other changes.

**Comment by johnlumley** [comment]
This addition of `@select|<sequence-constructor>` syntax to the conditionals suggests to me whether this can also be added to `xsl:template` or indeed` xsl:function` declaration/instructions ?

**Comment by michaelhkay** [comment]
The only reason I have hesitated adding a `select` attribute to `xsl:function` and `xsl:template` is the relationship to `xsl:param`. It feels a little bit odd to have the function implementation before the parameter declarations:

```
<xsl:function name="f:square" as="xs:double" select="$x * $x">
  <xsl:param name="x" as="xs:double"/>
</xsl:function>
```

But it's certainly doable.

Also related is the idea that it should be possible for template rules to access the values of parameters in the match pattern.

```
<xsl:template match="para[@class=$c]">
  <xsl:param name="c" as="xs:string"/>
</xsl:template>
```

**Comment by Arithmeticus** [comment]
Just getting to this in prep for today's meeting.

I do not understand how `xsl:switch` differs fom `xsl:choose`. What is the impetus?

I like the idea of `@then` and `else`, but as a prospective programmer, I immediately think of reaching out for `<xsl:then>` and `<xsl:else>` children of `<xsl:if>`, to handle complex constructions. Rationale: the same one that prompts me to avoid `@select` and use a content constructor instead. Sometimes the content if only for maintenance shouldn't be compressed in an attribute value.

**Comment by michaelhkay** [comment]
xsl:switch is a fairly minor convenience to the author and to the optimiser: instead of writing

```
<xsl:choose>
  <xsl:when test="$xxx = 1" select="'January'"/>
  <xsl:when test="$xxx = 2" select="'February'"/>
  <xsl:when test="$xxx = 3" select="'March'"/>
  ...
</xsl:choose>

```
you can write

```
<xsl:switch select="$xxx">
  <xsl:when test="1" select="'January'"/>
  <xsl:when test="2" select="'February'"/>
  <xsl:when test="3" select="'March'"/>
```

Not a very big deal, just a bit of sugaring for a very common use case.

The construct `<xsl:if test="C" then="X" else="Y"/>` is mainly intended for use as a replacement for

`<xsl:sequence select="if (C) then X else Y"/>`

which is often found as the body of an `xsl:function`. It's more concise and more readable than either that form, or the alternative

```
<xsl:choose>
  <xsl:when test="C" select="X"/>
  <xsl:otherwise select="Y"/>
</xsl:choose>
```

**Comment by michaelhkay** [comment]
The changes were accepted on 2022-11-08 - https://qt4cg.org/meeting/minutes/2022/11-08.html
