### ISSUE TITLE
XSLT Extension Instructions invoking Named Templates

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#168]
This feature is already present in the draft specification; the issue is being raised to seek WG endorsement of the change.

See section 10.1.3 of the draft.

The change is self contained with no dependencies. It adds no new functionality, merely syntactic convenience.

**Comment by ndw** [comment]
👍 👍 👍

**Comment by michaelhkay** [comment]
See also issue #92 which proposes a modification to the propsed spec.

**Comment by kosek** [comment]
I would like to extend this proposal and allow sequence constructor inside extension instruction. I'm using such instructions in my code and it would be nice to be able to rewrite them to pure XSLT 4.0 code. Sequence constructor could be mapped to predefined parameter name. E.g.

````
<t:_>Hello world.</t:_>
````

Would be translated to
````
<xsl:call-template name="t:_">
  <xsl:with-param name="xsl:input">Hello world.</xsl:with-param>
</xsl:call-template>
````

**Comment by Arithmeticus** [comment]
What if anything would prevent an application of the same convenience to functions as well?

How likely is it that a writer or reader might confuse an extension instruction with a result tree element or vice versa? Is there a way to mitigate the potential confusion? Probably not, other than inculcating a habit of not using a namespace for both functionality and output.

**Comment by Arithmeticus** [comment]
Answered my own second question, of course less than a minute after sending, namely, the guardrail of [extension instructions](https://qt4cg.org/specifications/xslt-40/Overview.html#extension-instruction).

**Comment by ndw** [comment]
Jirka will raise his idea for an extension as a separate issue.

**Comment by ndw** [comment]
The CG agreed to close this issue without further action at [meeting 081](https://qt4cg.org/meeting/minutes/2024/06-11.html#close-without-action)

**Comment by michaelhkay** [comment]
For clarification: the issue was to seek WG confirmation of the status quo text, which is now approved. Note that there is no PR.
