### ISSUE TITLE
XPath ternary conditional operator

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#171]
The draft XPath specification proposes a ternary conditional operator

`C ?? X !! Y`

with the same semantics as

`if (C) then X else Y`

This issue seeks WG endorsement of this enhancement.

The choice of operator symbols is from Perl; no other obvious candidates are available.

The proposal is free-standing, it has no dependencies or interactions.

The proposal adds no new functionality, but in some contexts (especially in the middle of an expression that uses symbolic operators rather than keywords) it aids readability:

`//employee[@salary > (@currency == 'GBP' ?? 10000 !! 12000)]/@name`

There is room for debate about the operator precedence.

**Comment by ChristianGruen** [comment]
Thanks for adopting the proposal for the ternary operator.

The current specification gives `IfExpr` and `TernaryConditionalExpr` the same precedence, which seems reasonable to me.

**Comment by ndw** [comment]
Perl uses `?` and `:`, `currency eq 'GBP' ? 10000 : 12000`. (I  suppose it might also use `??` and `!!`, but I've never seen them in a Perl script.) 

To be honest, I'm not sure I find

```
//employee[@salary > (@currency == 'GBP' ?? 10000 !! 12000)]/@name
```

more readable than

```
//employee[@salary > (if (@currency == 'GBP') then 10000 else 12000))]/@name
```

I'm not going to object if the CG wants to do this, but I wouldn't bother.

BTW, is `==` in your example a typo? I don't see `==` as an equality operator in the current 4.0 draft, but I might have missed it.

**Comment by ChristianGruen** [comment]
`?` and `:` have been declared obsolete in Perl 6 and replaced with `??` and `!!`. In 2019, Perl 6 was [renamed to Raku](https://en.wikipedia.org/wiki/Raku_(programming_language)). To further complicate things, there will also be Perl 7 in the future, which may again be based on Perl 5 …

The conditional operator has already become fairly popular in BaseX. It would be nice to have it officially supported.

**Comment by ndw** [comment]
Right. I've no objection. And thanks for the Perl update. There was a time when I did a lot with Perl, but not recently.

**Comment by dnovatchev** [comment]
> //employee[@salary > (@currency == 'GBP' ?? 10000 !! 12000)]/@name

**`==`**   ?

**Comment by ChristianGruen** [comment]
> `==` ?

Just a typo.

**Comment by michaelhkay** [comment]
The group decided on 2023-01-17 to drop this feature.
