### ISSUE TITLE
Record Tests

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#172]
The draft XPath specification includes a proposal for Record Tests - see section 3.6.4.3. This issue seeks WG endorsement of this enhancement, and also for the use of Record Tests as match patterns in XSLT.

The purpose of the feature is to provide more useful type checking for common use cases where maps are used to represent heterogeneous data. The feature enhances the type system but doesn't change the data model (that is, the new types represent a new way of placing constraints on the value space of maps, without introducing new kinds of values or new operations).

The type subsumption rules for record tests proposed in §3.7.2 clauses (m) et seq include a couple of TODO entries that need completing.

**Comment by rhdunn** [comment]
The record tests should support `record(*)` like with the other types. See https://github.com/qt4cg/qtspecs/issues/52 for the proposed syntax and semantic changes.

**Comment by michaelhkay** [comment]
I'm closing this. Record tests have become, de facto, a core feature of the QT4 specifications.
