### ISSUE TITLE
parse-json() - option to return numbers as xs:decimal

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#176]
In response to a user request (https://saxonica.plan.io/issues/5708) I propose addition of an option to `fn:parse-json()`, say `number-type=double|decimal|string`, which causes numbers in JSON to be returned as `xs:decimal` or `xs:string` values rather than `xs:double`. Use of values with more digits of precision than `xs:double` supports is common in JSON practice, despite warnings in the RFC that it's not interoperable; and the fallback to `xs:string` is handy for people who have the misfortune to be processing incoming JSON where leading zeroes are significant (for example, Belgian VAT numbers).

The change also affects `fn:json-doc()`

**Comment by benibela** [comment]
Like that: https://github.com/qt4cg/qtspecs/issues/33

**Comment by michaelhkay** [comment]
Closed as a duplicate of issue #33.
