### ISSUE TITLE
Should we allow vendor-defined optional parameters on built-in functions?

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#182]
Now that we allow optional parameters on functions, with invocation by keyword, we could permit vendors to extend the function signature with optional parameters in a vendor-defined namespace. It would be required (obviously) that such parameters are optional.

A caveat is that under the current specification, (a) we can't stop the value of such a parameter being supplied positionally (perhaps unintentionally), and (b) the availability of such a parameter changes the arity range of the function, which potentially brings it into conflict with other like-named functions (for example functions introduced in the future).

A possible way of resolving this conflict is to propose that parameters whose name is namespaced can ONLY be supplied by keyword, and don't contribute to the arity range of the function. However, for user-defined functions, this rule would not be backwards compatible.

And a possible way around that is to say that the extensibility policy for a function is a property of its namespace; and to adopt different extensibility policies for built-in function namespaces and user-defined function namespaces.

Perhaps this is over-elaborate, and we should just make sure that functions that vendors might wish to extend have an options parameter, even if no standardised options are defined.

**Comment by dnovatchev** [comment]
I am strongly opposed to allowing vendors to "extend" standard functions.

With unknown and unpredictable possible multitude of "extensions" such a function no longer deserves to be called "standard" and I strongly caution and urge users to stay away from using such "standard" functions.

The only purpose such "extensions" have is for a vendor to achieve users' lock-in, as committing to such a vendor-specific extension would make any future attempts to switch vendors/implementations highly impossible.

Let us try to promote portability and vendor-independence despite the fact that nearly a half of us work for the same vendor.

**Comment by ChristianGruen** [comment]
I agree with Dimitre. I believe we should rather try to get interesting vendor-specific extensions defined in the specification.

**Comment by ChristianGruen** [comment]
My primary reaction was a rather strict denial. My reflected reaction now is to confess that I repeatedly stumble upon custom function parameters that are difficult, if not impossible, to standardize. Two arbitrary examples from our microcosm:

* [util:replicate](https://docs.basex.org/wiki/Utility_Module#util:replicate) has a `$multiple` parameter, which enforces the first argument to be evaluated repeatedly.
* [file:read-text-lines](https://docs.basex.org/wiki/File_Module#file:read-text-lines) has `$offset` and `$length` parameters to restrict the lines to be returned.

In both cases, I would not vote for making the parameters part of the official specifications, as they are too specific, driven by performance considerations, or used by internal query rewritings. It would indeed be helpful to make them legal in the built-in functions.

I insinuate that Michael had similar cases in his mind.

**Comment by michaelhkay** [comment]
Yes, there are cases where we've created a variant of a standard function in the Saxon namespace in order to add extra parameters, e.g. saxon:doc() is fn:doc() with an options parameter to control things like schema validation and DTD validation. In that case I would actually be happy to see all those options standardised. saxon:deep-equal() similarly.

**Comment by michaelhkay** [comment]
I think our approach should probably be to identify functions where adding an options parameter would be beneficial. Once the function accepts an options parameter, it automatically allows vendor-defined options.

**Comment by michaelhkay** [comment]
The proposal attracted little support so I am withdrawing it.
