### ISSUE TITLE
Highlight EBNF grammar differences in the diff versions of the specs

### ISSUE THREAD

**Issue by rhdunn** [qt4cg/qtspecs#20]
The diff versions of the specs highlight what has changed in the wording of the specifications, which is useful, but don't highlight the differences in the EBNF grammar. This makes it harder for implements and tool vendors to work out what has changed in the grammar to then know what changes need to be made to the lexer and parser in order to support the new constructs.

**Comment by michaelhkay** [comment]
I'd be happy to do this if I had the technology...

**Comment by ChristianGruen** [comment]
@rhdunn I’d love to see this happening, too, but I guess we won’t be able to fix this. Should we close the issue?

**Comment by michaelhkay** [comment]
I've been thinking about the diff-ing.

For our internal use, we're moving to automated diffing of the rendered HTML, which works fine, and handles grammar changes just like anything else, though of course it has problems e.g. highlighting irrelevant changes like section numbers and production numbers.

For external publication, I think we should aim to publish a diff against the last W3C spec (3.0 or 3.1) as the baseline. That means we should keep diff markup in the XML, and the versioning in the diff markup should identify the external draft we are publishing (so we have the capability to diff against the previous external draft if we so decide). That means in the current phase of work, all changes should be marked `at="A"`. I don't think there's any real technical difficulty in doing this for the grammar, it just needs a few hours' work understanding the relevant XSLT code.

**Comment by ndw** [comment]
We should **absolutely** continue to publish editorially managed diffs off the 3.0 or 3.1 baseline specifications. The automated markup is not a replacement for good diffs on the published specifications, it's just an aid for review.

Since I appear to have become the build master, I'm happy to look at the XSLT changes necessary for diffing the grammar changes, if someone will explain what's needed.

**Comment by ChristianGruen** [comment]
@ndw, @rhdunn Stupid question: Is this one still valid / do we want to keep it open?

**Comment by ndw** [comment]
I have no current plans to work on this, but if someone can explain what is needed, I'm not unwilling to try.

**Comment by ndw** [comment]
The CG agreed to close this issue without action [meeting 59](https://qt4cg.org/meeting/minutes/2023/12-19.html).
