### ISSUE TITLE
Make higher-order-function support mandatory

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#205]
I think higher-order-functions are becoming a core part of XQuery and XSLT; we shouldn't encourage the mindset that they should be avoided because not all implementations will support them. I therefore propose dropping this as an optional feature; the relevant capabilities should become a core part of the language in 4.0, supported by all conformant implementations.

**Comment by michaelhkay** [comment]
This can be achieved by the following textual changes:

* Delete XQuery section 5.2.6, Higher-Order Function Feature
* Delete error code XQST0129
* In F&O, abandon the tagging of functions as higher-order
* In XSLT. delete section 28.7 Higher-Order Function Feature and the references to it
* Delete error code XTSE3540
* The system property xsl:supports-higher-order-functions is retained, and always returns yes
* In F+O 16.1 delete the sentence "Some host languages may exclude higher-order functions from the set of functions that they support, or may include such functions in an optional conformance feature."
* In the XQuery and XSLT change logs, explain the change.

**Comment by ndw** [comment]
Closed by PR #326
