### ISSUE TITLE
New reserved function names

### ISSUE THREAD

**Issue by rhdunn** [qt4cg/qtspecs#21]
In section A.3 (Reserved Function Names) of the XPath 4.0 and XQuery 4.0 draft specifications, the tuple and union keywords have been added.

I don't think these (or more accurately, the keywords for the new item type constructs) are needed, as they cannot currently be used in places where functions can. Only KindTests can appear as path expressions, and the only other reserved names should be for other types of expression (if, switch, typeswitch, etc.).

From a similar reasoning, the following keywords should be able to be removed from the list as they are also only ItemTypes/SequenceTypes:
1. array
2. empty-sequence
3. map

Kind regards,
Reece

**Comment by rhdunn** [comment]
Note: removing `array` and `map` from the reserved function name list would allow variadic `fn:array` and `fn:map` constructor functions to be defined, which would be accessible as unprefixed functions from an XSLT+XPath context.

**Comment by michaelhkay** [comment]
I think the reason these were included in the list was some combination of (a) a desire for parsing to be context-independent, (b) clearer error diagnostics when users get things wrong, (c) leaving space in the language for future growth.
