### ISSUE TITLE
Loss of OS-specific line breaks

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#212]
When an XML document is parsed, `CR` is discarded and replaced by `LF`. The serialized result won’t have `CR` either:

```xquery
let $CR := '&#xd;', $LF := '&#xa;'
let $input := '<a>' || $CR || '</a>'
let $xml := parse-xml($input)
let $output := serialize($xml)
return (
  contains($xml, $CR), contains($output, $CR),
  contains($xml, $LF), contains($output, $LF)
)
```

This is no proposal, but something we should keep in mind when discussing #101 and #121: Do we want to pursue and motivate an asymmetric approach by focusing on the processed and output data (i.e. insertion of `CR` characters in strings; new serialization parameter for custom newline strings), or should we rather strive for a solultion that also takes care of the input/import? Which could be:

1. Provide newline parameters for `fn:parse-xml`, `fn:doc`, `fn:collection`, possibly others; or
2. Use OS-specific newline strings

Interestingly, `CR` is preserved if `fn:unparsed-text` is used.

**Comment by michaelhkay** [comment]
The normalization of line endings in XML is defined by the XML specification, and isn't something we have any control over; we won't get CR characters in the result of XML parsing unless the user has gone to great lengths by escaping them. I don't think there are any changes we can usefully make to XML parsing or serialization.

Text input and output is another matter. 

The `unparsed-text()` function leaves line endings as written; but the unparsed-text-lines() function essentially handles them in the way XML does.  I'm not sure any change there would be useful; though if we added an options parameter to unparsed-text() then we could provide an option to normalize line endings.

For text serialization (and presumably this applies also to JSON) there has long been a demand for an option to set how line endings should be written.

Was there anything else you had in mind?

**Comment by ChristianGruen** [comment]
Oh right. I shouldn’t mess with rules that have been specified 25 years ago (https://www.w3.org/TR/WD-xml-971117#sec-line-ends). That said, it sounds like a good decision anyway to normalize line endings. Intuitively, I would have expected `fn:unparsed-text` to apply the same normalization rules as for XML; but things are as they are. Adding an  option for that sounds like a good choice to me (I have created #216 for that).

I’ll close the issue, and I take away that `&#xa;` can be regarded as line-ending/newline character for values in XML.
