### ISSUE TITLE
FLWOR without FL

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#214]
Resulting from thoughts in https://github.com/qt4cg/qtspecs/pull/210: Do we want to make `let` and `for` optional?

From the query optimization perspective, this seems reasonable as especially `let` clauses may become obsolete after inlining variables.

From a user point of view, I’m not convinced that the resulting syntax would be intuitive:

```xquery
return 123
```

…could indicate that the `return` keyword has some special meaning, or people might be confused that/why it's equivalent to `123`, or night start using the keyword esp. in function bodies.

```xquery
where test()
return 'ok'
```

…could be used as alternative for an `if` expression with any empty `else` branch; but people might be confused why `if` cannot be used without `else`.

What do others think?

**Comment by michaelhkay** [comment]
I don't see a pressing need to make changes here. It's one of those cases where a an over-zealous pursuit of orthogonality suggests allowing things that quite likely to be user errors (the orthogonality versus paternalism debate). The group-by, order-by, and count clauses are completely pointless as the first thing in a FLOWR expression, and while orthogonality means you should sometimes allow things for which there is no known use case, I don't think the current design is broken and I don't think it needs to be fixed.

**Comment by ChristianGruen** [comment]
Of informational nature; closing this.
