### ISSUE TITLE
fn:unparsed-text: End-of-line characters

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#216]
**UPDATED PROPOSAL (2023-10-31):**

Change the default behavior and normalize the input as known from XML (https://www.w3.org/TR/xml/#sec-line-ends). Even though backward-incompatible, the change should be noninvasive enough, and it allows us to dispense with adding options to this and other functions.

----

**ORIGINAL PROPOSAL:**

### Motivation

`fn:unparsed-text` can only be used if the input is valid. Next, the result may contain OS-specific newlines that may need to be normalized in a subsequent step. Two additional parameters might simplify things:

* `normalize`: normalizes line endings in the input, as done by `fn:doc`, `fn:parse-xml` and `fn:parse-xml-fragments` and as defined in https://www.w3.org/TR/xml/#sec-line-ends (inspired by the discussion in #212).
* `fallback`: Process characters that are not valid in the version of XML supported by the implementation (inspired by `fn:parse-json`)

### Signature

```xquery
fn:unparsed-text(
  $href    as xs:string?,
  $options as map(*)
) as xs:string?
```

### Rules

The entries that may appear in the `$options` map are as follows:

Key | Meaning
-- | --
`encoding` | The name of an encoding … (see existing rules)
`normalize-newlines` |  `false` by default. If set to `true`, two-character sequences `#xD#xA` and any `#xD` that are not followed by `#xA` are translated to single `#xA` characters.
`fallback` | A function which is called when the input contains an escape sequence that represents a character that is not valid […] (see [`fn:parse-json`](https://qt4cg.org/specifications/xpath-functions-40/Overview-diff.html#func-parse-json)).

**Comment by ndw** [comment]
I'm not even sure I would have remembered that unparsed-text didn't normalize line endings. I bet I've got code that only works because of luck!

👍

**Comment by michaelhkay** [comment]
I would prefer to do it by adding an open-ended $options parameter, for future extensibility.

Normalize has too many meanings (for example it could imply normalize-unicode). I suggest normalize-newlines.

The description of $fallback is wrong (there are no escape sequences). Should say "which is called when the input contains a character that is not valid ..."

Perhaps we should also allow (at implementor discretion) an option to accept invalid characters as if they were valid, and just say that if you do that, the effect of using strings containing invalid characters in subsequent operations is implementation-dependent.

**Comment by ChristianGruen** [comment]
> I would prefer to do it by adding an open-ended $options parameter, for future extensibility.

+1. Good to hear we can probably rewrite this to an `$options` parameter.

> The description of $fallback is wrong (there are no escape sequences). Should say "which is called when the input contains a character that is not valid ..."

Absolutely (I should have quoted some more words from the original text).

> Perhaps we should also allow (at implementor discretion) an option to accept invalid characters as if they were valid, and just say that if you do that, the effect of using strings containing invalid characters in subsequent operations is implementation-dependent.

My personal preference would be to remain as strict as possible, and to ensure that processed items will never violate general rules of the data model. But I would first need to find out if there are rules at all.

I have updated the initial proposal.

**Comment by ChristianGruen** [comment]
Related (character set restrictions): https://github.com/qt4cg/qtspecs/issues/414

**Comment by ChristianGruen** [comment]
We’ve got repeated feedback that preserving `#xd;` in the parsed result is unexpected (and I think it’s mostly because `fn:doc` behaves differently) and I cannot think of any use cases in which it would be necessary, even more because the serialization follows its own rules.

Would it be too invasive to change the default behavior and to normalize the input as it’s done for XML (https://www.w3.org/TR/xml/#sec-line-ends)? I believe we could then dispense with adding options to this and other functions.

**Comment by michaelhkay** [comment]
I'd be reasonably comfortable with normalizing line endings by default but I think we'll hit trouble if we don't provide an option to retain the existing behaviour. I bet someone somewhere is using unparsed-text() to read content that requires the line endings to be done a particular way, and where they expect to reject the content if it doesn't follow the rules.
