### ISSUE TITLE
Function library for maps with composite keys: and thoughts on encapsulation

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#218]
I propose creating a function library that handles maps with composite keys. I'll start by defining a set of functions, then we'll consider how to package these, in particular issues of encapsulation and types. Even it we don't want to implement this particular feature, it might help to generate infrastructure that makes it easier to create such function libraries.

For the sake of a name, I'll call the data structure we are manipulating an **atlas**. (Like a map, but generalized.) An atlas is a mapping from sequences of atomic values to values. Two sequences of atomic values are equal if they are the same length and their constituent atoms are pairwise equal according to op:same-key(). Note that keys are variable length and it's permitted to have both ("a") and ("a, b") as entries in the atlas.

We'll start by defining the API we want to offer. The semantics for these functions are essentially the same as the corresponding functions for maps. The type of $key is always xs:anyAtomicType*. We'll discuss the type of $atlas later.

- atlas:build($input, $keyFunction, $valueFunction, $onDuplicates) => atlas

- atlas:get($atlas, $key) => value

- atlas:contains($atlas, $key) => value
 
- atlas:put($atlas, $key, $value) => atlas

- atlas:keys($atlas) => array(key)

- atlas:for-each($atlas, function(key, value)) => value

- atlas:size($atlas) => integer

plus some more specific functions:

- atlas:get-branch($atlas, $partial-key) => atlas

returns an atlas containing all those entries in the supplied atlas whose keys start with the supplied partial-key; the returned atlas contains the remaining parts of the keys.

- atlas:put-branch($atlas, $partial-key, $atlas branch) => atlas

Similarly, grafts one atlas as a subtree into another.

It's not too hard to come up with an implementation of this API that uses nested maps. For example: An atlas-node is a map from atomic-values to `record(leaf? as value, branch? as atlas-node)`, where leaf contains the value if the atlas contains the relevant key in full, while branch contains a nested atlas if the atlas contains nodes starting with the relevant prefix; either or both may be present.

Now the tricky part: how to handle encapsulation. There are two parts to this: (a) defining a type that can be used to represent an "atlas" in the API, and (b) preventing users subverting the API by accessing the implementation objects (atlas-nodes) directly.

There are features we can build on: the proposal for named item type aliases, and the sketchy definition of "external objects" in XSLT.

We could handle the first part by allowing the declaration of a named item type (or alias) to specify something like visibility=closed. So the function library comes with an item type whose name is atlas:atlas, and this type name is available for use by anyone who imports the function library, but they never get to know exactly what an atlas:atlas is other than the fact that it's an item, so they can never know what other functions they might be able to call on it.

But that doesn't stop them guessing (or asking, using `if ($atlas instance of map(*)` interrogatives).

To deal with that, we could consider expanding the existing half-defined concept of an "external object". XSLT 3.0 §24.1.3 sketches out the idea:

> An implementation may allow an extension function to return an object that does not have any natural representation in the XDM data model, whether as an atomic value, a node, or a function item. For example, an extension function sql:connect might return an object that represents a connection to a relational database; the resulting connection object might be passed as an argument to calls on other extension functions such as sql:insert and sql:select.
> 
> The way in which such objects are represented in the type system is [implementation-defined](https://www.w3.org/TR/xslt-30/#dt-implementation-defined). They might be represented by a completely new datatype, or they might be mapped to existing datatypes such as integer, string, or anyURI.
> 

So `atlas` could be an external object type. The module that implements the function library could contain private methods that wrap a map as an atlas, or that unwrap an atlas to reveal the underlying map. I think the only additional support needed is a construct to wrap a value as an encapsulated object of a given type, and to unwrap an encapsulated object to return the original value.

Note: I can imagine the same mechanism being useful to handle "parcels", and no doubt we will find many other applications for it.

**Comment by dnovatchev** [comment]
Thanks for posting this. It is interesting.

The first questions that come into mind:

1. Why not just extend the existing `map` datatype by saying that a map key can be any sequence (of atomic items in this case, though we could also consider any item type that is different from a (non-map or non-array) function.

2. What pressing reason is there to introduce new concepts such as "atlas", and "atlas-branch" when we know that this is essentially a map?

**Comment by michaelhkay** [comment]
There were two aims in posting this. First, to test the feasibility of creating such "class libraries", reducing the need to add new features to the core specifications; and to investigate what new primitives were needed to enable this. Secondly, to explore whether we could meet the requirement for maps with composite keys without a data model change, because data model changes are always complicated and pervasive in their impact and best avoided if at all possible; they also tend to lead to backwards incompatibilities. (We've so far managed to avoid touching the XDM and serialisation specs, and we would immediately need to make changes to both.)

**Comment by ChristianGruen** [comment]
I really think we shouldn’t touch existing maps. I think we’ll be more flexible in the long run by not trying to push all new requirements into the existing native data structures, even more if they haven't been designed for such extensions. If you think of other languages such as Java, there are hash maps, identity maps, tree maps and numerous other kinds, each of which has advantages and drawbacks. The concept of defining extensions that build upon the basic data model looks promising, it could also be used (I assume) to allow ordered maps, maps with nodes as keys, and so on.

Sorry for repeating myself; I know many concerns on changing the status quo have already been discussed in #119.

**Comment by dnovatchev** [comment]
Personally I feel seek of seeing so many new types being introduced...

I t is really difficult to remember even their names and purpose. 

"**_Parcels_**", now "**_Atlases_**" ... (<s>Eww...</s>)

Why can we in C# (a much more general PL) have just a **_Dictionary_** and a **_HashSet_** class and that's it. And having generics helps keep things general and simple.

An obvious reason for not loving the next versions of XPath/XQuery/XSLT emerges as they are becoming more and more overwhelming with new concepts that are difficult to understand, neither completely related nor unrelated to each other, and all this brings unwanted and unexpected ambiguity that hinders understandability.

At the rate this is growing, I wouldn't be surprised to wake up one morning and find that "**_parcels_**" are within "**_containers_**" and "**_Atlases_**" (which have many **_maps_** in "**_branches_**" ) are a projection of a "**_cosmic view_**", and god knows what...

And then, probably "**_entanglement_**" and something "**_charming_**"...

**Please, don't get me wrong**: I am not against the new functionality. I am against presenting it with more and more concepts, while in fact this functionality belongs to and naturally extends concepts that we already know well.

**Comment by dnovatchev** [comment]
In order to make things much simpler:

**_For any key we want to specify a non-atomic value for, let us do so by giving it the string produced by the serialization_** (say with :`"method":"json"`) of the sequence.

**Example**:

We want to have a map with key-value: 

```xq
[ map{"x" : 1, "y": 2}, [2,   3] ]
```

Then when we specify this:

```xq
let $myMap := map
{ 
     [ map{"x" : 1, "y": 2} , [2,   3], (), []  ] : "myValue"
}
return $myMap(map{"x" : 1, "y": 2}, [2,   3] ])
```

It will be processed by the XPath processor as if the following XPath 3.1 expression was specified

```xq
let $myMap := map
{ 
    "[{'x':1,'y':2},[2,3],null,[]]" : "myValue"
}
return $myMap("[{'x':1,'y':2},[2,3],null,[]]")
```
and would correctly return:

`myValue`

![image](https://user-images.githubusercontent.com/10605892/197077027-a33fd71f-c077-48d8-aca8-b104c37f29cc.png)



**What do you think**?

**Comment by liamquin** [comment]
By analogy with sort, another way might be to have a sort of map that uses a key generator function. It could be a regular map,
keymaker : function($items as item()*) as xs:string,
map: map(*)

and if user-defined types include maps, could be declared as a named type.

**Comment by dnovatchev** [comment]
I think @liamquin wants to say that **_`fn:serialize`_** may be an instance of the **_`keymaker`_** argument of **_`map`_** (or **_`map-build_`** ? )

**Comment by michaelhkay** [comment]
Generalising what maps can contain certainly affects existing functionality. It affects most of the functions that operate on maps, the lookup operators, serialization methods, functions such as `deep-equal()`, the subsumption rules, the rules for option parameters, record types, and probably quite a few things I haven't immediately thought of.

**Comment by dnovatchev** [comment]
> I'm completely confused by the suggestion of using the JSON serialization of a sequence as a key. Currently we allow keys that can't be properly serialized in JSON, **for example dates.** I don't see how that would be a useful way forward.

I am still under the impression that dates can be serialized successfully, for example with BaseX this code:

```xq
let $d := current-date()
  return  map{serialize($d, map{"method":"json"}) :  current-date()}
```

is evaluated successfully and  gives us:

```xq
map{"""2022-10-24-07:00""":xs:date("2022-10-24-07:00")}
```

And this:

```xq
let $d := current-date(),
    $older :=  xs:date("2022-10-23")
  return  map{serialize($d - $older, map{"method":"json"}) :  $d - $older}
```

is evaluated to:

```xq
map{"""P1D""":xs:duration("P1D")}
```

Besides dates, what other datatype to try?

**Comment by michaelhkay** [comment]
If a map contains dates as keys, they are serialized as strings, so they don't round-trip. In the worst case, if a map includes both strings and dates as keys, the result of serialization contains duplicate strings. JSON is **more** restrictive than XDM in what it allows as keys; I thought our aim was to be **less** restrictive.

**Comment by dnovatchev** [comment]
@michaelhkay,

The suggestion was:

> **_For any key we want to specify a non-atomic value for, let us do so by giving it the string produced by the serialization_** 

an `xs:date` is an atomic type, thus we will not serialize it, it is the value of the key.

If a value is not an atomic one, in this case only we serialize it and use the result of the serialization as the value of the key.

**Comment by dnovatchev** [comment]
> JSON is **more** restrictive than XDM in what it allows as keys; I thought our aim was to be **less** restrictive

I am reading the **_[Serialization Specification](https://www.w3.org/TR/xslt-xquery-serialization-31/#json-output)_** and do not see any restriction for keys. It literally says (the 2nd bullet):

> _- A [map item](https://www.w3.org/TR/xslt-xquery-serialization-31/#dt-map-item) in the data model instance is serialized to a JSON object by outputting, for each key/value pair, the [string value](https://www.w3.org/TR/xslt-xquery-serialization-31/#dt-string-value) of the key [to a JSON string](https://www.w3.org/TR/xslt-xquery-serialization-31/#to-a-json-string), followed by ..._

**Comment by ChristianGruen** [comment]
> I am still under the impression that dates can be serialized successfully, for example with BaseX this code:
> 
> ```xq
> let $d := current-date()
>   return  map{serialize($d, map{"method":"json"}) :  current-date()}
> ```
> 
> is evaluated successfully and gives us:
> 
> ```xq
> map{"""2022-10-24-07:00""":xs:date("2022-10-24-07:00")}
> ```

The BaseX GUI uses a custom serialization method for presenting results, which combines features of existing serialization methods. For function items (including maps and arrays), the `adaptive` method comes into play, the output of which is of mainly informational nature. The result can be ambiguous or incomplete. For example, `map { 0: ->{} }` is output as `map { 0: (anonymous-function)#1 }`.

**Comment by dnovatchev** [comment]
> The BaseX GUI uses a custom serialization method for presenting results, which combines features of existing serialization methods. For function items (including maps and arrays),

@ChristianGruen Thanks for explaining this.

Still, the idea is to represent the map-key as a string (thus serialization) and use an unambiguous way of doing so.

Just the ability to represent an array in this way is sufficient (as noted by @benibela in #119)

This is much simpler and easier to understand and work with than introducing the concept of "atlas".

**Comment by Arithmeticus** [comment]
I find the introduction of an atlas confusing. As a prospective developer in the language, I first assume the construct to be as different from maps and arrays as the two are from each other (otherwise why would such an unusual name be needed?). That an atlas is (I think) merely a map on steroids is confusing (so far).

On the other hand, I am growing more hesitant about allowing maps to have composite keys, reflected in questions posed in a recent [post to #119 ](https://github.com/qt4cg/qtspecs/issues/119#issuecomment-1291285847). I wonder what other map functions might suffer complications that hinder adoption.

As I understand it, the idea of composite keys is motivated by an attempt to avoid the hassle of constructing and navigating a treelike structure of nested maps. Understandable enough. But maybe that's the ideal we should be serving.

I'll float a different approach, if only so it can be shot down. 

What about keeping the map model as is, but introducing the syntactic sugar needed for creating/navigating maps that gives the impression of working with composite keys (the map example @dnovatchev led with in #119), but was built and internally represented as a nested map structure? That is, composite keys would be merely an alias for nested maps whose entries have single keys.

This approach I realize would require discussion on what additional restrictions if any should be imposed. For example, someone might construct the following: `map{ (1, 2) : "x", 1 : map{ 2 : "x" } }`. What would `map:get-xpath4((1, 2))` return? I wouldn't have a problem with `("x", "x")` (that's how it was made), but others might have such a problem. Is it ok that `map:get-xpath4(1)` would return `(map{ 2 : "x" }, map{ 2 : "x" })`? I'm ok with that (again, it's up to the builder to be responsible), but maybe others won't be so keen. I think such shorthand makes the navigation of nested maps significantly easier, and more XPath-like. The most significant challenge I think would be expressing the syntactic rules.

One other benefit (I think) from my suggestion is that the map functions would not need to be overhauled because the map's data structure would remain unchanged. Instead, the suggestion lends impetus to a desideratum I've heard expressed more than once, to develop map functions so they can be applied deeply. For that, I propose that for as many map functions as is appropriate a deep counterpart, e.g.: 

- `map:deep-keys($map as map(*)) as array(xs:anyAtomicType*)`
- `map:deep-get($map as map(*), $key as xs:anyAtomicType*) as item()*`
- `map:deep-contains($map as map(*), $key as xs:anyAtomicType*) as xs:boolean`
- `map:deep-size($map as map(*)) as array(*)`

I suppose those should be raised as separate items. (I did a search in the issues section and didn't see anything. Does anyone know? It's hard to keep track of all the proposals.)

**Comment by dnovatchev** [comment]
> This approach I realize would require discussion on what additional restrictions if any should be imposed. For example, someone might construct the following: `map{ (1, 2) : "x", 1 : map{ 2 : "x" } }`. What would `map:get-xpath4((1, 2))` return?

So:

```xq
let $m := `map{ (1, 2) : "x", 1 : map{ 2 : "x" } }
  return ( $m((1, 2)), $m(1), $m(1)(2) )
```

produces:

```xq
 "x",
 map{ 2 : "x" },
"x"
```

> I wouldn't have a problem with `("x", "x")` (that's how it was made), but others might have such a problem. Is it ok that `map:get-xpath4(1)` would return `(map{ 2 : "x" }, map{ 2 : "x" })`?

No, as shown above, evaluating this produces:

 `map{ 2 : "x" }`

**Comment by michaelhkay** [comment]
This discussion fizzled out with no concrete proposal for a way forward, so I propose closing it with no action.

**Comment by ndw** [comment]
The CG agreed to close this issue without further action at [meeting 070](https://qt4cg.org/meeting/minutes/2024/03-19.html#close-without-action).
