### ISSUE TITLE
Options on fn:deep-equal

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#219]
The function `fn:deep-equal` makes some arbitrary decisions about how values are compared, and many applications need slightly different comparison semantics. This issue proposes adding an options parameter to customise the comparison rules.

The following options are proposed (detailed syntax TBA):

- For comparing atomic values, use op:same-key rather than eq. Note this implies ignoring the collation.
- When comparing children of a node, don't ignore comments
- When comparing children of a node, don't ignore processing instructions
- When comparing children of an element, ignore whitespace text nodes (except where the element node has a simple type)
- When ignoring comments and processing instructions, merge adjacent text nodes
- When comparing strings (etc), perform Unicode normalization
- When comparing strings (etc), perform whitespace normalization
- Compare as if untyped (ignore type annotations and typed value)
- Compare as typed (type annotation must match)
- Require the same in-scope namespace bindings on every element
- Require elements and attributes to have matching prefixes
- Compare the is-ID and is-IDREF properties on elements and attributes

**Comment by rhdunn** [comment]
These and possibly others are listed in the discussion for #98.

**Comment by michaelhkay** [comment]
Closed as a duplicate of #98
