### ISSUE TITLE
Encapsulation

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#220]
Let's suppose that I want to provide a library to do complex number arithmetic, and I want to hide how complex numbers are actually implemented (it could be an array of two doubles, or a map containing two doubles, it could be in polar coordinates, etc).

How might I go about doing this? One approach is like this (please be patient):

```
module namespace complex...;

declare %public type alias complex:number as function(*);

declare %private variable SECRET := <e/>;

declare $private function complex:wrap($content as record(re as xs:double, im as xs:double)) as complex:number {
    function($key as node()) {if ($key is $SECRET then $content else error());
};

declare $private function complex:unwrap($cx as complex:number) as record(re as xs:double, im as xs:double) {
   $cx($SECRET);
};

declare %public function complex:new($re as xs:double, $im as xs:double) as complex:number {
  complex:wrap(map{'re':$re, 'im':$im})
}

declare %public function complex:real($x as complex:number) as xs:double {
  complex:unwrap($x)?re
}

declare %public function complex:add($x as complex:number, $y as complex:number) {
  etc;
}

```
What's going on here? We're representing a complex number as an arity-1 function; the function "unlocks" the complex number to reveal its internal implementation, but it can only be called if you know the secret argument to pass, and this is encapsulated within the library module that implements the functionality. So we've successfully encapsulated the implementation, and we've done it without any data model changes. Within the provider module, the functions wrap() and unwrap() are available to convert from the internal representation to the external representation; these functions are not available to the caller. 

It works, but it's hardly elegant.

From the point of view of the user of the library, it's quite usable: they just import the library and call the functions. They probably don't care that the type complex:number is actually a function, and if they do care, there's not much they can do with the knowledge.

From the point of view of the author of the library, there's a lot of boilerplate. One thing we could do to improve matters would be to provide some syntactic sugar. Instead of a module declaration, use a class declaration:

```
class complex:number wraps record(re as xs:double, im as xs:double);

declare %public function complex:real($x as complex:number) as xs:double {
  complex:unwrap($x)?re
}

declare %public function complex:add($x as complex:number, $y as complex:number) {
  etc;
}
```

The boilerplate, especially the wrap and unwrap functions, is now implicitly declared.

And we could provide "import class" for the caller as an alternative to "import module".

We could go further and give the magic function used to represent an encapsulated value some kind of special status in the data model. But do we need to?

**Comment by michaelhkay** [comment]
One thing that's missing from this design is type safety. Because `complex:number` is merely an alias for the type `function(*)`, there's nothing to stop the caller of a function that expects an argument of type `complex:number` from supplying a decoy function that matches this signature. Moreover, the library function would typically call the decoy function, with the secret key as the supplied argument, and the decoy function could capture the secret key and misuse it. So the mechanism certainly isn't secure. Does this matter? Encapsulation is primarily about software robustness, not about security.

**Comment by line-o** [comment]
On the topic of secret keys: JavaScripts Symbols are a good way to have properties or keys that are only known and therefore accessible for the scope they are created in. 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol

**Comment by michaelhkay** [comment]
See also issue #720.

**Comment by ndw** [comment]
The CG decided to close this issue without any further action at [meeting 069](https://qt4cg.org/meeting/minutes/2024/03-12.html).
