### ISSUE TITLE
Expose op:same-key() as a user-visible function

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#221]
In issues #94, #96, and #99 a set of functions for comparing sequences are proposed; all of them are parameterized with a function for comparing items.

A useful function for comparing items is op:same-key() (useful because it is error-free, context-free, and transitive). For this and other reason, it would be useful to expose op:same-key() as a user-visible function.

The only tricky question is what to call it. I suggest "atomic-equal".

Alternatively, we could overload the "is" operator to compare atomic values using `op:same-key()`, and use op("is") as the argument to the sequence comparison functions.

**Comment by michaelhkay** [comment]
I think it would also be useful to reorganise the exposition so that the 'eq' operator for `xs:boolean`, `xs:hexBinary`, `xs:base64Binary`, `xs:duration`, `xs:QName`, and `xs:NOTATION` is defined in terms of `fn:atomic-equal()` rather than having `fn:atomic-equal()` refer to `fn:deep-equal()` which itself refers to "eq".

**Comment by ndw** [comment]
Closed by PR #319
