### ISSUE TITLE
Extending element and attribute tests to NameTest unions

### ISSUE THREAD

**Issue by rhdunn** [qt4cg/qtspecs#23]
In the XPath and XQuery drafts the element and attribute tests have been extended to support any NameTest, meaning they now support all wildcard forms, which is great.

It is possible to write a path expression that takes a union of different paths -- such as `html//(ol|ul)` -- however it is not possible to define a precise type that accepts that path expression in variables, parameters, or return types, so if a user does specify a type some type information is lost during the static analysis phase.

As such, I propose renaming `CatchErrorList` to `NameTestUnion` and making `ElementTest` and `AttributeTest` accept a `NameTestUnion`:

    [86] CatchClause ::= "catch" NameTestUnion EnclosedExpr
    [87] NameTestUnion ::= NameTest ("|" NameTest)*
    [212] AttributeTest ::= "attribute" "(" (NameTestUnion ("," TypeName)?)? ")"
    [215] ElementTest ::= "element" "(" (NameTestUnion ("," TypeName "?"?)?)? ")"

Kind regards,
Reece

**Comment by michaelhkay** [comment]
If we're going to do this then there's also an argument for making the whole type system closed under union, e.g. allowing `union(element(), attribute())` or `union(map(), array())` as types. It's hard to know where to draw the line. This feels to me like a bridge too far.

**Comment by rhdunn** [comment]
There are use cases for unions of item types, such as functions that take elements (for compatibility) or maps as options, so could be defined as `union(element(options), record(...))` if that were supported in the type system.

I think this proposal (element/attribute) extension would be more common and useful given the prevalence of things like `ol`/`ul` for specifying lists in HTML compared with.

**Comment by rhdunn** [comment]
One of the major use-cases I have for this is where the thing being unioned over is element or attribute names. -- I would be happy for this to be limited to that scope instead of a full type union. For example:
1. Dublin Core metadata elements in either the `/elements/1.1` namespace or the `/terms` namespace;
2. HTML elements in -- no namespace, HTML 4 namespace (Word HTML), or the XHTML namespace;
3. Syntactically related elements, such as list type elements (`ol`, `ul` in HTML).
