### ISSUE TITLE
[XPath] `%variadic("sequence")` does not allow specifying some argument values in the variadic sequence, and in one case even not the variadic sequence itself

### ISSUE THREAD

**Issue by dnovatchev** [qt4cg/qtspecs#25]
**The current specification for sequence variadic functions (at: https://qt4cg.org/branch/master/xquery-40/xpath-40-diff.html#id-static-functions) has the following issues**:

1. An empty sequence cannot be specified into the sequence of variadic arguments
2. Even the last (sequence) argument that is supposed to contain the variadic arguments "disappears" when no variadic argument is specified on the function call

This results in difficulties to describe, explain and implement such sequence-variadic functions, and in inability to provide any argument value (like the empty sequence) within the last, sequence argument.

**Proposed improvement**, which doesn't have the above problems:

Use **_array-variadic_** functions instead of sequence-variadic:

`%variadic("array")` indicates that the function is _array-variadic_. An _array-variadic_ function declares one or more parameters, of which the last must be an array. If the declaration includes N parameters, then a call on the function may supply N-1 or more arguments. However, the effective call always consists of N arguments, the first N-1 of which are the values for the positional parameters of the function, and the Nth argument is an array that contains all provided variadic arguments.

Why an _array-variadic_ function doesn't have the problems 1 and 2 above?

1. An empty sequence can be specified in the last argument, for example: [1, (), 2]. For example: 
`myFun($posArg1, $posArg2, ..., $posArgN_minus_1, [1, (), 2])`
2. When no variadic arguments are supplied, the last argument of the effective function call is still supplied -- it is the empty array. For example:  `myFun($posArg1, $posArg2, ..., $posArgN_minus_1, [])`

**Comment by michaelhkay** [comment]
The previous draft syntax for sequence-variadic functions has been dropped, so this comment is no longer relevant. We are working on a new proposal.
