### ISSUE TITLE
Improving the styling/presentation/prepresentation of the record types in the F&O spec

### ISSUE THREAD

**Issue by rhdunn** [qt4cg/qtspecs#257]
I'm not keen on the † symbol being used to indicate and link record types. This is not used elsewhere, and when a record type is used as a type, there is a link to the record type definition. I think that that link is sufficient.

The presentation of the record type definition has the following format:

    †type-name:
    record(
        ...
    )

The record part is fine, but I find the `†type-name:` part clunky. For functions, omiting the `declare function` part from the XQuery syntax makes sense as the function signature is readable without that.

The XQuery 4.0 draft spec has the following (as of yet unapproved) syntax for defining type aliases: https://qt4cg.org/specifications/xquery-40/xquery-40.html#id-item-type-declaration. I would suggest using something similar, e.g.:

    type-name as record(
        ...
    )

That is in line with the way function declarations are specified and looks more readable to me.

Finally, ommitting the id from the `record` element results in `†:` before the record. -- It would be nice if instead of:

            <div3 id="html-parser-options">
               <head>HTML parser options</head>
               <example role="record">
                  <record id="parse-html-options">
                     <arg name="method" type="union(enum(&quot;html5&quot;), xs:string)"/>
                     <arg name="*"/>
                  </record>
               </example>

you could write something like:

            <div3 id="parse-html-options">
               <head>HTML parser options</head>
               <example role="record">
                  <record type-name="parse-html-options">
                     <arg name="method" type="union(enum(&quot;html5&quot;), xs:string)"/>
                     <arg name="*"/>
                  </record>
               </example>

**Comment by ndw** [comment]
Yes, I think you're right. The presentation style doesn't work as well (if it ever did work well) now that the record is in its own section. I'll try something along the lines you suggest.
