### ISSUE TITLE
[XPath]A value in the last row (for "sequence-variadic" functions) of the table "Number of Arguments allowed in a Function Call" is incorrect

### ISSUE THREAD

**Issue by dnovatchev** [qt4cg/qtspecs#26]
In another issue ( #25 ) it was already discussed that the proposed "sequence-variadic" functions have definite problems.

**This issue is about the incorrect value in the MaxK column of the "sequence-variadic" (last) row of the table titled "Number of Arguments allowed in a Function Call", which is in the section "[4.4.1 Static Functions](https://qt4cg.org/branch/master/xquery-40/xpath-40-diff.html#id-static-functions)**".

As published, the value of the 7th (last, for the MaxK column) item in this row is 0.

In fact all of the required positional arguments can be entered as keyword arguments in a function call (there is no reason why this cannot/shouldn't be done).

Thus, the value for MaxK (the maximum number of keyword arguments) must be R, (the current value of 0 is wrong).

**Proposed corrective action**:

1. Replace "sequence-variadic" with "array-variadic", which avoids the problems of "sequence-variadic" (as discussed in #25 )
2. In the row for "array-variadic" of the table, specify R as the value for the column MaxK

**Comment by michaelhkay** [comment]
This table has been dropped from the spec, so the comment is no longer relevant. We are working on a revised proposal to add (so-called) sequence-variadic functions.
