### ISSUE TITLE
array:index-of

### ISSUE THREAD

**Issue by dnovatchev** [qt4cg/qtspecs#260]
Seems we are missing the corresponding array function to the standard (on sequences) **_fn:index-of(_**).

### Summary

Returns a sequence of positive integers giving the positions within the array `$input` of items that are equal to the `$search-member`.

### Signature

```xq
array:index-of(
               $input  as array(*),	
               $searched-member as item()*,
               $compare($x as item()*, $y as item()*) as xs:boolean := fn:deep-equal#2
                 ) as xs:integer*
```

### Properties

This function is deterministic, context-independent, and focus-independent

### Rules

The result of the function is a sequence of integers, in monotonic ascending order, representing the `1`-based positions in the input array of those members `$mem` for whom `$compare($mem, $searched-member)` is `true()` .

More formally, the function returns the result of the XPath expression:

```xq
  (1 to array:size($input)) ! (-> {  .[$compare($input(.), $searched-member)] }) (.)
```

### Examples

![image](https://user-images.githubusercontent.com/10605892/202876246-0256f0e7-c736-48b5-b862-7ebbe142d9ce.png)

And also this:

![image](https://user-images.githubusercontent.com/10605892/202876368-9dd18c8c-888f-41e2-991d-b0779bc6dcd9.png)

**Comment by martin-honnen** [comment]
Is the part `$compare($x as item()*, $y as item()*) as xs:boolean := fn:deep-equal#2` is the signature correct? Shouldn't that be `$compare as function(item()*, item()*) as xs:boolean := fn:deep-equal#2`? 

It would be good to add your examples also as text to the issue, the BaseX screenshots are certainly conveying the examples but screenshots are hard to be used for test cases/experiments.

Couldn't the implementation/function body be simplified to 
```
(1 to array:size($input))[$compare($input(.), $searched-member)]
```
?

I also wonder `array:index-of` should be using `fn:index-where` e.g. 
```
declare function array:index-of(
               $input  as array(*),	
               $searched-member as item()*,
               $compare as function(item()*, item()*) as xs:boolean := fn:deep-equal#2
                 ) as xs:integer*
{
  fn:index-where(1 to array:size($input), -> { $compare($input(.), $searched-member) })
};
```

**Comment by michaelhkay** [comment]
The fn:index-of() function for sequences doesn't allow a user-specified comparison operator, it always uses `eq`, customised perhaps by a collation. I don't think there's an equivalent universal equality operation for sequences, so it would need to be a user-supplied comparison, as you have proposed. But once you allow a user-specified comparison, I don't think there is any meaningful distinction from the index-where() function. In short, if you have array:index-where(), I don't think you need array:index-of() as well.

**Comment by dnovatchev** [comment]
> The fn:index-of() function for sequences doesn't allow a user-specified comparison operator, it always uses `eq`, customised perhaps by a collation. I don't think there's an equivalent universal equality operation for sequences, so it would need to be a user-supplied comparison, as you have proposed. But once you allow a user-specified comparison, I don't think there is any meaningful distinction from the index-where() function. In short, if you have array:index-where(), I don't think you need array:index-of() as well.

It is true that `array:index-of()` can be expressed using `array:index-where()` .

There are two arguments for having **_`array:index-of()`_** as a separate function:

1. It corresponds directly to the **_`fn:index-of()`_** for sequences, with which the XPath programmer has been accustomed for many years. Thus having a function for arrays with the same name and semantics assures immediate and smooth adoption and no need for any new learning.

2. As shown with XPath oracle functions, it is natural to define the semantics of **_`array:index-where`_** using the  **_`array:index-of()`_**   function, and it is a good principle to define more complex things from simpler things.

**Comment by michaelhkay** [comment]
While I think it's nice to have symmetry between functions on sequences and functions on arrays wherever possible, `fn:index-of()` relies on an equality operator for items that is "eq using a supplied or default collation". That operator doesn't extend naturally to comparison of sequences; we would need to use a different equality operator.

(a) it's not obvious what equality operator should be used by default
(b) if we allowed a user-specified equality test then we would be replicating array:index-where()
(c) whatever we chose as a default, it would be different from the fn:index-of() semantics, which would mean that the apparent similarity of `fn:index-of` and `array:index-of` is misleading and spurious.

So I would vote against providing this function.

**Comment by ChristianGruen** [comment]
Since this has been proposed by Dimitre, I already had two use cases in which the function would have been useful.

Personally, I would propose a simple version without function argument, though, and which uses `fn:deep-equal` as a comparator, as I believe that only advanced users require sophisticated comparison rules:

```xquery
array:index-of(
  [1, (2, 3), 4, () ],
  (2, 3)
) → 2
```

For more complex comparisons, `array:index-where` could be used and motivated.

**Comment by ChristianGruen** [comment]
@dnovatchev Would you be interested in creating a pull request for your proposal?
I’ll be glad to help if you have any questions.

**Comment by ChristianGruen** [comment]
Copied from https://github.com/qt4cg/qtspecs/issues/843#issuecomment-1907129625

> Perhaps then `array:index-of()` should have signature `array:index-of(array(xs:anyAtomicType), xs:anyAtomicType)` and array:index-of($A, $V) should return `fn:index-of($A?*, $V)`.

As the input of `fn:index-of` is not limited to atomic types – see for example `index-of(<a>A</a>, 'A')` – and as a major advantage of arrays is the structuring of data, my suggestion for a better symmetry would be the following signature:

```xquery
array:index-of(
  $array   as array(*),
  $search  as xs:anyAtomicType*
) as xs:integer*`
```

For lookups, we could use:

```xquery
for member $member at $pos in $array
where count($search) = count($member)
where every $p in 1 to count($sequence) satisfies index-of($member[$p], $search[$p])
return $pos
```

This would reduce inconsistencies to a minimum, and e.g. give us `4` for:

```xquery
array:index-of(
  [ (), 1, ('1', 2), (<x>1</x>, <x>2</x>) ],
  ('1', <x>2</x>)
)
```

I believe it’s not possible to write down a really short equivalent expression for `fn:index-of`; otherwise the equivalent expression for `array:index-of` could be simpler, too. The shortest version I found is:

```xquery
for $item at $pos in $input
return try { if($item eq $search) { $pos } } catch err:XPTY0004 { }
```

**Comment by michaelhkay** [comment]
Yes, that looks viable. It does the intuitive thing in simple cases and is only a little bit weird in edge cases, which is probably the best we can hope for.

It would be useful if all functions that perform comparison included a cross-reference to the new XPath Appendix I; and I note that appendix doesn't seem to mention index-of.

Another expansion (this one pure XPath) might be

```
(1 to array:size($array))
   [count($array(.) eq count($search) 
      and for-each-pair($array(.), $search, fn($x, $y){index-of($x,$y) eq 1})]
```

**Comment by dnovatchev** [comment]
> As the input of `fn:index-of` is not limited to atomic types – see for example `index-of(<a>A</a>, 'A')` – and as a major advantage of arrays is the structuring of data, my suggestion for a better symmetry would be the following signature:
> 
> ```xq
> array:index-of(
>   $array   as array(*),
>   $search  as xs:anyAtomicType*
> ) as xs:integer*`
> ```

I find the argument name "$search" confusing. Search is a process (and a verb).

Better name to use: **$search-for**

**Comment by ChristianGruen** [comment]
> Better name to use: **$search-for**

This request could be addressed in a separate Github issue. If we change it, we would need to change the signatures of other existing functions.

**Comment by dnovatchev** [comment]
> > Better name to use: **$search-for**
> 
> This request could be addressed in a separate Github issue. If we change it, we would need to change the signatures of other existing functions.

Yes, correct this name and open a new issue for other functions.
