### ISSUE TITLE
Navigation in deep-structured arrays

### ISSUE THREAD

**Issue by dnovatchev** [qt4cg/qtspecs#262]
At present there is no convenient way to navigate down a deep-structured array (whose members are themselves arrays and maybe even (recursively) deep-structured arrays themselves).

For example, given the array:

```xq
 [1, [2, 3], [4, [5, 6]], (7, 8, 9) ]
```

we cannot navigate to `6` with a single function call, nor do we have a convenient search mechanism that will give us all index(es)-paths that navigate to `6`, in this case just the single index-path (3, 2, 2).

**This proposal is to extend the **_[`array:get()`](https://qt4cg.org/pr/258/xpath-functions-40/autodiff.html#func-array-get)_** function and the [**_array lookup using function call syntax_**](https://qt4cg.org/specifications/xquery-40/xpath-40-diff.html#id-array-lookup) to accept as their last argument not just a single integer position, but a sequence of integers.**

The sequence of integer position is called **"item-navigation-path"**, or simply: **"navigation-path"**.

For the array defined above, the navigation path to the contained item `6` is:

**`(3, 2, 2)`**

**XPath implementation**:

```xq
let $ar := [1, [2, 3], [4, [5, 6]], (7, 8, 9) ],
    $get := -> ($input as array(*), $indices as xs:integer*)
            {
              let $getHelper := -> ($input as array(*), $indices as xs:integer*, $self as function(*))
              {
                let $headIndex := head($indices), $restindices := tail($indices)
                  return
                    if(exists($restindices))
                      then $self($input($headIndex),$restindices, $self)
                      else if(exists($headIndex))
                             then $input($headIndex)
                             else $input
               }
              return $getHelper($input, $indices, $getHelper)
            }
  return
    $ar => $get((3, 2, 2))
     (: (: Or alternatively : :) $get($ar, (3, 2, 2)) :)
```
When the above expression is evaluated, the expected, correct result is produced:

`6`

**Goals**

1. To allow a simple and intuitive deep-indexing navigation with a single function call.

2. To allow for sophisticated deep-searching functionality (like the current `array:index-where()` and `array:index-of()`, but not just scratching the surface) to return the navigation paths to wanted items of interest, which then could be stored, passed to other functions and easily retrieved.

**Other examples**:

```xq
let $ar := [1, [2, 3], [4, [5, 6]], (7, 8, 9) ],
    $get := -> ($input as array(*), $indices as xs:integer*)
            {
              let $getHelper := -> ($input as array(*), $indices as xs:integer*, $self as function(*))
              {
                let $headIndex := head($indices), $restindices := tail($indices)
                  return
                    if(exists($restindices))
                      then $self($input($headIndex),$restindices, $self)
                      else if(exists($headIndex))
                             then $input($headIndex)
                             else $input
               }
              return $getHelper($input, $indices, $getHelper)
            }
  return
     ( $get($ar, (3, 2, 2)), $get($ar, 2), $get($ar, (3,1)),   $get($ar, (3,2)), $get($ar, ())  )
```

When the above expression is evaluated, all the expected, correct results are produced:

```xq
6
[2,3]
4
[5,6]
[1,[2,3],[4,[5,6]],(7,8,9)]
```

![image](https://user-images.githubusercontent.com/10605892/202931815-9fd429f4-55e1-4a79-bd0a-fc6c98990393.png)

**Comment by liamquin** [comment]
Sequences of integers used for tree navigation are sometimes called tumblers.

What would it look like if you had a map at an intermediate level, with array children?

**Comment by dnovatchev** [comment]
> Sequences of integers used for tree navigation are sometimes called tumblers.
> 
> What would it look like if you had a map at an intermediate level, with array children?

This proposal addresses deep-array navigation. If an item that is navigated to is not an array, it must be the path's destination.

Of course, if we know that this destination is a map, then we could continue the navigation from this point on using map-specific navigation expression (which we already have in the language).

For example, if we have this:

```xq
let $ar := [1, [2, 3], [4, [5, 6]], (7, 8, 9), [1, map{"x": "y", "z": "t"}] ]
```

then in order to navigate to "y", we evaluate this expression:

```xq
 $byIndex($ar, (5, 2))?x
```

![image](https://user-images.githubusercontent.com/10605892/202946088-1290579f-2c8a-4b6a-bd2b-32497800d19e.png)

**Comment by michaelhkay** [comment]
There are certainly gaps in our ability to do deep processing of maps and arrays (for example searching), but I think that simple multi-level indexing is already well handled using the lookup operator. I'd like to see this one tackled as part of a more comprehensive look at use cases for navigating, searching, and updating nested map/array structures.

Michael Kay

On 20 Nov 2022, at 23:10, dnovatchev ***@***.******@***.***>> wrote:



At present there is no convenient way to navigate down a deep-structured array (whose members are themselves arrays and maybe even (recursively) deep-structured arrays themselves).

For example, given the array:

 [1, [2, 3], [4, [5, 6]], (7, 8, 9) ]

we cannot navigate to 6 with a single function call, nor do we have a convenient search mechanism that will give us all index(es)-paths that navigate to 6, in this case just the single index-path (3, 2, 2).

This proposal is to extend the array:get()<https://qt4cg.org/pr/258/xpath-functions-40/autodiff.html#func-array-get> function and just the array lookup using function call syntax<https://qt4cg.org/specifications/xquery-40/xpath-40-diff.html#id-array-lookup> to accept as their last argument not just a single integer position, but a sequence of integers.

The sequence of integer position is called "item-navigation-path", or simply: "navigation-path".

For the array defined above, the navigation path to the contained item 6 is:

(3, 2, 2)

XPath implementation:

let $ar := [1, [2, 3], [4, [5, 6]], (7, 8, 9) ],
    $get := -> ($input as array(*), $indices as xs:integer*)
            {
              let $getHelper := -> ($input as array(*), $indices as xs:integer*, $self as function(*))
              {
                let $headIndex := head($indices), $restindices := tail($indices)
                  return
                    if(exists($restindices))
                      then $self($input($headIndex),$restindices, $self)
                      else if(exists($headIndex))
                             then $input($headIndex)
                             else $input
               }
              return $getHelper($input, $indices, $getHelper)
            }
  return
    $ar => $get((3, 2, 2))
     (: (: Or alternatively : :) $get($ar, (3, 2, 2)) :)

When the above expression is evaluated, the expected, correct result is produced:

6

Goals

  1.  To allow a simple and intuitive deep-indexing navigation with a single function call.

  2.  To allow for sophisticated deep-searching functionality (like the current array:index-where() and array:index-of(), but not just scratching the surface) to return the navigation paths to wanted items of interest, which then could be stored, passed to other functions and easily retrieved.

Other examples:

let $ar := [1, [2, 3], [4, [5, 6]], (7, 8, 9) ],
    $get := -> ($input as array(*), $indices as xs:integer*)
            {
              let $getHelper := -> ($input as array(*), $indices as xs:integer*, $self as function(*))
              {
                let $headIndex := head($indices), $restindices := tail($indices)
                  return
                    if(exists($restindices))
                      then $self($input($headIndex),$restindices, $self)
                      else if(exists($headIndex))
                             then $input($headIndex)
                             else $input
               }
              return $getHelper($input, $indices, $getHelper)
            }
  return
     ( $get($ar, (3, 2, 2)), $get($ar, 2), $get($ar, (3,1)),   $get($ar, (3,2)), $get($ar, ())  )

When the above expression is evaluated, all the expected, correct results are produced:

6
[2,3]
4
[5,6]
[1,[2,3],[4,[5,6]],(7,8,9)]

**Comment by ChristianGruen** [comment]
@dnovatchev What about this?

```xquery
let $ar := [1, [2, 3], [4, [5, 6]], (7, 8, 9) ]
return (
  $ar?3?2?2,
  $ar?2,
  $ar?3?1,
  $ar?3?2,
  $ar
```

**Comment by michaelhkay** [comment]
Also in this same general area: issues #29, #77, #115, #218. I don't think these issues should be considered in isolation from each other: they all point to different parts of the same problem.

**Comment by dnovatchev** [comment]
> @dnovatchev What about this?
> 
> ```xq
> let $ar := [1, [2, 3], [4, [5, 6]], (7, 8, 9)]
> return (
>   $ar?3?2?2,
>   $ar?2,
>   $ar?3?1,
>   $ar?3?2,
>   $ar
> )
> ```

@ChristianGruen ,

This is exactly what we need to avoid, as it requires (re-) compilation.

If you pass `?3?2?2,` to a function as a single argument, then the function needs to do some additional processing before it would be able to get the indexes out of the string. And not to mention that search functions will also need to do additional (unnecessary) formatting to present their results in this format.

The goal of this proposal is for us to be able to pass the navigation as a single argument that can immediately be acted upon (navigated) by our function(s).

Do we have a simpler alternative than the sequence of consecutive indexes?

Even for a human being something like  `?3?2?2,`  is quite unreadable...

**Comment by ChristianGruen** [comment]
> This is exactly what we need to avoid, as it requires (re-) compilation.
> 
> If you pass `?3?2?2,` to a function as a single argument, then the function needs to do some additional processing before it would be able to get the indexes out of the string. 

I’m not sure what you mean by that: The syntax uses the lookup operator, so there is no need to recompile code, or to supply arguments. Maybe I got you wrong?

> The goal of this proposal is for us to be able to pass the navigation as a single argument that can immediately be acted upon (navigated) by our function(s).

Wouldn’t that be similarly helpful for maps as well, or also paths with simple child steps? We have `a/b/c`, but we don’t have a function for passing on multiple steps as a single argument (that just reminds me of https://stackoverflow.com/questions/74418989/how-to-convert-string-to-xpath-in-basex).

> Even for a human being something like `?3?2?2,` is quite unreadable...

Some users prefer parens (for both maps and arrays): `$ar(3)(2)(2)`.

**Comment by dnovatchev** [comment]
> 



> > This is exactly what we need to avoid, as it requires (re-) compilation.
> > If you pass `?3?2?2,` to a function as a single argument, then the function needs to do some additional processing before it would be able to get the indexes out of the string.
> 
> I’m not sure what you mean by that: The syntax uses the lookup operator, so there is no need to recompile code, or to supply arguments. Maybe I got you wrong?

What is the type of `?3?2?2,` ? It is at best xs:string. 

If we pass this as an argument to a function, it isn't directly usable. The function code will have to tokenize the string  and get the indexes before being able to do anything with them.

The function will not be able to dynamically evaluate the string `?3?2?2,` unless it invokes `fn:transform()` and passes to it a constructed XSLT transformation that does `<xsl:evaluate>` on that particular string.

> 
> > The goal of this proposal is for us to be able to pass the navigation as a single argument that can immediately be acted upon (navigated) by our function(s).
> 
> Wouldn’t that be similarly helpful for maps as well, or also paths with simple child steps? We have `a/b/c`, but we don’t have a function for passing on multiple steps as a single argument (that just reminds me of https://stackoverflow.com/questions/74418989/how-to-convert-string-to-xpath-in-basex).
> 

Yes, this is what both @michaelhkay and I are talking about -- and this would really be useful.

> > Even for a human being something like `?3?2?2,` is quite unreadable...
> 
> Some users prefer parens (for both maps and arrays): `$ar(3)(2)(2)`.

Here we are not talking about "users". Or, we can say that our "users" are functions.

We still don't have a function that will take the string  `$ar(3)(2)(2)`, analyze it and as result perform 3 function calls in a row.
And even if we did have such a function, it would need to perform 3 function calls, but we want to do just one function call and pass the navigation path to it in a convenient, natural format that doesn't need further analyzing or even compilation (re-evaluation).

**Comment by michaelhkay** [comment]
My thinking here isn't complete, but to deep update in particular, I think we need some kind of concept like a path or "trail" representing a selection within a tree of maps and arrays. At one level this "trail" is a function that selects a point within the tree from the root of the tree, but it offers more capability than simply the ability to evaluate the function and find out what's at that point; it also offers the capability to create a new tree by doing something like

modify-jtree($origin, $trail, $modification)

where origin is the root of the "j-tree" (a tree of maps and arrays), $trail is a downwards path through the tree, and $modification is a function that returns a new value for the destination object; the function modify-jtree returns a new j-tree that's a replacement for the original one at $origin.

A trail can be described as a sequence of steps where the steps are for example indexing into an array, selecting a key in a map, etc. But it might be more complex than that. We need to allow for sequences, which complicates things, and the steps might be value-based rather than key-based.

I explored these ideas with saxon:pedigree (https://www.saxonica.com/documentation11/index.html#!functions/saxon/pedigree) and saxon:with-pedigree (https://www.saxonica.com/documentation11/index.html#!functions/saxon/with-pedigree) and with the saxon:deep-update instruction in XSLT: https://www.saxonica.com/documentation11/index.html#!extensions/instructions/deep-update - but none of these is a final or complete solution.

The zipper concept in functional programming is relevant: https://en.wikipedia.org/wiki/Zipper_(data_structure), of which I can only claim a rather superficial understanding.

**Comment by michaelhkay** [comment]
Let's try to expand this idea. I'll use the term "selector" in place of "trail".

A selector is a function that selects items within a hierarchic structure. It's not any function; it's constrained to be a function with the annotation selector=yes, which is reserved for system use. 

We define a number of built-in functions that have this annotation, including functions such as map:get, array:get, fn:items-at, fn:subsequence, array:subarray, head, tail, foot, trunk, etc, as well as functions on node trees corresponding to the child and attribute axes.

Two or more selector functions can be composed to create another selector function, so for example a sequence of array:get() operations is itself a selector.

The combination of a selector and a predicate is also a selector. This gives us search capability.

We also need to be able to form recursive selectors (like the descendant axis, and map:find) to navigate within recursive trees.

Evaluating a selector just evaluates the function with respect to some root item and returns the selected items; that in itself isn't very interesting.

A more interesting operation ("deep update") is one that takes a root item, a selector function, and an update action. The effect of deep update is to return a modified copy of the tree rooted at the root item, in which all items selected by the selector function have been modified by applying the update action. Note that the selector function here can't be any function, it has to be one that the deep update operation understands.

The update action here might be deleting an item, replacing an item with another, or inserting an item. These operations require a knowledge not just of the item being processed, but of the route by which it was reached from the supplied root. Internally, applying the selector leaves a trail, and all items on this trail get updated (by copy).

I don't think this requires any data model changes (we already have the concept of function annotations in the data model). It will require some new functions, for example functions to compose selector functions, and functions corresponding to the XPath downwards axes. In principle I think it can be done without any new syntax, though when we explore the detail we may find that it becomes more usable with custom syntax, similar perhaps to the "copy modify" expression in XQuery update.

**Comment by michaelhkay** [comment]
Here's a practical use case. I was analysing the XML representation of the Saxon source code to find methods that had deeply nested statements. Here's the query I used:

```
let $depth :=  function($member) {
     max($member//statement/count(ancestor::statement))}
for $m in collection('.?select=*.xml;recurse=yes')//member 
group by $d := $depth($m) 
where $d ge 4 
return ($d, $m!(../../name/@identifier || '.' ||name/@identifier))
```

Now, let's suppose that instead of an XML representation of the code, we were working with a JSON representation. How would we handle the absence of the ancestor axis?

We would have to write a recursive function that walks down the tree, returning all the "statement" objects found at any level, together with the depth at which they were found. That's not impossible, but it's a lot harder than a simple search for descendant elements with a count of their ancestors.

Also note that there's a second upward navigation in the return clause: having found the "member" objects we are interested in (Java methods, actually), we need to identify them in the output, and this involves upwards navigation to find the name of the containing class.

Looking at the second requirement first, we want some map-and-array equivalent of 

`for $m in collection('.?select=*.xml;recurse=yes')//member `

where the variable $m contains not only the member objects that were selected, but the "trail" of how each one was reached, available in such a way that we can take two steps back to get the value of `?name?identifier`.

Similarly we want a map-and-array equivalent of `$member//statement`, that returns not only the selected `statement` but the trail that led to it, with the ability to compute the equivalent of count(ancestor::statement) by examining the trail.

One way of achieving this might be for the equivalent of "//" to return a copy of the selected map (the "member" or "statement" object) augmented with a parent pointer: another entry in the map whose value is the parent map, or rather, a copy of the parent map that is itself similarly augmented. This is tricky because of course we now have cycles in the map structure, or depending on how you look at it, a map whose serialisation is non-terminating.

Perhaps better is for a map:search function to return a composite result containing both the found items and their trail; with a destructuring assignment we could write something like

```
for {$m, $trail} in collection('.?select=*.xml;recurse=yes') => map:search(...)
return .... array:member-at($trail, -2)?name?identifier
```

and the recursive search would be something like

```
$depth := function($member) {
   max(
      for {$statement, $trail} in map:search(...)
      return array:size(array:filter($trail, ->{?type = 'statement'}))
  )}
```

**Comment by michaelhkay** [comment]
Let's have a go at specifying a `map:search()` function. (It doesn't work exactly as in the previous comment, I'm still exploring ideas).

We'll start with some terminology. A gMap (generalised map) is either a map or an array. An array is treated like a map with integer keys. We will talk about the entries in a gMap as key-value pairs, remembering that for arrays this means the integer position of a member and the actual value of the member.

The function `map:search` takes as input a gMap, and a predicate applied to key-value pairs (so the predicate is `function ($key, $value) as s:boolean`). It returns a sequence of trails, each trail representing the route to a key-value pair that matches the predicate. The trail is an array of triples in the form `record(container, key, value)`). The container is a gMap, and the key and value represent an entry within the gMap. The last member in each trail represents a key-value pair that match the search predicate. The first member in the trail has the supplied input gMap as its `container`. The `container` in the Nth member of the trail (for N>1) is always the same as the `value` in the N-1th member.

The map:search function operates as follows. The function `map:search($gMap, $predicate)` invokes an internal function `map:_search($gMap, $predicate, $trail := [])` supplying an empty trail as the third argument.

The internal function `map:_search($gMap, $predicate, $trail)` examines each entry in $gMap in turn.

(a) if the entry matches the predicate, then it adds to the result set a trail consisting of the supplied $trail with an additional member appended, comprising $gMap as the contained, plus the key and value of the matching entry.

(b) in addition (whether or not the entry matches the predicate), if the value part of the entry is a gMap, then it calls `map:_search($gMap, $predicate, $trail)` recursively, supplying a trail constructed as in step (a); the result of this call (a possibly empty sequence of trails) is added to the result of the function.

Now we can consider how this would work with the use case presented earlier. Without being too precise about the actual representation of the syntax tree, we can imagine doing something like:

```
let $depth :=  function($member) {
     max(map:search($member, ->($k, $v)[$k = 'statement']) ! count(array:index-where(., ->{?k = 'statement'}))
}
for $m in collection('.?select=*.xml;recurse=yes') => map:search(->($k, $v)[$k = 'member']
group by $d := $depth($m) 
where $d ge 4 
return ($d, $m!(array:member-at(-2)?container?name?identifier || '.' || array:foot()?container?name?identifier))
```

which feels usable, though no doubt it can be improved.

**Comment by dnovatchev** [comment]
> let $depth :=  function($member) {
>      max(map:search($member, ->($k, $v)[$k = 'statement']) ! count(array:index-where(., ->{?k = 'statement'}))
> }
> for $trail in **collection**('.?select=*.xml;recurse=yes') => map:search(->($k, $v)[$k = 'member']

I am trying to read/understand this.

The very first question is:

What `collection()` has to do with this whole problem? Can't we eliminate `collection()` from any of the  examples?

**Comment by michaelhkay** [comment]
The example uses collection() because that's the real use case I was trying to solve, I made no attempts to simplify it for exposition. It arises from an issue raised on the XML Slack.

**Comment by ChristianGruen** [comment]
The PR related to this issue was merged. Do we want to keep the issue open?

**Comment by ndw** [comment]
The CG decided to close this issue without any further action at [meeting 069](https://qt4cg.org/meeting/minutes/2024/03-12.html).
