### ISSUE TITLE
Type hierarchy tables/diagrams

### ISSUE THREAD

**Issue by ndw** [qt4cg/qtspecs#265]
On 22 November, we mentioned in passing that the type hierarchy tables in the Data Model spec are hard to read. They're a garish yellow for no obvious reason and the font size is very small. Would replacing them with diagrams like this be an improvement?

![out](https://user-images.githubusercontent.com/36793/203549753-a970038e-4b8b-44cb-97cb-8d52d2fc736f.png)

(This is the largest and most difficult to represent, I think. I've grouped some of the atomic types together to make the drawing more aesthetically pleasing. I don't think that interferes with comprehension, though might need to be explained.)

There's no particular rhyme or reason to the order of the items in the "second column" except to leave room for the longer hierarchies further to the right.

**Comment by ndw** [comment]
Alternatively, this presentation does away with the grouping:

![out](https://user-images.githubusercontent.com/36793/203569637-4f24401d-c46d-4625-92b4-708efd497215.png)

**Comment by ChristianGruen** [comment]
Definitely nice (although it might prevent you from finding types as text strings in the document). The first figure is my favorite.

**Comment by joewiz** [comment]
I agree that this is a wonderful improvement over the original image. Between these two, I like the first one too. The grouping has a mnemonic quality and is useful. 

In the grouping of the g-prefixed types, would it be possible to order them: gYear, gMonth, gDay, gYearMonth, gMonthDay?

Also, if grouping is purely based on similarities, could the 2 duration subtypes (xs:dayTimeDuration and xs:yearMonthDuration) be grouped together? Same with xs:ID and xs:IDREF (I forget what xs:ENTITY is and if it would belong in a group with the former two).

Lastly, would it be possible to move the xs:double & xs:float group down below xs:decimal, so these are nearby each other? Along the same lines, would it be possible to keep the date/time/duration entries in the "2nd column" adjacent to each other?

**Comment by ndw** [comment]
Ah, thank you @joewiz. I was using grouping purely to limit the number of lines from `xs:anyAtomicType` and hadn't considered applying it more generally. I think that will look nice and be less ad hoc.

Based on the positive replies, I'll keep tinkering. I think all of the suggestions you made are good. I'll see what I can come up with. (This is a "tinker while the compiler is running" background task, so it might take a few days.) And I'll go ahead and try to do the rest of them.

With respect to @ChristianGruen's comment, I think we should adjust the prose that goes with each diagram so that all of the types appear in text. I'm also a little concerned about the accessibility, so might explore how to mitigate that.

**Comment by Arithmeticus** [comment]
Greatly improved. My first impulse was that the data structure should just be rendered as an XML tree.

**Comment by dnovatchev** [comment]
Great artwork!

I like both but the first seems more concentrated.

It is especially good to see all the primitive atomic types in the 1st column, I would even suggest shading this whole column in light-gray and/or giving it a title.

**Comment by joewiz** [comment]
On a similar topic, has the WG ever considered adding an XPath Axes diagram like G. Ken Holman's - as shown at https://nwalsh.com/docs/tutorials/xsl/xsl/foil22.html? I found that diagram to be an amazing resource, and along with the type hierarchy charts, were tacked up on the wall next to my computer at work for years.

**Comment by ChristianGruen** [comment]
I agree such a diagram could be helpful. Here's a figure we used in our teaching slides:

![Screenshot_20221125-210917](https://user-images.githubusercontent.com/196589/204051235-4ce45bf0-bcf9-49b6-b03d-4f406fa0477b.png)

**Comment by michaelhkay** [comment]
This particular version appears to suggest wrongly that all preceding elements are descendants of preceding-sibling elements, and that all following elements are descendants of following-sibling elements...

Michael Kay

On 25 Nov 2022, at 20:12, Christian Grün ***@***.******@***.***>> wrote:



I agree such a diagram could be helpful. Here's a figure we used in our teaching slides:

[Screenshot_20221125-210917]<https://user-images.githubusercontent.com/196589/204051235-4ce45bf0-bcf9-49b6-b03d-4f406fa0477b.png>

**Comment by ChristianGruen** [comment]
> This particular version appears to suggest wrongly that all preceding elements are descendants of preceding-sibling elements, and that all following elements are descendants of following-sibling elements...

G. Ken Holman's version is definitely more helpful.

**Comment by michaelhkay** [comment]
A reminder that the type hierarchy diagrams also appear in F&O. Whether that's useful is open to debate; but if we improve one version, we should improve both.

**Comment by ndw** [comment]
I've updated PR #268 to put the SVG versions in the F&O spec as well.
