### ISSUE TITLE
Enumeration types

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#283]
The draft specification includes a proposal to provide enumeration types. The proposal is incomplete, for example it does not include all the rules for conversions and casting. This issue is raised in order to outline where we are, what needs to be done, and to elicit consensus on whether we want to proceed with this.

What's the motivation? Primarily, making function signatures more expressive.

_Q0: do we really need this?_

The essence of the proposal is an ItemType that matches an enumerated set of xs:string values:

`[131] | EnumerationType | ::= | "enum" "("  StringLiteral (","  StringLiteral)* ")" 
`
For example, the type enum("red", "green", "blue") matches the string "green".

_Q1: why restrict it to strings? I think my main reason was that the syntax gets complicated if we try to do it for data types that have no literal representation._

Subtyping is based on the value space. An enumeration type E is a subtype of another enumeration type F if the set of strings in E is a subset of those in F. All enumeration types are subtypes of xs:string.

Strings are not "labelled" as belonging to an enumeration type, matching is purely based on the value ("datum"). This doesn't provide very strong typing. If "violet" and "pink" are allowed by both the enumeration types `colour` and `flower`, then it's not intrinsically an error to use a variable of type `flower` where a `colour` is expected. Equally, a variable of type `xs:string` can be used where a `colour` is expected.

_Q2: should enumerations be more strongly typed?_ 

I would expect that an enumeration type can be used as the target of "cast" or "castable", but this is not currently in the spec.

The coercion rules as currently written say that if the expected type is an enumeration type, then the rules are largely the same as for any other subtype of `xs:string`:  casting from `xs:untypedAtomic` applies, promotion from `xs:anyURI` does not apply, 1.0 compatibility mode rules do not apply.

Operators and functions on enumeration types are the same as for `xs:string`. This means, for example, that there are no special rules for comparison: values are ordered as strings and are compared using the default collation.

**Comment by michaelhkay** [comment]
From #337:

I wonder if the definition of local enum types should be aligned more closely with an XSD type derived from xs:string by restricting with an enum facet. Now that we allow down-casting in the coercion rules, the objections to this seem to disappear.

cast and castable should also probably pay more attention to these types.

**Comment by michaelhkay** [comment]
Because local enum types are not named, I think we should probably avoid every using a local enum type as a type annotation; rather (as with union types), matching against a local enum type should be essentially a predicate test. Specifically, an item should match an enum type if (a) it is an instance of xs:string, and (b) it is codepoint-equal to one of the enumerated values.

This means that (a) `cast to enum('x', 'y', 'z')` has the effect of casting to xs:string and testing whether the value conforms, (b) the definition of `castable` follows.

An enum type is a subtype of xs:string, and one enum type is a subtype of another if the value space is a subset.

But is an enum type an atomic type? And can it be used as a member type in a union? Needs further thought on the implications. For example, if it's an atomic type then it's a schema type and that makes it eligible to be used in an ElementTest as `element(e, enum('x', 'y', 'z'))` which feels wrong because that's invading XSD territory.

An alternative line would be to say that `enum('x', 'y', 'z')` is equivalent to an anonymous type defined in XSD by restricting xs:string with an enum facet. Being anonymous, it can't be used in contexts such as `element(e, T)`. But this would lead to different subsumption rules, because two anonymous types derived directly from xs:string have no subtype relationship with each other regardless of the set of enumerated values.

**Comment by Arithmeticus** [comment]
For readers' reference, I believe the current draft specification mentioned in the opening comment is here (correct me if I'm wrong): https://qt4cg.org/specifications/xquery-40/xpath-40-diff.html#id-enumeration-types 

It is difficult for me to see the big picture here. It would be nice to see an example or two of how enum types hook into the existing XPath apparatus, e.g., a function where an enum makes its signature more expressive.

For conversion to/from integers and string values, are `index-of()` and `[position() = X]` sufficient, or are other functions envisioned to support conversion and operations? For example, `fn:is-subset-of($item1 as enum(xs:string), $item2 as enum(xs:string)) as xs:boolean` and, signature _mutatis mutandis_, `fn:is-superset-of()`.

In C# one can specify which integer position an enum should be assigned, and zero and negative integers are supported. So also here? I assume not, hurts neither to ask nor to be explicit.

The draft specs do not address cases where a sequence of strings with duplicates are treated as an enum type.

It feels to me as if, under the hood, the enum is not an atomic type but a species of `map(xs:positiveInteger,xs:string)`.

**Comment by ChristianGruen** [comment]
I propose to close this issue. As stated in #1077, …

> Local union types and enumeration types became an official part of the spec with the acceptance of PR https://github.com/qt4cg/qtspecs/pull/691

**Comment by ndw** [comment]
The CG agreed to close this issue without further action at [meeting 070](https://qt4cg.org/meeting/minutes/2024/03-19.html#close-without-action).
