### ISSUE TITLE
DTD validity of F&O spec

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#291]
Despite PR #228, I'm still seeing a lot of validation errors when (using Oxygen) I apply DTD validation to build/expanded/xpath-functions-40/xpath-functions-40.xml

Many of these relate to style attributes not being allowed on table, td, and code elements.

The merge-function-specs.xsl explicitly creates elements with these attributes:

See 

* `<xsl:template match="fos:options">` line 382
* `<xsl:template match="fos:option">` line 408
* `<xsl:template match="processing-instruction('local-function-index')">` line 347

It all works because xmlspec-2016.xsl handles these attributes even though the DTD doesn't allow them: see `<xsl:template name="style-attributes">` at line 2096.

There seem to be three possible options:

* Extend the DTD to allow these attributes
* Change merge-function-specs.xsl to not generate these attributes, instead perhaps generating a role attribute which gets picked up in the final styling
* Sweep the issue under the carpet; avoid validating the intermediate file.

The main problem with the third approach is that it allows other errors to go unnoticed, for example putting text directly within an `<item>` without a containing `<p>`.

**Comment by michaelhkay** [comment]
I've changed merge-function-specs.xsl so it no longer generates styling attributes for the options and local-summary tables, insteead the rendering logic is now in xpath-functions.xsl.

This gives a considerable reduction in the number of validation errors in the expanded `xpath-functions-40.xml` (to 118) which I will now examine.

**Comment by michaelhkay** [comment]
Next step is to ensure that function-catalog.xml is valid against its schema. This involves

* One case of moving fos:errors before fos:notes
* Several cases of removing the <eg> element within `<fos:result>` (may need to reinstate something during styling...)
* A couple of problems with `@return-type` and `@return-type-ref`

**Comment by michaelhkay** [comment]
I'm inclined (a) to change `type-ref="XXX"` to `type="#XXX"` to reduce the amount of schema change, and (b) to move the actual record structure from xpath-functions.xml into function-catalog.xml, with a processing instruction to pull it in at the appropriate place.

**Comment by michaelhkay** [comment]
Remaining problems:
* `<sup><var>x</var></sup>` - I think we should change the DTD to allow this.
* `<table class="data">` - should probably be `<table role="data">`
* `<pre class="small">`
* `<pre>` as a paragraph-level element (should be `<eg>`?)

**Comment by ndw** [comment]
The `sup` and `table` questions look like input issues. The `pre` is an output issue, isn't it?

In any event, I recommend that you make a separate PR for the DTD and style changes that doesn't change any document. PRs are always formatted with the current "main" schemas and stylesheets, so you won't be able to have DTD changes and a document that relies on them in the same PR.

**Comment by michaelhkay** [comment]
I've now got to the point where the function catalog is schema-valid and the expanded xpath-functions-40.xml is DTD-valid (and the HTML rendering looks roughly OK)

**Comment by michaelhkay** [comment]
@ndw, the problem is certainly much deeper than a few `ul`/`ulist` substitutions. I've been primarily working on making xpath-function-40 in the build directory DTD-valid. The validation failures there were partly due to stuff that merge-functions-specis was generating, partly stuff that it was copying from the input files (e.g `<table class="data"/>`, or `<td style="..."/>`. Note, in the course of this I've done some reworking of your changes to add named record types, the named record types are now in the function catalog.

**Comment by ndw** [comment]
Did you rebase your 278 branch off the most recent master? I just went to double check my diffs and I realized that I did rebase off master after I pulled your branch. If your starting point predates the DTD and style changes I made in November, that could be ... confusing.

**Comment by ndw** [comment]
Here's what I did:

```
$ git checkout mhk/Issue278-array-bound-checking
Note: switching to 'mhk/Issue278-array-bound-checking'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 19ac940 Proposal to add fallback behaviour to map:get and array:get
```

This is commit `19ac940` which was current when I pulled your Issue278 branch over the weekend.

```
$ git switch -c test-branch
Switched to a new branch 'test-branch'

$ git rebase master
Successfully rebased and updated refs/heads/test-branch.

$ copy /tmp/function-catalog.xml specifications/xpath-functions-40/src/
```

That's the `ul` to `ulist` change:

```
$ git diff
diff --git a/specifications/xpath-functions-40/src/function-catalog.xml b/specifications/xpath-functions-40/src/function-catalog.xml
index 41c3408..5439921 100644
--- a/specifications/xpath-functions-40/src/function-catalog.xml
+++ b/specifications/xpath-functions-40/src/function-catalog.xml
@@ -18139,15 +18139,15 @@ return fn:fold-left($MAPS, map{},

          <p diff="add" at="2022-12-16">The <code>$fallback</code> function can be used in a number of ways:</p>

-         <ul diff="add" at="2022-12-16">
-            <li>It might return a conventional value such as <code>NaN</code> to indicate that no matching
-            key was found.</li>
-            <li>It might raise a dynamic error, by means of a call on <code>fn:error</code>.</li>
-            <li>It might compute a result algorithmically. For example, if the map holds a table of
+         <ulist diff="add" at="2022-12-16">
+            <item><p>It might return a conventional value such as <code>NaN</code> to indicate that no matching
+            key was found.</p></item>
+            <item><p>It might raise a dynamic error, by means of a call on <code>fn:error</code>.</p></item>
+            <item><p>It might compute a result algorithmically. For example, if the map holds a table of
             abbreviations, such as <code>map{'CA':'Canada', 'UK':'United Kingdom', 'US':'United States'}</code>,
             then specifying <code>fallback := fn:identity#1</code> has the effect that the key value is returned
-            unchanged if it is not found in the map.</li>
-         </ul>
+            unchanged if it is not found in the map.</p></item>
+         </ulist>

          <p>Invoking the <termref def="dt-map"
                >map</termref> as a function item has the same effect
```

Now building:

```
$ gradle clean publish
Running ./gradlew… (instead of /usr/local/bin/gradle)
> Task :clean
> Task :datamodel_make_svg
> Task :datamodel_svg

> Task :datamodel_merge
Validating /Volumes/Saxonica/src/qt4cg/qtspecs/build/expanded/xpath-datamodel-40/xpath-datamodel.xml
Attempting validating, namespace-aware parse
Parse succeeded (0.217) with no errors and no warnings.

> Task :datamodel_xml
> Task :etc_DM40

> Task :fo_merge
Transforming specifications/xpath-functions-40/src/xpath-functions.xml...
Validating /Volumes/Saxonica/src/qt4cg/qtspecs/build/expanded/xpath-functions-40/xpath-functions-40.xml
Attempting validating, namespace-aware parse
Parse succeeded (0.333) with no errors and no warnings.

> Task :etc_FO40

> Task :etc_SE40
Transforming specifications/xslt-xquery-serialization-40/src/xslt-xquery-serialization.xml...

> Task :grammar_40
Transforming specifications/grammar-40/xpath-grammar.xml...
Validating /Volumes/Saxonica/src/qt4cg/qtspecs/build/grammar-40/xpath-grammar.xml
Attempting validating, namespace-aware parse
Parse succeeded (0.112) with no errors and no warnings.

> Task :xquery_xpath_grammar

> Task :xquery_assemble_xpath
Transforming specifications/xquery-40/src/xpath.xml...
Validating /Volumes/Saxonica/src/qt4cg/qtspecs/build/xquery-40/src/xpath-assembled.xml
Attempting validating, namespace-aware parse
Parse succeeded (0.258) with no errors and no warnings.

> Task :etc_XP40
> Task :xquery_xquery_grammar

> Task :xquery_assemble_xquery
Transforming specifications/xquery-40/src/xquery.xml...
Validating /Volumes/Saxonica/src/qt4cg/qtspecs/build/xquery-40/src/xquery-assembled.xml
Attempting validating, namespace-aware parse
Parse succeeded (0.311) with no errors and no warnings.

> Task :etc_XQ40
> Task :xquery_shared_grammar

> Task :xquery_assemble_shared
Transforming specifications/xquery-40/src/XPathXQueryShared.xml...
Validating /Volumes/Saxonica/src/qt4cg/qtspecs/build/xquery-40/src/shared-assembled.xml
Attempting validating, namespace-aware parse
Parse succeeded (0.317) with no errors and no warnings.

> Task :etc_XQ40XP40

> Task :xslt_grammar
Transforming specifications/xslt-40/src/xslt.xml...

        WARNING!! production with name="MapTest" not found


        WARNING!! production with name="ArrayTest" not found


        WARNING!! production with name="EnumerationType" not found


        WARNING!! production with name="NamedItemType" not found


> Task :xslt_merge_catalog
Transforming specifications/xslt-40/src/function-catalog.xml...
Checking internal links...
**** Dangling reference to termdef  dt-arity

> Task :etc_XT40 UP-TO-DATE
> Task :etc_copy
> Task :setup_crossref_indexes
> Task :datamodel_html
> Task :datamodel_html_diff
> Task :datamodel_resources
> Task :datamodel_40
> Task :publish-datamodel-40

> Task :fo_html
Function fn:parcel in catalog but not spec
Function fn:parts in catalog but not spec
Function array:members in catalog but not spec
Function array:of in catalog but not spec
specdoc is FO40
Warning at mode (unnamed)
  XTDE0540  Ambiguous rule match for /spec/body[1]/div1[4]/div2[1]/table[1]
Matches both "table[xs:string(@role) eq "hierarchy"]" on line 1161 of
  file:/Volumes/Saxonica/src/qt4cg/qtspecs/specifications/xpath-functions-40/style/xpath-functions.xsl
and "table[xs:string(@role) eq "hierarchy"]" on line 1146 of
  file:/Volumes/Saxonica/src/qt4cg/qtspecs/specifications/xpath-functions-40/style/xpath-functions.xsl
Warning at mode (unnamed)
  XTDE0540  Ambiguous rule match for /spec/body[1]/div1[5]/div2[1]/table[1]
Matches both "table[xs:string(@role) eq "hierarchy"]" on line 1161 of
  file:/Volumes/Saxonica/src/qt4cg/qtspecs/specifications/xpath-functions-40/style/xpath-functions.xsl
and "table[xs:string(@role) eq "hierarchy"]" on line 1146 of
  file:/Volumes/Saxonica/src/qt4cg/qtspecs/specifications/xpath-functions-40/style/xpath-functions.xsl

> Task :fo_html_diff
Function fn:parcel in catalog but not spec
Function fn:parts in catalog but not spec
Function array:members in catalog but not spec
Function array:of in catalog but not spec
specdoc is FO40
Warning at mode (unnamed)
  XTDE0540  Ambiguous rule match for /spec/body[1]/div1[4]/div2[1]/table[1]
Matches both "table[xs:string(@role) eq "hierarchy"]" on line 1161 of
  file:/Volumes/Saxonica/src/qt4cg/qtspecs/specifications/xpath-functions-40/style/xpath-functions.xsl
and "table[xs:string(@role) eq "hierarchy"]" on line 1146 of
  file:/Volumes/Saxonica/src/qt4cg/qtspecs/specifications/xpath-functions-40/style/xpath-functions.xsl
Warning at mode (unnamed)
  XTDE0540  Ambiguous rule match for /spec/body[1]/div1[5]/div2[1]/table[1]
Matches both "table[xs:string(@role) eq "hierarchy"]" on line 1161 of
  file:/Volumes/Saxonica/src/qt4cg/qtspecs/specifications/xpath-functions-40/style/xpath-functions.xsl
and "table[xs:string(@role) eq "hierarchy"]" on line 1146 of
  file:/Volumes/Saxonica/src/qt4cg/qtspecs/specifications/xpath-functions-40/style/xpath-functions.xsl

> Task :fo_resources
> Task :fo_xml
> Task :xpath_functions_40

> Task :xpath_keyword_tests
Transforming specifications/xpath-functions-40/src/function-catalog.xml...

> Task :publish-xpath-functions-40
> Task :xquery_resources

> Task :xquery_shared_html
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-PITarget"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-CharRef"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-NCName"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-S"
Warning: link-text-with-check was unable to make a link for $ref-id="doc-xpath40-Char"

> Task :xquery_shared_html_diff UP-TO-DATE
> Task :shared_40
> Task :xquery_xpath_html
> Task :xquery_xpath_html_diff UP-TO-DATE
> Task :xpath_40
> Task :xquery_xquery_html
> Task :xquery_xquery_html_diff UP-TO-DATE
> Task :xquery_40
> Task :publish-xquery-40
> Task :xslt_make_svg
> Task :xslt_svg
> Task :xslt_resources

> Task :xslt_html
Error: cannot resolve nt: prod-xslt40-patterns-StringLiteral

> Task :xslt_html_diff
Error: cannot resolve nt: prod-xslt40-patterns-StringLiteral

> Task :xslt_xml
> Task :xslt_40
> Task :publish-xslt-40

> Task :serialization_xml
Validating /Volumes/Saxonica/src/qt4cg/qtspecs/specifications/xslt-xquery-serialization-40/src/xslt-xquery-serialization.xml
Attempting validating, namespace-aware parse
Parse succeeded (0.186) with no errors and no warnings.
Transforming specifications/xslt-xquery-serialization-40/src/xslt-xquery-serialization.xml...

> Task :serialization_html
Transforming specifications/xslt-xquery-serialization-40/src/xslt-xquery-serialization.xml...

> Task :serialization_html_diff
Transforming specifications/xslt-xquery-serialization-40/src/xslt-xquery-serialization.xml...

> Task :serialization_resources
> Task :serialization_40
> Task :publish-xslt-xquery-serialization-40
> Task :publish

BUILD SUCCESSFUL in 2m 37s
47 actionable tasks: 43 executed, 4 up-to-date
```

Succeeds without any DTD errors.

**Comment by michaelhkay** [comment]
What I find surprising here is that gradle reports

`Validating /Volumes/Saxonica/src/qt4cg/qtspecs/build/expanded/xpath-functions-40/xpath-functions-40.xml`

but if you open this file and try to validate it in Oxygen, it's clear that it contains many validation errors.

**Comment by ndw** [comment]
I have no idea what Oxygen is doing, but:
```
$ xjparsex -v build/expanded/xpath-functions-40/xpath-functions-40.xml
Attempting validating, namespace-aware parse
Parse succeeded (0.306) with no errors and no warnings.
```
and
```
$ saxon -dtd:on build/expanded/xpath-functions-40/xpath-functions-40.xml /Volumes/Documents/xsl/identity.xsl -o:/dev/null
```
both suggest that it's valid according to the DTD it refers to.  ¯\_(ツ)_/¯

**Comment by michaelhkay** [comment]
Strange.

I've switched back to the master branch, rebuilt, and Oxygen is showing 968 validation errors on this file.

The first of them is on line 1333, it objects to <table class="index"> saying the class attribute isn't allowed on table.

At this stage I have to start reading the DTD, which is not something I find easy!

xsl-query.dtd doesn't mention `table`.

xmlspec.dtd has

<!ATTLIST table
        %common.att;
        %width.att;
        %css.att;
        summary         CDATA           #IMPLIED
        border          CDATA           #IMPLIED
        frame           (void|above
                        |below|hsides
                        |lhs|rhs
                        |vsides|box
                        |border)        #IMPLIED
        rules           (none|groups
                        |rows|cols
                        |all)           #IMPLIED
        cellspacing     CDATA           #IMPLIED
        cellpadding     CDATA           #IMPLIED>
]]>

% css.att appears to allow class and style. So what's going on?

Michael Kay


On 20 Dec 2022, at 09:49, Norman Walsh ***@***.******@***.***>> wrote:



I have no idea what Oxygen is doing, but:

$ xjparsex -v build/expanded/xpath-functions-40/xpath-functions-40.xml
Attempting validating, namespace-aware parse
Parse succeeded (0.306) with no errors and no warnings.


and

$ saxon -dtd:on build/expanded/xpath-functions-40/xpath-functions-40.xml /Volumes/Documents/xsl/identity.xsl -o:/dev/null


both suggest that it's valid according to the DTD it refers to. ¯_(ツ)_/¯

**Comment by michaelhkay** [comment]
I've raised an issue with Oxygen support. It seems my efforts on this thread were based on the assumption that the validation errors reported by Oxygen were legitimate, and this now seems questionable. Having said that, most of the changes I made are either still beneficial or at least harmless, so I'll take another look at them rather than scrapping them entirely.

**Comment by michaelhkay** [comment]
I've discovered that if I rename xmlspec.dtd to xmlspec-2022.dtd, and change the reference in xsl-query.dtd accordingly, then Oxygen validates the file OK. It looks suspiciously as if Oxygen is recognizing the name "xmlspec.dtd" and using its own version rather than our version.

**Comment by michaelhkay** [comment]
Response from Octavian:

> It seems that the schema used for validation is Oxygen is the one from XMLSpec document type (frameworks\xmlspec\schema\xmlspec.dtd), instead of the schema from "qtspecs\schema\xmlspec.dtd".
> If you you want to use a custom xmlspec.dtd schema you can disable the XMLSpec document type from Options->Preferences->Document Type Association option page. You can also change the catalog file from the XMLSpec document type, to point to the custom schema.
> 

I confirmed that the fix works.

However, to avoid other people having to reconfigure their Oxygen set-up, perhaps we should rename the file?

**Comment by ndw** [comment]
Yes. Definitely.

Odds are, we should never *have* changed that file, we should have made the changes with overrides. But really, we've made a lot of changes, so that was probably less and less convenient.

**Comment by ndw** [comment]
They must be using a `systemSuffix` catalog entry. I think that's a bit heavy handed in a system-wide framework, but I suppose we're in the small minority of folks who edit schemas used by frameworks. Yay, us.
