### ISSUE TITLE
Error in fn:doc-available specification

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#293]
Observed on the XML.com slack (Oct 6 2022):

A rule in the XQFO 3.1 specification seems to be inconsistent. In the error summary, it’s stated that:

> `err:FODC0005`, Invalid argument to fn:doc or fn:doc-available. Raised (optionally) by `fn:doc` and `fn:doc-available` if the argument is not a valid URI reference.

The rules for `fn:doc-available` say: “[…] In all other cases this function returns false. This includes the case where an invalid URI is supplied, and also the case where a valid relative URI reference is supplied, and cannot be resolved, for example because the static base URI is absent.”

**Comment by michaelhkay** [comment]
The error summary is non-normative, so that's what we should change.
