### ISSUE TITLE
Abstract supertype for map and array

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#298]
I've been wondering whether there would be any mileage in introducing an abstract super type for map() and array(), perhaps called lookup(). This would basically treat an array as a map with integer keys.

This would allow a cleaner type signature for map:find() and any future functions such as xx:search() that work both on maps and arrays. It might simplify the description of the lookup operator "?". For functions that already exist in both the map and array namespaces, such as get(), we could introduce a unified function in the fn namespace with the cosmetic benefit of reducing the need for namespace prefixes and namespace declarations.

I'm still keen to find a better way of doing iteration, filtering, mapping, and construction of maps and arrays, and I think this might be a useful stepping stone.

**Comment by dnovatchev** [comment]
I would be inclined to name it: **_`xs:keyed`_**

**Comment by ChristianGruen** [comment]
`data-structure()` could be another option.

This proposal reminds me of #130, though, in which the usage of local union types was favored over adding new types.

**Comment by michaelhkay** [comment]
Revisiting this, I think a simpler development would be to make arrays be a subtype of maps. An array is basically a map whose keys are consecutive integers starting at 1. All operations that take maps as input could perfectly well take an array as input, viewed in this way. One could define some additional behaviours, for example that map:keys() when applied to an array returns the index values in order.

Note that operations like map:remove(), when applied to an array, return a map that is not an array.

map:get($array, $n) gives the same result as array:get($array, $n) except that there is no error if $n is out of range.

**Comment by michaelhkay** [comment]
I'm thinking of a package of proposals to make navigation and transformation of trees of maps and arrays significantly easier. I think the benefits and use cases for making arrays a special kind of map will only become clear in the context of the full package. Watch this space.

**Comment by ChristianGruen** [comment]
> Revisiting this, I think a simpler development would be to make arrays be a subtype of maps.

I can see that it would be comfortable from a technical point of view, but I think we shouldn't do that:

It would make existing coffee incompatible. Think of:

```xquery
if($x instance of map(*)) then 'map'

```

**Comment by michaelhkay** [comment]
I think that the introduction of choice item types `(map(*) | array(*))` reduces the need for this feature, so let's drop it.

**Comment by ndw** [comment]
The CG agreed to close this issue without further action at [meeting 073](https://qt4cg.org/meeting/minutes/2024/04-16.html).
