### ISSUE TITLE
Improve the discoverability and parseability of the mathematical operator symbols

### ISSUE THREAD

**Issue by rhdunn** [qt4cg/qtspecs#30]
In order to keep the XPath and XQuery languages parseable without the need of a pre-processing step, the operators should be integrated into the grammar, such as in:

    [29] UnionExpr ::= IntersectExceptExpr ( ("union" |  "|" | "∪") IntersectExceptExpr )*

To make them more easily discoverable to someone reading the specification, the behaviour of the Unicode aliases should be included the description in the text related to that section. For example:

> The union, |, and ∪ operators are equivalent. They take two node sequences as operands and return a sequence containing all the nodes that occur in either of the operands. 

__NOTE:__ With the introduction of the `LocalUnionType`, a pre-processing step would need to map `∪` to `|` in order to avoid `∪(xs:string, xs:integer)` being valid. -- This would then mean that things like the `CatchErrorList` would then be able to use `∪`, as in `try {} catch err:FOER0001 ∪ err:FOER0002 {}`.

**Comment by michaelhkay** [comment]
This is essentially editorial.

**Comment by ChristianGruen** [comment]
Closed (see #460 and #204).
