### ISSUE TITLE
parse-xml() and whitespace stripping

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#305]
There seems to be nothing in either the XSLT spec or in F+O that says explicitly whether stylesheet-defined space stripping rules (xsl:strip-space and xsl:preserve-space) apply to documents loaded using `fn:parse-xml` (or, by extension, `parse-html`).

The spec says that these rules apply to "source trees" defined as "any tree provided as input to the transformation. This includes the document containing the [global context item] if any, documents containing nodes present in the [initial match selection], documents containing nodes supplied as the values of [stylesheet parameters], documents obtained from the results of functions such as [document], [doc], and [collection]...".

I guess one reasonable interpretation is that the "such as" includes `parse-xml()`. But it goes rather against the grain that the behaviour of parse-xml() should be affected by the containing stylesheet declarations, when there is no mention of such a context-dependency in the function specification; in this, parse-xml() is rather different from doc() which deliberately says very little about how the XDM instance returned relates to the URI supplied as input.

**Comment by michaelhkay** [comment]
FWIW, I think that SaxonJ does apply the space-stripping rules to `parse-xml()`, while SaxonJS does not.

**Comment by dnovatchev** [comment]
`parse-xml()` may be called in an xpath-only environment where there isn't anything corresponding to the XSLT `xsl:strip-space` and `xsl:preserve-space` declarations.

This means that the implementation must know "who called it from where" and this contradicts the well-established architectural design practices (such as **_[loose coupling](https://en.wikipedia.org/wiki/Loose_coupling)_**).

Therefore, a better alternative is to have a new, additional argument that specifies the space-handling strategies, if any such are required. The current behavior will have to be the default.

**Comment by ChristianGruen** [comment]
Related: #490

**Comment by ndw** [comment]
Consensus at the F2F in Prague in June, 2024 is that there should be `option` map arguments on functions (`fn:parse-xml`, `fn:doc`, etc.)
