### ISSUE TITLE
Basic Operations on Maps and Arrays

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#314]
# Manipulating Arrays and Maps

This is an outline of proposed new facilities designed to make processing of maps and arrays easier. The basic facilities needed for transformation of maps and arrays are the ability to decompose them into their parts, manipulate the parts, and the compose new arrays and maps from these parts.

Further background is in my 2022 Balisage paper, https://balisage.net/Proceedings/vol27/html/Kay01/BalisageVol27-Kay01.html

This proposal considers only the "shallow" operations on maps and arrays. Further proposals for deep search and update of nested structures are to be expected.

## Basics

A map entry is an item used to represent a key-value pair in a map; it is an item of type `record(key as xs:anyAtomicType, value as item()*)`, aliased in this proposal as `type(map-entry)`.

Note: _an alternative representation for key-value pairs is as a singleton map, and that's the representation used by the existing map:entry() function and by the xsl:map-entry instruction. A representation as `record(key, value)` is rather more convenient to enable extraction of the key and value, but does create some compatibility issues..._ 

An array entry is an item used to represent a member of an array; it is an item of type `record(value as item()*)`, aliased in this proposal as `type(array-entry)`.

## Decomposing Maps and Arrays

The function `map:entries($map)` returns a sequence of map entries, in unpredictable order, representing the contents of the supplied map. It is equivalent to `map:for-each($map, ->($k, $v){map:entry($k, $v)})`.

The function `array:entries($array)` returns a sequence of array entries, in array order, representing the members of the supplied array. It is equivalent to `array:for-each($array, ->($v){array:entry($v)})`.

## Constructing Maps and Arrays

The function `map:of($entries as type(map-entry)*) as map(*)` constructs a map from a sequence of map entries. A second parameter, `$options`, is available to control handling of duplicates, as with `map:merge()`. The function is equivalent to `map:merge($entries!map{'key':?key, 'value':?value})`.

The function `array:of($entries as type(array-entry)*) as array(*)` constructs an array from a sequence of array entries. It is equivalent to `array:fold-left($entries, [], array:append#2)`.

The function `map:entry($key, $value) as type(map-entry)` is equivalent to `map{'key':$key, 'value':$value}`. _Problem: we already have a function map:entry() in 3.1 that does something different. Need to change the terminology..._

The function `array:entry($value) as type(array-entry)` is equivalent to `map{'value':$value}`.

## Filtering Maps and Arrays

The construct `$map?[PREDICATE]` is equivalent to `map:of(map:entries($map)[PREDICATE])`. For example, given a map in which the keys are dates, `$map?[year-from-date(?key)=2023]` returns a map containing those entries in which the key is a date in 2023.

The construct `$array?[PREDICATE]` is equivalent to `array:of(array:entries($array)[PREDICATE])`. For example, `$array?[1]` selects the first item in the array (as a single-member array), while `$array?[exists(?value)]` returns an array containing all those entries in the input array that are not empty. If `$array` is an array of maps, then `$array?[?value?name='John']` selects those members of the array that are maps having `?name='John'`.

## Mapping Maps and Arrays

The construct `$map!!EXPR` evaluates `EXPR` once for each entry in `$map` and returns the result as a flattened sequence. For example `map:of($map!!map:entry(?key, ?value+1))` returns a map in which each value has been incremented by one.

The construct `$array!!EXPR` evaluates `EXPR` once for each entry in `$array`, and returns the result as a flattened sequence. For example, `array:of($array!!array:entry(?value+1))` returns an array in which every value has been incremented by one.

## FLWOR Expressions

The for-member clause `for member $m in $array` is equivalent to `for $sys:var in array:entries($array) let $m := $sys:var?value`.

The for-entry clause `for entry ($k, $v) in $map` is equivalent to `for $sys:var in map:entries($map) let $k := $sys:var?key, $v := $sys:var?value`.

## XSLT

Iteration over maps and arrays is achieved using `<xsl:for-each select="array:entries()">` and `<xsl:for-each select="map:entries()">` directly.

Construction of maps uses the existing instructions `<xsl:map>` and `<xsl:map-entry>`. There is an inconvenience here in that the `<xsl:map-entry>` instruction returns a singleton map (`map{key:value}`) rather than a map entry as defined in this proposal (`map{'key':key, 'value':value}`)..

Construction of arrays uses the new instructions `<xsl:array>` and `<xsl:array-entry>`. The `xsl:array-entry` instruction is defined to construct an array entry as defined in this proposal.

## Use Cases

To be supplied.

**Comment by michaelhkay** [comment]
See also issue #29.

**Comment by ChristianGruen** [comment]
Copied from https://github.com/qt4cg/qtspecs/pull/360#issuecomment-1436890243:

If `array:members` returns records instead of singleton arrays, I believe we should extend `array:join` to also accept array records:

```xquery
array:join((
  for $i in 1 to 5
  return array:members($i)
))
```

**Comment by ChristianGruen** [comment]
And one more thought (sorry for creating multiple comments):

The implicit atomization of array members is a powerful feature, which might get lost if we represent array members as records. We should definitely try to extend atomization to “value records”. This would allow people to write…

```xquery

array:members([ (), 2, (3, 4) ]) ! element numbers { . },
substring(map { 'value': 'xyz' }, 2),
...
```

…instead of…

```xquery
array:members([ (), 2, (3, 4) ]) ! element numbers { ?value },
substring(map { 'value': 'xyz' }?value, 2),
...
```

**Comment by michaelhkay** [comment]
Reopened: PR 360 tackles the "arrays" part of the issue, but the "maps" part remains outstanding.

**Comment by michaelhkay** [comment]
Most of this has been delivered or is the subject of other more specific issues, so I think it's time to close this issue with no further action.

**Comment by ndw** [comment]
The CG decided to close this issue without any further action at [meeting 069](https://qt4cg.org/meeting/minutes/2024/03-12.html).
