### ISSUE TITLE
fn:transform inconsistency: initial-mode

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#315]
The `fn:transform` specification in F+O says that if no initial-mode is supplied, the unnamed mode is used.

The XSLT 3.0 specification says that if no initial mode is supplied, then the default mode is used if one has been specified, or the unnamed mode is used if not.

I think the XSLT 3.0 spec should win here: it makes more sense if a default has been declared that it should actually be used.

(Thanks to Amanda Galtman for pointing this out.)

**Comment by ndw** [comment]
👍
