### ISSUE TITLE
try/catch: New variable for all error information

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#32]
Within the scope of a catch clause, some variables are implicitly declared. However, it’s more than tedious to forward all this information to another function:

```xquery
try {
  'oh' + 'dear'
} catch * {
  handle-error($err:code, $err:description, $err:line-number, $err:column-number, ...)
}
```

What about binding all data to an additional `$err:map` variable?

```xquery
map {
  'code': $err:code,
  'value': $err:value,
  'description': $err:description,
  'line-number': $err:line-number,
  'column-number': $err:column-number,
  'additional': $err:additional
}
```

The code could then be shortened to:

```xquery
try {
  'oh' + 'yes'
} catch * {
  handle-error($err:map)
}
```

**Comment by michaelhkay** [comment]
Yes, I agree, I've had the same idea myself.

**Comment by benibela** [comment]
>What about binding all data to an additional $err:map variable?

Could also call it `$err:error` or `$err:or`

**Comment by line-o** [comment]
This pattern can be found all over the xquery code base. A great thing to standardise.

**Comment by rhdunn** [comment]
This should also be available for XSLT -- https://www.w3.org/TR/xslt-30/#element-try.

**Comment by ChristianGruen** [comment]
Accepted at [meeting 034, 16 May 2023](https://qt4cg.org/meeting/minutes/2023/05-16.html)
