### ISSUE TITLE
Switch Cases: Lift single-item restriction on operands

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#328]
## Motivation

[XQuery switch cases](https://www.w3.org/TR/xquery-31/#id-switch) have a peculiar restriction: The operand of a single case must yield an empty sequence or a single item. There seem to be no (obvious) reasons why this restriction exists, so I believe we should lift it and allow arbitrary sequences.

A similar extension is planned for Java 12 ([JEP 325: Switch Expressions](http://openjdk.java.net/jeps/325)). The required changes in XQuery are simpler, though, as the 3.1 grammar already supports arbitrary expressions as operands.

## Examples

```xquery
switch($value)
  case 1
  case 2
  case 3
  case 4
  case 5
    return 'small'
  default
    return 'big'
```

Proposed syntax:

```xquery
switch($value)
  case 1 to 5
    return 'small'
  default
    return 'big'
```

## Required Changes

The [current matching rules](https://www.w3.org/TR/xquery-31/#id-switch) could be rephrased as follows:

1. The SwitchCaseOperand is evaluated.
2. The resulting value is atomized.
3. The case matches if the value is empty and if the value of the switch expression is empty as well.
3. Otherwise, the atomized value of the switch operand expression is compared with each item of the atomized value of the SwitchCaseOperand using `fn:deep-equal`, with the default collation from the static context.

## References

* Original Proposal: https://github.com/expath/xpath-ng/pull/12
* Discussion on Slack: https://xmlcom.slack.com/archives/C011NLXE4DU/p1675006336963479

**Comment by michaelhkay** [comment]
If we make this change then I'm wondering whether the CaseOperand could be an Expr rather than an ExprSingle, allowing

`case 1, 3, 5, 7, 8, 10, 12 return 31`

rather than

`case (1, 3, 5, 7, 8, 10, 12) return 31`

**Comment by michaelhkay** [comment]
Note that the proposed xsl:switch instruction in XSLT 4.0 uses "=" for comparison.

I suspect that I didn't notice the semantics don't match XQuery, since I think I'm compiling to the same underlying code...
