### ISSUE TITLE
Extend fn:path to support arrays and maps.

### ISSUE THREAD

**Issue by rhdunn** [qt4cg/qtspecs#331]
Currently, `fn:path` is defined for nodes. This means it is not possible to use it with arrays or maps (e.g. to determine the path to a JSON item when a comparison fails).

As such, I recommend:
1. changing the type to `item()`
2. If the value is a node use the current logic.
3. If the value is in an array, use `?n` where n is the nth item of the array where the item is located.
4. If the value is in a map, use `?name` or `?"name"` where name is the key name of the map where the item is located.
5. If the value is an atomic item, or the root of a map/array structure, use `.`.

Example: `.?4?user?name`

**Comment by michaelhkay** [comment]
I don't see how this works: maps and arrays have no parent pointers, so there is no way of discovering the route or routes by which they might be reached. And indeed, there is no unique route - there's no way of distinguishing a `map{1:red, 2:blue}` appearing in one "tree" from the same map appearing in any number of other trees.

The idea is related, however, to the concept of a trail or selector described in comments on issue #262. The idea there is that you can do deep navigation into a tree of maps and arrays and leave behind a trail of your route into the structure; the "path" being described here could be considered to be a string representation of this trail.

**Comment by michaelhkay** [comment]
Issue #334 proposes ¶path as a transient property of a value that has been found by downward selection in a tree of maps and arrays.

**Comment by michaelhkay** [comment]
As originally suggested, I think the proposal is technically flawed: an array such as `[1,2,3]` might be found in many different trees, and there is no way of identifying a particular tree that it is found in. The requirement is real, but it needs a different solution. I'm therefore going to propose closing the issue with no action.

**Comment by ndw** [comment]
At [meeting 039](https://qt4cg.org/meeting/minutes/2023/06-20.html#open-pull-requests) the CG agreed to close this issue without further action.
