### ISSUE TITLE
The constraints on document-uri are too...constraining

### ISSUE THREAD

**Issue by ndw** [qt4cg/qtspecs#339]
The XPath data model imposes the following constraints on the document-uri property:

> If the `document-uri` is not the empty sequence, then the following constraint must hold: the node returned by evaluating `fn:doc()` with the document-uri as its argument must return the document node that provided the value of the `document-uri` property.
> 
> In other words, for any Document Node `$arg`, either `fn:document-uri($arg)` must return the empty sequence or `fn:doc(fn:document-uri($arg))` must return `$arg`.

This contraint turns out to be inconvenient whenever the larger environment doesn’t enforce a 1:1 mapping between URIs and documents.

For example, in a browser context, a JavaScript function that returns different versions of the same document over time cannot identify those documents with the same document-uri.

In XProc, a `p:add-attribute` step that returns a copy of its input document with one additional attribute, cannot identify the output document with the same document-uri as the input document.

Given that the document URI is often necessary to evaluate relative URI references within a document, the constraints imposed in the data model are too strict.

**Comment by ChristianGruen** [comment]
@ndw Should we close this one in favor or #898 ?

**Comment by ndw** [comment]
Yes, absolutely.
