### ISSUE TITLE
Missing rule for matching atomic values against atomic types

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#345]
In XPath §3.6.2 we have forgotten to state the obvious rule:

"An Atomic Value AV matches a generalized atomic type GAT if the type annotation of AV (call it T) satisfies the condition derives-from(T, GAT)."

At the same time it would a good idea to clarify whether locally-declared union and enum types fall within the definition of "schema types" (I think they should do so.)

**Comment by ndw** [comment]
Closed by #363
