### ISSUE TITLE
fn:function-annotations (Allow support for user-defined annotations)

### ISSUE THREAD

**Issue by rhdunn** [qt4cg/qtspecs#36]
### Requirements/Use Cases
1. It should be possible for a library or application written in XQuery to define, access, and use custom annotations without relying on vendor extensions.
2. It should be possible for a processor or editor/IDE to check and verify user-defined annotation usage (can an annotation be used multiple times; what argument values/types are valid) to provide better validation for custom annotations.
3. It should be possible to access the details of the annotations on a function (name, argument values) so tools like xqDoc can read and format annotations without using vendor extensions.

### Annotation Declarations
1. An annotation declaration is a function declared using the `%annotation` annotation.
2. Annotation parameters must be a SequenceType that has an ItemType which is either a) a subtype of `union(xs:string, xs:double, xs:float, xs:decimal)*`, or b) `item()` (to denote any permitted literal value). __Note:__ This is because annotation values are restricted to literal values. __Note:__ It is therefore possible to use an EnumerationType to define a set of allowed string values (e.g. "yes" and "no").
3. If a function annotation name matches an annotation declaration in the statically-known functions using the function name resolver, it is verified using the same rules for static function calls; if there are no matching annotation declarations, then no error is issued, although an implementation may choose to issue a warning.

### Annotation Tests
1. A new AnnotationTest (`annotation(...)`) SequenceType is provided with the same structure and semantics as a FunctionTest.
2. AnnotationTest parameters must be a SequenceType that has an ItemType which is either a) a subtype of `union(xs:string, xs:double, xs:float, xs:decimal)*`, or b) `item()` (to denote any permitted literal value). __Note:__ This is because annotation values are restricted to literal values. __Note:__ It is therefore possible to use an EnumerationType to define a set of allowed string values (e.g. "yes" and "no").

### fn:annotations
> `fn:annotations($f as function(*)) as annotation(*)*`

Returns all the annotations on the function.

The `annotation` signature will match the signature of the annotation, so `%a(1, 2)` will have the `annotation(xs:integer, xs:integer)` annotation type.

If a function has multiple annotations with the same signature (e.g. `%values(1) %count(2)`) then two annotations will be returned with the same signature, referring to the different annotations.

### fn:annotation
> `fn:annotation($f as function(*), $name as xs:QName) as annotation(*)*`

Returns all the annotations on the function with the name `$name`.

The `annotation` signature will match the signature of the annotation, so `%a(1, 2)` will have the `annotation(xs:integer, xs:integer)` annotation type.

If a function has multiple annotations with the same name and signature (e.g. `%values(1) %values(2)`) then two annotations will be returned with the same signature, referring to the different annotations.

### fn:annotation-name
> `fn:annotation-name($annotation as annotation(*)) as xs:QName`

Returns the name of the annotation.

### fn:annotation-arguments
> `fn:annotation-arguments($annotation as annotation(*)) as array(*)`

Returns the arguments passed to the associated annotation.

**Comment by ChristianGruen** [comment]
Related (BaseX): https://docs.basex.org/wiki/Inspection_Module#inspect:function-annotations

**Comment by ChristianGruen** [comment]
I had more thoughts on the proposed features. I believe a single function would be sufficient:

```xquery
fn:function-annotations(
  $function  as function(*)
) as map(xs:QName, xs:anyAtomicType*)
```
