### ISSUE TITLE
Named arguments: $input vs. $value

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#361]
Great effort has been made in unifying the parameter names of the XQFO standard; thanks for that!

I believe to remember that:

* `$value`, `$values`, `$value1`, etc. is used for atomic/atomized arguments, whereas
* `$input`, `$input1`, etc. is used for input, mostly of type `item()`, that is processed unchanged.
* `$uri` is used for arguments that could have been defined as items of type `xs:anyURI`.

I believe the following argument names need to be double-checked (if not, It may be that I haven’t fully grasped how the naming rules are supposed to work):

Function | Currently | Presumably | Justification
--- | --- | --- | ---
`array:slice` | `$input` | `$array` | Alignment with `array:size` et al.
`trace` | `$value` | `$input` | Argument is not atomized
`json` | `$input` | `$value` | Argument is atomized
`string` | `$item` | `$value`  | `$item` is used nowhere else
`expanded-QName` | `$qname` | `$value` | Alignment with `prefix-from-QName` et al.
`resolve-QName` | `$qname` | `$value` | Alignment with `prefix-from-QName` et al.
`parse-QName` | `$eqname` | `$value` | Alignment with `parse-xml` et al.
`parse-json` | `$json` | `$value` | Alignment with `parse-xml` et al.
`json-to-xml` | `$json` | `$value` | Alignment with `parse-xml` et al.
`char` | `$name` | `$value` | Input may also be codepoint values, etc.
`namespace-uri-for-prefix` | `$prefix` | `$value` | `$prefix` is used nowhere else
`resolve-uri` | `$relative` | `$uri` | Absolute URIs are legal as well
`array:append` | `$add` | `$member` | Alignment with `array:put`

And we should probably pay particular attention to the naming conventions when adding new functions.

**Comment by ChristianGruen** [comment]
@michaelhkay Do you believe the suggested amendment would be reasonable and consistent?

**Comment by michaelhkay** [comment]
It's moving in a slightly different direction from what I originally envisaged, which was to use a specific name describing the role of the argument unless I couldn't think of anything suitable; but I have no objection to these changes.

**Comment by ChristianGruen** [comment]
Thanks. I’ve created a PR.

> It's moving in a slightly different direction from what I originally envisaged, which was to use a specific name describing the role of the argument unless I couldn't think of anything suitable; but I have no objection to these changes.

It will be helpful if the parameter names don’t change too often, as this needs to be reflected in other implementations. Next, the underlying conventions may affect the current and future naming of functions in vendor-specific modules.
