### ISSUE TITLE
switch, typeswitch: Optional braces

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#365]
The indentation of switch expressions is often a mess. Now that we allow curly braces for `if`, it would be nice to also allow optional braces for `switch` and `typeswitch`:

```xquery
typeswitch($item) {
  case xs:numeric return 'number'
  default return '...'
},
switch($item) {
  case 0 to 9 return 'single digit'
  default return '...'
}
```

The current syntax is:

```xquery
typeswitch($item)
  case xs:numeric return 'number'
  default return '...',

switch($item)
  case 0 to 9 return 'single digit'
  default return '...'
```

**Comment by rhdunn** [comment]
Note that IDEs and editors can support (re)formatting of code based on user styles/preferences. They can also support code folding on expressions.
