### ISSUE TITLE
apparent copy/paste error in annotation documentation of simple type yes-or-no-or-maybe

### ISSUE THREAD

**Issue by martin-honnen** [qt4cg/qtspecs#373]
The XSD 1.1 schema for XSLT 3 and the one for XSLT 4 (at https://qt4cg.org/specifications/xslt-40/schema-for-xslt40.xsd) has an error in the annotation/documentation section of the simple type `yes-or-no-or-maybe` as it there says `One of the values "yes" or "no" or "omit".`. I think that should be `One of the values "yes" or "no" or "maybe"`, the error probably exists as someone copied the text from the `yes-or-no-or-omit` type declaration and forgot to adapt the description.

**Comment by michaelhkay** [comment]
Interesting, that also suggests a missing test case, because we do have a test that validates all the non-error stylesheets in the test suite against the schema-for-xslt.

**Comment by michaelhkay** [comment]
Fixed by PR #445
