### ISSUE TITLE
Can't view the XSD for XSLT in the browser

### ISSUE THREAD

**Issue by ndw** [qt4cg/qtspecs#374]
If you attempt to open `https://qt4cg.org/specifications/xslt-40/schema-for-xslt40.xsd` in the browser (in Firefox), you'll get:

```
Error loading stylesheet: An unknown error has occurred (805303f4)
http://www.w3.org/2008/09/xsd.xsl
```

In a Chrome-derived browser I get a blank screen on which even the context menu doesn't work. Digging about in the inspect window leads me to

```
Unsafe attempt to load URL http://www.w3.org/2008/09/xsd.xsl from frame with URL
https://qt4cg.org/specifications/xslt-40/schema-for-xslt40.xsd. Domains, protocols and ports must match.
```

I conclude that the problem is trying to load the XSL for XSD from a different domain. Boo. I guess we should copy those stylesheets to `qt4cg.org`, or remove the stylesheet PI, or ignore the whole thing on the assumption that we'll eventually publish these specifications in some W3C location and the probem will go away. Maybe.

**Comment by michaelhkay** [comment]
Alternatively, enable CORS?

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

Michael Kay
Saxonica

**Comment by ndw** [comment]
Ahh. Perhaps. I'd got it the wrong way around in my head. I thought of CORS, and then I thought I'd have to get the W3C site to change something for that to work. But that's backwards. Thank you.

**Comment by ndw** [comment]
Hmmm... `qt4cg.org` serves:

```
access-control-allow-origin: *
```

so maybe my intuition was right about having to change something on the W3C side?

I really should get my head around how CORS actually works, I guess.

**Comment by ndw** [comment]
Note that the XSD stylesheet reference is currently commented out so it "works" for some definitions of "work".

**Comment by ndw** [comment]
On closer examination, I'm not wholly convinced this is worth persuing. The stylesheet isn't up-to-date with XSD 1.1 features, so it would need to be improved. The output that it produces is, maybe, better than the raw XSD, only maybe.

If we want to do this, I suggest that we update the XSD stylesheet to a modern version of XSLT, format the specification during the build process, and produce a page with the marked up content. The Invisible XML CG does this for the full serializations of the iXML grammar, for example, for both the [text](https://invisiblexml.org/current/ixml.ixml.html) and [XML](https://invisiblexml.org/current/ixml.xml.html) formats.

Doing that, or removing the PI and closing this issue without any further action, seem like the best options. IMHO.

**Comment by ndw** [comment]
There doesn't seem to be consensus that this is worth the effort.

**Comment by ndw** [comment]
The CG agreed to close this issue without further action at [meeting 103](https://qt4cg.org/meeting/minutes/2024/12-17.html).
