### ISSUE TITLE
add documentation prefix attribute to xsl:stylesheet

### ISSUE THREAD

**Issue by liamquin** [qt4cg/qtspecs#376]
Although the addition of xsl:note is very welcome, i had been hoping for something like the xsl:stylesheet attribute extension-element-prefixes, e.g. ignored-element-prefixes.

The specification would be something like,
Elements and attributes associated with an ignored element prefix are not treated as direct constructors, and are removed when the stylesheet is compiled. For such an element, this is equivalent to having an xsl:use-when attribute with value false on the element; for attributes, they are simply discarded along with their value.

It is not an error for a prefix to be listed both as an ignored element prefix and as an extension element prefix; the result is implementation dependent in this case, but MUST not result in neither an extension being invoked nor the element or attribute being ignored.

Ignored elements may appear anywhere in the input tree, and ignored attributes may appear on any element.

Example:
```
<xsl:template match="city/park" css:module="main">
  <css:rule>
    color: green;
    trees: tall;
  </xsl:rule>
  <div class="park">
    <xsl:apply-templates />
  </div>
</xsl:template>
```

**Comment by michaelhkay** [comment]
I didn't pursue the `ignored element prefix` approach because I had prototyped it in Saxon and found too many difficulties with the detail of the spec; and that's probably because there are different use cases with different requirements. It's a question of defining the exact details of where it is ignored and where it isn't.

**Comment by pgfearo** [comment]
@liamquin You don't mention that we can already add attributes in our own namespace (not null) to any XSLT instruction and they will be ignored by the XSLT compiler.

 I'm hoping to use an `edit:as` attribute to retrofit XSLT 4.0 type aliases in an XSLT 3.0 editor implementation. The editor will use this attribute for auto-completion, symbol-renaming and in-situ warnings in the editor but the attribute will be ignored by the XSLT processor.

**Comment by michaelhkay** [comment]
>and they will be ignored by the XSLT compiler

The attributes will be ignored, but the namespace won't. Any namespace declared in the stylesheet becomes part of the static context, which in turn becomes effectively part of the dynamic context. If your `xsl:stylesheet` element has a namespace declaration xmlns:doc="http://mydoc/", then at run-time a call to `xs:QName($prefix || ':local')` will take this binding into account, which means it has to be carried through into the compiled code.

**Comment by michaelhkay** [comment]
I would like to propose closing this with no action, for the reasons explained in my comments. I believe it adds yet more complexity to the specification, which few users will master. I believe that the xsl:note addition provides a viable solution to the requirement identified.

**Comment by liamquin** [comment]
I think you are suggesting i’d put css:rule elements inside a css:node, or that i'd use an extension attribute on css:note to say it's got CSS in it. Probably putting the css:rule elements inside a css:note element would work, even if it's a bit clunky. I could also use significant comments,  which would remove the need to pre-process the XSLT, but i've never liked doing that.

I have no problem with needing to add "css" to exclude-result-prefixes though, and will still need to do that with or without being able to identify all elements associated with the "css" namespace as "notes"

Would it help implementation to say, "any element whose namespace name is in the list of documentation namespaces is discarded, along with its children, during construction of the stylesheet"? This is orthogonal to having the namespace itself be visible.

**Comment by liamquin** [comment]
Hmm, actually i might be able to use, ```
<css:rule>
  <xsl:fallback/>
  color: red;
  font-size: 1.2;
  </css:rule>```
  which would be better than using xsl:note, although still a mess.
  
The use case is not simply embedding foreign languages in XSLT, such as CSS, but doing it in a way that encourages keeping the foreign language and the XSLT in sync, up to date, and experience strongly suggests that any syntactic burden is a disincentive and for many people a barrier, so I’ve been looking at ways to reduce the barrier. So, xsl:note is a step forward perhaps, but doesn’t solve all aspects.

**Comment by ndw** [comment]
At [meeting 039](https://qt4cg.org/meeting/minutes/2023/06-20.html#open-pull-requests) the CG agreed to close this issue without further action.
