### ISSUE TITLE
Published XQuery 4.0 spec renders XML predefined entities instead of literal characters

### ISSUE THREAD

**Issue by pgfearo** [qt4cg/qtspecs#377]
When rendered in the browser, XML examples in the [XQuery 4.0 specification](https://qt4cg.org/specifications/xquery-40/xquery-40.html) show, for example, '`&lt;`' instead of '`<`':

![Screenshot 2023-02-28 at 07 21 49](https://user-images.githubusercontent.com/2734234/221782371-1d119a80-72b3-4ede-b9c9-0b2b464533c0.png)

**Comment by ndw** [comment]
Thanks. I'm working on some stylesheet issues today and I'll fix this. I wonder when it started...

**Comment by ndw** [comment]
Ah. This isn't a style issue, this is a markup error:
```
                     <eg role="parse-test"><![CDATA[&lt;shoe size="7"/&gt;]]></eg>
```
I wonder how pervasive that is...

**Comment by ndw** [comment]
No, I take that back. It must be a change in how `eg` is processed because that markup hasn't changed in years.

**Comment by michaelhkay** [comment]
I have a theory. I might have done a transformation to get rid of all change markup. If I did that, I would have tried to preserve entity references, which I would have done by changing `&` globally to `§`, reversing the change later. If the transformation said `cdata-section-elements="eg"`, which is entirely possible, the code would have gone through the iterations:

`1. <eg role="parse-test">&lt;shoe size="7"/&gt;</eg>`

`2. <eg role="parse-test">§lt;shoe size="7"/§gt;</eg>`

`3. <eg role="parse-test"><![CDATA[§lt;shoe size="7"/§gt;]]></eg>`

`4. <eg role="parse-test"><![CDATA[&lt;shoe size="7"/&gt;]]></eg>`

Oops!

Mike

**Comment by ndw** [comment]
The only practical thing I can think to do is write a little script to examine each CDATA section and remove the CDATA section markup if it doesn't contain any unescaped markup.
