### ISSUE TITLE
Improve whitespace handling in deep-equal

### ISSUE THREAD

**Issue by ndw** [qt4cg/qtspecs#382]
At [meeting 024](https://qt4cg.org/meeting/minutes/2023/02-28.html) where PR https://github.com/qt4cg/qtspecs/pull/320 was accepted, there remained an open question of how to deal with whitespace.

The current options can be seen as having somewhat overlapping domains. Can this be improved?

**Comment by michaelhkay** [comment]
Firstly, I think the rule in 3.1 that after stripping comments and PIs, you don't merge adjacent text nodes, can be considered a bug and we can change it. I can't see anyone relying on this behaviour (other than a test suite, which is always awkward, but manageable). That gets rid of the "preserve boundaries" option.

Then, as suggested in discussion, I think we can probably reduce it to a single three-valued option: `whitespace = retain | normalize | strip`, with the default `retain`.

- Retain does nothing.
- Strip removes all whitespace text nodes, except those representing the content of elements that are schema-validated to have simple content. (Perhaps it should also respect `xml:space="preserve"`?)
- Normalize does the same as strip, plus it does `normalize-space()` on all text and attribute nodes.

**Comment by Arithmeticus** [comment]
This sounds good to me.

Make sure that all discussions of the options respect the same order: retain, strip, normalize. Prima facie it's not immediately apparent that the third encompasses the second.

Yes, I think xml:space should be respected by both the strip and the normalize options. That will be an important mechanism for anyone who needs to use a preprocessing stage to fine-tune space handling in an input tree.

Should the strip option also affect attribute values that consist only of space?

**Comment by michaelhkay** [comment]
It seems I created a branch to resolve this issue some while ago, but for some reason it never turned into a PR. 

I've reworked and resubmitted the PR.

**Comment by michaelhkay** [comment]
Change accepted and applied
