### ISSUE TITLE
Should parsing and building URIs attempt to special case Windows URIs for UNC names?

### ISSUE THREAD

**Issue by ndw** [qt4cg/qtspecs#390]
Depending on the platform and language APIs involved, we see `file:` URIs encoded in a variety of different ways. It doesn't help that there's no official RFC for `file:` URIs.

* `file:/path/part` is a `file:` URI with no host and a path of `/path/part`.
* `file:///path.part` is a `file:` URI with an explicitly empty host and a path of `/path/part`.
* `file://path/part` is a `file:` URI with an authority of `path` and a path of `/part`. I think one common way to interpret this is as if it was `file:/part`. That is, in `file:` URIs, although a different host is possible, it's often just ignored.
* `c:\path\part` is most usefully interpreted as `file:/c:/path/part`, a `file:` URI with no host and a path of `/c:/path/part`. These are only going to be useful on a Windows system, so it isn't a problem to treat them the same way on all platforms. (Aside: I don't actually know if the path part should be `c:/path/part` instead, but it's currently got the leading slash in `fn:parse-uri()`.)

And then there's this: `file:////name/path/part`.

One interpretation is, "look, we accept `file:/` and `file:///` so let's just accept `file://` and `file://///////`, etc. as the same." And I think that's generally right, with the single special exception of `file:////`. The problem is that on Windows, this is a very common way to encode the URI for a UNC path, that is: `\\name\path\part` which is a Windows UNC path for `\path\part` on a host named `name` (via whatever networking protocol backs UNC).
 
You'd think that this should be `file://name/path/part`, but I think because browsers and maybe other tools just discard the authority part of a `file:` URI (or maybe because these are *paths* in some Windows sense?), that's not how they're encoded.

> Aside: Yes, I'm sure you also see `file:\\\\name\path\part` and `file:c:\path\part` and other forms as well. Those are out of scope, they're simply, flatly, completely wrong. You can't use `\` as a delimiter in a URI. RFC 3986 is authoritative on this point. Step one of dealing with random strings we think should be URIs is replacing all `\` with `/` because RFC 3986.

It's problematic to deal with `file:////` as a special case, but it's also problematic to leave out support for a common pattern on a widely deployed operating system.

Recognizing four slashes after `file:` and treating that specially isn't hard. The hard part is how do we encode this in the map that `fn:parse-uri` produces bearing in mind that the result should round-trip if you push it back through `fn:build-uri`.

Consider `file:////uncname/path/part`

Today, that is parsed as:

```
map {
  "uri": "file:////uncname/path/part",
  "scheme": "file",
  "authority": "uncname",
  "host": "uncname",
  "path": "/path/to/file",
  "path-segments": array { "", "path", "to", "file" }
}
```

and that doesn’t round trip. If you feed that to `fn:build-uri`, you get `file://uncname/path/part` and that absolutely doesn’t mean the same thing on a Windows machine.

We could encode the slashes in the `authority` in which case we also have to encode them in the `host` because in the presence of `host`, the `authority` isn’t used to by `fn:build-uri()`:

```
map {
  "uri": "file:////uncname/path/part",
  "scheme": "file",
  "authority": "////uncname",
  "host": "////uncname",
  "path": "/path/to/file",
  "path-segments": array { "", "path", "to", "file" }
}
```

It kind of works, but it’s really ugly and it means we have a host value that is a complete kludge. It doesn’t match the RFC rules for hostnames at all.

The other option that occurs to me is to add a “unc-path” property to the map:

```
map {
  "unc-path": true(),
  "uri": "file:////uncname/path/part",
  "scheme": "file",
  "authority": "uncname",
  "host": "uncname",
  "path": "/path/to/file",
  "path-segments": array { "", "path", "to", "file" }
}
```

That works but it introduces all sorts of possibilities for incoherent data, such as an `https:` URI with a `unc-path` flag set to `true()`.

What’s the right answer?

1. Ignore the UNC path special case, it’s the users problem to deal with them.
2. Recognize them, encode the details in the `authority` and `host`.
3. Recognize them, use a special property like `unc-path`.
4. Recognize them, and do this other much better idea I have: ________________

**Comment by michaelhkay** [comment]
> It doesn't help that there's no official RFC for file: URIs.

There is now RFC 8089, but it's one of those RFCs that tries to document what's out in the wild rather than force a standard.

> "This document specifies a syntax based on the generic syntax of
>    [[RFC3986](https://datatracker.ietf.org/doc/html/rfc3986)] that is compatible with most existing usages."

But it would be a good idea to follow it where possible.

**Comment by ndw** [comment]
Ah. That's interesting. I'll try to digest what it says about UNC paths. At a glance, it's about as ugly as I thought.

A new "answer 4" occurs to me this morning. A "unc-paths" *option* with values to indicate which URI form(s) are intended to represent UNC paths. On `fn:parse-uri` it says what forms should be recognized as UNC paths and parsed so that the host name and path are correctly identified. On `fn:build-uri` it indicates how `file:` URIs that include a host component should be constructed.

**Comment by ndw** [comment]
Apparently `file:c:/path/to/file` should be supported.

**Comment by ndw** [comment]
Do we special case this parse:

```json
{
  "uri": "file:c:/path/to/file",
  "scheme": "file",
  "hierarchical": true,
  "path-segments": ["c:", "path", "to", "file"],
  "path": "c:/path/to/file"
}
```
to create `file:c:/...` or do we leave the current rules alone which produces `file://c:/...`?

**Comment by ndw** [comment]
I've got two PRs in flight, so I don't want to edit the specification again. Here's my proposal:

1. Where we check for a DOS/Windows drive letter, `X:`, we also check for `X|`. We normalize `|` to `:` in the segments.
2. We add a `unc-path` property to the `$options` map.

In `fn:parse-uri`, if `unc-path` is true and we get a path that matches `^//[^/].*$`, we assert that it is the `file:` scheme (otherwise it would have no `scheme`). This is the only parsing change, the existing rules do the right thing for paths and hosts.

In `fn:build-uri`, if `unc-path` is true and the `scheme` is `file`, then we begin the URI with `file:////` instead of `file://`.

We could make error conditions for combinations of `unc-path` with schemes that make no sense (such as for `http:` URIs), but I'm not inclined to do so.

**Comment by ChristianGruen** [comment]
> (Aside: I don't actually know if the path part should be `c:/path/part` instead, but it's currently got the leading slash in `fn:parse-uri()`.)

Indeed it should better be `c:/path/part`. If a Windows path starts with a slash, `c:` would be interpreted as path segment and result in an error (as `:` is no valid character in Windows path segments). – Hope this helps.

**Comment by ndw** [comment]
Does the WHAT WG say anything about file URIs? Yes: https://url.spec.whatwg.org/
