### ISSUE TITLE
User-defined functions clashing with constructor functions

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#398]
There is no explicit rule in either XQuery or XSLT that a user-defined function must not clash (in name and arity) with a constructor function for an imported atomic type. It's implicit in the rule that you can't have two conflicting functions in the static context, but it would be helpful to say so explicitly and define an error code.

I have added tests to the XSLT3 and XQuery3 test suites.

See also Saxon bug 5921 - https://saxonica.plan.io/issues/5921

**Comment by ndw** [comment]
Closed by #408
