### ISSUE TITLE
Priorities for type-based patterns

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#400]
XSLT §6.6 currently has a big TODO:

TODO: define default priorities for type patterns, as suggested in https://www.saxonica.com/papers/xmlprague-2020mhk.pdf section 6.5.1

We need to plug this gap. [Note: it's worth reading that cited section as it points out some of the difficulties].

I'm going to suggest an alternative approach. Rather than allocating a numeric priority to patterns such as `record(lat, long)`, we allocate them a relative priority -- called their `selectivity` -- based on the subtype relationship among types. This is a partial ordering. So we extend the rule that currently orders patterns by (1) import precedence, (2) priority, (3) declaration order, to become instead (1) import precedence, (2) selectivity, (3) priority, (4) declaration order.

Type-based patterns (such as `type(xs:integer)`, `record(lat, long)`) are defined to have higher selectivity than any non-type-based pattern; all the latter (that is, all XSLT 3.1 patterns) are defined to have equal selectivity, which means the rules for discriminating among 3.1 patterns are unchanged.

For type-based patterns, we define that a pattern based on type T has higher selectivity than a pattern based on type U if T is a subtype of U. If neither is a subtype of the other, then they have equal selectivity.

The type pattern `type(T)` followed by one or more predicates is deemed to have higher selectivity than type(T) with no predicates, but apart from this, the predicates are ignored. Explicit numeric priorities can be used to define an ordering among type patterns that have the same selectivity.

**Comment by michaelhkay** [comment]
Note that as defined above `match="type(xs:decimal)" priority="1"` wins over `match="type(s:integer)[. gt 100]" priority="2"`, because selectivity trumps priority. We could try to be more subtle: consider explicit priority first, then selectivity, then implicit priority.

**Comment by ndw** [comment]
I think we have to consider explicit priorities first (or something). The example you give is going to be utterly baffling to most users and equally baffling to me 18 months from now when all these details are no longer fresh in my mind.

**Comment by michaelhkay** [comment]
Thanks for that pointer, it's useful.

One of the problems, of course, is that we can't break compatibility (at least not in anything except extreme edge cases).

**Comment by ndw** [comment]
Accepted at [meeting 027](https://qt4cg.org/meeting/minutes/2023/03-21.html#pr-400)

**Comment by ndw** [comment]
Closed by #401
