### ISSUE TITLE
array and map attribute in xsl:iterate and xsl:for-each-group

### ISSUE THREAD

**Issue by innovimax** [qt4cg/qtspecs#418]
It seems there is still some places where we can still spot some remnant peices of attribute array and attribute map in the spec

You can find this sentence at two places

> , or constructed from the expressions in the array or map attributes. 

Also there is some examples 

- Example: Grouping entries in a Map
- Example: Processing an array using xsl:iterate

**Comment by michaelhkay** [comment]
These examples have been corrected but the correction for Example: Processing an array using xsl:iterate is incorrect. It should use `array:members()` rather than `map:pairs()`.
