### ISSUE TITLE
Support standard and user-defined composite values using item type definitions

### ISSUE THREAD

**Issue by rhdunn** [qt4cg/qtspecs#43]
The composite values defined in *4.14.4 Composite Atomic Values* are currently specified as a table. This means that it is not possible for users to define their own properties for custom types. It is also harder for editors/IDEs, or other tools to implement as there is an element of hard-coding the logic.

These could be implemented as a properties/values record associated with the defined type. The values of the record could then be arity-1 functions that are called with the supplied value when accessed via maps. For example, in XQuery:

    declare %composite-values("composite-values") type xs:date external; (: built-in :)
    declare type date-composite-values := record(
        year: fn:year-from-date#1,
        (: ... :)
    );

and XSLT:

    <xsl:item-type name="xs:date" composite-values="date-composite-values"/>
    <xsl:item-type name="date-composite-values" as="record(
        year: fn:year-from-date#1,
        (: ... :)
    )"/>

So `xs:date("1999-10-15")?year` would be evaluated as `date-composite-values?year(xs:date("1999-10-15"))`.

**Comment by rhdunn** [comment]
Note that Composite Atomic Values have been removed from the spec as of the W3C Editor's Draft 12 April 2021 edition. If that section is re-added then this should be considered as an enhancement to that feature.

**Comment by ChristianGruen** [comment]
@rhdunn As Composite Atomic Values have been removed from the spec, I propose to close this issue (feel free to jump in).

**Comment by ndw** [comment]
The CG agreed to close this issue without action at [meeting 066](https://qt4cg.org/meeting/minutes/2024/02-20.html#close-without-action)
