### ISSUE TITLE
xsl:where-populated and table with header

### ISSUE THREAD

**Issue by innovimax** [qt4cg/qtspecs#437]
Dear all,

I just discover the use of xsl:where-populated but was surprised it cover only a narrow use case of single level of wrapping

My use case is about table and I have to wrap thing into a table with header

```xml
<table ... bunch of attributes'
    <thead ....>
    <xsl:for-each ... >
       <tr>  
          <xsl:for-each ... >
              <td>...</td>
         </xsl:for-each>
     </tr>
   </xsl:for-each>
</table>
```

How can I do that with  xsl:where-populated ?

**Comment by michaelhkay** [comment]
Have you looked at the example at

https://www.w3.org/TR/xslt-30/#where-populated-example
