### ISSUE TITLE
What are the "non-whitespace control characters"?

### ISSUE THREAD

**Issue by ndw** [qt4cg/qtspecs#438]
In Section 5, XML Serialization, we find:

>A consequence of this rule is that certain characters MUST be output as character references, to ensure that they survive the round trip through serialization and parsing. Specifically, CR, NEL and LINE SEPARATOR characters in text nodes MUST be output respectively as "&amp;#xD;", "&amp;#x85;", and "&amp;#x2028;", or their equivalents; while CR, NL, TAB, NEL and LINE SEPARATOR characters in attribute nodes MUST be output respectively as "&amp;#xD;", "&amp;#xA;", "&amp;#x9;", "&amp;#x85;", and "&amp;#x2028;", or their equivalents. In addition, the non-whitespace control characters #x1 through #x1F and #x7F through #x9F in text nodes and attribute nodes MUST be output as character references. 
(The reference to "non-whitespace control characters" appears in a few other places as well, but for basically the same purpose.)

But what **are** the "non-whitespace control characters"? The spec doesn't say. I think it means *all* of the C0 and C1 control characters except CR, NL, TAB, and NEL. The fact that vertical tab and line feed might be considered "white space" doesn't really matter anyway since none of the other C0 control characters are allowed in XML 1.0 anyway (encoded or otherwise).

XML 1.0 doesn't actually care about the C1 control characters. There's no reason to encode them, but it does no harm, I suppose. You'd have to encode the C0 and C1 control characters for an XML 1.1 parser, but none of those exist. 

I wonder if it might be a little clearer to say

> A consequence of this rule is that certain characters MUST be output as character references, to ensure that they survive the round trip through serialization and parsing. Specifically, CR, NEL and LINE SEPARATOR characters in text nodes MUST be output respectively as "&amp;#xD;", "&amp;#x85;", and "&amp;#x2028;", or their equivalents; while CR, NL, TAB, NEL and LINE SEPARATOR characters in attribute nodes MUST be output respectively as "&amp;#xD;", "&amp;#xA;", "&amp;#x9;", "&amp;#x85;", and "&amp;#x2028;", or their equivalents. In addition, the other control characters #x1 through #x1F (except  #x9, #xA, and #xD) and #x7F through #x9F (except #x85) in text nodes and attribute nodes MUST be output as character references.

**Comment by michaelhkay** [comment]
Yes, I think that's what it's trying to say. Control characters = C0 + C1, Non-whitespace control characters  = C0 + C1 - x9 - xD - xA.
