### ISSUE TITLE
[XPath] [XQuery] Support RecordTest self references without occurrence indicators

### ISSUE THREAD

**Issue by rhdunn** [qt4cg/qtspecs#44]
This would be useful for defining things like binary trees, where the fields are optional but (if supplied) the values are not. So it is more logical to define them as:

    declare item-type binary-tree as record(
        left? as ..,
        right? as ..,
        value as item()*
    );

**Comment by michaelhkay** [comment]
This was the intent, evidenced by the example

`record(error-code as xs:QName, message as xs:string, cause? as ..)`

but the grammar needs amending to allow it.

**Comment by rhdunn** [comment]
The latest editor's draft resolves this issue by making the occurrence indicator optional in the EBNF grammar.
