### ISSUE TITLE
Support extended dateTime formats of ISO-8601:2019?

### ISSUE THREAD

**Issue by ndw** [qt4cg/qtspecs#448]
The ISO 8601:2019 [standard](https://www.iso.org/obp/ui#iso:std:iso:8601:-2:ed-1:v1:en:term:3.1.1.4) supports extended dateTime formats including support for uncertain or approximate times and new quantifiers. Apparently, the extension are documented in [Extended Date/Time Format (EDTF) Specification](https://www.loc.gov/standards/datetime/) from the US LoC.

**Comment by michaelhkay** [comment]
I would want to see evidence of widespread use of these formats, otherwise it all feels too specialised. I'm not keen on introducing atomic types that aren't supported by XSD, and I'm not keen on debating how arithmetic and comparison should work.

**Comment by duncdrum** [comment]
@michaelhkay they are supported by [marc](https://www.oclc.org/bibformats/en/fixedfield/dates.html) and widely used in the´bibliographic community´

**Comment by michaelhkay** [comment]
It sounds like an opportunity for an EXPath-like function library, not a core language feature.

**Comment by duncdrum** [comment]
Since the xdm types are `following ISO 8601` I don't see why they shouldn't do so here. It ll be very difficult for users to understand why some ISO 8601 dates can use language features and others can't. Standard compliance is desirable in and of itself no?

**Comment by michaelhkay** [comment]
XSD support for ISO 8601 has always been partial. Looking at the 2004 version, for example, we don't support time intervals, ordinal dates, week numbers, leap seconds, recurring time intervals, basic formats, comma as a decimal separator. I don't think it's difficult for users to understand why we don't support all thse features.

**Comment by sydb** [comment]
1. (In response to @ndw initial post) Are the LOC EDTF and 8601:2019 specs sufficiently the same to code to one in the hopes of supporting the other? I have not read through them carefully enough to know either way myself.
2. (In response to @michaelhkay’s caution) While I agree with @duncdrum that support for 8601:2019 would be useful, and have dozens of anecdotal cases myself where the WWP will be using “extended” dates, my instinct is that @michaelhkay’s caution is appropriate on this one. There are a _lot_ of features to 8601:2019 that would require a _lot_ of work, and it is not clear how much benefit the world would see from support for them. (At least, not yet.)

That said, even if the xdm:edtf datatypes did not support comparison or arithmetic (after all, how do you compare an approximate day to an uncertain month?), just simple stuff like
- validating an 8601:2019 expression is syntactically correct,
- having a function that parses the expression and returns a data structure that is, itself, easy to manipulate with Xtoys, and
- based on above function having functions that returned specific bits of the expression

could be enormously helpful.

**Comment by Arithmeticus** [comment]
Ordinarily I would jump on anything that presents a significant breakthrough for scholars who need nuanced dating, e.g., epigraphers and papyrologists. But the most common way those dates would be used--sorting--would be fraught with difficulty. Users would differ on how or whether to calculate a "fulcrum" of an extended dateTime for sorting purposes.

Might I suggest, however, that this is a perfect use case illustrating the benefit of proposed named records, and could be the basis for an example in the specs. A given extended dateTime would naturally decompose into a sequence of object-records ("object-record" here offered as a synonym for "record"), each with constituent object-records. The example doesn't need to be perfect, just illustrative.

The specifics on defining an object-record data structure, parsing a string into it, extracting data, and comparing object-records, are best left to 3rd party libraries. Gotta say, I'm looking forward to writing, or contributing to, such a library.

**Comment by ndw** [comment]
I opened the issue so that we could record the CG position explicitly. Given that it wouldn't fit into the existing XSD `dateTime` data type, adopting it as a new primitive type seems problematic. I'm enthusiastic about the idea of doing just what @Arithmeticus suggests: providing a library that decomposes ISO8601:2019 values into records and implements various sorts of access and comparison functions for them. I am going to try to resist starting a new, fun project in the immediate term, but we shall see. Depends how frustrating work on the ~350 tests that XML Calabash 3.0 is currently failing, I expect.

**Comment by ndw** [comment]
Parsing ISO8601:2019 strings looks like a job for Invisible XML. That generated [some thoughts](https://lists.w3.org/Archives/Public/public-ixml/2023Apr/0018.html).

**Comment by michaelhkay** [comment]
I think the general style of ISO 8601 is that it defines multiple grammars for multiple kinds of value, rather than a single grammar for everything. You have to know what kind of animal you want to parse, rather than leaving it for the parser to work out.

**Comment by ndw** [comment]
Indeed, whether `1934-12` is intended to be December, 1934 or 7:34pm twelve hours away from GMT is probably something you know from context.

**Comment by ndw** [comment]
Right then. I was working from the examples in the LoC document and didn't see that note (if it's present at all).

**Comment by michaelhkay** [comment]
I'm going to propose this for closure. I don't think there is any appetite for extending the set of data types or for defining more arithmetic and comparison operators. As for parsing, we are introducing InvisibleXML as a general solution to handling strings with arbitrary microsyntax.

**Comment by ndw** [comment]
The CG agreed to close this issue without further action at [meeting 070](https://qt4cg.org/meeting/minutes/2024/03-19.html#close-without-action).
