### ISSUE TITLE
Second parameter of fn:sum must be neutral element for +

### ISSUE THREAD

**Issue by ghislainfourny** [qt4cg/qtspecs#45]
Currently fn:sum specifies the intent of the second parameter in a note:

> The second argument allows an appropriate value to be defined to represent the sum of an empty sequence. For example, when summing a sequence of durations it would be appropriate to return a zero-length duration of the appropriate type. This argument is necessary because a system that does dynamic typing cannot distinguish "an empty sequence of integers", for example, from "an empty sequence of durations".

When implementing fn:sum on sequences of billions of items (numerics, or durations, etc), another aspect arises: this second parameter must also be, for this to work and for optimizations to be possible, a neutral element for +.

Indeed, a distributed system like Spark will produce intermediate sums for (possibly empty) subsets, and will naturally use `$zero` for the sum of an empty subset. Intermediate totals are aggregated in a treewise fashion. For the result to be correct, it must be the case that `$zero + $x eq $x` for any item in the sequence provided as the first parameter. It is fully aligned with the idea of the note above, but I would suggest to make this requirement a bit stricter.

**Comment by michaelhkay** [comment]
I think a change here would be backwards-incompatible, given that it's currently quite legitimate to have "()" or "N/A" as the $zero value. (Apparently SQL returns "null" as the sum of an empty sequence, which is pretty bizarre, but that was one of the arguments used to justify the current spec).

**Comment by ghislainfourny** [comment]
Thank you for the context, especially about the SQL side.

Arguably, in the context of SQL where columns are statically typed, having null as the sum of an empty sequence does not preclude from a distributed execution because a distributed implementation is free to internally pick 0 or whichever neutral element fits for the (known) column type (which Spark SQL very probably does as well for DataFrames). The challenge with XQuery (as also formulated in the note in the spec) is that types may not be known statically -- and neither the applicable neutral element -- which is why the second parameter is a crucial hint for a distributed execution.

I do see your point on backwards incompatibility. What would you make of a softer approach of:

- allowing for implementation-defined behavior on requiring `$zero` being a neutral element?

or

- providing a new version of fn:sum with arity 3 where the third parameter is the optional neutral element, its default value for fn:sum#2 is that of the second parameter, or the integer 0 for fn:sum#1?

**Comment by michaelhkay** [comment]
To be honest, I'm not really sure why this is needed. Can't you, for example, return () as the total of any empty sub-partition, and then generate the requested $zero value only for the case where all the partitions have returned ()?

**Comment by ghislainfourny** [comment]
It's mainly because of impedance mismatch. If a system were built from scratch, your suggestion would be very sensible.

However, distributed implementations are typically modular and built on top of an existing parallel data processing framework, such as Spark, which has a specific model and API that sequences of items and XQuery can be mapped to. Spark's fold() function requires the provision of a neutral element, and its main construct, RDDs, cannot have nested empty sequences.

`fold(T zeroValue, scala.Function2<T,T,T> op)`

I hope it helps clarify.

**Comment by michaelhkay** [comment]
Changing the language spec to suit such implementation constraints feels wrong. Why not just define an extension function, or a configuration option to vary the language semantics?

**Comment by ndw** [comment]
The CG agreed to close this issue at [meeting 024](https://qt4cg.org/meeting/minutes/2023/02-28.html#closure)
