### ISSUE TITLE
window: make 'start' and 'when' optional

### ISSUE THREAD

**Issue by benibela** [qt4cg/qtspecs#452]
Every time I use `tumbling window`, I write `start when true()`.    If start would be optional, default to true, that would be easier

**Comment by ChristianGruen** [comment]
+1 The syntax could certainly be simplified.

**Comment by ChristianGruen** [comment]
We often see `when true()` in windows expressions, which I believe we could make optional, too:

```xquery
(: result: 1: 1, 2: 3, 3: 1, 4: 1 :)
for tumbling window $w in (1, 2, 2, 2, 3, 4)
start $s (: when true() :)
end next $e when $e != $s
return head($w) || ': ' || count($w)

(: result: <w>1 2 3</w>, <w>2 3 4</w> :)
for sliding window $w in 1 to 4
start at $s (: when true() :)
only end at $e when $s + 2 = $e
return <w>{ $w }</w>
```

**Comment by ChristianGruen** [comment]
This window expression is already legal in XQuery 3.1:

```xquery
for tumbling window $w in (20 to 40)
start $first when $first mod 3 = 2
return array { $w }
```

With an optional `start` clause, the following equivalent expression will also get legal (see #483):

```xquery
for tumbling window $w in (20 to 40)
end $last when $last mod 3 = 0
return array { $w }
```

**Comment by ChristianGruen** [comment]
Accepted at [meeting 034, 16 May 2023](https://qt4cg.org/meeting/minutes/2023/05-16.html)
