### ISSUE TITLE
Support parsing numeric, alphabetic, and additive number systems.

### ISSUE THREAD

**Issue by rhdunn** [qt4cg/qtspecs#457]
This proposal is based on the work done in https://www.w3.org/TR/css-counter-styles-3/ when defining CSS rules for formatting the numbers in list items.

The idea is to define 3 parsing strategies:
1. `numeric` -- number-like systems such as decimal;
2. `alphabetic` -- alphabetical-like systems such as spreadsheet columns (A, B, ..., Z, AA, AB, ...)
3. `additive` -- systems like roman and hebrew where the symbol represents a fixed value that is added together

Parsing these, we have 3 properties:
1. `system as enum("numeric", "alphabetic", "additive") := "numeric"` -- which of the parsing strategies (number systems) to use;
2. `symbols as xs:string := "0123456789"` -- the list of characters used to represent a digit;
3. `additive-symbols as map(xs:integer, xs:string) := map {}` -- a map of the symbols in an additive system with the corresponding value of that symbol.

Consideration 1 -- Should these also allow any whitespace and optional "+"/"-" symbols like the radix-based parse-integer?

Consideration 2 -- Should we define decimal format options for these, so the decimal format name can format/represent other number systems (binary, hex, hebrew, tamil, roman numerals, etc.). -- Note: this would make `system`, `symbols`, and `additive-symbols` properties of the decimal format object with the above defaults. The formatting would work in the same way as it is defined in the CSS Counter Styles specification.

## Design 1 -- Separate functions
```
fn:parse-numeric-integer($value as xs:string,
                         $symbols as xs:string := "0123456789") as xs:integer

fn:parse-alphabetic-integer($value as xs:string,
                            $symbols as xs:string := "ABCDEFGHIJKLMNOPQRSTUVWXYZ") as xs:integer

fn:parse-additive-integer($value as xs:string,
                          $additive-symbols as map(xs:integer, xs:string)) as xs:integer
```

## Design 2 -- Combined functions
```
fn:parse-integer($value as xs:string,
                 $system as xs:string := "numeric",
                 $symbols as xs:string := "0123456789",
                 $additive-symbols as map(xs:integer, xs:string) := map {}) as xs:integer

fn:parse-integer($value as xs:string,
                 $radix as xs:integer) as xs:integer
```

**Comment by rhdunn** [comment]
Here is a reference XQuery implementation for `fn:parse-numeric-integer`:
```xquery
declare function local:parse-numeric-integer(
  $value as xs:string,
  $symbols as xs:string := "0123456789"
) as item()* {
  let $length := fn:string-length($value)
  let $radix := fn:string-length($symbols)
  let $value := fn:characters($value)
  let $symbols := fn:characters($symbols)
  return local:parse-numeric-integer-impl($value, $symbols, $radix)
};

(: Recursive implementation due to not having while/until and updating variables. :)
declare %private function local:parse-numeric-integer-impl(
  $value as xs:string*,
  $symbols as xs:string*,
  $radix as xs:integer
) as item()* {
  if (empty($value))
  then 0
  else
    let $digit := fn:index-of($symbols, $value[last()]) - 1
    let $rest := fn:trunk($value)
    return $digit + ($radix * local:parse-numeric-integer-impl($rest, $symbols, $radix))
};
```

**Comment by michaelhkay** [comment]
Just because it can be done doesn't mean it should be done... Who needs this?

**Comment by Arithmeticus** [comment]
I am a big fan of such functions. I have written a number of them that are in the TAN library. IMO, this is a job for independent function libraries, not the specs. 

Each numbering tradition has peculiarities. Numeric systems in some contexts may adopt special characters or ligatures. Some cultures drop or add letters from a standard alphabet, or intentionally skip over core letters (e.g., I or J). In so-called additive systems, variations are rich, e.g., whether medial and final forms should have similar or different values, whether geminate number-letters should be counted singularly or double, the order of a given number (e.g., is an alpha to be treated as 1 or 1,000). 

Brokering these decisions should not be put on the shoulders of those trying to implement the core specs.

**Comment by ChristianGruen** [comment]
I tend to agree that the functions seem to be too specific in order to be added to the core functions set.

**Comment by ChristianGruen** [comment]
I’ve assigned »Propose Closing with No Action«, as I think the functionality may be too specific (everyone: please object)

**Comment by ndw** [comment]
The CG agreed to close this issue without action at [meeting 040](https://qt4cg.org/meeting/minutes/2023/06-27.html).
