### ISSUE TITLE
xsl:sequence: @as

### ISSUE THREAD

**Issue by liamquin** [qt4cg/qtspecs#46]
I'd like to see@as on xsl:sequence. That way i can write, e.g.
```
<xsl:function name="dc:slice-count" as="xs:integer">
  <xsl:param name="toast" as="element(toast)" />
  <xsl:for-each select="$toast" as="xs:integer">
    <xsl:sequence select="@cooked-slices + @raw-slices"  as="xs:integer" />
  </xsl:for-each>
</xsl:function>
```
It would be an error for the for-each to have other than exactly one integer as its result, and the same for the `@sequence`. In this simple example there's not much scope for that to happen of course, 

Maybe on anything with a `select`  attribute?

Parenthetically, a context-item attribute on xsl:sequence would obviate the XSLT1-ish xsl:for-each there, although $toast/(@a, @b) => sum() would work as well and be XSLT  3-ish.

**Comment by yamahito** [comment]
Yes please to @as on xsl:sequence.  In fact, I would go so far as saying it ought to be allowed on almost any sequence constructor, e.g. xsl:apply-templates - is that too radical?
> Maybe on anything with a select attribute?

Seems to me that this part would be better implemented in XPath within the select attribute.  Perhaps we could add "as [datatype]" as a suffix to any xpath sequence?

_________________
Tomos Hillman
eXpertML Ltd
+44 7793 242058

**Comment by liamquin** [comment]
let $n as xs:integer := function($input as xs:integer) as xs:integer { $input + 3 }(12) return $n * 2;

**Comment by michaelhkay** [comment]
We have "treat as" and "cast as" in XPath, but neither does exactly the same as the "as" attribute in XSLT (that is, so-called "function coercion"). We could introduce "coerce as" as a third option. But would anyone actually use it?

(I don't know whether "as" on its own would parse OK, it looks as if it would, but I've been wrong before.)

**Comment by ChristianGruen** [comment]
In BaseX, we introduced the keywords `promote to` to make the conversion of function arguments and return values explicit.

**Comment by ChristianGruen** [comment]
The CG agreed to accept the PR at [meeting 085](https://qt4cg.org/meeting/minutes/2024/07-09.html).
