### ISSUE TITLE
Mathematical Operator Symbols

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#460]
Appendix B.3 of the specification proposes a set of non-ASCII symbols that can be used in place of language keywords, for example "∃" for "some" and "∀" for "every".

I haven't detected a great deal of enthusiasm for this idea, and I can see it causing some confusion, partly because Unicode offers such a wide choice of symbols some of which are visually very similar.

I propose retaining a much smaller set of these symbols:

- "÷" (xF7) for "div" because the symbol is widely recognised and "div" here is pretty ugly
 
- "≺" (x227A) and "≻" (x227B) as alternatives to "<" and ">" in all operator symbols (other than XML markup contexts) that use these characters: for readability in contexts, especially XSLT, where the "<" and ">" characters need to be escaped

**Comment by ndw** [comment]
Given ≺" (x227A) and "≻" (x227B) are Unicode "precedes" and "succeeds", the possibility of confusion with preceding and following axes seems a bit troubling to me. I might be happier with xFF1C and xFF1E, the "full-width" less- and greater-than signs.

But I'm not going to block consensus for my opinion.

**Comment by ChristianGruen** [comment]
+1 for "÷", also because it’s included in good old Latin-1. To make it symmetric, we could also allow "×" (xD7) for multiplications.

> Given ≺" (x227A) and "≻" (x227B) are Unicode "precedes" and "succeeds", the possibility of confusion with preceding and following axes seems a bit troubling to me.

That would also have been my concern. Next, the rendering of Non-Latin-1 characters could fail, or be misleading, if an incomplete font is used and if an IDE does not resort to other character sets if a character is not contained in this font.

Related: https://github.com/qt4cg/qtspecs/issues/204

**Comment by michaelhkay** [comment]
Note, §4.8 states

> The semantics of div are defined in [Section 4.2.5 op:numeric-integer-divide ]. The semantics of idiv are defined in [Section 4.2.4 op:numeric-divide ].

This is obviously the wrong way round. The error first appeared in the 3.1 specification.

**Comment by ChristianGruen** [comment]
I have checked the rendering of FF1C with some text editors/viewers on Windows:

![one](https://user-images.githubusercontent.com/196589/235877864-27aff547-56f7-4ded-9fcd-b987f1dc4927.png) ![three](https://user-images.githubusercontent.com/196589/235877867-a22e1ce1-032a-4042-901d-f73db27d84c1.png) ![two](https://user-images.githubusercontent.com/196589/235877870-99a5e7ae-0daa-4a7c-9723-8172336230b9.png)

Maybe it’s one step too far to introduce them in the standard syntax of a programming language. What do others think?

**Comment by ChristianGruen** [comment]
Accepted at [meeting 034, 16 May 2023](https://qt4cg.org/meeting/minutes/2023/05-16.html) (#466).

**Comment by benibela** [comment]
`=!>` is not mentioned in A 3.3

Also, I do not think it makes sense to allow mixing both characters in one operator, like in `＜<`.  It combines the disadvantages of `<<` and `＜＜` without any advantages
