### ISSUE TITLE
map:keys-where: Return Keys That Match a Predicate

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#467]
**Edit, 23/05/17:** Reopened to discuss `map:keys($map, $predicate)` as an alternative.

----

### Motivation

We have `fn:index-where` and `array:index-where` to locate items/members in a sequence/an array that match a specific predicate, and we could introduce an equivalent function for maps. A recent use case can be found in https://github.com/qt4cg/qtspecs/issues/413#issuecomment-1531288167d.

#### Summary

Returns keys of map entries for which the value matches a supplied predicate.

#### Signature

```xquery
map:keys-where(
  $map        as map(*),
  $predicate  as function(item()*) as xs:boolean
) as xs:anyAtomicValue*
```

#### Properties

This function is ·deterministic·, ·context-independent·, and ·focus-independent·.

#### Rules

The function takes any ·map· as its `$map` argument and applies the supplied function to the value of each map entry. The function supplied as `$predicate` takes the value of the corresponding map entry as an argument, and the result is a sequence containing the keys of those entries for which the function returns true.

More formally, the function returns the result of the expression:

```xquery
map:for-each(
  $map,
  function($key, $value) {
    if($predicate($value)) then $key else ()
  }
)
```

#### Examples

```xquery
let $numbers := map { 0: 'zero', 1: 'one', 2: 'two', 3: 'three' }
return map:keys-where($numbers, function($string) { $string = 'two' })
```

### Comments

* **Edit (2023-05-04):** Renamed from `map:key-where` to `map:keys-where`.
* Similar functions (`index-of`, `index-where`) use the singular form.
* An alternative would be to add an optional `$predicate` function argument to `map:keys`.
* If we decide to introduce a shorter syntax (see [#129](https://github.com/qt4cg/qtspecs/issues/129) and [#436](https://github.com/qt4cg/qtspecs/issues/129)), we could have:

```xquery
map:keys-where($numbers, { . = 'two ' })
```

**Comment by dnovatchev** [comment]
A good one!

I would prefer the name to be in plural:

**_map:keys-where_**

Because this is what the function really produces: a set of keys.

Also, two other related functions returning `xs:boolean` are immediately useful:

   **_map:keys-any_**

and 

   **map:keys-all**
   
These could help us stop the filtering on the first match or mis-match.

**Comment by ChristianGruen** [comment]
> I would prefer the name to be in plural:
> **_map:keys-where_**

True. Probably we shouldn’t rely on inconsistent decisions in the past.

Maybe we should also rename the `index-where` functions to `indexes-where`?

**Comment by ChristianGruen** [comment]
Added to the spec on May 16.

**Comment by michaelhkay** [comment]
Was there a reason for rejecting the idea of adding a predicate argument to map:keys?,

`map:keys($map, ->{.=2})`

(or whatever syntax we go with for focus functions...)

**Comment by ChristianGruen** [comment]
> Was there a reason for rejecting the idea of adding a predicate argument to map:keys?,

Not really. I mentioned this as an alternative in the initial comment. It was well hidden, and I got no response on that, I sticked with the original proposal.

I’d b

**Comment by ChristianGruen** [comment]
Related: #504
