### ISSUE TITLE
[XPath] [XQuery] Allow argument placeholders on keyword arguments

### ISSUE THREAD

**Issue by rhdunn** [qt4cg/qtspecs#47]
This would allow a user to name the arguments that are used as placeholders, making the code more readable. For example:

    let $pow2 := math:pow(2, y: ?)

### Syntax

This proposal would change `KeywordArgument` from:

    KeywordArgument ::= NCName  ":="  ExprSingle

to:

    KeywordArgument ::= NCName  ":="  Argument

or (using the proposed `:` syntax) to:

    KeywordArgument ::= NCName  ":"  Argument

### Semantics

A function call with N argument placeholders will create an N-arity function. The order of the argument placeholders correspond to the order of the parameters in that new function. Those parameters map to the corresponding parameter in the target (partially applied) function, which can be in a different order, or bind to keys in an options map (in the case of functions like `fn:serialize`). For example:

    math:pow(y: ?, x: ?)

would create a function that calculates `y^x` instead of `x^y` as the arguments are reversed.

**Comment by michaelhkay** [comment]
I'm finding all the new stuff with keyword arguments pretty over-complex already, once you start working out all the detailed rules and test cases, and my instinct is that we've already gone overboard in the design, I would prefer to rein it back a bit rather than going even further.

**Comment by rhdunn** [comment]
That makes sense. This possibility came up when I was implementing parser support for `KeywordArgument`.

**Comment by rhdunn** [comment]
While writing things like `function($y, $x){math:pow($x, $y)}` is possible, I was thinking of possible use cases around bounded variadic functions -- that is where I could see this having more value. That is, instead of writing something like:

    f(?, (), (), ?)

or:

    ->($a, $b) { f($a, collation: $b) }

you could express it more cleanly as:

    f(?, collation: ?)

Here, it is clear that you are setting the collation as the second parameter, and can avoid issues where you have the wrong number of defaulted parameters and end up setting the wrong parameter.

**Comment by michaelhkay** [comment]
The current specification implements this feature so I am closing the issue.
