### ISSUE TITLE
fn:deep-equal: Input order

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#479]
#383 is about the specific order of children of element nodes.

I think we should also provide an option to ignore the top-level order of the input items:

```xquery
(: returns true: both input arguments contain the same items, but in a different order :)
deep-equal(
  (1 to 10),
  reverse(1 to 10),
  map { 'unordered': true() }
)

(: returns false: the compared elements are different :)
deep-equal(
  <a><b/><c/></a>,
  <a><c/><b/></a>,
  map { 'unordered': true() }
)

(: returns false: the second sequence contains duplicates :)
deep-equal(
  (1, 2),
  (2, 1, 1),
  map { 'unordered': true() }
)
```

**Comment by dnovatchev** [comment]
I have nothing against this specific proposal (and indeed the mere fact that the same issue is found and raised again and again shows that we need a more permanent and general, well-known and long-ago accepted solution) but I need to note the following, which applies to any similar case.

We are already causing a lot of harm to the language by not having a **set** datatype. 

Having the **set** datatype would free us from having to think, argue, agree and occupy Spec space whenever we could simply say that we want to have as argument, compare for equality or inclusion, or produce: a **set** (of keys, unordered children elements, attributes, namespace nodes, or whatever else ...).

Significant number of pages (and trees. and reader's time and possible confusion) could be saved.

Asking the readers of the Specs to read this and not telling them simply that "_these are sets_" looks like an abuse of the reader's time and intelligence.

**Comment by michaelhkay** [comment]
@dnovatchev You obviously feel strongly about this, so perhaps you could write a paper indicating the implications of adding sets to the data model: where would they fit in the type hierarchy, what new types would be needed, what functions and operators would be needed to operate on these types, what would the subsumption rules be, etc, etc.

My feeling is that the result would involve at least as much complexity as adding maps or arrays (each of which took about  2 years of WG time). If you think the complexity is less than this, then we can only judge this by seeing a complete proposal for the feature.

**Comment by ChristianGruen** [comment]
@dnovatchev Please note that sets require all entries to be distinct (in contrast to sequences for which the order is ignored).

Maybe we better use the existing issue #34 for further discussion on sets?

**Comment by dnovatchev** [comment]
> @dnovatchev Please note that sets require all entries to be distinct (in contrast to sequences for which the order is ignored).
> 
> Maybe we better use the existing issue #34 for further discussion on sets?

@ChristianGruen Sorry, but the two provided examples have all items in them distinct. Sets of items include sets of **_(item, count)_** and in this way can also represent the case where some items have more than one occurrence.

**Comment by ChristianGruen** [comment]
> @ChristianGruen Sorry, but the two provided examples have all items in them distinct. 

I hoped my description would be self-explanatory; but you're right, it's better to tweak the examples to avoid misunderstandings.

**Comment by michaelhkay** [comment]
I'm wondering whether this might not be done better with a separate function. Perhaps `is-permutation($seq1, $seq2, $comparator)`.

As has been noted elsewhere, deep-equal() is trying to do too many jobs at once, and it would be better to break it up.

However, there's a difficulty: for performance, this should be implemented either by sorting or by computing a hash code, and that's not possible if all we have is a general `$comparator` function that returns true or false.

**Comment by ChristianGruen** [comment]
> However, there's a difficulty: for performance, this should be implemented either by sorting or by computing a hash code, and that's not possible if all we have is a general `$comparator` function that returns true or false.

I think we could let this take care of the implementation, which could optimize comparisons for the most common data types and simple comparators. Next, it's already possible today to write trivial comparisons in plain XPath that won't be optimized by today’s processors.

**Comment by dnovatchev** [comment]
> I'm wondering whether this might not be done better with a separate function. Perhaps `is-permutation($seq1, $seq2, $comparator)`.
> 
> As has been noted elsewhere, deep-equal() is trying to do too many jobs at once, and it would be better to break it up.
> 
> However, there's a difficulty: for performance, this should be implemented either by sorting or by computing a hash code, and that's not possible if all we have is a general `$comparator` function that returns true or false.

Or, if we had the **set** datatype:

```xq
set:equals(set:of($seq1), set:of($seq2))
```

Or even simpler (having implicit conversion:

```xq
set:equals($seq1, $seq2)
```

**Comment by ChristianGruen** [comment]
> So, if we had the **set** datatype:

Let's please discuss this in #34.

**Comment by michaelhkay** [comment]
>It would be a mistake to think of implementation even before having defined the concept of set. Putting the cart before the horse.

Sets in Java work with acceptable efficiency only because every Object must have an `equals()` and a `hashCode()` method. Even then, they work only if users are disciplined in ensuring that these methods obey certain invariants. Do you think we can make sets work without altering the foundations of the data model in a similar way?

**Comment by dnovatchev** [comment]
> > It would be a mistake to think of implementation even before having defined the concept of set. Putting the cart before the horse.
> 
> Sets in Java work with acceptable efficiency only because every Object must have an `equals()` and a `hashCode()` method. Even then, they work only if users are disciplined in ensuring that these methods obey certain invariants. Do you think we can make sets work without altering the foundations of the data model in a similar way?

You already **[proposed that atomic items could have their own properties](https://github.com/qt4cg/qtspecs/issues/463)**, so why not? 

Guid, Hash, own functions  (standard functions taking as 1st argument this item()*), just to name a few.

**Comment by ChristianGruen** [comment]
I think we should include the option in the existing `fn:deep-equals` function, as this will allow us to take advantage of all the other options.
