### ISSUE TITLE
Predeclared namespaces in XQuery

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#485]
XQuery defines that the prefixes xml, xs, xsi, fn, and local are predeclared, and states:

Additional predeclared namespace prefixes may be added to the [statically known namespaces]) by an implementation.

I propose that we add map, array, and math to this list, so that these can be used interoperably without pre-declaring them. It is already permitted for an implementation to do this, but it is not required. The change is backwards compatible, because user-defined namespace declarations override predeclared declarations.

**Comment by ChristianGruen** [comment]
> I propose that we add map, array, and math to this list

+1 …I bet no one will object.

**Comment by michaelhkay** [comment]
Add "err" as well.

**Comment by dnovatchev** [comment]
Maybe also: "**_xhtml_**", "**_svg_**", and "**_mathml_**" ?

**Comment by dnovatchev** [comment]
**Let us do exactly the same in XSLT**, so that we completely eliminate the case when an XPath expression is evaluated in XQuery with no problems, but trying to evaluate the same XPath expression in XSLT raises a undeclared namespace error(s).

**Comment by michaelhkay** [comment]
>Maybe also: "xhtml", "svg", and "mathml" ?

I'm not in favour. I don't think we should be declaring prefixes for namespaces that have no special status in our specifications.

**Comment by dnovatchev** [comment]
> > Let us do exactly the same in XSLT
> 
> There are lots of subtle differences between namespace handling in XSLT and XQuery, so whatever we do, it won't be exactly the same.

Even so, doing something similar still would be very useful and would be overwhelmingly appreciated by the XSLT user-community.

**Comment by ndw** [comment]
The solution to 

> completely eliminate the case when an XPath expression is evaluated in XQuery with no problems, but trying to evaluate the same XPath expression in XSLT raises a undeclared namespace error(s).

is to **declare** the namespaces in your XQuery document. No specification changes required, no additional magic for users to learn.

**Comment by ChristianGruen** [comment]
Accepted at [meeting 034, 16 May 2023](https://qt4cg.org/meeting/minutes/2023/05-16.html) (#487).

**Comment by ChristianGruen** [comment]
What about adding `output` as well? Suggested by Joe: https://xmlcom.slack.com/archives/C01GVC3JLHE/p1690486692861529?thread_ts=1690486692.861529&cid=C01GVC3JLHE
