### ISSUE TITLE
https://qt4cg.org/specifications/xpath-functions-40/Overview-diff.html#func-map-pairs has wrong function syntax order

### ISSUE THREAD

**Issue by martin-honnen** [qt4cg/qtspecs#497]
In https://qt4cg.org/specifications/xpath-functions-40/Overview-diff.html#func-map-pairs the explanation of the new function `map:pairs` is given as:

```
map:for-each($map, ($k, $v) -> {map{"key":$k, "value":$v}})
```

I think the right syntax would be `map:for-each($map, -> ($k, $v) {map{"key":$k, "value":$v}})`.

**Comment by ChristianGruen** [comment]
Hi Martin, the discussion about the alternative syntax of anonymous functions is still ongoing (https://github.com/qt4cg/qtspecs/pull/447).

**Comment by michaelhkay** [comment]
Specifically, note that PR #447 proposes changing the syntax to

`($a, $b) -> {$a + $b}`

and today's discussion suggests that this change is likely to be accepted, subject to detailed technical checking.

I jumped the gun by using the syntax in examples before it was discussed or accepted.

**Comment by michaelhkay** [comment]
The new syntax has now been adopted, so the example that used the new syntax before its formal adoption is now correct. Closing the issue.
