### ISSUE TITLE
Arrow operator: Inline functions without parens

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#513]
See also https://github.com/qt4cg/qtspecs/issues/435#issuecomment-1508228624: If an inline function expression is used as the right-hand operand of the arrow operators, parentheses must be used:

```xquery
(: now :)
$seq => (function($x) { ... })()
(: desirable :)
$seq => function($x) { ... }()
```

This could be changed by adding the `InlineFunctionExpr` to the `ArrowDynamicFunction` rule:

> [115]  SequenceArrowTarget  ::=  "=>" ((ArrowStaticFunction ArgumentList) | (ArrowDynamicFunction PositionalArgumentList))
> [151]  ArrowStaticFunction  ::=  EQName
> [152]  ArrowDynamicFunction  ::=  VarRef | ParenthesizedExpr | `InlineFunctionExpr`
> [142]  ArgumentList  ::=  "(" ((PositionalArguments ("," KeywordArguments)?) | KeywordArguments)? ")"
> [143]  PositionalArgumentList  ::=  "(" PositionalArguments? ")"

It will be best to tackle this after we’ve resolved #503, and we’ll have to check if the simplification doesn’t cause ambiguities.

**Comment by michaelhkay** [comment]
Change accepted and applied.
