### ISSUE TITLE
Add position argument to HOF callbacks

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#516]
The coercion rules now allow a supplied function item to have lower arity than the signature of the declared type; the effect is that the information supplied in the additional arguments is ignored.

One of the intended use cases for this was to allow existing higher-order functions to be extended while retaining backwards compatibility. For example, in `fn:filter`, we can change the required type of the predicate function from `function(item()) as xs:boolean` to `function(item(), xs:positiveInteger) as xs:boolean`, with the second argument supplying the position of the item being tested. A function that isn't interested in the position can just ignore it, so existing calls will continue to work.

I propose that we add a position argument to the callbacks for:

```
fn:filter
fn:for-each
fn:for-each-pair
fn:partition
fn:items-after
fn:items-before
fn:items-starting-where
fn:items-ending-where
array:filter
array:for-each
array:for-each-pair
```

Other candidates include

```
fn:all
fn:some
fn:index-where
array:index-where
```

but I suggest we leave these unless someone can think of a use case.

**Comment by michaelhkay** [comment]
Some of these functions are specified using equivalent implementations that invoke fold-left, which makes it evident that fold-left would also benefit from the extra position argument in the callback function.

**Comment by ChristianGruen** [comment]
We should add `fn:iterate-while` to the list. The following example compares sequences pairwise until a difference is found:

```xquery
let $seq1 := ('a', 'b', '1'), $seq2 := ('a', 'c', '2')
return iterate-while(
  0,
  fn($diff, $pos) { $diff = 0 and $pos <= count($seq1) },
  fn($diff, $pos) { compare($seq1[$pos], $seq2[$pos]) }
)
```

Here’s an equivalent recursive solution:

```xquery
declare function local:cmp($seq1, $seq2) {
  let $item1 := head($seq1), $item2 := head($seq2)
  return if (empty($item1)) then 0 else (
    let $diff := compare($item1, $item2)
    return if ($diff != 0) then $diff else (
      local:cmp(tail($seq1), tail($seq2))
    )
  )
};
```
