### ISSUE TITLE
FO: fn:multi-compose : Evaluate a chain of functions in order

### ISSUE THREAD

**Issue by dnovatchev** [qt4cg/qtspecs#517]
**FO: fn:multi-compose : Evaluate a chain of functions**
=============================================================
As per Wikipedia: 

" In [mathematics](https://en.wikipedia.org/wiki/Mathematics), **function composition** is an operation  ∘  that takes two [functions](https://en.wikipedia.org/wiki/Function_(mathematics)) *f* and *g*, and produces a function 

*h* = *g*  ∘  *f* such that *h*(*x*) = *g*(*f*(*x*)).

In this operation, the function *g* is [applied](https://en.wikipedia.org/wiki/Function_application) to the result of applying the function *f* to *x*. That is, the functions 

*f* : *X* → *Y* and *g* : *Y* → *Z* 

are **composed** to yield a function that maps *x* in [domain](https://en.wikipedia.org/wiki/Domain_of_a_function) *X* to *g*(*f*(*x*)) in [codomain](https://en.wikipedia.org/wiki/Codomain) *Z*.

Intuitively, if *z* is a function of *y*, and *y* is a function of *x*, then *z* is a function of *x*.

The resulting *composite* function is denoted *g* ∘ *f* : *X* → *Z*, defined by:

 (*g* ∘ *f* )(*x*) = *g*(*f*(*x*)) for all *x* in *X*
"
______________________________

In this Proposal we generalize function composition to the case when a sequence of functions are composed together, so that the last one is applied on an argument \$x, then  the last-but-one is applied on the result of this application, and so on … until finally the first function in the sequence is applied on the result produced so far.

This is an effective way of chaining a sequence of functions together, and we don’t need to invent or use any special operators or syntax, but we just pass this sequence of functions as argument to **_fn:multi-compose_**.  
   
**fn:multi-compose := function($funs as function(\*)\*, $x)**
 
**Here is an XPath 3.0 implementation of fn:multi-compose**:  

```xq
let $apply := function($f, $x) {fn:apply($f, [$x])},
    $multi-compose := function($funs as function(*)*, $x)
                  {
                    fold-right($funs, $x, $apply)
                  },
    (: The functions $incr and $times are needed just to show this example :) 
    $incr := function($x) {op("+")(?, $x)},
    $times := function($y) {op("*")(?, $y)}                 
                  
 return
   $multi-compose(($times(5), $incr(1)), 2)
```
  
As wanted, the result of evaluating this is

15: (2 +1) \* 5

## Remarks

1. In this implementation the type of the 2nd (last) argument of **_$multi-compose_** and **_$apply_** is `item()*` (any) and as such it is omitted. In case the function to be applied first, needs  more than one argument, all of its arguments must be presented in the function call as a single sequence , and are passed (in order) as the members of a single array, as already implemented by the standard **[fn:apply](https://www.w3.org/TR/xpath-functions-31/#func-apply)**.

2. It is a dynamic error if any of the function applications produces a result which does not belong to the Domain of the function immediately preceding it in the function sequence.

**Comment by joewiz** [comment]
First, a naming question. Why the "multi-" prefix in "fn:multi-compose" and not just "fn:compose"? 

Second, a function signature/design question: wouldn't (2 + 1) * 5 be more natural to represent in the same left-to-right order as `(2, ($incr(1), $times(5)))`? Is there a reason you have the functions first in *right-to-left* (!?) order, and the input last?

**Comment by dnovatchev** [comment]
@joewiz , Good questions, thanks!

> First, a naming question. Why the "multi-" prefix in "fn:multi-compose" and not just "fn:compose"?

The reason is that people know function composition from Math (and also per the Wikipedia article, cited in this proposal, to involve just two functions:

" In [mathematics](https://en.wikipedia.org/wiki/Mathematics), **function composition** is an operation  ∘  that takes **two** [functions](https://en.wikipedia.org/wiki/Function_(mathematics)) *f* and *g*, and produces a function 

*h* = *g*  ∘  *f* such that *h*(*x*) = *g*(*f*(*x*))"

But what is defined here is a generalization, that allows the composition (chaining) of **any** number of functions.

> 
> Second, a function signature/design question: wouldn't (2 + 1) * 5 be more natural to represent in the same left-to-right order as `(2, ($incr(1), $times(5)))`? Is there a reason you have the functions first in _right-to-left_ (!?) order, and the input last?

I am just following the right-to-left order defined in Math, which is already widely known and accepted by anyone who has finished high school.

We could define _`fn:left-multi-compose`_ if someone really needs it, but let us stick with the real thing.

**Comment by PieterLamers** [comment]
@dnovatchev I concur with Joe on both points.
1. 'compose' in natural language does not infer just two ingredients. 
2. I would certainly expect functions to be applied in sequence, when there are no parentheses. so like | in the linux command line or => in xquery. I don't think there is anything right-to-left: in the mathematics function: there is inside first, then outside. the function has a prefixed label. I did finish high school, but I majored in French linguistics so I may be wrong :-P

**Comment by michaelhkay** [comment]
XBow (https://speakerdeck.com/minuso/shooting-arrows-fast-and-accurately?slide=42) has a combine() function which takes a list of functions and applies them in left-to-right order. It also does mapping (that is it corresponds to `=!>` rather than `=>`. It might be worth asking @line-o for any experience with this functions or alternatives.

left-to-right order certainly seems more natural to me, but then, I'm a programmer and not a mathematician.

**Comment by dnovatchev** [comment]
In response to the request to process the function chain from left to right, here is this:

**fn:chain := function($funs as function(\*)\*, $x)**

```xq
let $apply := function($x, $f) {fn:apply($f, [$x])},
    $chain := function($funs as function(*)*, $x)
                  {
                    fold-left($funs, $x, $apply)
                  },
    (: The functions $incr and $times are needed just to show this example :) 
    $incr := function($x) {op("+")($x, ?)},
    $times := function($y) {op("*")($y,  ?)}                 
                  
 return
   $chain(($times(5), $incr(1)), 2)
```

And as wanted, the result now is:

11: (2 * 5) + 1

**Comment by Arithmeticus** [comment]
Although I like the direction of this proposal, I don't think it's quite complete. What's the full signature of the new function? I see `function($funs as function(*)*, $x)` but I expect something more like `function(functions as function(*)*, item as item()*) as item()*`. Although I can read the XPath definition, it needs to be corroborated against a signature, so we can tell whether the implementation matches the intention.

I agree with other commenters, `multi-` is not needed. "Compose" implies two or more, not merely two.

More work needs to be done on error conditions, e.g., when the output of `f()` does not mesh with the targeted input of `g()`.

Can I suggest a variation of this proposal, where we dispense with the so-called `$x`, make it one-arity, and focus only on the sequence of functions. Under this variation, the signature would be: `fn:compose($functions as function(*)*) as function(*)?`. Given an input sequence `A1(), A2(), ... An()`, the resultant function would have the same arity as `A1()` and the same output signature as `An()`.

As mentioned above, error conditions would need to be thought through. And how output -> input parameter dependencies would work. Best way to do that, IMO, is with some examples, e.g., of some compositions of functions of mixed arities.

**Comment by dnovatchev** [comment]
@Arithmeticus Good observations, Joel, thank you.

> Although I like the direction of this proposal, I don't think it's quite complete. What's the full signature of the new function? I see `function($funs as function(*)*, $x)` but I expect something more like `function(functions as function(*)*, item as item()*) as item()*`.

This **is** intentional in order to keep the signature as short and concise as possible.

Thus I would rather keep the signature as:

**`function($functions as function(*)*,  $arg)`**.

Isn't the type `item()*` exactly the default type when  the type is omitted?


But of course, if somebody strongly insists for making this more <s>unreadable</s> complete, we could have it expanded to:

**`function($functions as function(*)*,  $initial-argument as item()*) as item()*`**


>Although I can read the XPath definition, it needs to be corroborated against a signature, so we can tell whether the implementation matches the intention.

Exactly, non-specified type is any type, ... is `item()*`

> 
> I agree with other commenters, `multi-` is not needed. "Compose" implies two or more, not merely two.

One can see (from my previous comment) that the name used for the left-to-right composition is just **fn:chain**

> 
> More work needs to be done on error conditions, e.g., when the output of `f()` does not mesh with the targeted input of `g()`.
> 

Hmm,,, ?  This was precisely defined, did you read it:

>> 2\. It is a dynamic error if any of the function applications produces a result which does not belong to the Domain of the function immediately preceding it in the function sequence.


> Can I suggest a variation of this proposal, where we dispense with the so-called `$x`, make it one-arity, and focus only on the sequence of functions. Under this variation, the signature would be: `fn:compose($functions as function(*)*) as function(*)?`. Given an input sequence `A1(), A2(), ... An()`, the resultant function would have the same arity as `A1()` and the same output signature as `An()`.

This is a nice suggestion. With the current signature nothing prevents `$x` to be any record (tuple) type, or sequence of values and this  really doesn't limit the arity of `A1`.

> 
> As mentioned above, error conditions would need to be thought through. And how output -> input parameter dependencies would work. Best way to do that, IMO, is with some examples, e.g., of some compositions of functions of mixed arities.

Again right.

**Comment by dnovatchev** [comment]
@Arithmeticus Please, see the just-updated example (and implementation) in the previous comment above.

**Comment by Arithmeticus** [comment]
I'm nudging you @dnovatchev to develop this proposal along a different line of writing. What you're offering is a proposal, but the proposal is, hopefully, aimed at providing some specific changes to the official specs. For that to happen, it needs to be shaped into structured prose that follows the traditional format--i.e., Summary, Signature, Properties, Rules, Notes, and Examples sections--to become an eventual pull request. 

For example, the complex if...then construction of the code needs to be converted into a prose description (to be placed under a prospective Rules section) describing the intent of how conditions are to be handled. That prose description of intent would appear before the code itself, and the two need to corroborate each other.

Also, I would expect that multiple error conditions need to be anticipated, and rules described. 

I am skeptical that we need `$x` and even if it turns out we do, I think participants will have different opinions as to how it should interface with the first function. But for the group to have that discussion, we need prose that follows the model of the specs.

**Comment by dnovatchev** [comment]
> I am skeptical that we need `$x` and even if it turns out we do, I think participants will have different opinions as to how it should interface with the first function

@Arithmeticus 

The signature is clearly specified without any $x parameter. 

`$chain := function($funs as function(*)*) as function(*)`

and then:

```xq
(:   .  .  .  .  .  .  .   :)
 return
  (
   $chain( ($doubleAll, op("+"), $incr(3)))  ( (2, 3) ),
   $chain( (op("+"), $incr(3)))  ( (2, 3) ) ,
   $chain( (sum#1, $incr(3))) ( (2, 3) )
  ) 
```

Where do you see any such parameter/argument being passed to `**$chain`** ? In the example implementation, we can have internally any variable names, and this is just inside the black box.

**Comment by Arithmeticus** [comment]
OK, I thought you were still holding to your original two-arity version, `fn:multi-compose := function($funs as function(*)*, $x)`. 

At this point it's difficult for me to quite understand your intent without some fresh prose that follows the structure of the traditional model used by the FO specs for functions.

**Comment by dnovatchev** [comment]
> OK, I thought you were still holding to your original two-arity version, `fn:multi-compose := function($funs as function(*)*, $x)`.
> 
> At this point it's difficult for me to quite understand your intent without some fresh prose that follows the structure of the traditional model used by the FO specs for functions.

Yes, it would require a little bit more time for me before the final spec-prose can be written.

**Comment by dnovatchev** [comment]
## Update

Here is the implementation of **fn:chain** with 8 examples where the first or following functions in the chain have arity greater than 1, and where the initial argument is a sequence or an array, or just an xs:integer:

```xq
let $apply := function($x, $f) 
               {fn:apply($f, 
                         if(function-arity($f) gt 1) then array{$x} 
                                                     else [$x]) },
    $chain := function($funs as function(*)*) as function(*)
                  {
                    fold-left($funs, ?, $apply)
                  },
    (: The functions $incr and $times are needed just to show this example :) 
    $incr := function($x) {op("+")($x, ?)},
    $times := function($y) {op("*")($y,  ?)},
    $doubleAll := function($nums as xs:numeric*) {$nums ! op("*")(., 2)},
    $range := function($n as xs:integer) {1 to $n}                
                  
 return
  (
   $chain( ($doubleAll, op("+"), $incr(3)))  ( (2, 3) ) || ' = $chain( ($doubleAll, op("+"), $incr(3)))  ( (2, 3) )',
   $chain( ($doubleAll, sum#1, $incr(3)))  ( (2, 3) ) || ' = $chain( ($doubleAll, sum#1, $incr(3)))  ( (2, 3) ) = ',
   $chain( (op("+"), $incr(3)))  ( (2, 3) ) ||  ' = $chain( (op("+"), $incr(3)))  ( (2, 3) )',
   $chain( (sum#1, $incr(3))) ( (2, 3) ) ||  ' = $chain( (sum#1, $incr(3))) ( (2, 3) )',  
   $chain( (array:size#1, $incr(3)) ) ( [1, (), 2, 3] ) || ' = $chain( (array:size#1, $incr(3)) ) ( [1, (), 2, 3] )',  
   $chain( (count#1, $incr(3)) ) ( (1, 2, 3) ) || ' = $chain( (count#1, $incr(3)) ) ( (1, 2, 3) )',  
   $chain( (count#1, $incr(3)) ) ( [1, 2, 3] ) || ' = $chain( (count#1, $incr(3)) ) ( [1, 2, 3] )',
   $chain( ($range, $doubleAll, sum#1) ) (5) || ' = $chain( ($range, $doubleAll, sum#1) ) (5)'
  ) 
```  
  The following correct result is produced:
  
13 = $chain( ($doubleAll, op("+"), $incr(3)))  ( (2, 3) )
13 = $chain( ($doubleAll, sum#1, $incr(3)))  ( (2, 3) ) = 
 8 = $chain( (op("+"), $incr(3)))  ( (2, 3) )
 8 = $chain( (sum#1, $incr(3))) ( (2, 3) )
 7 = $chain( (array:size#1, $incr(3)) ) ( [1, (), 2, 3] )
 6 = $chain( (count#1, $incr(3)) ) ( (1, 2, 3) )
 4 = $chain( (count#1, $incr(3)) ) ( [1, 2, 3] )
30 = $chain( ($range, $doubleAll, sum#1) ) (5)

**Comment by Arithmeticus** [comment]
Here is a practical use case that I think lends support to this proposal. Suppose we have a message and want to know if it contains various phrases that need first to be normalized. We want to do so via a function with the signature `($snippet as xs:string?) as xs:boolean`, indicating whether a normalized form of the snippet is found in `$message`, an in-scope variable to which is bound the message as a string.

The general approach to creating such a function might be:
`function($snippet) { contains($message, normalize-unicode(normalize-space($snippet))) }`

Under the proposal emerging from this issue the same could be tackled in this way:
`compose((normalize-space#1, normalize-unicode#1, contains($message,?)))`

AFAICT arrows, as currently constructed, cannot be used because the second parameter of `contains()` is being targeted.

Some programmers may prefer the syntax of `compose()`, for avoidance of nesting (and so the accumulation of parentheses), and for itemizing the chain of operations from left to right.

**Comment by ChristianGruen** [comment]
I favor the originally proposed right-to-left notation, it feels natural to me for function compositions (here is what Haskell offers: https://tomsmeding.com/blog/haskell/composition).

> AFAICT arrows, as currently constructed, cannot be used because the second parameter of `contains()` is being targeted.

I think so, too. The partial function application needs to be wrapped in parentheses and invoked subsequently:

```xquery
$message
=> normalize-space()
=> normalize-unicode()
=> (contains($message, ?))()
```

+1 for omitting `multi-`, providing the input as the first argument for consistency, and I’m looking forward to the prose version.

**Comment by ChristianGruen** [comment]
Here’s `fn:compose` and the arrow operator in comparison:

```xquery
(: one-liner version: 2 => (op('+'))(1) => (op('*'))(5) :)
let $incr := op("+")
let $times := op("*")
return 2 => $incr(1) => $times(5)

let $incr := function($x) {op("+")(?, $x)}
let $times := function($y) {op("*")(?, $y)}                 
return fn:compose(($times(5), $incr(1)), 2)
```

I think that both can be beneficial.

**Comment by line-o** [comment]
While implementing `xbow:combine`, I found that special care has to be taken when a function returns a sequence of items but the arity of function b can be larger than 1.

In its essence it boils down to the decision to use either `array{ $result }` or `[ head($result), tail($result) ]` before applying the next function. $result is the return value of the previous function call.

```
xbow:combine((function ($from, $to) { $from to $to },  sum#1))((1,2)),
xbow:combine((function ($from, $to) { $from to $to }, function ($a, $b) { $a + $b }))((1,2))
```

All this can be avoided when limiting function combination to functions that accept exactly one (sequence of) item(s).

**Comment by line-o** [comment]
@dnovatchev @michaelhkay I tried to come up with a solution that would work with functions of any arity but when I now looked at it I think it would be better to really set the function signature of the function to functions with arity 1.

```
fn:compose(
  $initial as item()*, 
  (function($argument as item()*) as item()*)*
)
```
- This allows for static checking of all functions in the sequence and greatly reduces edge-cases that need to be handled.
- for functions that return / expect more than one parameter the develop can wrap them accordingly allowing them to choose the appropriate strategy

**Comment by line-o** [comment]
see https://github.com/jpcs/functional.xq#-compose1

**Comment by line-o** [comment]
@dnovatchev In your updated function combination reducer

```
let $apply := function($x, $f) {
  fn:apply($f,
    if (function-arity($f) gt 1) 
    then if (not($x instance of array(*)))
      then array{$x}
      else $x                                                                              
    else [$x]) },
```

You assume a function that returns an array should be passed as the argument list of the following function, if it is of arity greater than 1.
This will fail if the the size of the array does not match the number of expected arguments.

**Comment by ChristianGruen** [comment]
> see https://github.com/jpcs/functional.xq#-compose1

:) John will be amused when spotting `fn:compose`, `fn:identity`, `fn:iterate-while`, `fn:items-before` etc. in the draft.

**Comment by line-o** [comment]
Especially since XQuery now has map-, record- and tuple-types together with good destructuring patterns the (un-)wrapping of functions and their return values should be good enough.

**Comment by dnovatchev** [comment]
To all people who responded: **Thank you!**

- We now have 15 examples covering (hopefully) every aspect of function chaining,

- We have demonstrated power that is greater than using arrows (as for example having functions with more than one arguments that are constructed from the current result in the chain)

 - The new name, **fn:chain**, is both shorter and meaningful.

 - The evaluation is performed from left to right, as people wish. I propose to still have a function **fn:multi-compose** that does the same but in right-to-left order, so that we don't attract the wrath of those of us who are mathematicians.

 - One last change I will make is to have the initial-argument (on which the chain of functions is to be evaluated) be the first (and not last) parameter of the function. This looks more natural. However, I am not sure if this parameter ordering will be better than the current one, where the sequence of functions comes first. I am trying to imagine having **fn:chain** to the right of the **=>**  (fat arrow), and it might be useful to be able to have a dynamically generated sequence of functions to the left of  **=>** . Your opinion on this will be appreciated.

In case I don't get any new feedback on this in the next few days, this will mean that we are probably good to start "writing prose" and prepare a PR.

**Thanks  again, and hoping to hear from you!**

**Comment by joewiz** [comment]
The two proposed functions differ only in the order of functions passed as arguments - left-to-right vs. right-to-left. Are both variants really needed? 

If so, for such closely related functions, they have strikingly different names: compose (for the right-to-left variant) and chain (for the left-to-right). Could they be named in a more parallel fashion? E.g., compose-left/compose-right or chain-left/chain-right; cf. fold-left, fold-right. 

I agree with Christian's suggestion that the initial argument would be better placed first, and with Dimitre's observation that this would facilitate its most likely form of use with arrow operators.

**Comment by dnovatchev** [comment]
> The two proposed functions differ only in the order of functions passed as arguments - left-to-right vs. right-to-left. Are both variants really needed?
> 
> If so, for such closely related functions, they have strikingly different names: compose (for the right-to-left variant) and chain (for the left-to-right). Could they be named in a more parallel fashion? E.g., compose-left/compose-right or chain-left/chain-right; cf. fold-left, fold-right.

@joewiz **`Compose`** has a strict definition in Mathematics, and it would be confusing to diverge from this meaning but preserve the same name.

This is why I have given a totally different (and still precise) name to the left-to-right function.

In a few days I will produce here the final prose for the two functions, And yes, **`fn:chain`** 's definition must be completely symmetrical to the one of **`fn:compose`**, thus the initial argument for function application in the former is at the 2nd (last) place while it is the 1st argument of the former (in its final, not yet shown specification).

**Comment by joewiz** [comment]
I look forward to the prose, but I will subject it to the same question: Are both variants really needed? Wouldn't one do?

**Comment by michaelhkay** [comment]
I'm sorry that I haven't been able to keep up with this thread. I've just skimmed through it and I'm afraid I don't have a very clear idea of what is being proposed: so much of the exposition has been in terms of code examples. I'm looking forward to something that gives me the function signature, the rules, and a few easy-to-understand examples.

If some people want left-to-right and others want right-to-left, then the classic committee solution is to provide both, and that's not the right course of action. The right course of action is to analyze the merits of each (e.g. familiarity to different user communities), then take a majority vote or toss a coin.

**Comment by dnovatchev** [comment]
> I'm sorry that I haven't been able to keep up with this thread. I've just skimmed through it and I'm afraid I don't have a very clear idea of what is being proposed: so much of the exposition has been in terms of code examples. I'm looking forward to something that gives me the function signature, the rules, and a few easy-to-understand examples.
> 
> If some people want left-to-right and others want right-to-left, then the classic committee solution is to provide both, and that's not the right course of action. The right course of action is to analyze the merits of each (e.g. familiarity to different user communities), then take a majority vote or toss a coin.

@michaelhkay Here is the latest update. Please, ask any questions you might have, and this would help improve the description:

The proposed function is **`fn:chain`** with this signature:

**`function($x as item()*, $funs as function(*)*) as item()*`**

The first function in `$funcs` (if such exists) is applied on the provided `$x`, then the next function in `$funcs` (if such exists), is applied on the result, and so on... finally the last function in `$funcs`  is applied on the current-result obtained so far, and the result of this final function application is the result of calling `fn:chain($x, $funcs)` .

If the provided argument `$funcs` is the empty sequence, the initial argument `$x` is returned

It is **not** a requirement that every function in **`$funcs`** must have arity of one. In fact, each of these functions can have any arity.

For a function with arity N, greater than 1, the result produced by the application of the previous function must be either a sequence (with **N** items), or, if some of the parameters of the function could be sequence themselves, than an array with **N** items, and each of these **N** items is passed by the implementation in the function call as its corresponding argument.

It is a dynamic error if the current result does not match the arity and the type(s) of the argument(s) of the current function, that is, it is a sequence or an array of M items (`M ne function-arity(current-function)`) or the  items /members of the current result cannot be coerced to the required types of the arguments of the current function.

Here is a successfully running XPath implementation with 15 examples:

```xq
let $apply := function($x, $f) 
               {fn:apply($f, 
                         if(function-arity($f) gt 1) 
                            then if(not($x instance of array(*))) then array{$x}
                                                                  else $x                                                                              
                            else [$x]) },
    $chain := function($x as item()*, $funs as function(*)*) as item()*
                  {
                    fold-left($funs, $x, $apply)
                  },
    (: The functions below: $incr, $times, $doubleAll, and $range, etc... are needed just to show these examples :) 
    $incr := function($x) {op("+")($x, ?)},
    $times := function($y) {op("*")($y,  ?)},
    $doubleAll := function($nums as xs:numeric*) {$nums ! op("*")(., 2)},
    $appendAll := function($strings as xs:string*, $addage as xs:string) {$strings ! concat#2(., $addage)},
    $makeUpperAll := function($strings as xs:string*) {$strings ! upper-case(.)},
    $countAll := function($ar as array(*)) {for $i in 1 to array:size($ar) return count($ar($i))},
    $product3 := function($x, $y, $z) {  $x * $y * $z},
    $range := function($n as xs:integer) {1 to $n}                
                  
 return
  (
   $chain( (2, 3), ($doubleAll, op("+"), $incr(3))) || ' = $chain( (2, 3), ($doubleAll, op("+"), $incr(3)))',
   $chain( (2, 3), ($doubleAll, sum#1, $incr(3))) || ' = $chain( (2, 3), ($doubleAll, sum#1, $incr(3)))',
   $chain( (2, 3), (op("+"), $incr(3))) || ' = $chain( (2, 3), (op("+"), $incr(3)))',
   $chain( (2, 3), (sum#1, $incr(3))) || ' = $chain( (2, 3), (sum#1, $incr(3)))',
   $chain( [1, (), 2, 3], (array:size#1, $incr(3)) ) || ' = $chain( [1, (), 2, 3], (array:size#1, $incr(3)) )',
   $chain(  (1, 2, 3), (count#1, $incr(3)) ) || ' = $chain(  (1, 2, 3), (count#1, $incr(3)) )',
   $chain(  [1, 2, 3], (count#1, $incr(3)) ) || ' = $chain(  [1, 2, 3], (count#1, $incr(3)) )',
   $chain( 5, ($range, $doubleAll, sum#1) ) || ' = $chain( 5, ($range, $doubleAll, sum#1) )',
   $chain( 2, ($range, $doubleAll, op("*")) ) || ' = $chain( 2, ($range, $doubleAll, op("*")) )',
   $chain( [(1,2,3), ()], ($countAll, op("+")) ) || ' = $chain( [(1,2,3), ()], ($countAll, op("+")) )',
   $chain( [(1,2,3), (), (5, 6)], ($countAll, sum#1) ) || ' = $chain( [(1,2,3), (), (5, 6)], ($countAll, sum#1) )',
   $chain( [(1,2,3), (), (5, 6)], ($countAll, $product3) ) || ' = $chain( [(1,2,3), (), (5, 6)], ($countAll, $product3) )',
   $chain( "abra cadabra", (tokenize#2(?, " "), string-join#2(?, "+")) ) 
                                           || ' = $chain( "abra cadabra", (tokenize#2(?, " "), string-join#2(?, "+")) )',
   $chain( "The cat sat on the mat", (tokenize#2(?, " "),  $appendAll(?, "."), $makeUpperAll, string-join#2(?, " ") )  )
   || ' = $chain( "The cat sat on the mat", (tokenize#2(?, " "),  $appendAll(?, "."), $makeUpperAll, string-join#2(?, " ") )  )',
   
   $chain(   (          
               $chain( ("A    long   message   ", "   long "), (head#1, normalize-space#1, normalize-unicode#1) ),
               $chain( ("A    long   message   ", "   long "),  (tail#1, normalize-space#1, normalize-unicode#1) )
              ),
              (contains#2)
         )
   )
```

The correct results produced are:

13 = $chain( (2, 3), ($doubleAll, op("+"), $incr(3)))
13 = $chain( (2, 3), ($doubleAll, sum#1, $incr(3)))
8 = $chain( (2, 3), (op("+"), $incr(3)))
8 = $chain( (2, 3), (sum#1, $incr(3)))
7 = $chain( [1, (), 2, 3], (array:size#1, $incr(3)) )
6 = $chain(  (1, 2, 3), (count#1, $incr(3)) )
4 = $chain(  [1, 2, 3], (count#1, $incr(3)) )
30 = $chain( 5, ($range, $doubleAll, sum#1) )
8 = $chain( 2, ($range, $doubleAll, op("*")) )
3 = $chain( [(1,2,3), ()], ($countAll, op("+")) )
5 = $chain( [(1,2,3), (), (5, 6)], ($countAll, sum#1) )
0 = $chain( [(1,2,3), (), (5, 6)], ($countAll, $product3) )
abra+cadabra = $chain( "abra cadabra", (tokenize#2(?, " "), string-join#2(?, "+")) )
THE. CAT. SAT. ON. THE. MAT. = $chain( "The cat sat on the mat", (tokenize#2(?, " "),  $appendAll(?, "."), $makeUpperAll, string-join#2(?, " ") )  )
true

**Comment by dnovatchev** [comment]
To all  people who suggested we need just one chaining function:

   Yes, I agree with you folks!

Let's not talk about anything like `fn:compose` or `fn:chain-from-right`.

Though, the implementation of such a function is a trivial mirror-reflection of the implementation of **fn:chain**, so if people  really need it we can provide it immediately.

**Comment by michaelhkay** [comment]
Thanks. I think we're getting there.

I feel that the proposed handling of arity>1 functions is going to be rather confusing and error-prone, for example if the signature of a function changes to allow a sequence of items instead of a single item, then calls on chain() can become broken, but that should be a compatible change.

I'm wondering if it would be possible to tackle this by explicitly wrapping an arity>1 function in an adapter to make it usable in a chain. For example if function F returns a sequence of two numbers, and we want to pass this result to op('+') which expects two numeric arguments, then we wrap `op('+')` as `accept-sequence(op('+'))`. The `accept-sequence()` function takes a function expecting N arguments of type`item()` and returns an equivalent function that expects one argument that is a sequence of length N. Similarly `accept-array()` would do the same, but return a function that expects one argument that is an array of length N.

So accept-array() turns any arity-N function into an arity-1 function, which seems a generally useful capability; and chain() then only needs to deal with arity-1 functions.

We could consider accept-map() as well, with the map entries setting parameters by name... (Or am I getting carried away?)

**Comment by dnovatchev** [comment]
> Thanks. I think we're getting there.
> 
> I feel that the proposed handling of arity>1 functions is going to be rather confusing and error-prone, for example if the signature of a function changes to allow a sequence of items instead of a single item, then calls on chain() can become broken, but that should be a compatible change.

A sequence or an item -- that is still the same arity of 1. There should not be any error as the current single-item argument will be interpreted as a sequence that happens to contain just one item.

There will be an error if the arity of the function is changed, but if we reference it like `functionName#2` and such overload still exists, there will be no error.

> 
> I'm wondering if it would be possible to tackle this by explicitly wrapping an arity>1 function in an adapter to make it usable in a chain. For example if function F returns a sequence of two numbers, and we want to pass this result to op('+') which expects two numeric arguments, then we wrap `op('+')` as `accept-sequence(op('+'))`. The `accept-sequence()` function takes a function expecting N arguments of type`item()` and returns an equivalent function that expects one argument that is a sequence of length N. Similarly `accept-array()` would do the same, but return a function that expects one argument that is an array of length N.
> 
> So accept-array() turns any arity-N function into an arity-1 function, which seems a generally useful capability; and chain() then only needs to deal with arity-1 functions.
> 
> We could consider accept-map() as well, with the map entries setting parameters by name... (Or am I getting carried away?)

I definitely think it will be useful to further discuss these adaptors. But this is what is currently being done inside the function `$apply` inside my implementation.  The fewer (internal) moving parts the user sees, the better.

**Comment by line-o** [comment]
@michaelhkay This was also my line of thinking (and I also got carried away)!
With keyword arguments and tuples we could get a really nice adaptor - a new version of `fn:apply` even.
`fn:apply-record($fn as function(*), $arguments as record(*))` where positional arguments would be handed over as the "rest" in a record where as keywords would be named values.

**Comment by dnovatchev** [comment]
> @michaelhkay This was also my line of thinking (and I also got carried away)! With keyword arguments and record types we could get a really nice adaptor - a new version of `fn:apply` even. `fn:apply-record($fn as function(*), $arguments as record(*))` where positional arguments would be handed over as the "rest" in a record where as keywords would be named values.

@line-o Yes, since the time we established  named reference and defaults for arguments in function calls, I have been raising the issue that the existing **fn:apply** needs to be extended to reflect these new capabilities.
