### ISSUE TITLE
Allow record(*) based RecordTests

### ISSUE THREAD

**Issue by rhdunn** [qt4cg/qtspecs#52]
The other ItemTypes that support specifying information about the type allow `type(*)` to represent any instance of the type. The new RecordTest ItemType should support this.

### Syntax

The:

    RecordTest ::= "record"  "("  FieldDeclaration  (","  FieldDeclaration)*  ExtensibleFlag?  ")"

symbol should be changed to:

    RecordTest ::= AnyRecordTest | TypedRecordTest
    AnyRecordTest ::= "record"  "("  "*"  ")"
    TypedRecordTest ::= "record"  "("  FieldDeclaration  (","  FieldDeclaration)*  ExtensibleFlag?  ")"

__NOTE:__ This follows the structure of the other any/typed tests (e.g. `MapTest`).

### Semantics

The `record(*)` item type test is equivalent to `map(*)`.

**Comment by michaelhkay** [comment]
I'm not sure I see much value in this - why do we need another way of saying "any map"?.  To make the proposal complete you need to describe the effect on the subsumption rules.

If you want to extend the syntax to cover boundary cases and be fully orthogonal, then you should also consider `record()`, a type that only matches an empty map.

**Comment by rhdunn** [comment]
The value here is consistency with the other types in the language, which helps users that are used to `array(*)` and `map(*)` where they would reasonably expect `record(*)` to also be valid. -- Especially if you are used to using `record` for map types instead of `map`.

**Comment by michaelhkay** [comment]
In order to get a decision on this, I'm going to propose closing with no action. I can see the argument in favour, but I think it's likely to cause confusion. The item type record(*) would be 100% identical to map(*) in its behaviour, and I don't think it's a good idea to have two ways of saying the same thing that look different but aren't.

**Comment by ndw** [comment]
@rhdunn asked for discussion of this issue before closing it, so I've removed the Propose Closing with No Action and given myself an action item to schedule time for that discussion in some future meeting.

**Comment by rhdunn** [comment]
From a question/discussion on slack, it was asked about defining the types of any field in a record like TypeScript's `{ [name: string]: SimpleType }`. This is similar to the TypedMapTest and could be useful to keep the syntax consistent.

This brings up the following questions:
1. how do you specify the type of the key values, like you can in typed map tests;
2. how do you specify the type of the extension field `*`.

To address these, I propose the following changes to the current syntax w.r.t. extensible fields:
1. allowing `record(*)` to be equivalent to `map(*)` -- w.r.t. records, this is defining a record with only an extensible field specifier;
2. allowing the extensible field specifier to take a type -- e.g. `* as xs:integer`;
3. allowing `record(* as SequenceType)` equivalent to `map(item(), SequenceType)` -- i.e. the extensible field flag is similar to other fields;
4. allowing the extensible field flag to appear anywhere in the declaration -- there isn't really a valid reason why it has to be at the end, and doing this simplifies the grammar (with the addition of an extra grammatical constraint to ensure there is only one extensible field).

I also propose an optional `ItemType ":"` at the start of the record to specify the key type, e.g. `record(xs:string : * as xs:anyAtomicType)` would be how to define the TypeScript example. Note that this is equivalent to the typed map test, so record tests are therefore a superset of map types. This makes it possible for a user to only use the record test in code when specifying types.

## Proposed Grammar
```
RecordTest ::= "record" "(" KeyType? FieldDeclaration ("," FieldDeclaration)* ")" 
KeyType ::= ItemType ":"
FieldDeclaration ::= NamedFieldDeclaration | AnyFieldDeclaration
NamedFieldDeclaration ::= FieldName "?"? ("as" (SequenceType | SelfReference))?
AnyFieldDeclaration ::= "*" ("as" SequenceType)?
FieldName ::= NCName | StringLiteral
SelfReference ::= ".." OccurrenceIndicator?
```

Note: `FieldName` and `SelfReference` are unmodified, and `NamedFieldDeclaration` is the same as the current `FieldDeclaration`.

**Comment by ndw** [comment]
The CG agreed to allow `record(*)` at [meeting 046](https://qt4cg.org/meeting/minutes/2023/09-19.html).
