### ISSUE TITLE
Dealing with component name conflicts with library packages

### ISSUE THREAD

**Issue by maxtoroq** [qt4cg/qtspecs#523]
## Override with visibility='hidden'

```xml
<override>
   <template name='foo' visibility='hidden'/>
</override>
```

This change allows the using package to override a component without running into a potential naming conflict with another component in the using package or in another used package. Because the visibility is hidden, the component is not invokable from the using package.

## Accept with alias

```xml
<accept component='template' names='foo' aliases='fu'/>
```

This change allows the using package to accept components but with a different name.

**Comment by maxtoroq** [comment]
If you must override a component **you are forced** to create a local component with the same name, and that name might already be used by your package or another library package. In the example I originally provided I used an empty template, and perhaps that was a little confusing because in reality you wouldn't use an empty template. This covers the case where you don't need to call the overriding component, only provide an implementation, which I believe is the most common case.

About the motivation for aliasing, avoiding the "middleman" package would be one. Another is using less qualified names. To write a reusable package you have to use qualified names for everything to avoid conflicts, and even that doesn't work if you want to use the same package twice. If the user has a way to handle conflicts then you could write `csv-parse` instead of `csv:parse`, or `acos` instead of `math:acos`.

**Comment by michaelhkay** [comment]
I would really like to avoid introducing extra complexity in this area: the packages feature in 3.0 has not been a great success story, and I don't think that adding extra bells and whistles is going to change this. I propose closing with no action.

**Comment by ndw** [comment]
The CG agreed to close this issue without further action at [meeting 103](https://qt4cg.org/meeting/minutes/2024/12-17.html).
