### ISSUE TITLE
fn:elements-to-maps (before: Review of the fn:json() function)

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#528]
I've been writing tests for the fn:json function, whose spec I haven't read for quite a while, so it's an opportunity (a) to request WG review of the spec, and (b) for some minor comments.

1. I think a better name for the function might be `fn:to-json`. Any other suggestions?
2. Where we specify that a JSON object should be output with particular properties, I think we should be consistent about whether or not we prescribe the order. Writing tests is a lot easier if the order is always prescribed!
3. Document nodes: it would be better to output both the document URI and the base URI where available.
4. Under "The children of the element are processed as follows" there are four rules. In the case where an element has just one element node child, I think rule 4 should apply rather than rule 3.
5. Under Processing-Instruction nodes: typo "A JSON object with a two properties".
6. The section starting "Strings are escaped as follows" should be promoted up a level.
7. Representing functions: I propose a different set of rules. (a) for a function that is a reference to a built-in or user-defined function definition, output "Q{uri}local#arity". (b) for an anonymous function, output "#anonymous-function". The rationale is that the JSON output here isn't going to be useful except as a placeholder to indicate that a function item is present.
8. We might want to be more prescriptive about how numbers are formatted (or to provide user options)
9. Like many XML-to-JSON libraries, there's the problem that two instances of the same element type might be output very differently depending on which children are present. For example the representation of a book with two authors might be very different from a book with one author. I would suggest that rather than the boolean `element-map` option, we allow the options to include a list of element names for which `object` representation rather than `array` representation is to be used.

**Comment by ChristianGruen** [comment]
Pull request: #529.
Related (serialization; `fn:xdm-to-json` vs. `fn:items-to-json` vs. `fn:element-to-map`): #576.

**Comment by ChristianGruen** [comment]
I’ve given some feedback on the proposal in the PR (https://github.com/qt4cg/qtspecs/pull/529#issuecomment-1765060154).
