### ISSUE TITLE
[XPath] [XQuery] Keyword arguments don't work with all parameters/keys in static functions.

### ISSUE THREAD

**Issue by rhdunn** [qt4cg/qtspecs#54]
The KeywordArgument symbol restricts the argument name to an NCName. This has two issues:
1. for non-variadic and bounded-variadic functions, a parameter can be a QName, so may be in a different namespace, or there can be ambiguity if there are multiple parameters with the same local-name in different namespaces;
2. for map-variadic functions, a parameter key can contain spaces, so cannot be expressed as an NCName.

### Syntax
    KeywordArgument ::= KeywordArgumentName  ":"  ExprSingle
    KeywordArgumentName ::= EQName | StringLiteral

__NOTE:__ I'm using the favoured map-based syntax here. If that is not used, then the `":"` should be `":="` as it is in the current draft.

### Semantics
For non-variadic and bounded-variadic functions, a KeywordArgumentName is matched as follows:
1. An *EQName* matches against the expanded QName of the parameter;
1. A *StringLiteral* is cast to an NCName (with an XPTY0004 error if it is not a valid NCName), which is in no namespace (like other variables such as VarName symbols); the resulting expanded QName then matches against the expanded QName of the parameter.

For map-variadic functions, a KeywordArgumentName is matched as follows:
1. An *NCName* uses the local-name as the key in the constructed map cast to the key type of the map. This follows the XQFO casting rules with the source type of the local-name being `xs:NCName` and the target type being the map's key type.;
2. A *QName* or *URIQualifiedName* results in an XPTY0004 error as it does not form a valid key name;
3. A *StringLiteral* uses the value of the string as the key in the constructed map.

**Comment by rhdunn** [comment]
The intention behind:
> An NCName uses the local-name as the key in the constructed map;

is for the local name to be converted to the key type, so I've edited the description of this issue from that to:
> An NCName uses the local-name as the key in the constructed map cast to the key type of the map. This follows the XQFO casting rules with the source type of the local-name being xs:NCName and the target type being the map's key type.;

Note: The intention here is to support the cases where the local name is castable to the map's key type. In the case of the map key being an xs:string, this would be a simple upcast per "19.3.2 Casting from derived types to parent types" of the XQFO specification.

**Comment by michaelhkay** [comment]
The current specification allows the keyword to be an EQName, so I am closing this issue.
