### ISSUE TITLE
Space separation in lambda expressions

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#548]
Currently the expression `$a -> {$a+1}` requires a space before the arrow, because the hyphen is otherwise tokenized as part of the variable name.

Not only is this a very easy trap to fall into, it also tends to result in poor diagnostics because we're in lookahead territory where we are also considering an alternative parse along the lines `$a- > EXPR` (where the variable name is `a-`), and this parse only gets disqualified because an expression can't begin with `{`.  

If we later introduce expressions that start with `{`, writing `$a->{3}` with no space would no longer be an error, it would just mean something completely different from what you intended.

One solution, not a very pretty one, is to require parentheses around the argument list even when there is only a single argument. Almost as inconvenient as requiring the space, but with better diagnostics if you forget.

Another solution might be to restrict the parameter name so it can't contain a hyphen. The problem with that is that the tokenization becomes sensitive to the grammatical context, which is not totally unexplored territory, but complicates the fact that we're already in lookahead territory where we are looking at alternative parses. (The Saxon implementation already does the lookahead by retokenizing, so it's not impossible.)

Would it be too horrendous to contemplate a backwards-incompatible change to say variable names cannot end in a hyphen, anywhere? Perhaps with a mode bit for compatibility? After all, all this complication is caused by the need to cater for something which no sane user ever does.

**Comment by ndw** [comment]
Just to start the ball rolling, I'll be the guy who comes down on the side of favoring a more verbose syntax. I actually don't think requiring parens is at all unreasonable: `($a) -> {$a+1}`

**Comment by ChristianGruen** [comment]
+1 for making parens obligatory.

**Comment by yamahito** [comment]
It may not be pretty (although I don't feel it's particularly *ugly*), but the parentheses is not only unambiguous for the parser, but also makes the intention easier to read for the user, and involves removing a special case, rather than adding one.

**Comment by pgfearo** [comment]
My proposal would be to avoid use of the `-` character in `->` and find a reasonable alternative character that is easily recognised and does not cause ambiguity for a tokeniser.

Thus, I would suggest using `+>`, allowing us to use the expression `$a+>$a+1`

With syntax-highlighting and with/without brackets and surrounding space characters:

<img width="266" alt="Screenshot 2023-06-13 at 16 16 42" src="https://github.com/qt4cg/qtspecs/assets/2734234/e2ab099f-89a2-45f7-a84e-bbabe0fb6344">

---
It would be difficult to call this a 'thin arrow operator' though, so we would need an alternative. PHP has a 'spaceship operator'...

**Comment by benibela** [comment]
>My proposal would be to avoid use of the - character in -> and find a reasonable alternative character that is easily recognised and does not cause ambiguity for a tokeniser.


How about `=>` ?

**Comment by michaelhkay** [comment]
A lot of the justification for the choice of syntax was similarity to other languages. C/C#/Java use -> or => in a very similar way. If we have to deviate from that we could always go back to `->($a){$a+1}`.

The name "thin arrow" is no longer used.

The symbol `=>` conflicts with the existing use of that symbol in 3.1.

For the record, `~>` was also suggested on Slack.

I'm inclined to think that the least bad option is to make the params mandatory. As @yamahito suggests, solving a problem by removing a special case has some appeal.

**Comment by benibela** [comment]
>The symbol => conflicts with the existing use of that symbol in 3.1.

Not if followed by {

3.1 does not allow => {

**Comment by michaelhkay** [comment]
Yes but `$input => tail() => ($a => {$a, 1})() => count()` would be terribly confusing.

**Comment by benibela** [comment]
> Yes but $input => tail() => ($a => {$a, 1})() => count() would be terribly confusing.

more than

    $input => tail() => (($a) -> {$a, 1})() => count() 
   
?

>Also, we've been trying to avoid getting into a situation where we can never have an expression that starts with "{".

Expressions do not matter for =>

It is 

  | ArrowFunctionSpecifier | ::= | EQName  \|  VarRef  \|  ParenthesizedExpr
-- | -- | -- | --


[ArrowFunctionSpecifier](https://www.w3.org/TR/2017/REC-xquery-31-20170321/#prod-xquery31-ArrowFunctionSpecifier) 	   ::=    	[EQName](https://www.w3.org/TR/2017/REC-xquery-31-20170321/#doc-xquery31-EQName) | [VarRef](https://www.w3.org/TR/2017/REC-xquery-31-20170321/#doc-xquery31-VarRef) | [ParenthesizedExpr](https://www.w3.org/TR/2017/REC-xquery-31-20170321/#doc-xquery31-ParenthesizedExpr)

Even if there were an expression starting with {..., it would need to be written as `=> ({...)`

**Comment by michaelhkay** [comment]
An intriguing possibility would be to drop the arrow entirely:

`($a){$a+1}`

**Comment by ndw** [comment]
Seems awfully confusing to me.

**Comment by Arithmeticus** [comment]
At this point we're simply dropping the `function` in `function($a){$a+1}`, at which point I have to ask how much more convenience than confusion an abbreviated lambda syntax provides.

(For reference, because it took me a while to find it, here's the [current spec on lambda expressions](https://qt4cg.org/specifications/xquery-40/xpath-40-diff.html#id-lambda-expressions).)

**Comment by ChristianGruen** [comment]
> An intriguing possibility would be to drop the arrow entirely:
> 
> `($a){$a+1}`

I concur with others that this might be too cryptic. Instead, I would still be in favor to have `fn` or `f` as a plain alias for `function` (and optionally drop the thin arrow syntax), simply because function items and declarations can get so frequent:

```
fn($a) { $a + 1 }
fn { . + 1 }
```

**Comment by Arithmeticus** [comment]
I like @ChristianGruen 's suggestion, and think we could simply incorporate 4.4.2.6 into 4.4.2.4, dropping lambda functions as a separate category. IMO, the XPath Inline Function Expression **is** a lambda function, albeit with slightly different syntax. Honestly, I wish the lambda expressions I've encountered in C# looked more like the XPath inline functions.

**Comment by ChristianGruen** [comment]
#550 was merged.
