### ISSUE TITLE
New function fn:substitute()

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#553]
The discussion on the parse-csv() use cases suggests there would be value in a function

`fn:substitute($value as item()*, $pos as xs:positiveInteger, $mangler as function(item()) as item()) as item()*`

whose effect is to return the input sequence `$value` with the item at position `$pos` replaced by the result of invoking `$mangler` on that item.

This should be aligned with similar functions for maps and arrays.

**Comment by ChristianGruen** [comment]
I think we can close this issue; it’s also listed in #583.

**Comment by ndw** [comment]
At [meeting 075](https://qt4cg.org/meeting/minutes/2024/04-30.html), the CG agreed to close this issue without further action.
