### ISSUE TITLE
The Transitive Closure function produces an incomplete result, completeness/success and number of actual iterations must also be returned

### ISSUE THREAD

**Issue by dnovatchev** [qt4cg/qtspecs#554]
@michaelhkay and CG members,

I initially reopened **[the original issue](https://github.com/qt4cg/qtspecs/issues/518)**, because there is some useful and needed functionality that the PR and the text of the FO specification do not provide, and we missed to discuss this at the June 13th meeting.

**I believe that typically a developer would need to know if the "whole" TC was completely produced, or not, and maybe how many iterations were needed**.

This can be provided if the result of the function was for example:

```xq
map{ 
        "TC" : $thefinalTCNodeset,
        "WasTCComplete": $boolForTCCompletion,
        "NumberOfIterations: $someInteger
       }
 ```
One could argue that if **_`$result? NumberOfIterations < max`_**, then we know that the complete TC was produced and thus we don't need the member "WasTCComplete".

However, this is not the case when **_`$result? NumberOfIterations eq max`_**. In this case both outcomes are possible: the complete TC was produced exactly in `max` iterations (so the value of `"WasTCComplete"`  must be `true()` ), or `max` iterations were performed and the `max + 1`st iteration produced additional nodes -- in this case `"WasTCComplete"` must be `false()`.

**Failure to produce the complete TC in many cases will be regarded as error, and the developer needs to be sure that this was (or this wasn't) the case**.

thus, the current specification of this function needs additional work to accomodate the full needed functionality.

**Comment by dnovatchev** [comment]
Here is the reply to **[this comment](https://github.com/qt4cg/qtspecs/issues/518#issuecomment-1590552398)**, made by @michaelhkay  in the original issue:

> I proposed the addition of this function because I've had to write it myself in half a dozen different applications, so I thought it was worth making it available to everyone. On none of those occasions have I needed any more functionality than the specified function now provides (in fact, I have generally needed less). 

With all due respect, **the functions we add to FO should be useful not just to suit a single user**, who seems content with not getting any information whether or not the creation of the complete TC was successful or not.

>I'd like to see more convincing evidence that extra functionality is truly needed, and that this isn't just feature creep. The proposed additions make the function a lot harder to use in simple cases.

Any developer who is <s>not reckless and uncareful</s> careful and does his job in a responsible manner, wants to know whether or not the requested operation completed successfully. This is the majority of all developers, and thus we have overwhelming examples of "convincing evidence" from the everyday practice of any good developer.

When an operation (like creating a complete transitive closure in a predefined number of iterations) was unsuccessful, silently failing to signal this fact creates a defect, whose root cause can be very challenging to determine thus making the code produce unexpected and unpredictable results, making it difficult to maintain.

> 
> Users after all have the option of writing a transitive closure function themselves if they need something more specialised.

@michaelhkay It seems that you really proposed this function only just for your personal use and not for other users? You seem to have said something like this above...

**Comment by michaelhkay** [comment]
Incidentally, if someone does want to know whether `transitive-closure($f, $max:=$N)` has indeed returned all the nodes in the transitive closure, this is easily discovered by comparing the result with the result of `transitive-closure($f, $max:=$N+1)`. If the results are different (easily tested with the `except` operator) then the search was cut short.

**Comment by Arithmeticus** [comment]
I appreciate the intent behind the request made by @dnovatchev but as a developer, I want the nodeset as direct output. I do not want to have to unpack a map to get the nodeset. If I have delimited the value of `$max` then I have no expectation that the closure will be complete, and the n + 1 method mentioned by @michaelhkay is perfectly handy to check for closure. If I need to know the number of iterations taken, it would be for diagnostics. I would probably use `<xsl:message>` within the `$step` function to do this.

BTW, I don't think the current spec indicates what happens if closure is reached before `$min` is reached. (I'm checking a [commit](https://github.com/qt4cg/qtspecs/pull/521/commits/18b5612ede0f2ff15a1fb51708a0ac730f294333) and I don't see any prose to that effect, but I could be missing it.) Presumably it will exit early, but it would be good to specify that behavior.

**Comment by dnovatchev** [comment]
> Incidentally, if someone does want to know whether `transitive-closure($f, $max:=$N)` has indeed returned all the nodes in the transitive closure, this is easily discovered by comparing the result with the result of `transitive-closure($f, $max:=$N+1)`. If the results are different (easily tested with the `except` operator) then the search was cut short.

This is complete disrespect to the users!

Why should the same opreation be performed twice?

**Comment by dnovatchev** [comment]
> I appreciate the intent behind the request made by @dnovatchev but as a developer, I want the nodeset as direct output. I do not want to have to unpack a map to get the nodeset. If I have delimited the value of `$max` then I have no expectation that the closure will be complete, and the n + 1 method mentioned by @michaelhkay is perfectly handy to check for closure. If I need to know the number of iterations taken, it would be for diagnostics. I would probably use `<xsl:message>` within the `$step` function to do this.
> 
> BTW, I don't think the current spec indicates what happens if closure is reached before `$min` is reached. (I'm checking a [commit](https://github.com/qt4cg/qtspecs/pull/521/commits/18b5612ede0f2ff15a1fb51708a0ac730f294333) and I don't see any prose to that effect, but I could be missing it.) Presumably it will exit early, but it would be good to specify that behavior.

@Arithmeticus (Joel), I understand the limited requirements that the currently specified function implements, and wouldn't mind it at all hadn't this function have the pretentious and misleading name **"transitive-closure"** while in reality its proper name is more matching **"onion-skins-of-transient-closure"**.

Folks, please, do not use misleading, largely-exaggerated and confusing names for the functions you propose!

Seems that in this CG naming is a game and nobody thinks about the user's confusion and loss of trust in the whole set of FO, which is becoming more of a set of chants and magic spells than something resembling a coherent, logical system.

## **Ew....**

**Comment by michaelhkay** [comment]
The naming of functions is always a compromise; you want the name to capture the general intent so that developers can find the function when looking for it and so that readers of code can guess correctly what it does most of the time without turning to the spec; at the same time you can never capture the entire semantics of the function in its name, and it's a mistake to try.

For the transitive-closure function we need to remember that the min and max parameters are optional parameters that modify the core behaviour. There are plenty of other similar examples, for example if you set the `zero` parameter of fn:sum to 42 then the function is no longer computing the mathematical sum of a set of numbers. Yet the name "sum" is still a good name because it reflects the indended and most common use of the function.

But rather than complaining, feel free to suggest a better name.

**Comment by dnovatchev** [comment]
> But rather than complaining, feel free to suggest a better name. Calling it _accrue-iterations-output_ would certainly not meet the objective of (a) helping a developer to find a function in the function library when their requirement is to compute a transitive closure, and (b) helping a reader understand the code.

After considering the meaning and consulting the dictionaries, these look good:

**_fn:transitive-closure-attempt_**

 **_fn:try-get-transitive-closure_**

 **_fn:accumulate-iterations_**.
 
 In .NET the prefix **`try-get`** or, more generally, **_try-someAction_**  is used systematically, for example:

```c# 
 someDictionary.TryGetValue(someKey)
 someDictionary.TryAdd(someKey, someValue)
 someServiceCollection.TryAdd(someServiceDescriptorsCollection)
```

Do note, that all these methods return a **_boolean_** value that indicates  the success or the failure of the attempted operation.

**The creators of these classes did really care for the user** and did not just say: "**Write your own function using _try/catch_**"

**Comment by dnovatchev** [comment]
> I'm trying to understand the problem space. Are none/any/all of the following true?
> 
> 1. If the function did not have min/max parameters it would always compute a true transitive closure.

Not always, because it may continue executing indefinitely.

> 2. The default values for min/max are such that it does compute a true transitive closure

No one knows what the defaults must be. For example, I personally would like to have `min := 0` as default. And, see above, the function may never stop its execution, thus: no, with the default values it masy never stop executing, or may return not the wanted TC (TC+ instead of TC*)

> 3. The ability to specify alternate values for min/max causes the function to behave in a way that isn't exactly transitive clousre because it may return a result before computing the whole transitive closure

Yes, and this is the problem for a caller who really believes, based on the name of the function, that he will get back the TC. Whenever an incomplete TC is returned, the caller is left unaware of this fact.

**Comment by ndw** [comment]
Sorry, I'm still confused.

Isn't "it may continue executing indefinitely" always a possible consequence of attempting to compute a transitive closure? If the step adds a new item each time, the closure will never be complete. That's not a problem with this function per se, is it?

With respect to "no one nows what the defaults must be", as I understand (perhaps misunderstand) the situation:

1. If you don't know the function has min/max arguments, and don't use them, the default values will give you transitive closure, so you'll get what you expected, no?
2. If you encounter an instance of the function with arguments and you don't know what they mean, we have documentation for that. And this isn't a new problem here, consider "string-join($a, $b)". Is that the items of $a interspersed with $b, or the items of $b interspersed with $a? Depending on your experience, you might think it's either. So look it up.

**Comment by dnovatchev** [comment]
> Sorry, I'm still confused.
> 
> Isn't "it may continue executing indefinitely" always a possible consequence of attempting to compute a transitive closure? If the step adds a new item each time, the closure will never be complete. That's not a problem with this function per se, is it?

This is the problem with the developer's code, most probably there was some erroneous act or assumption and the developer needs a way to be informed about this problem, other than being called by a user. In other PLs there is [**TimeoutException**](https://learn.microsoft.com/en-us/dotnet/api/system.timeoutexception?view=net-7.0), but in XPath there is no concept of the flow of time. This is why the next good thing that emulates a timeout is to specify a maximum  iteration count (say 10 000), which if **exceeded** (not just reached) means that maybe our TC might be infinite.

> 
> With respect to "no one nows what the defaults must be", as I understand (perhaps misunderstand) the situation:
> 
> 1. If you don't know the function has min/max arguments, and don't use them, the default values will give you transitive closure, so you'll get what you expected, no?

No, for example  the TC you want is equivalent to **`ancestor-or-self::node()`** but with the default values you get just **`ancestor::node()`**

> 2. If you encounter an instance of the function with arguments and you don't know what they mean, we have documentation for that. And this isn't a new problem here, consider "string-join($a, $b)". Is that the items of $a interspersed with $b, or the items of $b interspersed with $a? Depending on your experience, you might think it's either. So look it up.

I tried, but I still don't understand what this is meant to say...  😞  And this doesn't seem to be a question.

Please, elaborate.

**Comment by dnovatchev** [comment]
> (Note: if we don't think we should use the name "transitive closure" because it's only an engineering approximation, then we probably shouldn't be using the name "function" either, for the same reason...)

No, in this case this is not "an engineering approximation", in fact it is an **arbitrary cut**.

**Comment by dnovatchev** [comment]
> A pedantic name for this might be the _bounded transitive union_ of a function.

I think we need to entirely drop "TC" from the name.

Good names (and 2 functions, not one):

**KleeneStarBounded**

**KleenePlusBounded**

**Comment by Arithmeticus** [comment]
In the interests of moving the conversation along, here are some alternative names that occur to me:

- `fn:recurse-node()`
- `fn:recurse-over-node()`
- `fn:node-recurse()`

Or variations above using `iterate` instead of `recurse`, or pluralize `node`. 

Transitive closure is a rather remote concept from the universes I traverse ("Kleene" is even more remote and obscure), so when this developer asks what I want to do when I want to put a node through a tail-end recursive function to get a full set of nodes, I haven't a clue what the name of the thing is I want to do, and I will browse the list of functions names without presumption. So for all I care, call it `fn:rinse-and-repeat()` or `fn:go-go-go()` -- with enough cross-coverage and examples we'll figure it out. 

Whatever name is chosen, the description should state under what conditions the function can be taken to provide transitive closure.

**Comment by ChristianGruen** [comment]
I’ve assigned the »Discussion« label, as there seems to be no consensus yet on how to proceed.
