### ISSUE TITLE
Allow item-type to be matched within its definition scope

### ISSUE THREAD

**Issue by rhdunn** [qt4cg/qtspecs#56]
In https://qt4cg.org/branch/master/xpath-functions-40/Overview-diff.html#func-random-number-generator, the `rng` item type is defined as:

    record(
        number   as xs:double,
        next     as (function() as record(number, next, permute, *)),
        permute  as (function(item()*) as item()*),
        *
    )

It would be helpful and more type specific if this could be defined as:

    record(
        number   as xs:double,
        next     as (function() as rng),
        permute  as (function(item()*) as item()*),
        *
    )

where the `next` field references the `rng` type being defined -- this is like how structures in other languages (C/C++, Java, C#) can reference themselves as property types.

This would also provide an alternative for the `..` (self reference) specifier.

> __Note:__ the `..` syntax is still useful in the case of anonymous record types.

**Comment by michaelhkay** [comment]
Closing this as it was essentially implemented by PR #737.
