### ISSUE TITLE
Formatting Monospace

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#560]
It would be great if we could further tweak and unify the representation of monospaced text. On my machine, I see…

* `monospace` (13px) for the function signature (using `<code>` instead of `<pre>`, with increased line heights)
* `monospace` (11.7px) for `<code>`
* `Menlo, Consolas, "DejaVu Sans Mono", ...` (13px) for `<pre>`
* `Menlo, Consolas, "DejaVu Sans Mono", ...` (14,4px) for `<pre>` in examples

…and I guess there are other cases. Would it be possible to use the same font style, size & line height for monospaced text? Maybe a friendlier light grey color for all `<pre>` blocks, similar to the GitHub rendering.

-----

![image](https://github.com/qt4cg/qtspecs/assets/196589/7a3bdc02-b181-4370-b2ee-2a5ca2b05e04)

**Comment by ndw** [comment]
Yes, there should be a consistent style. PRs for the CSS most welcome :-) but I'll take a look perhaps this afternoon.

**Comment by ChristianGruen** [comment]
> Yes, there should be a consistent style. PRs for the CSS most welcome :-) but I'll take a look perhaps this afternoon.

;) Thanks. You’ll probably be faster than me.

**Comment by ChristianGruen** [comment]
That’s definitely an improvement. Some more trivia (feel free to close the issue if you believe it’s not worth the trouble):

1. The indentation for the function parameters of function parameters could be reduced. Currently, we have cases like:

![image](https://github.com/qt4cg/qtspecs/assets/196589/10775b7b-9eb5-4a44-8550-b7eb76dc7631)

Maybe two leading spaces are sufficient:

```xquery
array:sort(
  $array     as array(*),
  $collation as xs:string?                             := fn:default-collation(),
  $key       as function(item()*) as xs:anyAtomicType* := fn:data#1
) as array(*)
```

2. Maybe the line height of the lines of the function signature can be reduced as well?

3. The font size of `<pre/>` blocks differs. It’s 13px in the full-text, and it’s 14,4px in the examples sections (14,4px is also used for function signatures and `<code/>` tags).

![image](https://github.com/qt4cg/qtspecs/assets/196589/77319da0-8c9b-44dc-8104-a6be8914f94c)

4. The examples take a lot of vertical space, compared to the other sections:

![image](https://github.com/qt4cg/qtspecs/assets/196589/b3843bae-c9ff-4c88-916a-d3c4eb8c8212)

**Comment by ndw** [comment]
More improvements, I believe. Thanks for pointing out the problems!

**Comment by ChristianGruen** [comment]
Great!
