### ISSUE TITLE
The item-type(T) syntax is not defined

### ISSUE THREAD

**Issue by rhdunn** [qt4cg/qtspecs#57]
Section 3.7.2 *The judgement subtype-itemtype(A, B)* of the XPath 4.0 and XQuery 4.0 specifications mention `item-type(N)`, as does section 5.19 *Item Type Declarations* of the XQuery 4.0 specification. It is also not in the EBNF grammar -- searching for `"item-type"` only finds the `ItemTypeDecl` symbol in the XQuery 4.0 EBNF.

This should be defined in section 3.6 *Item Types*.

**Comment by rhdunn** [comment]
I would personally prefer it if the custom item types didn't need to be wrapped in an `item-type(T)` construct. From a user perspective, this is a lot of characters to type (similar to needing to type `struct` in older versions of C).

This could work by combining the __In-scope schema types__ and __Item type aliases__ into a set of __Statically-known types__ that `AtomicOrUnionType` (`ItemTypeName`?) uses to resolve its type. If that is an *item type alias*, then it is expanded per the currently described rules, and if it is a schema type then that type definition is used.

> __Note:__ This is how MarkLogic defines its custom types (`map:map`, `cts:query`, etc.), and could be used to shorten types that return an element of a specified type by an implementation (e.g. `element(http:response)` could be mapped to an `http:response` item type alias).

**Comment by michaelhkay** [comment]
I think this issue has been overtaken by events. Closing it.
