### ISSUE TITLE
fn:evaluate-xpath() function

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#572]
XSLT 3.0 introduced an instruction, xsl:evaluate, for dynamic evaluation of XPath expressions. But there is no way of doing this in XQuery.

It was done as an instruction in XSLT because functions at the time were not flexible enough to cope with a range of optional parameters. This situation has changed.

An `fn:evaluate()` function might operate successfully with the following parameters:

* xpath - the XPath expression as a string.
* namespaces - the namespace bindings as a map from prefix to URI, defaulting to the namespace bindings in the static context of the caller
* parameters - parameter values as a map from QName to value, defaulting to an empty map
* context-item - the context item for evaluation, defaulting to the context item of the caller
* options:
  - default collation
  - base URI
  - schema-aware = true/false
  - allow-external-access = true/false
  - cache = true/false (whether to cache compiled expressions for reuse)

Before `xsl:evaluate` as introduced, there was some concern in the WG about security and the risk of injection attacks. I think that the allow-external-access switch is sufficient for this: if you don't trust the expression, set it to false, and all dangerous things like access to external documents and other resources, use of extension functions, etc, is disabled.

**Comment by ChristianGruen** [comment]
I suggest closing this issue in favor of #1194.

**Comment by ndw** [comment]
The CG agreed to close this issue without further action at [meeting 077](https://qt4cg.org/meeting/minutes/2024/05-14.html).
