### ISSUE TITLE
fn:log: Trace and discard results

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#574]
See https://github.com/qt4cg/qtspecs/issues/359#issuecomment-1465971781

### Summary

Outputs trace information and discards the result.

### Signature

```
fn:dump(
  $value  as item()*,	
  $label  as xs:string?  := ()
) as empty-sequence()
```

### Properties

This function is ·deterministic·, ·context-independent·, and ·focus-independent·.

### Rules

Similar to `fn:trace:`, the values of `$value`, converted to an `xs:string`, and `$label` (if supplied and non-empty) may be directed to a trace data set. The destination of the trace output is ·implementation-defined·. The format of the trace output is ·implementation-dependent·, as is the ordering of the output.

In contrast to `fn:trace`, the function returns an empty sequence.

**Comment by michaelhkay** [comment]
I'ev always hated the name "dump", since it implies "delete". I'd prefer, say, "show" or "message". 

Also a common usage will simply be to output a string message: `fn:show("Entered my:complex-function")` reads better than `fn:dump("Entered my:complex-function")`.

**Comment by ChristianGruen** [comment]
Perfectly fine; I’d probably dislike the German equivalent as well.

My favorite alternative would be `fn:message`. If we add an error code option, I think we should also add it to `fn:trace`.

**Comment by Arithmeticus** [comment]
One issue in calling it `fn:message()` is that the signature differs significantly from `<xsl:message>`. Is alignment possible?

**Comment by michaelhkay** [comment]
Yes, I've been trying to specify it and have been hitting exactly that obstacle. In part this is due to a deficiency in xsl:message - it's defined to produce an XML tree, which means that outputting the content of a map or array requires contortions like an explicit call to fn:serialize().

**Comment by ChristianGruen** [comment]
Alternatives: `fn:info`, `fn:print`.

By the way, I know what `fn:trace` is supposed to do, but the rule in the spec seems incomprehensible to me (maybe because I’m no native speaker):

> In addition, the values of `$input`, converted to an `xs:string`, and `$label` (if supplied and non-empty) may be directed to a trace data set.

I’m missing a definition of »trace data set«, and what a direction to this set is supposed to do. Maybe we can simply align the wording with `xsl:message`:

> In addition, the values of `$input`, typically serialized and converted to an `xs:string`, and `$label` (if supplied and non-empty) may be output to an ·implementation-defined· destination.

**Comment by ndw** [comment]
>  In addition, the values of $input, converted to an xs:string, and $label (if supplied and
>  non-empty) may be directed to a trace data set.
>
> I’m missing a definition of »trace data set«, and what a direction to this set is supposed to do.
> Maybe we can simply align the wording with xsl:message:
>
>  In addition, the values of $input, typically serialized and converted to an xs:string, and $label
>  (if supplied and non-empty) may be output to an ·implementation-defined· destination.

Yes, I think that’s what’s intended.

                                        Be seeing you,
                                          norm

--
Norm Tovey-Walsh ***@***.***>
https://norm.tovey-walsh.com/

> The intelligent man finds almost everything ridiculous, the sensible
> man hardly anything.--Johann Wolfgang von Goethe

**Comment by michaelhkay** [comment]
"Data set" is IBM mainframe speak for "File". There were a number of IBMers on the XQuery WG.

**Comment by ChristianGruen** [comment]
Which function name seems most appropriate to those who’re reading this (for a function that outputs trace information and discards the result)?

1. `fn:dump`
2. `fn:message`
3. `fn:show`
4. `fn:info`
5. `fn:print`
6. `fn:log`

**Comment by joewiz** [comment]
+1 to `fn:log`. The function described here reminds me of eXist's `util:log` function - https://exist-db.org/exist/apps/fundocs/index.html?q=util:log - which sends the message to the `exist.log` file on disk. The only downside is that someone might think it does what `math:log` does. Still, I like it more than the alternatives. In the spirit of ranked choice voting:

1. `fn:log`
2. `fn:dump`

**Comment by Arithmeticus** [comment]
I prefer 6, 1, 4. But if its signature can be reconciled to `<xsl:message>` I would put 2 at the top priority.

**Comment by micheee** [comment]
I'm leaning slightly towards `fn:log` but I agree that `fn:dump` is fine as well to avoid confusion with `math:log`.

**Comment by ChristianGruen** [comment]
Thanks for the feedback. `fn:log` was mentioned as a favorite three times; let’s go for it. I’ll create a PR.

**Comment by michaelhkay** [comment]
I definitely prefer fn:log to fn:dump. The word "dump" makes me think (a) of deleting things, and (b) of the six-inch high piles of line printer paper containing hex memory dumps that we used to use for debugging in my youth.

**Comment by ChristianGruen** [comment]
> the six-inch high piles of line printer paper containing hex memory dumps that we used to use for debugging in my youth.

Sounds like bad memories ;)

**Comment by michaelhkay** [comment]
Solving puzzles is always fun. We took pride in our skill. People made templates on clear plastic sheets that identified the fields of common data structures. Debugging some Saxon issues, with all the lazy evaluation that's going on, is much harder because what's in memory is far less closely related to the program logic.
