### ISSUE TITLE
[FO] fn:replace no longer has the 3 an 4 argument variants

### ISSUE THREAD

**Issue by rhdunn** [qt4cg/qtspecs#59]
The signature for fn:replace in FO 4.0 [1] only has the new 5 argument variant, whereas FO 3.1 has 3 and 4 argument variants.

1. https://qt4cg.org/branch/master/xpath-functions-40/Overview-diff.html#func-replace
2. https://www.w3.org/TR/xpath-functions-31/#func-replace

**Comment by ChristianGruen** [comment]
Superseded (all function signatures were replaced by a single signature with optional default values).
