### ISSUE TITLE
fn:decode-from-uri: counterpart of fn-encode-to-uri

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#600]
Adopted from https://github.com/qt4cg/qtspecs/issues/566#issuecomment-1607397586:

The initial suggestion in #72 was to provide a function for decoding a URI. Maybe we should still think about adding a `fn:decode-uri` or `fn:decode-from-uri` function, in which we could tackle the open issues that need to be solved for `fn:parse-uri`. The current URI decoding rules could then be replaced with a reference to this new function.

**Comment by ndw** [comment]
It would make the function library more symmetric. I assume we're thinking that `decode-from-uri` would do the decoding of URIs to IRIs.

1. If the input does not contain any '%' characters, return it unchanged.
2. Replace all %nn with the corresponding bytes and then UTF-8 decode the resulting string to get a sequence of Unicode characters. Return that.

I suggest that if the string contains invalidly encoded characters (A `%` followed by less than two characters or followed by characters not in the range 0-9, a-f, A-F; or if the resulting sequence of bytes isn't a valid UTF-8 encoding) the function inserts U+FFFD characters in the relevant locations but does not throw an error.

**Comment by ChristianGruen** [comment]
> I assume we're thinking that `decode-from-uri` would do the decoding of URIs to IRIs.

I must admit I’ve never purposely worked with IRIs. Maybe we could have an additional `fn:uri-to-iri` function for that, but maybe that wouldn’t make any sense?

> If the input does not contain any '%' characters, return it unchanged.

Similar as for, `fn:parse-uri`, I would expect `+` to be converted to a space.

> Replace all %nn with the corresponding bytes […]

I’ve added another comment on scanning UTF-8 at about the same time; I think variant 2 would be the most flexible one:

* For `%F0%9F%92%41`, we get `�A`, as only the 4th byte does not match the UTF-8 rules.
* For `%F0%F0%9F%92%A1`, we get `�💡`, as the 2nd byte does not match the rules, but can successfully be scanned as first byte of the upcoming UTF-8 sequence.

> […] but does not throw an error.

+1
