### ISSUE TITLE
fn:all → fn:every?

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#601]
Feedback we got (translated):

There are the `every` and `some` keywords, and there are the new functions `fn:some` and `fn:all`. They appear to be more or less similar, so it would be consistent if `fn:all` was renamed to `fn:every`.

If `fn:all` is called this way because there’s also `fn:all-different` and `fn:all-equal`, we should also have `fn:some-different` and `fn:some-equal`.

**Comment by michaelhkay** [comment]
I'll abstain on renaming `fn:all` as `fn:every`.

I don't think we need `some-different` and `some-equal` because they're the same as (or confusingly similar to) `not(all-equal(X))` and `not(all-different(X))` respectively.

**Comment by ChristianGruen** [comment]
PR created (#640) as agreed in [meeting 043](https://qt4cg.org/meeting/minutes/2023/07-25.html).
