### ISSUE TITLE
Formatting Monospace (II)

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#608]
Bugging you again, @ndw …

My feedback has been triggered by #607. I’ve moved various code examples into `eg` blocks. In principle, the result is promising, but it produces cases such as the following one (see https://qt4cg.org/pr/607/xpath-functions-40/Overview.html):

<img src='https://github.com/qt4cg/qtspecs/assets/196589/d64fd37a-2918-487c-967c-08570208d6c8' width='500'/>

Maybe the result is better to read if single-line and multi-line monospace is formatted identically (i.e., without lines at the top and bottom, and with a transparent background)?

Next, it would be fine if we could get rid of the scrollbars. Often, it’s not apparent from the rendering that the presentation includes results at all:

<img src='https://github.com/qt4cg/qtspecs/assets/196589/b86d688b-fbdc-4a54-bd22-fa47e027dec2' width='500'/>

We could possibly fix it by wrapping even more examples manually. That can be challenging, though, for example if long strings are used (such as `"http://www.w3.org/2013/collation/UCA?lang=en;alternate=blanked;strength=primary"`).

Finally, the formatting on mobile devices (here: an Android tablet with a Chrome renderer) differs from the desktop view: code blocks are rendered much smaller than the rest. – That’s just to mention it; I’d probably be annoyed if I was tasked with fixing that.

<img src='https://github.com/qt4cg/qtspecs/assets/196589/b2dd898a-cd20-4ba2-a3d6-cc87c9e4e835' width='400'/>

**Comment by rhdunn** [comment]
For the issue with long URIs, you could try `word-break: normal; overflow-wrap: anywhere;`.

[1] https://developer.mozilla.org/en-US/docs/Web/CSS/word-break
[2] https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap

**Comment by rhdunn** [comment]
Regarding the results side-by-side, I ike that, but it needs to be controlled via a screen width media query so that on smaller width windows it will be displayed below the example, not side-by-side.

**Comment by ChristianGruen** [comment]
I’m closing this; due to recent changes by Michael, and due to further edits of rebellious examples, the current presentation is pretty fine (and much better than 3.1 anyway).
