### ISSUE TITLE
[FO] fn:all and fn:some have an xs:integer* return type, but describe an xs:boolean return type

### ISSUE THREAD

**Issue by rhdunn** [qt4cg/qtspecs#61]
The `fn:all` function states:

> The result of the function is true if and only if the expression every $i in $input satisfies $predicate($i) is true. 

but the return type is specified as `xs:integer*`. -- It should have a return type of `xs:boolean`.

A similar issue occurs with `fn:some`.

**Comment by michaelhkay** [comment]
Fixed.
