### ISSUE TITLE
Allow "union" as synonym for "|" everywhere

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#613]
It seems silly to allow "union" as a synonym for "|" in some places and not others. For example it's not allowed in a "case" clause of a typeswitch, nor in a catch clause of try/catch.

We've introduced the ability to write `child::(a|b)` as a synonym for `child::a | child::b`, but we don't allow `child::(a union b)` as a synonym for `child::a union child::b`.

**Comment by ChristianGruen** [comment]
I wonder why we have `A | B` with `A & B` and `A ^ B` being omitted.
Is it again XPath 1.0 that led to this inconsistency?

**Comment by michaelhkay** [comment]
XPath of course just had "|". But then XQuery came along and favoured the more wordy style of syntax from SQL (`SELECT FROM WHERE`) rather than the algebraic style of XPath `(/a/b[/c/d])` and XQuery folk felt that `|` got lost among the keywords, so they introduced `union` as a synonym; and then "intersect" and "except" fell into the same pattern. So no, it wasn't XPath that led to the inconsistency, it was XQuery!

**Comment by ChristianGruen** [comment]
> So no, it wasn't XPath that led to the inconsistency, it was XQuery!

A fair point of view. Thanks.

**Comment by ChristianGruen** [comment]
I would tend to stick with `|` as long as we don’t also support `intersect` and `except` everywhere else.

**Comment by michaelhkay** [comment]
The WG agreed to close this with no action on 2024-04-09.
