### ISSUE TITLE
XDM: X Node vs. x node

### ISSUE THREAD

**Issue by Arithmeticus** [qt4cg/qtspecs#616]
At the risk of being branded a pedant....

Currently the XDM specs have a predilection for Attribute Node, Element Node, Comment Node, Document Node, Text Node, Processing Instruction Node, Namespace Node. But in a healthy minority of cases in the XDM specs, they are rendered lowercase.

To complicate matters further, the other specs, which rely upon the XDM specs for the definition of the terms, universally prefer the lowercase form, and they use the terms preponderantly more. A healthy sample of four of the terms across five of the specifications ("elective" excludes instances where that particular case is required, e.g., capitalization in headers):

Term | Spec | Capitalized | Electively Capitalized | Electively Noncapitalized
-- | -- | -- | -- | --
Attribute node | XDM | 71 | 41 | 18
Element node | XDM | 79 | 71 | 23
Comment node | XDM | 44 | 39 | 0
Document node | XDM | 55 | 48 | 10
Attribute node | Serialization | 0 | 0 | 15
Element node | Serialization | 0 | 0 | 39
Comment node | Serialization | 0 | 0 | 2
Document node | Serialization | 0 | 0 | 15
Attribute node | XQuery | 1 | 0 | 82
Element node | XQuery | 0 | 0 | 141
Comment node | XQuery | 0 | 0 | 9
Document node | XQuery | 2 | 0 | 50
Attribute node | XFO | 1 | 0 | 28
Element node | XFO | 1 | 0 | 67
Comment node | XFO | 1 | 0 | 4
Document node | XFO | 1 | 0 | 57
Attribute node | XSLT | 8 | 0 | 100
Element node | XSLT | 16 | 0 | 77
Comment node | XSLT | 1 | 0 | 6
Document node | XSLT | 12 | 0 | 144

Options:

1. Do nothing.
2. Change all specs to capitalize these terms universally. 
3. Change only XDM to capitalize these terms universally.
4. Determine a principle that would differentiate the contexts in which the term should be capitalized or not within XDM only.
5. Change all specs to uncapitalize these terms universally.

My personal preference is no. 5. I do not see any passages in XDM where the reader would be confused by the term being uncapitalized (the minority cases being witnesses). Lowercase would bring XDM into conformity with the other specifications, and with how the term is commonly used outside the specs. Further, the XDM specs do not capitalize other terms it specially defines, e.g., accessor. And in all the specs, including XDM, the clear preference is to use the lowercase for the names in the raw (i.e., without "node"): element, attribute, namespace, etc.

I wanted to bring this to the group before doing any edits. I am happy to do the work, but do not want to do it if it is unwelcome, or if there is a clear preference for another option.

**Comment by michaelhkay** [comment]
I agree. Drop the capitalization.

While you're about it, consider (a) which instances of such terms should be hyperlinked to their definition, and (b) what typography should be used. I suspect that the XDM spec makes less use than others of <termref> markup when using defined terms, and rather more use of <term> markup.

Incidentally, I personally hate the American-style use of title case in headings ("Relationship Between Typed-Value and String-Value") (and I can never remember the American rules for which words to capitalize) but I guess we're stuck with it.

Michael Kay
Saxonica

**Comment by ChristianGruen** [comment]
> At the risk of being branded a pedant....

Quite the contrary: Thanks for confirming that there is no inherent semantics in the current presentation. It’s something that’s much easier in German (nouns are always capitalized, other words only at the beginning of a sentence, that’s basically it).

> I can never remember the American rules for which words to capitalize

Good to know as well. I regularly resort to https://capitalizemytitle.com/ and similar websites.

Out of interest, on Wikipedia (https://en.wikipedia.org/wiki/Letter_case#Headings_and_publication_titles), I find:

> R. M. Ritter's Oxford Manual of Style (2002) suggests capitalising "the first word and all nouns, pronouns, adjectives, verbs and adverbs, but generally not articles, conjunctions and short prepositions"

Is it something that’s applied in the UK as well (…or only in the region around Oxford)?

**Comment by ndw** [comment]
It may (or may not) be pedantic, but it's absolutely an editorial improvement. I'm responsible for the capitalized forms in the XPath Data Model specification; so please accept my apologies. It must have seemed like the right thing at the time.

I concur with MK that adding links to definitions and improving the markup where appropriate is a good idea.

I'd be happy to lose *Title Case* in favor of *lower case*.

If no one objects to this change, then procedurally, I suggest you submit a series of PRs for the changes rather than accumulating them all for a single PR. This is the kind of global change that invites merge conflicts. It will be easy to scan the diffs and merge the PRs as editorial which I'll do as promptly as I can.

**Comment by michaelhkay** [comment]
> R. M. Ritter's Oxford Manual of Style (2002) suggests capitalising "the first word and all nouns, pronouns, adjectives, verbs and adverbs, but generally not articles, conjunctions and short prepositions"
> 
> Is it something that’s applied in the UK as well (…or only in the region around Oxford)?
> 
> 

That's on p77 in my edition, and it's talking about "Titles and subtitles of works", not about section headings. The heading of the section that it appears in is "Titles and subtitles of works", not  "Titles and Subtitles of Works"

Mike

**Comment by ChristianGruen** [comment]
> That's on p77 in my edition, and it's talking about "Titles and subtitles of works", not about section headings. The heading of the section that it appears in is "Titles and subtitles of works", not  "Titles and Subtitles of Works"

Got it, thanks. Yet another distinction I haven’t made so far (I’ll save my time and avoid comparing the American English rules for titles of works & section headings).

A good (and expected) example of ChatGPT spreading rubbish, by the way:

> In British English, the capitalization of section headings depends on the specific style guide or publishing house's guidelines. However, as a general rule, British English tends to follow title case capitalization for section headings. […] In American English, the capitalization of section headings generally follows a different convention compared to British English. In American English, section headings often use sentence case capitalization. […]

**Comment by Arithmeticus** [comment]
I'm working on the cap. adjustment for the Seven Nodes, and am also under the impression that there is a general desire to migrate toward sentence-style capitalization in headers -- fine by me. (I hadn't even noticed that, as it stands, that too is an inconsistency.) I note that in XDM some of the heads are defined by entities that will need to be given the boot, to be reflected in a coming PR.

**Comment by Arithmeticus** [comment]
Closed with #620
