### ISSUE TITLE
XPath function definition clarification

### ISSUE THREAD

**Issue by Arithmeticus** [qt4cg/qtspecs#624]
In the XPath specs, 2.2, [function definitions](https://qt4cg.org/specifications/xquery-40/xpath-40-diff.html#dt-function-definition), the reader is informed that every (statically known) function definition takes one of three mutually exclusive categories: application, system, or external.

> [Definition: Application functions are function definitions written in a host language such as XQuery or XSLT whose semantics are defined in this family of specifications. Their behavior (including the rules determining the static and dynamic context) follows the rules for such functions in the relevant host language specification.]

The first sentence appears to point to user-written functions in the host languages, and the second sentence appears to point to functions defined by the host language specifications. I assume that this category is meant to include both, and I propose the language be tightened up to make that clear. If my assumption is incorrect, then some other type of revision is needed.

Later on, when the term “built-in function” is introduced, it is not as clearly stated as it should be how that term maps onto the three-way division. It seems that “built-in function” encompasses all system functions and only those application functions that are defined by the specifications, and not user-written functions. Whatever the case, and whatever the best path of revision, this paragraph would be most effective if moved up with the tripartite category discussion.

The term "external function" is introduced here in the static context, with language that is highly suggestive of a definition. But the definition proper is reserved for the dynamic context, and in shorter, different prose that I think loses some of the considerations provided in the static context. I propose that the two passages be consolidated and located in the static context, where the two other types of functions are defined, with an xref in the dynamic context to the meaning of external function.

Down in the dynamic context: 

> The dynamically known function definitions may include external functions.

This sentence is a bit puzzling, because of course they are allowed to include all three types of functions -- none are forbidden, since, after all, the dynamically known functions are a superset of statically known ones. Perhaps the point is to drawn the reader's attention to those functions that are known dynamically but not statically? Perhaps this revision?: "Many of the function definitions known dynamically but not statically will be external functions, but they may include user-written application functions written in a host language, known only dynamically, e.g., through `fn:transform`."

Cumulatively the above points could go beyond mere minor touch-up, so comments are welcome before I attempt any edits.

**Comment by michaelhkay** [comment]
I think I made good progress in tidying this up from its state in 3.1 (got rid of "functions with an implementation-defined implementation"...) but I agree there is still room for further improvement.

For example, it should probably be stated that so-called "constructor functions" for atomic types (both built-in types and user-defined types) are classified as "system functions".

> The first sentence appears to point to user-written functions in the host languages, and the second sentence appears to point to functions defined by the host language specifications. I assume that this category is meant to include both, and I propose the language be tightened up to make that clear. If my assumption is incorrect, then some other type of revision is needed.

No, my thinking is that a function defined using `xsl:function` is an application function, while something like fn:key (a function defined in the XSLT specification) is a system function. (What about functions defined by XForms? It gets difficult). 

> Later on, when the term “built-in function” is introduced, it is not as clearly stated as it should be how that term maps onto the three-way division. 

I think that all references to built-in functions could safely be replaced by references to system functions. I think I may have had in mind that (a) vendor-defined extensions and (b) constructor functions for user-defined types are system functions but not built-in functions, but I don't think the distinction ever matters.

>The term "external function" is introduced here in the static context,...

By all means try and sort this out; but take into account that XQuery and XSLT both have something to say on the subject, in addition to what XPath says (XSLT calls them extension functions, but they're the same thing).

>The dynamically known function definitions may include external functions

I think that sentence is only there as a lead-in to the paragraph that follows. I would avoid your proposed revision, it begs too many questions. To be honest, I think the main practical rationale for `fn:function-lookup()`, and therefore for having "dynamically known function definitions" is to enable applications to handle differences between implementations as to what is present in the static context; so actually it's not so much that there are functions in the dynamic context that were not present in the static context, it's more that the query has to cope with different static contexts provided by different implementations. We could certainly explain that better.

**Comment by Arithmeticus** [comment]
Closed with #627
