### ISSUE TITLE
distinct-values and duplicate-values: order of results

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#628]
I've noticed that a few tests have appeared in QT4tests distinct-values() that assume the order of results is "order of first appearance" (search for `assert-deep-eq`). We should either change the tests, or change the spec to require order of first appearance.

Since no implementors have objected to these tests, it seems likely that implementations are delivering results in "order of first appearance", and if that is the case, then I think it would be a convenience to users to guarantee this in the spec.

To allow for parallel implementations, we could say that the order is undefined if ordering mode is unordered.

**Comment by ChristianGruen** [comment]
Sounds fine to me.

I assume the function will lose the `·nondeterministic-wrt-ordering·` annotation, and we should probably look at all other functions that are annotated similarly . The definition is:

> [Definition] Some functions (such as fn:distinct-values, fn:unordered, map:keys, and map:for-each) produce results in an ·implementation-defined· or ·implementation-dependent· order. In such cases two calls with the same arguments are not guaranteed to produce the results in the same order. […]

Wouldn’t it be more appropriate (for the functions that will keep this annotation) to state something like “two calls with the same arguments are not guaranteed to produce the results in an order that may be implied by the input”?

**Comment by michaelhkay** [comment]
>Wouldn’t it be more appropriate (for the functions that will keep this annotation) to state something like “two calls with the same arguments are not guaranteed to produce the results in an order that may be implied by the input”?

We're making a stronger statement than that: we're saying that you can call the function twice with exactly the same argument value and get different results. That's to allow for parallel multi-threaded implementations.
