### ISSUE TITLE
fn:slice, array:slice: Signatures, Examples

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#63]
**EDIT:** 1. is obsolete, 2. and 3. are still up-to-date:

1. The current specification for `fn:slice` has only one signature.

It might be recommendable to also provide signatures with 1 and 2 arguments (especially for users who don’t want to use the new syntax for specifying optional arguments).

2. The last examples look wrong; I would expect the input as results:

> The expression fn:slice(("a", "b", "c", "d"), 0) returns ().
> The expression array:slice(["a", "b", "c", "d"], 0) returns [].

3. The first argument of `array:slice` should be renamed from `$input` to `$array`.

**Comment by rhdunn** [comment]
I suspect that with optional arguments, fn:slice will have 1 to 4 arguments, with the single signature being something like:

    fn:slice($input as item()*,
             $start as xs:integer? := (),
             $end as xs:integer? := (),
             $step as xs:integer? := ()) as item()*

That would make this a `%variadic("bounded")` function, with `A` (declared arity) of 4, and `R` (the number of required parameters -- i.e. without a default value) of 1. According to the properties table, this gives: MinA=1, MaxA=4, MinP=0, MaxP=4, MinK=0, MaxK=4. This means that it can be called with 0 to 4 positional arguments, and 0 to 4 keyword arguments, but requires a total of 1 to 4 arguments (positional or keyword).

**Comment by ChristianGruen** [comment]
Sounds good. – In the current version of the spec, all 4 arguments are listed (without the variadic properties).

I noticed that the last example may be wrong; I would expect the full sequence as result:

> The expression fn:slice(("a", "b", "c", "d"), 0) returns ().

**Comment by ChristianGruen** [comment]
I've revised the initial comment. Only 2. and 3. remain relevant.
