### ISSUE TITLE
Ternary operator

### ISSUE THREAD

**Issue by Arithmeticus** [qt4cg/qtspecs#636]
Per #171 the WG decided to allow the ternary operator. I'm looking at [4.16 of the current version of XPath 4.0](https://qt4cg.org/specifications/xquery-40/xpath-40-diff.html#id-conditionals) and the ternary operator is presented as illustrative, but the operator does not appear to have been properly introduced and defined in the specs. The terms "ternary", "??", and "!!" appear only twice each, and in contexts that could be confused as being illustrative. 

By my reading, the definition of `[11] ExprSingle` should be expanded to allow a new option, call it `TernaryOption`, and to the grammar should be new entry `TernaryOption ::= Expr "??" ExprSingle "!!" ExprSingle`. Does such a definition allow any ambiguous constructs?

I propose that 4.16 be subdivided into two subsections, the first one briefly introducing the ternary operator and the second handling if/then statements. Slight aside: the latter should also include a note pointing out how to avoid a then branch (and an example), a courtesy to developers who are overly accustomed to the unbraced approach as to not give the braced approach much thought.

**Comment by Arithmeticus** [comment]
For reference, the then-less if construction is discussed at issue #234

**Comment by Arithmeticus** [comment]
There already exists a note about the then-less if, but it could be improved.

**Comment by michaelhkay** [comment]
We made a decision to drop the ternary operator when we introduced the braced construction `if (c) {thenExpr} else {elseExpr}. (I'll try to find that in the minutes if need be...)

**Comment by michaelhkay** [comment]
What seems to be happening here is that the diff version of the specs is displaying some text that is marked in the XML master as deleted, and which is not displayed in the non-diff version.

**Comment by ChristianGruen** [comment]
@Arithmeticus The ternary operator was dropped; see https://github.com/qt4cg/qtspecs/issues/171#issuecomment-1399079888 and https://qt4cg.org/meeting/minutes/2023/01-17.html for more details.

I’m closing the issue (feel free to reopen it).

**Comment by Arithmeticus** [comment]
Thanks @ChristianGruen @michaelhkay . The large swath of yellow in the diff version at 4.16 signaled to me that the text was changed but live. The nested deleted paragraph on the ternary expression didn't have a different color, so it appeared to be activated. My mistake for trusting that before looking more closely at the XML. 

I suggest we adjust showdiff.css line 4 so that `div.diff-del` becomes `.diff-del` cc @ndw .
