### ISSUE TITLE
Annotation Values: Booleans

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#637]
Functions annotations in XQuery have become a popular feature to attach vendor-specific information (for unit testing, locking, RESTXQ, etc.) to functions.

Annotation values are limited to literals, though. It would often be helpful to supply boolean values, but we don’t have literals for that in the language.

I suggest enhancing the existing grammar…

```
Annotation  ::=  "%" EQName ("(" Literal ("," Literal)* ")")?
```

…and allowing the strings `false()` and `true()` as values:

```
Annotation  ::=  "%" EQName ("(" AnnotationValue ("," AnnotationValue)* ")")?
AnnotationValue  :=  Literal | "false()" | "true()"
```

The suggestion is upward compatible if we should decide later on that we want to allow arbitrary expressions for annotation values.

**Comment by michaelhkay** [comment]
There's a minor problem with this if the default function namespace isn't "fn". I propose tackling that simply by saying that within the Annotation, the default function namespace IS "fn", regardless what it might be outside.

**Comment by ChristianGruen** [comment]
> There's a minor problem with this if the default function namespace isn't "fn". I propose tackling that simply by saying that within the Annotation, the default function namespace IS "fn", regardless what it might be outside.

Good point. +1.

I wasn't sure if we should also allow `fn:true()` and `fn:false()`. I eventually omitted those in order to minimize hard-coded string handling.
