### ISSUE TITLE
Editorial: Avoid e.g.

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#638]
Occurrences of `e.g.` should be replaced with alternatives, such as `(for example)`.

See https://github.com/qt4cg/qtspecs/pull/629#issuecomment-1649952964

**Comment by michaelhkay** [comment]
I've worked with some publishers who were paranoid about this kind of thing, but it's not really worth making an issue out of it.

**Comment by ChristianGruen** [comment]
+1, I'll close it.
