### ISSUE TITLE
Editorial: Use `\n` instead of `\r\n` in XML documents

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#645]
If we use a consistent newline encoding in all XML documents, it will be easier to perform cleanups and to edit documents in the GitHub frontend. Most documents already use Unix-style newlines. If I am correct, only three documents need to be updated:

```
specifications/xslt-xquery-serialization-40/src/errors.xml
specifications/xslt-xquery-serialization-40/src/ns-xslt-xquery-serialization.xml
specifications/xslt-xquery-serialization-40/src/xslt-xquery-serialization.xml
```

**Comment by michaelhkay** [comment]
There's always a danger, of course, that some future contributor will use an editor that turns the newlines back into Windows format.

**Comment by ChristianGruen** [comment]
> There's always a danger, of course, that some future contributor will use an editor that turns the newlines back into Windows format.

True. I think we should reject those changes, at least as long we use GitHub.

**Comment by ndw** [comment]
Better than that, we can tell git to fix the line endings in comments. I'll see about getting that setup. It's Balisage next week, so I may be a little...distracted.
