### ISSUE TITLE
fn:log → fn:message

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#651]
I think we've made a mistake in the choice of name for this function. Without the namespace prefix, it looks far too much like a function that computes logarithms. Also, it would be nice in the future to find some way of allowing the math functions to be called without a namespace prefix, and this choice scuppers that possibility.

I think my choice would be fn:message.

**Comment by benibela** [comment]
```
fn:writeln

fn:std-err-println

fn:trace-and-forget

fn:cerr--

fn:scrap

fn:wormhole
```

**Comment by Arithmeticus** [comment]
If alignment with `xsl:message` is possible (could not the XSLT construction be tweaked?), `fn:message` is the obvious name.

If not, then, I adjust my comment in #574 to prefer `fn:info` and then `fn:dump` (but the latter seems to suggest the items are being removed). If the group still favors `fn:message` I might suggest `fn:msg`, a slight orthographical shift, to remind users that it is not the same as the XSLT feature.

**Comment by ChristianGruen** [comment]
If we change `fn:log`, I concur with @Arithmeticus that `fn:info` might be the best alternative.
For me, `fn:message` would imply that the function triggers an active operation (like creating an event).

**Comment by ChristianGruen** [comment]
I’ve assigned »Proposed for V4.0« label: Maybe we can decide soon how we want to have the final function named.

**Comment by ChristianGruen** [comment]
The function will be called `fn:message`; I’ll prepare a PR.
