### ISSUE TITLE
XQuery - option to suppress entity expansion

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#653]
As an enabler for #652 (and for other reasons) I propose that XQuery should have an option to suppress recognition of entity references. This is appropriate for any context in which XQuery expressions are embedded in XML (including our own test suite), where entity expansion will have already been done before the XQuery text is parsed. With this change, any XPath expression becomes a valid and equivalent XQuery expression.

This could be done using a new prolog declaration such as

`declare entity-expansion on|off;`

If set to "off", `&` is treated as a normal character in contexts such as string literals and direct element constructors, rather than signalling an entity reference. The default remains "on".

**Comment by michaelhkay** [comment]
The main difficulty with this is how to present it in the spec, because the option affects the grammar. I suspect the most palatable way is to split StringLiteral, CommonContent, and ElementContentChar each into two choices with an extra-grammatical note to say that only one of these is actually accepted, depending on the entity-expansion mode.

A further complication is that the first StringLiteral (the module namespace in the module declaration) is necessari;ly encountered BEFORE any "declare entity-expansion" declaration.

**Comment by michaelhkay** [comment]
Another difficulty: while suppressing entity expansion in string literals makes sense, it makes little sense in element content where it is necessary to distinguish `<` as the start of a child element constructor from `&lt;` as a literal angle bracket. The purpose of this option is primarily to provide a mode in which an XQuery processor interprets an XPath expression in the same way that an XPath processor does, so this is not as much of a drawback as it might seem.

**Comment by michaelhkay** [comment]
Another option might be to allow `L"AT&T"` for a string literal in which entities are not expanded, and E"AT&amp;T" for a string literal in which they are expanded, with the default being `L` in XPath and `E` in XQuery. But perhaps that's overkill now we have backtick-delimited strings.

(Note, I think Christian recently changed an assertion on a test case to use the XQuery convention rather than the XPath convention, meaning that the assertion fails if executed using an XPath processor.)

**Comment by ChristianGruen** [comment]
> But perhaps that's overkill now we have backtick-delimited strings.

…just my thoughts.

> (Note, I think Christian recently changed an assertion on a test case to use the XQuery convention rather than the XPath convention, meaning that the assertion fails if executed using an XPath processor.)

I’ll be happy to fix that (as soon as I find out which test cases are affected… Is it possible to run the tests with a freely available implementation?).

**Comment by benibela** [comment]
>As an enabler for https://github.com/qt4cg/qtspecs/issues/652 (and for other reasons) I propose that XQuery should have an option to suppress recognition of entity references.

I have implemented an option for both ways in Xidel.

XPath with entity expansion,  and XQuery without entity expansion

Latter is

      declare option Q{http://pxp.benibela.de}string-entities "off"; 
      "a&amp;"


And an option, where it skips invalid &, so you can use either `"a&b"` or `"a&amp;b"` for former. And `"&&amp;&"` would be expanded to `"&&&"`. It is the way the browser handles entity expanding in HTML


> Another option might be to allow `L"AT&T"` for a string literal in which entities are not expanded, and E"AT&T" for a string literal in which they are expanded, with the default being `L` in XPath and `E` in XQuery. But perhaps that's overkill now we have backtick-delimited strings.
> 
> (Note, I think Christian recently changed an assertion on a test case to use the XQuery convention rather than the XPath convention, meaning that the assertion fails if executed using an XPath processor.)

I suggested that [years ago](https://www.w3.org/Bugs/Public/show_bug.cgi?id=29360)

**Comment by ndw** [comment]
PR #749 suggests that the answer to "perhaps that's overkill now that we have backtick-delimited strings" is "no, it isn't." 

Are we sure about that?

**Comment by ChristianGruen** [comment]
> Are we sure about that?

I’m not, to be honest. I think we already have more strings constructors than most people will ever use.
