### ISSUE TITLE
ThinArrowTarget should use FunctionBody

### ISSUE THREAD

**Issue by rhdunn** [qt4cg/qtspecs#66]
For consistency with `FunctionDecl` and `InlineFunctionExpr` (both of which use `FunctionBody` for the function body instead of `EnclosedExpr`), `ThinArrowTarget` should also use `FunctionBody` for the inline function call version (e.g. `2 -> { . + 1 }`):

    ThinArrowTarget ::= "->" ( (ArrowStaticFunction ArgumentList) |
                               (ArrowDynamicFunction PositionalArgumentList) |
                               FunctionBody )

**Comment by michaelhkay** [comment]
This has been overtaken by events, so I am closing it with no action.
