### ISSUE TITLE
Static functions, default parameters

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#660]
In the current XQuery draft in [5.18.3 Function Parameters](https://qt4cg.org/specifications/xquery-40/xquery-40.html#id-function-parameters), it’ stated that:

> If a parameter is optional, then all subsequent parameters in the list must also be optional. In other words, the parameter list includes zero or more required parameters followed by zero or more optional parameters.

I would suggest raising `XPST0017` if that’s not the case.

**Comment by michaelhkay** [comment]
Alternatively it should perhaps be enforced as a syntax rule, in which case it becomes XPST0003.

The grammar could be expressed as:

```
ParamList := MandatoryParams ("," OptionalParams)? | OptionalParams 
MandatoryParams := MandatoryParam ("," MandatoryParam)*
OptionalParams := OptionalParam ("," OptionalParam)*
MandatoryParam ::= "$" EQName TypeDeclaration?
OptionalParam := MandatoryParam  ":=" ExprSingle
```

It's hard to know whether we should always follow the principle that if a rule CAN be defined in the grammar, then it SHOULD be defined in the grammar; but certainly some implementations might want to put this rule in the grammar which makes it awkward to have a different error code.

**Comment by ChristianGruen** [comment]
I had similar thoughts. The earlier errors are raised, the better, and it should usually be possible to provide a good error message even for XPST0003.
