### ISSUE TITLE
Polyfill function implementations

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#666]
For transition purposes, it may be useful to provide or enable "polyfill" implementations of functions that are specified in QT40, but not yet available in all implementations. Currently this is not possible because the relevant namespaces are reserved.

I propose that we relax the rule on reserved function namespaces:

(a) in XQuery, if the function has an annotation along the lines `%polyfill('http://www.w3.org/2005/xpath-functions'), where the parameter indicates that the function should be injected into the specified namespace instead of the namespace of the containing module.

(b) in XSLT, if the attribute `xsl:function/@override-extension-function="no"` is present. A function is allowed to be in a reserved namespace if this attribute is present.

I've chosen syntax here that's already available in 3.0/3.1, to minimise the impact on existing processors. Of course, we can't retrospectively change the 3.0/3.1 specs to authorise older processors to make this work as intended. But we can suggest that they bend the rules.

In both cases, (a) if the annotation is present then the rules on reserved namespaces don't apply, and (b) the function declaration is ignored if the processor provides its own internal implementation of the function.

I'm proposing to publish polyfill implementations of many of the new functions (not the complex ones like parse-html!). But I don't intend to make this a QT4 deliverable, I'm thinking of doing it as an open source project in GitHub/Saxonica space.

**Comment by sashafirsov** [comment]
# XSLT Error handling with inline recovery fallback

With different versions and implementations of the transformation, the ability to provide the fall back processing or polyfill via different implementation would become critical.

For example, the function or template mode is missing, the handler would be able to load those and re-try the processing. That would open the "lazy load"/"load on demand" pattern. Which is critical for large codebase.

The unsupported XSL/XPath version on the section can be recovered by external service with the current context passed. Allowing the mix of versioning even when particular processor is supporting exclusively own (like 4) version. It would require the ability to explicitly define the version context for the section. Perhaps as namespace override as for `xsl:` prefix in XSLT section...
As for XPath functions. So the error handler would be able to recognize the failed/missing function version.

### Unconditional override.  
Useful for polyfills (forward-) and for backward- compatibility.
The syntax is same kind of tricky. Unlike error handler it has to be triggered when function call/XSL template of particular version would be invoked unconditionally. Kind of AOP approach. The syntax would be similar to the error handler definition.

The ability to call original version would be needed for the wrapper/facade pattern used.

**Comment by michaelhkay** [comment]
>So this has to be about XSLT 4 and a putative XSLT 5

Indeed. My thinking when I raised the issue was that if we can get a polyfill mechanism into Saxon 13, then we can drip-feed new functions implemented in XSLT or XQuery and downloaded dynamically from a web site, rather than making people wait until we publish a new product release.

I did find when I tried a year ago that many of the functions we are specifying are quite hard to implement in XSLT or XQuery. Mainly because the relevant function calling mechanisms (e.g. new coercion rules) weren't yet in place. Perhaps that's changed now.

**Comment by sashafirsov** [comment]
Ability to override functions from implementation engine I guess is out of scope for this discussion. 
While I agree that all implementations should give ability to define and override functions, that is not a part of general platform. Unless we would make it. 
Some time during last year the discussions mentioned to expand the XSLT stack standard into engine. Like the package management parameters, etc. 100% needed.

But here we are talking about XSLT+XPath as a language which would benefit from error handling and evolutionary architecture on expanding the capabilities of versions.

**Comment by sashafirsov** [comment]
@liamquin have proposed to use namespace prefix to define functions. If the function override belong to particular namespace, it would be used with search namespace resolution and priority. The `fn:` namespace could belong to default implementation for call the original by override function.

The same search priority can be used for error handling. If error happen the execution stack would look up for lover priority one and invoke as error handler. Additional data with error info need to be passed along with normal context for proper recovery.

As I see it, 
* override with highest priority on `xsl:` namespace is executed
* if error occur, the lover priority (in same namespace?) error handler called
* from withing handler `fn:` namespaced ( engine provided ) function can be called. 

It covers override, polyfill, and error handling.

**Comment by michaelhkay** [comment]
The WG agreed to close this with no action on 2024-04-09.
