### ISSUE TITLE
Allow optional parameters and keyword arguments on map and sequence variadic functions.

### ISSUE THREAD

**Issue by rhdunn** [qt4cg/qtspecs#67]
These proposed draft changes seek to address the following issues with, and limitations of, the current draft specification:
1. A `%variadic("sequence")` function where the sequence type uses the `+` occurrence indicator should not have an implicit default value. That would mean passing `()` to the sequence, which would generate a coercion error.
2. Map-variadic and sequence-variadic functions cannot have user-specified default parameter values with the current draft wording. In this case the map/sequence last parameter need to be given a default in the function declaration. This allows those to be defaulted to something other than an empty map/sequence, as well as specifying the defaults for other parameters (e.g. in the case where a map is the last of several parameters).
3. It should be possible to allow parameters to be specified as keyword arguments for map-variadic functions. For map-variadic functions, a keyword argument will be bound to a parameter if it matches the parameter, or added to the map if not.

> Design Note:
>
> It would be nice to support keyword arguments for sequence-variadic functions. The other design notes detail a possible way to implement this logic. This would resolve issue #26, and make the features (keyword arguments in this case) usable in all cases.

## Proposal
There are two orthogonal concepts related to variadic functions:
1. *arity bounds* -- the number of required and optional parameters a function has;
2. *variadic type* -- how the function behaves in relation to its last parameter.

### Arity Bounds
[Definition: The *declared arity* of a function is the number of parameters defined in the function declaration.] The declared arity includes both required and optional parameters.

[Definition: An *optional parameter* is a parameter with a default value.] The default value may either be specified in the function declaration, or determined by the logic described below.

[Definition: A *declared optional parameter* is an optional parameter specified in the function declaration.] TODO: Define a syntax for specifying declared optional parameters. [Note: see issue #64 for a proposal on doing this.]

The property `A` is the *declared arity* of a function.

The property `D` is the number of optional parameters. This is determined as follows:
1. If there are any declared optional parameters, `D` is the number of declared optional parameters.
2. If the last parameter is a `MapTest` or `RecordTest`, `D` is 1.
3. If the last parameter is a sequence type with a minimum item occurrence of 0 (e.g. using the `*` occurrence indicator), `D` is 1.
4. If none of the above apply, `D` is 0.

The property `R` is the number of required parameters, and is determined by evaluating `A-D`.

### Variadic Type
The *variadic type* is given by the `%variadic(enum("no", "map", "sequence"))` annotation. It is determined as follows:
1. If the last parameter is a `MapTest` or `RecordTest`, `%variadic("map")` is specified.
2. If the last parameter is a sequence type with an unbounded maximum item occurrence (e.g. using the `*` or `+` occurrence indicator), `%variadic("sequence")` is specified.
3. If none of the above apply, `%variadic("no")` is specified.

[Definition: The *variadic parameter* of a function refers to the last parameter of a map-variadic or sequence-variadic function.]

The values of the MinA/MaxA, MinP/MaxP, and MinK/MaxK properties are given by the following table, where `A` and `R` are defined in the *arity bounds* section.

| `%variadic`    | MinA | MaxA      | MinP | MaxP      | MinK | MaxK      |
|----------------|------|-----------|------|-----------|------|-----------|
| `no`           | R    | A         | 0    | A         | 0    | A         |
| `map`          | R    | unbounded | 0    | A         | 0    | unbounded |
| `sequence`     | R    | unbounded | R    | unbounded | 0    | 0         |

For `%variadic("no")` and `%variadic("map")` functions, positional and keyword arguments can be mixed, or the arguments can be specified as either all positional arguments, or all keyword arguments.

> Note:
>
> If a keyword argument has the name of the variadic parameter for a map-variadic function, it is used to specify the value of that map, and not a key in a constructed map. In this case, the other keyword arguments must specify parameter names as the value of the variadic parameter has already been specified, and would result in a conflicting value if any of the keyword arguments were specifying keys in the variadic parameter.

For `%variadic("sequence")` functions, only positional parameters are allowed.

> Design Note:
>
> Keyword arguments *could* be supported for sequence-variadic functions if the presence of a keyword argument makes it function like `%variadic("no")`. That is, it is not unbounded in this case. This would work, as keyword arguments occur after positional arguments, and the variadic parameter would need to be specified as a keyword argument.
>
> The tricky part of this is that MinA/MaxA would no longer be statically determinable, in that they would depend on whether the function call used keyword arguments.
>
> The `sequence` row would be modified as follows:
>
> | `%variadic`    | MinA | MaxA      | MinP | MaxP      | MinK | MaxK      |
> |----------------|------|-----------|------|-----------|------|-----------|
> | `sequence`     | R    | variable [1] | 0    | unbounded | 0    | A         |
>
> [1] If the function call has at least one keyword argument, `MaxA` is `A`. Otherwise, `MaxA` is `unbounded`.

### Evaluating Static Function Calls
...

3. Positional argument values are mapped to parameters in the function declaration as follows:
   Let the number of declared parameters be N.
   1. A positional argument with position M, (M < N) corresponds to the parameter in position M.
   2. For sequence-variadic functions, the values of arguments in positions greater than or equal to N are concatenated into a sequence, and the resulting sequence is supplied as the value of parameter N. If there are no such arguments (that is, if N-1 arguments are supplied), then the value supplied for parameter N is an empty sequence.

4. Keyword argument values are mapped to parameters in the function declaration as follows:
   Let the keyword corresponding to a keyword argument be K.
   1. If there is a parameter with name K, the keyword argument corresponds to the named parameter K.
   2. For map-variadic functions, the keyword argument is assembled into a map. For each keyword argument, the map has an entry whose name is the keyword (as an instance of `xs:string`) and whose corresponding value is the argument value.
   3. For non-variadic functions, an XPST#### error is raised if there is no parameter with name K.

> Design Note:
>
> If supporting keyword arguments for sequence-variadic functions, 4/iii would handle them. That is, an error is raised if the keyword name does not match a parameter name.

5. If no argument corresponds to a parameter in the function declaration:
   1. If the parameter has a default value, then that value is used.
      TODO: define how the default value is evaluated, i.e. what context is used.
   2. For sequence-variadic functions, the value supplied for parameter N is an empty sequence.
   3. For map-variadic functions, the value supplied for parameter N is the map constructed in step 4. If no keyword arguments were used to construct the map, and empty map is used.
   4. If none of the above apply, an XPST#### error is raised.

6. If more than one argument corresponds to a parameter in the function declaration, an XPST#### error is raised.

...

**Comment by michaelhkay** [comment]
I propose to close this. A lot of water has flowed under the bridge since it was written, and if there are any ideas here that are still worth considering, they need to be reformulated in terms of the current status quo.

**Comment by michaelhkay** [comment]
The WG agreed to close this with no action on 2024-04-09.
