### ISSUE TITLE
GitHub: Line Endings

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#698]
@ndw I’ve copied your suggestion from https://github.com/qt4cg/qtspecs/issues/645#issuecomment-1657056816 to a new issue:

> we can tell git to fix the line endings in comments. I'll see about getting that setup.

In addition, it would be great if line endings were not changed when editing files in place.

![image](https://github.com/qt4cg/qtspecs/assets/196589/ef3b9ccf-04a0-4c57-a696-62ed8522f824)

Due to my changes in #645, all relevant files should now use Unix-style line endings, so this would be a sane default (e.g. if the modification of files leads to a mixture of \n and \r\n).

**Comment by ChristianGruen** [comment]
Further details: https://lists.w3.org/Archives/Public/public-xslt-40/2023Oct/0029.html

**Comment by michaelhkay** [comment]
I think this was fixed by PR #833
