### ISSUE TITLE
GitHub: Signing

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#699]
@ndw Sorry to keep you busy. I think we should disable the enforced signing of commits. We know the persons who send PRs, and currently we only have three persons (you, Reece, me) who sign their commits.

If signing is disabled, for example, also non-admins will be able to merge those PRs.

**Comment by ChristianGruen** [comment]
Resolved (https://lists.w3.org/Archives/Public/public-xslt-40/2023Oct/0026.html).

**Comment by ChristianGruen** [comment]
…and reopened: @ndw Could it also be disabled for the qt4tests repository? https://github.com/qt4cg/qt4tests/pull/49

**Comment by ndw** [comment]
Done, I think.

**Comment by ChristianGruen** [comment]
Works fine!
