### ISSUE TITLE
fn:concat: Support for 0 or more arguments

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#701]
With #161, we plan to introduce support for variadic functions.

The scope of this issue is much smaller and can be seen as a preparatory one; it’s about allowing the first two arguments of the function optional. I’ll create a little PR for it.

**Comment by michaelhkay** [comment]
I always thought that the restriction to two or more arguments was excessively paternalistic.

I would also like to see it generalised to allow sequences, so `concat((A,B))` has the same effect as `concat(A,B)`. (Perhaps we've already done this, I need to check, but I don't think we've discussed it.)

**Comment by ChristianGruen** [comment]
Good point, I’ll include that in the PR.

**Comment by ChristianGruen** [comment]
`Tests Pending` label removed (test suite does already include tests).
