### ISSUE TITLE
FLWOR: for member $m1 in $a1, member $m2 in $a2

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#706]
Currently, the `member` keyword must always be placed directly after the `for` clause:

```xquery
(: valid :)
for $a in 1 to 10
for $m member $m in $array

(: invalid :)
for $a in 1 to 10, member $m in $array
```

In addition, the keyword applies to all other bindings in the same `for` clause:

```xquery
for member $m1 in $array1, $m2 in $array2
```

My feeling is that this syntax is a bit odd, as other keywords (`allowing empty`, `at`) only refer to the currently bound variable. Next, the `member` syntax would differ from the semantics of XQuery Full Text: The `score` keyword is placed before the variable name, and can be used more than once (or omitted):

```xquery
let score $s1 := $data1, score $s2 := $data2
```

I think we should change this. It would also simplify the grammar:

```
InitialClause     ::=  ForClause | LetClause | WindowClause
ForClause         ::=  "for" ForBinding ("," ForBinding)*
ForBinding        ::=  (SimpleForBinding | ForMemberBinding) PositionalVar? "in" ExprSingle
SimpleForBinding  ::=  VarBinding AllowingEmpty?
ForMemberBinding  ::=  "member" VarBinding
AllowingEmpty     ::=  "allowing" "empty"
PositionalVar     ::=  "at" "$" VarName
VarBinding        ::=  "$" VarName TypeDeclaration?
```

And one more motivation for changing is that map bindings will be easier to define (see [#31](https://github.com/qt4cg/qtspecs/issues/31#issuecomment-1721400625)).

**Comment by ChristianGruen** [comment]
I’m often too impatient when reading grammars (and, admittedly, specs in general), but I believe that the example given in the spec…

```xquery
for member $x in $expr1, member $y in $expr2
```

…cannot be expressed by the current grammar. It should be possible with the proposed grammar.

**Comment by benibela** [comment]
> I’m often too impatient when reading grammars (and, admittedly, specs in general), but I believe that the example given in the spec…
> 
> ```xq
> for member $x in $expr1, member $y in $expr2
> ```
> 
> …cannot be expressed by the current grammar. It should be possible with the proposed grammar.

I have implemented it that way. 

I assumed the examples are how it is meant to be and contradicting  parts of the spec  were mistakes

**Comment by michaelhkay** [comment]
>Currently, the member keyword must always be placed directly after the for clause:

I was puzzled by your remarks until I realised you were looking at the XQuery grammar. The XQuery and XPath grammars seem to have got out of sync here.

**Comment by ChristianGruen** [comment]
> The XQuery and XPath grammars seem to have got out of sync here.

Good to hear that this is mostly editorial. I’ve updated and added tests to reflect the behavior in the example.

**Comment by michaelhkay** [comment]
The status quo seems to be:

XQuery:

```
InitialClause ::= ForClause | ForMemberClause | ...
ForMemberClause ::= "for" "member" ForMemberBinding ("," ForMemberBinding)*
ForMemberBinding ::= "$" VarName TypeDeclaration? PositionalVar? "in" ExprSingle
```

XPath:

```
ForExpr ::= SimpleForClause SimpleReturnClause
SimpleForClause ::= "for"  SimpleForBinding (("for" | ",") SimpleForBinding)* 
SimpleForBinding ::= "member"? "$"  VarName "in"  ExprSingle
```

A further complication is that XQuery allows the "allowing empty" qualifier when processing a sequence, but not when processing an array.

I propose changing the XQuery grammar to:

```
InitialClause ::= ForClause  ...
ForClause ::= "for" ForBinding ("," ForBinding)*
ForBinding ::= ForItemBinding | ForMemberBinding
ForItemBinding ::= "$" VarName TypeDeclaration? AllowingEmpty? PositionalVar? "in" ExprSingle
ForMemberBinding ::= "member" "$" VarName TypeDeclaration? PositionalVar? "in" ExprSingle
```

**Comment by ChristianGruen** [comment]
I like `ForItemBinding` instead of `SimpleForBinding`. That was the XQuery grammar I proposed in the initial comment:

```
InitialClause     ::=  ForClause | LetClause | WindowClause
ForClause         ::=  "for" ForBinding ("," ForBinding)*
ForBinding        ::=  (SimpleForBinding | ForMemberBinding) PositionalVar? "in" ExprSingle
SimpleForBinding  ::=  VarBinding AllowingEmpty?
ForMemberBinding  ::=  "member" VarBinding
AllowingEmpty     ::=  "allowing" "empty"
PositionalVar     ::=  "at" "$" VarName
VarBinding        ::=  "$" VarName TypeDeclaration?
```

My thought was that `VarBinding` could also be used at various other places, and it served as preparation for supporting maps (see https://github.com/qt4cg/qtspecs/issues/31#issuecomment-1721400625).

For “allowing empty”, I assume it should be legal to write this:

```xquery
for $n as xs:integer allowing empty in 1 to 10
return $n
```

**Comment by michaelhkay** [comment]
I've taken the view that you should write

```
for $n as xs:integer? allowing empty in 1 to 10
return $n
```

But XQuery 3.1 seems to leave it underspecified.

**Comment by ChristianGruen** [comment]
> I've taken the view that you should write
> 
> ```
> for $n as xs:integer? allowing empty in 1 to 10
> return $n
> ```

Yes, I agree it makes more sense; I mostly think there’s no strong reason to disallow `as xs:integer`. Similarly (or in reverse), “?” as an occurrence indicator is legal, but not really required for window clauses.

```xquery
for tumbling window $w as item()? in ...
```
