### ISSUE TITLE
[FO] Provide better support for URI processing within an expression

### ISSUE THREAD

**Issue by rhdunn** [qt4cg/qtspecs#72]
> Use Case 1: Decode an encoded URI string.

This is difficult to implement correctly, and is a commonly asked question/request on sites like stackoverflow. Vendors have even implemented their own functions, like `xdmp:uri-decode`.

> Use Case 2: Extracting the hash/parameters from a URI string.

This is common when manipulating URI strings and not using something like RESTXQ to bind the query parameters to function parameters. The API should:
1. extract the hash as a string, and the parameters as a name/value map;
2. combine parameters with the same name into the same map entry;
3. decode the values where necessary.

> Use Case 3: Extract the other parts of a URI string.

This can be useful if writing a RESTXQ or similar implementation in XSLT/XQuery. It can also be useful for generating response headers such as Origin, or doing HTTP to HTTPS redirects.

It is easy to make mistakes and the wrong assumptions when writing a URI parser by hand. Additionally, it is not easy to implement in XSLT/XQuery as functions like `analyse-string` and `tokenize` are not powerful enough to implement a lexer, and manipulating codepoints is difficult without stateful logic.

**Comment by namedgraph** [comment]
Use case: modifying a URI
E.g. appending/replacing path segments, query parameter(s), fragments etc.

Java's [`UriBuilder`](https://javaee.github.io/javaee-spec/javadocs/javax/ws/rs/core/class-use/UriBuilder.html) provides a builder pattern for this, e.g.:
```java
UriBuilder.fromUri("http://localhost/").
  path("whatever").
  path("{id}").
  queryParam("name", "value").
  fragment("frag").
  build(id);
```

**Comment by Conal-Tuohy** [comment]
NB it can also be necessary to encode parameter _names_, not just their _values_.

**Comment by benibela** [comment]
>Vendors have even implemented their own functions, like xdmp:uri-decode.

I have also a few, e.g. [x:request-decode](https://www.benibela.de/documentation/internettools/xpath-functions.html#x-request-decode), they could be standarized


```
$ xidel -e 'request-decode("https://example.org/?a=1&a=2&b=3&b=4")'
{
  "url": "https://example.org/?a=1&a=2&b=3&b=4",
  "protocol": "https",
  "host": "example.org",
  "path": "",
  "query": "a=1&a=2&b=3&b=4",
  "params": {
    "a": ["1", "2"],
    "b": ["3", "4"]
  }
}
$ xidel -e 'request-combine("https://example.org/?a=1&a=2&b=3&b=4&c=5", "a=7&a=8&b=x") '
{
  "url": "https://example.org/?a=7&a=8&b=x&c=5"
}

```

**Comment by ChristianGruen** [comment]
Some more (web:create-url, web:encode-url, web:decode-url): https://docs.basex.org/wiki/Web_Module

**Comment by joewiz** [comment]
In eXist, there's [`xmldb:decode()`](https://exist-db.org/exist/apps/fundocs/view.html?uri=http://exist-db.org/xquery/xmldb&details=true&function=xmldb:decode) and [`xmldb:decode-uri()`](https://exist-db.org/exist/apps/fundocs/view.html?uri=http://exist-db.org/xquery/xmldb&details=true&function=xmldb:decode-uri):

> <img width="789" alt="Screen Shot 2021-05-04 at 10 51 37 AM" src="https://user-images.githubusercontent.com/59118/117023075-c4314f00-acc6-11eb-8a66-8dcea62597cb.png">

**Comment by michaelhkay** [comment]
We should have a pair of functions to convert between a string representation of a URI and a map representation that enables access to its parts. Called perhaps `parse-uri()` and `build-uri()`. This is easier said than done, because of the complexity and fuzziness (and variety) of the URI specifications. There are plenty of precedents to follow (such as the URI classes in Java and .NET), but it's notable that they all give different results, varying for example in whether delimiters are included as part of the components, whether %-escaping is done/undone, etc. Need a volunteer to propose a detailed specification.

**Comment by ndw** [comment]
I'll take a stab at it, I fancy a little spec writing as a relaxing interlude.
