### ISSUE TITLE
Support for inline (anonymous) xslt functions

### ISSUE THREAD

**Issue by MarkNicholls** [qt4cg/qtspecs#745]
I propose adding support for inline xslt functions.

Whilst XPath supports this, Xpath functions are limited in what they can do, and how "look" e.g. returning newly constructed elements isnt possible without parse-xml-fragment.

I would suggest the syntax would be basically the same as for xsl:function except with the name omitted, e.g.

```
    <xsl:template name="apply-function" as="xs:integer">
        <xsl:param name="input" as="xs:integer"/>
        <xsl:param name="function" as="function(xs:integer) as xs:integer"/>
        <xsl:sequence select="$function($input)"/>
    </xsl:template>

`    <xsl:template ....>
        <xsl:call-template name="apply-function">
            <xsl:with-param name="input" select="1"/>
            <xsl:with-param name="function">
                <xsl:function as="xs:integer">
                    <xsl:param name="value" as="xs:integer"/>
                    <result>
                        <xsl:sequence select="$value * 2"/>
                    </result>
                </xsl:function>
            </xsl:with-param>
        </xsl:call-template>
    </xsl:template>
`
```

benefits

- less syntactic "noise" of named functions
- the ability to embed xslt functions inline inside maps (and other data types)
- functional parity with xpath (and more)
- natural generalisation to local function proposal

alternatives

- use reference to explicitly named XSLT function
- use XPath (though problematic when constructing new nodes)

**Comment by MarkNicholls** [comment]
If i assign as anonymous function to local variable, isn't that a local function? (barring syntax)

**Comment by michaelhkay** [comment]
>If i assign as anonymous function to local variable, isn't that a local function? (barring syntax)

Not quite. Local variables aren't in scope within their own body, or within earlier instructions/declarations, so it's hard to do recursion with anonymous functions bound to variables, in the way that you can do with named functions. In addition (in 4.0) named functions have some additional capabilities such as defaulted parameter values.

**Comment by MarkNicholls** [comment]
ah, its not until you point it out that you realise the nuances.
I'm used to functions just being values and only in scope for subsequent instructions, does that mean they effectively precede all instructions in the scope? and thus can't form closures (except from params)?
Is this a problem?

**Comment by michaelhkay** [comment]
Global `xsl:function` declarations in XSLT are in scope throughout the stylesheet, including within their own bodies, and within other functions declared earlier. They have access to global variables, but global variables are immutable, so they don't need to go in any kind of closure.

**Comment by ndw** [comment]
The CG agreed to close this issue without further action at [meeting 081](https://qt4cg.org/meeting/minutes/2024/06-11.html#close-without-action)
