### ISSUE TITLE
JSON serialization - number formatting

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#756]
We get a lot of complaints about the use of exponential notation when formatting large numbers with the JSON serializer.

I propose adding an option such as number-format="picture" to control this, where the picture is a subset of what is allowed for format-number().

And perhaps we should bring `xml-to-json()` into line. The current capability of providing a callback function is more powerful, but difficult to align with serialization.

**Comment by ChristianGruen** [comment]
> I propose adding an option such as number-format="picture" to control this, where the picture is a subset of what is allowed for format-number().

…hopefully really a (small) subset ;) But I definitely agree we need more flexibility for outputting JSON numbers.

**Comment by michaelhkay** [comment]
I would imagine the subset would be restricted to contain only "0", '.', '#', and 'e', but I'm not sure of the exact detail yet.

**Comment by michaelhkay** [comment]
I've been attempting to specify this, and it gets very complicated; in addition, I think that specifying a single format that works for all numeric values in a document may prove difficult in many cases.

The current serialization spec allows use of any format that's legal in JSON.

I think I'm going to try and make the Saxon implementation smarter, and avoid any changes to the spec. The main problem that seems to arise is the use of exponential notation for `xs:double` values outwith the range 1e-6 to 1e6, and I think we can probably achieve acceptable results by extending this range, say to 1e-20 to 1e+20.

**Comment by ndw** [comment]
The group agreed to close this issue without action at [meeting 053](https://qt4cg.org/meeting/minutes/2023/11-07.html)
