### ISSUE TITLE
XQFO UCA keyword strength, quaternary setting

### ISSUE THREAD

**Issue by Arithmeticus** [qt4cg/qtspecs#758]
In the XQFO specs, [5.3.3](https://qt4cg.org/specifications/xpath-functions-40/Overview.html#uca-collations), the description of keyword `strength`, option `quaternary`, is I think confusing/misleading:

> quaternary considers spaces and punctuation that would otherwise be ignored (for example `data-base`=`database`).

I propose the following: 

"quaternary always considers as significant spaces and punctuation (data-base≠database; if `maxVariable` is `punct` or higher and `alternate` is not `non-ignorable`, lower strengths will treat data-base=database)."

That's a lot more words, but I think more accurate. And it may help the reader become familiar with the other two keywords. 

Editors' input is welcome.

**Comment by michaelhkay** [comment]
Perfectly happy to use that wording if you think it's accurate. Personally, I find this aspect of the UCA algorithms completely impenetrable, and my attempts to use these features to achieve a sensible sort order for strings that include spaces and punctuation have proved totally unsuccessful - which makes it very difficult to write text that explains it to other people.
