### ISSUE TITLE
Serialization: JSON Parameters

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#759]
We have more and more serialization parameters that are specific to JSON (related: #530, #756, #576, #641). It won’t get better with each new option we add, so maybe it’s time to introduce a custom serialization parameter for JSON (and possibly other methods):

```xquery
serialize(
  map { "abc": 123 },
  map { 'method': 'json', 'json': map { 'escape-solidus': true(), 'number-format':'#' }
})
```

If we want to be able to use output options in the XQuery prolog, we additionally need to define a syntax for serializing the options to a single string:

```xquery
declare namespace output = 'http://www.w3.org/2010/xslt-xquery-serialization';
declare option output:method 'json';
declare option output:json 'escape-solidus=yes,number-format=#';
map { "abc": 123 }
```

Both suggestions are inspired by our own implementation; we use it for our custom JSON and CSV options.

**Comment by michaelhkay** [comment]
I have to confess I'm not especially keen on introducing micro-syntax here; it means for example that the mechanisms for overriding serialization parameters selectively using xsl:import in XSLT don't work "out of the box"; those mechanisms already have ad-hoc tweaks for cdata-section-elements and suppress-indentation and I don't want to make it worse. But I can see the problem.

**Comment by michaelhkay** [comment]
It's very similar to adding functions one-by-one to the fn namespace. You realise at a certain point that it would have been better to organise things differently, but introducing a discontinuity of approach at any point in the process is painful and leaves things looking ugly. I think we're better off letting it grow incrementally without changing the design approach.

**Comment by ChristianGruen** [comment]
You're right; I agree, and I close the issue.
