### ISSUE TITLE
XQuery: Simplify module imports

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#764]
With XQuery, you can import library modules as follows:

```xquery
import module namespace utils = 'http://project.org/utils' at 'org/project/utils.xq`;
utils:action()
```

If an implementation has a mechanism to resolve a namespace URI, you can also do this:

```xquery
import module namespace utils = 'http://project.org/utils`;
utils:action()
```

It would be desirable to simplify this further, and be able to do one of…

```xquery
(: already legal, but no namespace binding takes place :)
import module namespace 'http://project.org/utils';
(: not supported yet :)
import module namespace http://project.org/utils;
(: no URI rewriting needed for relative paths :)
import module namespace org/project/utils;

utils:action()
```

…and…

1. rewrite namespace URIs to local paths (this is how we proceed: https://docs.basex.org/wiki/Java_Bindings#URI_Rewriting)
2. extract the prefix from the path.

I can imagine that the current ways to simplify imports depend a lot on the used implementations. Suggestions are welcome.

**Comment by ChristianGruen** [comment]
> Is it explicilty the last part of the path that's used as the prefix?

Yes, that would be one option (which would be similar to what Java does, which basically interprets the module string as file path).

I’m mostly wondering what others do to avoid bulky and semantically redundant import sections in complex XQuery projects.

**Comment by ndw** [comment]
I have an affinity for explicit declarations, so I just declare them all at the top of the query. (I'd have required declarations for all namespaces used in a query if it had been up to me, so I expect I'm just weird.)

**Comment by michaelhkay** [comment]
There seems to be a tension here between making the module namespace more like a name, and making it more like a location. Of course Java solves that by having a convention that ties the two together, so if you name something com.saxonica.widgets.Wizard, that's enough to tell the system where to find it.

We could introduce a URI scheme that works like this: `module://com.saxonica.widgets.Wizard`.

**Comment by ChristianGruen** [comment]
> We could introduce a URI scheme that works like this: `module://com.saxonica.widgets.Wizard`.

Interesting. Maybe we should use slashes as delimiters, as the dot is a legal NCName character.

The current `import module namespace` statement is a bit unfortunate; it implies that a “namespace” is imported, not a module. We could allow…

```xquery
import module a/b/c;
```

…as a shortcut for…

```xquery
import module namespace "module://a/b/c";
```

…with `c` being adopted as prefix.

**Comment by PieterLamers** [comment]
@ChristianGruen for your last example, leaving out the word namespace would be more correct as the path is used, and not the namespace:
`import module 'org/project/utils';` I'd leave quotes around the path. I actually like this shortest form. However, I see from our libraries alone that there are a lot of duplicate names where you would need to reintroduce a namespace prefix binding to disambiguate. Also, would you skip the suffix in your path example?

**Comment by ChristianGruen** [comment]
> @ChristianGruen for your last example, leaving out the word namespace would be more correct as the path is used, and not the namespace: `import module 'org/project/utils';` I'd leave quotes around the path.

True, thanks; I’ve fixed it.

> I actually like this shortest form. However, I see from our libraries alone that there are a lot of duplicate names where you would need to reintroduce a namespace prefix binding to disambiguate.

Existing projects may need to be refactored to benefit from the compact syntax. Next, a root directory must be defined by an implementation; otherwise, `a/b` would be resolved differently if the base URI of two modules differ (e.g., if module2 is located in the subdirectory of module1).

> Also, would you skip the suffix in your path example?

`project/mod` could reference a `project/mod.xq` file, but I think it should be up to the implementation to decide how to resolve the path (as it’s already the case when the module location is omitted in the import module statement).

My concept is pretty much based on Java imports: A Java class `ROOT/org/project/X.java` can be referenced via `import org.project.X` if you adddress if from the ROOT directory.

**Comment by PieterLamers** [comment]
Alternatively, the application could use the namespace prefix as it is used in the module itself, rather than from a path segment. I think that would make more sense: to use the binding as defined in the module unless overridden by a `namespace mfn = '#my-funky-namespace` declaration.

**Comment by PieterLamers** [comment]
To support my latter view, let's take this example: I have a module with the following:
`module namespace bcr="http://www.benjamins.nl/ns/components/prd/bbr/pull-from-crossref";`
we'd want to import this with `import module '/db/apps/prd/xqlmod/pull-from-crossref.xqm';`
Then we'd want an association with the prefix `bcr`, not with `pull-from-crossref`. Filenames can be long for clarity. Prefixes should be short for efficiency.

**Comment by adamretter** [comment]
> I have an affinity for explicit declarations, so I just declare them all at the top of the query. (I'd have required declarations for all namespaces used in a query if it had been up to me, so I expect I'm just weird.)

@ndw I totally 100% agree with you. I also write my XQuery in this way.

**Comment by adamretter** [comment]
@ChristianGruen I think I am missing something here, at the moment I am afraid that I don't really see how this makes anything "simpler". Could you elaborate?

I might also add some other use-cases in that need to be considered when thinking about modules:

1. This is currently also valid:
```
import module namespace utils = 'http://project.org/utils' at 'utils/a.xqm`, `utils/b.xqm`;
```

2. Also, what about Library Modules that are implemented in the native host language, e.g. Java instead of XQuery - should they be handled via `import module` and/or via `declare namespace` - different approaches have been taken in different processors already here.

**Comment by ChristianGruen** [comment]
Thanks @adamretter, thanks everyone, for the feedback. It has shown to me that the way how module imports are used is too diverse to justify a more compact notation, so I’m closing this again.

A last explanation: BaseX installations have a `repo` directory, which imitates the semantics of Java projects. If modules are stored in that directory, it’s possible to reference them without supplying the location in the import statement:

```xquery
import module namespace get = 'data/get';
import module namespace render = 'view/render';
render:table(get:all('abc'))
```

It would often be straightforward to simplify the syntax by omitting the prefix and deriving it from the last path segment:

```xquery
import module data/get;
import module view/render;
render:table(get:all('abc'))
```

The compact notation could be used optionally when the import patterns are regular enough. However, the responses indicate that it would be tricky to reasonably apply this idea to other implementations, and that it would only be appropriate for specific use cases.

**Comment by adamretter** [comment]
@ChristianGruen I hope you didn't give up on this because of me. My remarks were not intended to be disparaging, rather I just didn't "get it", and needed a bit more context and information.

I certainly agree that module imports as they stand are not great, I just couldn't see how your approach would help much there, but... I did want to understand it!

I am working on a proposal for a revision to EXPath Packaging Standard which has to unfortunately also consider *import mechanisms* for XQuery, XSLT, XProc, etc. I would be very interested once I have something down on paper to get your input on that, I doubt I will propose changes to the XQuery (et al) languages though.

**Comment by ChristianGruen** [comment]
> @ChristianGruen I hope you didn't give up on this because of me. My remarks were not intended to be disparaging, rather I just didn't "get it", and needed a bit more context and information.

…just fine. It has been the overall impression of the replies that made me doubt that it’s something enough users would benefit from. If you have more questions on how we resolve module imports, I’ll be glad to give more feedback.

> I am working on a proposal for a revision to EXPath Packaging Standard which has to unfortunately also consider _import mechanisms_ for XQuery, XSLT, XProc, etc.

Definitely interesting, looking forward to reading it…
