### ISSUE TITLE
parse-html(): case of SVG element names

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#767]
Gunther Rademacher points out at https://github.com/qt4cg/qt4tests/issues/57 that the expected test results for parse-html() expect SVG elements to be output in lower case; and as far as I can see, this is consistent with the spec. But is it useful? It means we're producing XML that isn't valid according to the SVG schema, and that presumably might be rejected by tools that expect to handle valid SVG.

In passing, I note that it's very hard to work out from the parse-html() spec what the function actually does; it's somehow written as if it's obvious, but it never gets around to actually saying it explicitly. It also doesn't say what happens when the `method` option is omitted, as it is in these tests.

In addition, it seems that we don't have any tests that exercise the various options of the function, e.g. the ability to consue binary as well as character input.

**Comment by michaelhkay** [comment]
I note that in §15.6.10 we say

> For example, in [[DOM: Living Standard]] section 13.2.9 Coercing an HTML DOM into an infoset, it uses a Unnnnnn escape sequence. That would map : to U00003A.

The  cited document does not appear to have a section 13.2.9, or to mention the concept of an infoset. This highlights the danger of citing a "living" (i.e. unstable) standard. I can't find any text in the current HTML DOM spec that talks about how characters that aren't allowed in NCNames should be treated.

**Comment by rhdunn** [comment]
It would be useful to link to the sections in the external specs, to make this easier to follow.

**Comment by michaelhkay** [comment]
Thanks, the specific problem appears to be that we link to §13.2.9 of the WHATWG DOM spec, not the WHATWG HTML spec.

I don't know if the section numbers/identifiers of the whatwg specs are stable enough for us to link to?

**Comment by michaelhkay** [comment]
I believe that the only outstanding actions under this issue are (a) to fix the reference to the HTML5 spec, and (b) to add tests for the parse-html options parameter.
