### ISSUE TITLE
British vs. American English

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#771]
Purely editorial: Some words in the specification seem to be British English (organised, generalised, behaviour), whereas the majority of the text is American English. Should this be fixed?

I assume there are tools to get this straight? I am too rarely affected by it to know more about it…

**Comment by ndw** [comment]
I believe that the W3C style was American centric. This is the sort of cleanup that's probably best done closer to the end of the process. Otherwise, it'll just have to be done again anyway.

**Comment by michaelhkay** [comment]
The W3C editorial rules specify American English. But for those of us who aren't native speakers, we get it wrong sometimes. (What a surprize!)

**Comment by michaelhkay** [comment]
I would propose closing this unless there are specific changes that can be identified. Anyone can raise a PR to make editorial improvements of this nature, it doesn't need an open issue.

**Comment by ChristianGruen** [comment]
:+1:
