### ISSUE TITLE
new replace() parameter $action

### ISSUE THREAD

**Issue by Arithmeticus** [qt4cg/qtspecs#777]
In the current draft for [replace()](https://qt4cg.org/specifications/xpath-functions-40/Overview.html#func-replace) the history log states that the new parameter `$action` has not yet had community review. This ticket provides a placeholder for attention and discussion. 

If the CG has already reviewed and accepted `$action`, comment here and I will update the function history accordingly.

**Comment by ChristianGruen** [comment]
:+1: Sounds good. I would expect the function to be stable now.

**Comment by Arithmeticus** [comment]
I vaguely remember discussing this at a meeting in the previous year, but I do not have a convenient way to search the minutes. @ndw could you assist?

**Comment by ndw** [comment]
There is a search interface in the [email archive](https://lists.w3.org/Archives/Public/public-xslt-40/). In addition, the agendas, minutes, and all of the other files on https://qt4cg.org/ are in the `gh-pages` branch of the `qtspecs` repository.

On a quick search, [PR #612](https://github.com/qt4cg/qtspecs/pull/612) was about `fn:replace`. We agreed to merge it without discussion at [meeting 042](https://qt4cg.org/meeting/minutes/2023/07-18.html) on 18 July 2023.

**Comment by Arithmeticus** [comment]
Thanks, Norm. Can you put a link to the search interface at the top of the page: https://qt4cg.org/meeting/minutes/ ? (That's the first place I looked, and it seemed like a dead end.)

**Comment by Arithmeticus** [comment]
Closed by #785
