### ISSUE TITLE
Editorial: errors are raised (not reported, signaled, generated, or thrown).

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#783]
The most common phrase we use when describing an error condition is "A (dynamic|static|type) error is raised if ...".

There are other cases where we use the verb "reported" or "signaled" (and occasionally, "thrown" or "generated"). We should avoid these verbs, partly in the interests of consistency, and partly because they are misleading: an error is not reported if it is caught by a try/catch, but it is still raised.

XSLT also commonly uses the phrase "It is a (dynamic|static|type) error if ... " which is also acceptable.

**Comment by ChristianGruen** [comment]
Remaining case (there shouldn’t be many):
https://github.com/qt4cg/qtspecs/blob/master/specifications/xpath-functions-40/src/function-catalog.xml#L26163

**Comment by ChristianGruen** [comment]
…closed.

> Remaining case (there shouldn’t be many): https://github.com/qt4cg/qtspecs/blob/master/specifications/xpath-functions-40/src/function-catalog.xml#L26163

I’ve added a little todo for that in #822.
