### ISSUE TITLE
allow explicit type expressions in XPath variable bindings

### ISSUE THREAD

**Issue by liamquin** [qt4cg/qtspecs#796]
It would be useful to be able to write

`   let $n as xs:integer := some_expr ....`

and also maybe

` for $s as xs:string, $p as my:name return....`

This might occur e.g. in the body of a function, for example... and would help type safety and debugging.

**Comment by dnovatchev** [comment]
> It would be useful to be able to write
> 
> ` let $n as xs:integer := some_expr ....`
> 

Note that specifying the type is already allowed for function items:

**`let $fun($x) as xs:integer { 2 * $x }`**

so, even in XPath 3.1 if someone wants this feature, they can achieve it with code like this:

```xq
let $fun := function($x) as xs:integer
                    { 2 * $x},
    $n := function() as xs:integer {3}
 return $fun($n())
```

![image](https://github.com/qt4cg/qtspecs/assets/10605892/9c039cbf-cb93-4554-a569-052269da761b)


> and also maybe
> 
> ` for $s as xs:string, $p as my:name return....`
> 
> This might occur e.g. in the body of a function, for example... and would help type safety and debugging.

Seems you wanted this:

**` for $s as xs:string in Expr1, $p as my:name in Expr2 return Expr3`**

One could go even further and find use for:

**`for ($k, $v) in (map(xs:string, xs:integer) {...}) . entries() return Expr`**

But we have a better construct (not strictly speaking _type_) for that in the language - the **_[record](https://qt4cg.org/specifications/xquery-40/xpath-40.html#id-record-test)_**.

**Comment by michaelhkay** [comment]
Adding to the comment from @dnovatchev, you can also declare the expected type of any variable using `treat as`:

```
let $x := my:birthday(2023) treat as xs:date
return ....
```

Does 

```
let $x as xs:date := my:birthday(2023)
return ..
```.
really add anything? (Apart from coercion...)
