### ISSUE TITLE
Coercion Rules: Unifications

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#812]
It has always been a challenge to teach the difference between a conversion, coercion, promotion, casts and treats. Of course, we cannot get rid of the complexity, but I think it’s a good step forward that the conversion rules have recently been unified in the specification.

Maybe we can push it even further. I would suggest…

1. renaming “Coercion Rules” to “Type Coercion” (…most other sections contain rules as well),
2. making “Function Coercion” a subsection of “Type Coercion”, and
3. making “Type Promotion” another subsection of “Type Coercion”.

I’m the wrong person to decide this, but maybe the full section can be moved to the Appendix, as it’s referenced all around the documents.

**Comment by michaelhkay** [comment]
I've been thinking about a better way to describe promotion now that we are introducing more allowed promotions, and one approach indeed is to get rid of the term, and just integrate it into the coercion rules.

One approach is a unified rule along the lines:

If the supplied value is an instance of a type listed in the LH column below and the required type is the corresponding type in the RH column, then the supplied value is cast to the required type.

untypedAtomic         any atomic type
any atomic type T     any type derived from T
xs:string                   xs:anyURI
xs:anyURI                xs:string
xs:integer                 xs:double
etc.

Of course this is just a sketch.

Michael Kay
Saxonica

**Comment by michaelhkay** [comment]
Handled in PR #815.

**Comment by ChristianGruen** [comment]
#815 has been merged. I wouldn’t say it was too early for that, but I’d like to keep this issue open for discussion:

I think it’s safe to say that the current promotion and coercion rules have really become complex, and I suspect that hardly anyone, except for those who have to implement the rules (sigh), will be able to tell in the future what exactly is going on. Is this what we aim for? If conversion rules are well designed and comprehensive, this can be perfectly fine. If they are more or less pragmatic, chances are high that people get confused.

Here are some examples that I believe reflect the current rules:

Query | Result
--- | ---
`fn($n as xs:double ) { $n }(xs:float(1))` | `1` *no loss*
`fn($n as xs:byte   ) { $n }(123)` | `1234567.1` *no loss*
`fn($n as xs:double ) { $n }(12345678901234567890.0)` | `1.2345678901234567E19` *loss of precision*
`fn($n as xs:float  ) { $n }(1234567.1234567)` | `1234567.1` *loss of precision*
`fn($n as xs:integer) { $n }(1234567.1234567)` | *error*
`fn($n as xs:token  ) { $n }('x')` | `'x'` *no loss*
`fn($n as xs:anyURI ) { $n }('x')` | `'x'` *no loss*
`fn($n as xs:string ) { $n }(xs:anyURI('x'))` | `'x'` *no loss*
`fn($n as xs:token  ) { $n }(xs:anyURI('x'))` | `'x'` *error*

Some observations:
* It may come as a surprise that sometimes loss of precision is accepted, sometimes not.
* Casts and relabeling seems to be mutually exclusive (`xs:anyURI` → `xs:string` and `xs:string` → `xs:token` is allowed, `xs:anyURI` → `xs:token` is not).
* We should clarify if we really need bidirectional/each-to-each coercions. Wouldn’t it be better to only allow `xs:string` → `xs:anyURI` and `xs:hexBinary

I know it’s much easier to create complexity than to create simplicity, and our time is limited, but it could pay out in the long term.

**Comment by michaelhkay** [comment]
The fact that we promote decimal to double, potentially losing precision, is unfortunate. It's mainly a legacy of 1.0 where double was the only numeric type. For the coercion rules we could probably consider making all three primitive numeric types mutually convertible. For operands of binary arithmetic and comparison operators it's much harder to make a change (without introducing yet more complexity...).

**Comment by ChristianGruen** [comment]
I’m closing this one (I can’t offer any improvement, and the spec has further evolved).
