### ISSUE TITLE
XSLT: Rules for on-no-match="shallow-copy-all"

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#814]
There are some details missing for the error handling of the built-in template processing for `shallow-copy-all`.

When the built-in template processes an array, the built-in rule constructs a value record for each member, and applies-templates to this value record, expecting the result to be a value record.

* It's not stated whether the "value record" is extensible, that is, whether it can contain fields other than "value"
* No error code is given, and it's not identified explicitly as a type error.

Similarly when a map is processed, the result is expected to be a key-value record, but the details of the error are not spelled out.

**Comment by michaelhkay** [comment]
From working a use case (mode-4008):

We're trying to modify `"Authors": ["Enid Blyton", {"Note": "possibly misattributed"}]` to delete the `Note`, by having an empty template rule `<xsl:template match="record(Note)"/>`. This is currently producing the output `"Authors": ["Enid Blyton", null]`, although a stricter reading of the spec suggests it should be `"Authors": ["Enid Blyton", {}]`. There's certainly a need for more examples and use cases, and possibly some refinement of the spec.

**Comment by ndw** [comment]
Superseded by #1238
