### ISSUE TITLE
Foxpath integration

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#818]
This is a placeholder issue for Syd Bauman’s [suggestion on Slack](https://app.slack.com/client/T011VK9115Z/C01GVC3JLHE) to integrate Foxpath, or parts of it, in the standard.

**Comment by michaelhkay** [comment]
My feeling is that this doesn't hit a cost/benefit target.

**Comment by ndw** [comment]
The CG agreed to close this issue without action [meeting 062](https://qt4cg.org/meeting/minutes/2024/01-23.html)
