### ISSUE TITLE
FLWOR: Variable Bindings, coercion

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#820]
In the current XQuery 4, the coercion rules are applied to variable bindings of FLWOR expressions:

https://qt4cg.org/specifications/xquery-40/xquery-40-diff.html#id-binding-rules

I believe this is yet another feature that needs to be formally accepted. If it has already been done so, this issue can be closed again immediately (maybe with a reference to the related issue, or the associated QT4 meeting).

**Comment by michaelhkay** [comment]
This was issue #189

**Comment by ChristianGruen** [comment]
Thanks.
