### ISSUE TITLE
build-uri() - is {"port":()} legal?

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#847]
The (only) example in the spec of a build-uri() call specifies `{"port":()} `. But `uri-structure-record` has 

`port? as xs:string,`

which means that the empty sequence is not a valid value. Either the record structure should be changed to specify the type as `xs:string?`, or the example should be changed.

**Comment by gimsieke** [comment]
A random guy on the Internet dares to correct the CEO of Saxonica – this is unheard-of!
