### ISSUE TITLE
Spec for deep-equal() still references FOTY0015

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#856]
The errors section of fn:deep-equal still says

A type error is raised [[err:FOTY0015] if either input sequence contains a function item that is not a map or array.

This is no longer the case (and error FOTY0015 is now obsolete and should be removed from the appendix)

**Comment by ChristianGruen** [comment]
I guess this means that the `false-on-error` option needs to be removed as well?
