### ISSUE TITLE
fn:intersperse → fn:join, array:join($arrays, $separator)

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#868]
With `string-join`, you can create a string for multiple strings, optionally interspersed with a separator. `array:join` can be used to create an array from multiple arrays.

`fn:intersperse`, which has been added to the XQuery 4 draft, does something very similar, and early feedback indicates that the function is useful, but easily to overlook due to its name.

I propose to unify the functions by…

1. renaming `fn:intersperse` to `fn:join`;
2. adding a parameter to `array:join`: `$separator as array(*)* := ()`; and
3. allowing a separator sequence for `fn:string-join`: `$separator as xs:string* := ()`.

#### Examples

Query | Result | Info
-- | -- | --
`string-join((1, 2))` | `'12'` | *existing syntax*
`string-join((1, 2), '-')` | `'1-2` | *existing syntax*
`string-join((1, 2), ('-', '+'))` | `'1-+2'` | *new*
`array:join([ [ 1 ], [ 2 ] ])` | `[ 1, 2 ]` | *existing syntax*
`array:join([ [ 1 ], [ 2 ] ], [ '-' ])` | `[ 1, '-', 2 ]` | *new*
`array:join([ [ 1 ], [ 2 ] ], [ '-', '+' ])` | `[ 1, '-', '+', 2 ]` | *new*
`join((1, 2))` | `(1, 2)` | `intersperse((1, 2))`<br/>(*or just* `(1, 2)`)
`join((1, 2), '-')` | `(1, '-', 2)` | `intersperse((1, 2), '-')`
`join((1, 2), ('-', '+'))` | `(1, '-', '+', 2)` | `intersperse((1, 2), ('-', '+'))`

**Comment by ChristianGruen** [comment]
> Could also call it `sequence-join` or `items-join`, then it is more consistent with `string-join`

I suggested `fn:join` as we already have `array:join` and various other sequence functions that don’t include `sequence`.

> `items-join` variant would also be consistent with `items-after`

The `items-` functions will probably be renamed:

https://qt4cg.org/pr/855/xpath-functions-40/Overview.html#func-subsequence-after
https://github.com/qt4cg/qtspecs/issues/844#issuecomment-1826276165

> or it could be a sequence.
> `array:join([1,2,3], '-')` to make it `[1,'-',2,'-',3]`

I thought about this, but then it wouldn’t be possible to include multiple arrays.

**Comment by joewiz** [comment]
+1 to `fn:join` (and `array:join`)

**Comment by michaelhkay** [comment]
I'm still a little uneasy that for many people with a database background, join means relational equijoin.

**Comment by ChristianGruen** [comment]
I noticed that during XML Prague the `PRG-required` label was added to this issue.

Does someone remember which of my suggestions were regarded as necessary? Would it be helpful if I create a PR for my initial proposal?

**Comment by michaelhkay** [comment]
>Does someone remember

Not I, I'm afraid.
