### ISSUE TITLE
Symmetry: fn:items-at → fn:get

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#872]
I think that `fn:items-at` should be changed to `fn:get`:

* In #843, we try to harmonize the function names across sequences, maps, and arrays. We have `array:get` and `map:get` to retrieve single entries of the input, but we have `fn:items-at` for sequences.
* `fn:items-at` allows you to supply more than a single position, but `items-at($seq, (1, 3, 2)` can easily be rewritten to `(1, 3, 2) ! get($seq, .)` – similar to `(1, 3, 2) ! array:get($array, .)` and `(1, 3, 2) ! map:get($map, .)`.
* With #844, `fn:items-at` would be the only function left with `items` in its name.

The function signature would be as simple as:

```xquery
fn:get(
  $input  as item()*,
  $at     as xs:integer	
) as item()
```

Obviously, most people will still use `$input[$at]` – but the same applies to arrays and maps (and other functions like `fn:head`). One of the advantages of `fn:get` is that you can pass on the context item as position argument.

**Comment by michaelhkay** [comment]
I support the renaming, but I think it's useful to be able to get multiple items. One of the reasons for having this function was that you can't do `$seq[1 to 5]`, but you can do `$seq => items-at(1 to 5)`.

(One possibly unintended benefit of the renaming is that you don't have the problem of using a plural form (items-at) when you are only trying to get one item).

**Comment by michaelhkay** [comment]
See also issue #825, proposing `array:members-at` for symmetry with `fn:items-at`. This would suggest changing `array:get` to accept multiple integers; but of course, that doesn't work, because if you select more than one member of an array then you want to wrap the result in an array.

**Comment by ChristianGruen** [comment]
I’ll create a PR for renaming `fn:items-at` to `fn:get`, with unchanged semantics. We could open a new issue for…

* restricting `fn:get` to return single items, or
* extending `array:get` and `map:get` to return multiple values flattened

**Comment by benibela** [comment]
I had written a comment here, and then Github showed a notification, "confirm your 2FA", and then I confirmed it, and now my comment is gone before I could submit it :( 

2FA makes everything unusable

**Comment by benibela** [comment]
>extending array:get and map:get to return multiple values flattened

I had already proposed that in the bug tracker: https://www.w3.org/Bugs/Public/show_bug.cgi?id=29427#c1 (the bug tracker was much better to use, no  2FA there)

And it got rejected for being against "policy".

**Comment by michaelhkay** [comment]
Sorry about the inconvenience of 2FA, but the vulnerabilities of open source software have become such an issue that it's hardly surprising GitHub are trying to make things more secure.

Your previous 2016 comment was turned down not because it was "against policy", but because it came at the wrong time in the cycle of creating and publishing a spec. You've come up with a lot of good ideas over the years which would probably have made it into the spec if you had been a full participant in the process (knowing when and how to present a proposal that the group will be receptive to is often the key to success). Can I encourage you to join the group? We have a Zoom call for an hour once a week on Tuesdays.

**Comment by ChristianGruen** [comment]
Questions to be answered in the next meeting (or to be dropped, if it takes more than 5–10 minutes):

1. Accept the PR to replace `fn:items-at` with `fn:get` ?
2. Limit the function to single positions (in alignment with `array:get` and `map:get`) ?
3. If `fn:items-at` stays unchanged, add `array:members-at` ?

**Comment by ndw** [comment]
The CG decided to close this issue without further action at [meeting 067](https://qt4cg.org/meeting/minutes/2024/02-27.html).
