### ISSUE TITLE
Placement of fn:in-scope-namespaces(), fn:in-scope-prefixes(), fn:namespace-uri-for-prefix()

### ISSUE THREAD

**Issue by Arithmeticus** [qt4cg/qtspecs#876]
Currently `fn:in-scope-namespaces()`, `fn:in-scope-prefixes()`, and `fn:namespace-uri-for-prefix` are filed under XQFO chapter 10, which purports to deal exclusively with QNames. But these three functions have no direct bearing on QNames in either input or output.

Two options occur to me: 
1. Move sections 10.2.6-8 to fall after 13.3.
2. Rename chapter 10 to "Functions related to QNames and namespaces". Create a 10.3 that pertains exclusively to namespaces. Move to this new subchapter 10.2.4, 10.2.6-8, as well as 13.3 `fn:namespace-uri()` .

Or some variant of the above.

At any rate, I think the current placement doesn't properly expose these functions to the browsing reader.

**Comment by michaelhkay** [comment]
I don't think there is any partitioning of functions that will please everyone. That's why in my reference book I just decided to put them all in alphabetical order.

**Comment by Arithmeticus** [comment]
Although I think this the inconsistency is real and relevant, I am closing the issue until such a time as the CG is inclined to revisit the XQFO structure.
