### ISSUE TITLE
Proposed extension to subsequence

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#878]
Copied from https://github.com/qt4cg/qtspecs/issues/844#issuecomment-1841415417:

-------

I'm thinking again about integrating the items-* quartet into a heavily overloaded `subsequence` function.

Must supply zero or one of:

- $start - the start position
- $from - a predicate, such that the start is the first item to match the predicate
- - defaulting to 1

And zero or one of:

- $length - the number of items to include
- $while - a predicate, the subsequence takes items so long as the predicate is true
- $until - a predicate, the subsequence takes items up to and including the first for which the predicate is false
- - defaulting to the end of the sequence.

This omits the "items-after" combination, but that one is easily achieved using `tail(subsequence(from:="xxx"))`.

**Comment by michaelhkay** [comment]
Yes, I left out the "items-after" combination partly because I don't think it's needed as much as the others, and partly because it's easy to drop the first item of the result if unwanted.

**Comment by michaelhkay** [comment]
This was dropped in favour of the new `subsequence-where()` function.
