### ISSUE TITLE
[XPATH] breaking ancestor or descendant axes

### ISSUE THREAD

**Issue by mricaud** [qt4cg/qtspecs#88]
A common issue that I often have to deal with in Xpath (within xslt most of the time) is to be able to break descendants or ancestors axes. To do that I have to use predicates which are sometimes quite complicated, because it has to appen to every encountered nodes, which force to think really globally. Maybe this is proper to functionnal langages but maybe it would be possible to add simple feature for this common use-case.

An really simple example (no difficult to resolve here, but it's sometimes much more complex) : 

Let's say I want to get all "doc" elements that have a table _as content_ : 

```xml
<doc id="doc1">
  <header/>
  <table/>
  <doc id="doc2">
    <p/>
    <doc id="doc3">
      <table/>
    </doc>
  </doc>
  <footer>
    <doc id="doc4">
      <table/>
    </doc>
  </footer>
</doc>
```

In this example doc1, doc3 and doc4 all have a table "as content", but doc2 doesn't, though it has a table as descendant.

The xpath to get all doc that have a table as content would be something like : 

```
//doc[let $self := . return exists (descendant::table[ancestor::doc[1] is $self])]
```

I don't really have any idea on how to express a new way to break this axis, let's suggest a predicate on the axis itself, something like : 

```
//doc[descendant[break-axis-on-matching='self::doc']::table]
```

This syntax is really not nice, but I guess you see the idea ?
Maybe I missed a way to achieve this in Xpath 3.1 ?

**Comment by yamahito** [comment]
Why not simply:
```
//doc[.//table]
```
Or even:
```
//table/ancestor::doc
```
?

**Comment by mricaud** [comment]
Because it will select doc2 which has no table "as content". Each doc element should break the "filiation", this would be so easy without otherwise ;)

**Comment by davidcarlisle** [comment]
<xsl:value-of select="//doc[.//table except .***@***.***"/>

would give doc1 doc3 doc4

**Comment by yamahito** [comment]
```//table/ancestor::doc[1]```?

**Comment by mricaud** [comment]
Hi David, Hi Thomas, 

Sorry for this late reply, I was not on.

David, I tried your xpath on Oxygen with xpath 3.1, it says it's not valid, I must confess I never seen such strange expressions, is it xpath 4 ?

Thomas, you expression works fine, thought it takes the problem on the other side : 
- the goal was rather to express a predicate on doc 
- one can't use it in a xslt `match` attribute

The use-case here was really simple, but this is a common problem I often faced, maybe I'm the only one ;) ?

**Comment by davidcarlisle** [comment]
On Mon, 6 Sept 2021 at 10:07, Matthieu Ricaud-Dussarget <
***@***.***> wrote:

> Hi David, Hi Thomas,
>
> Sorry for this late reply, I was not on.
>
> David, I tried your xpath on Oxygen with xpath 3.1, it says it's not
> valid, I must confess I never seen such strange expressions, is it xpath 4 ?
>

You mean this?

<xsl:value-of select="//doc[.//table except .***@***.***"/>

That is xpath 2 so certainly valid in 3.1

what part do you find strange?
It selects all doc elements that have a table descendent not counting table
that are within a nested doc, which seemed to match your description of the
desired output?.

If you have this in a function call you would need to select a document
first as the leading // assumes that you have a current item that is in a
document.


Thomas, you expression works fine, thought it takes the problem on the

**Comment by ChristianGruen** [comment]
@mricaud I must confess I haven’t encountered this use case, but an alternative solution could be as follows (it’s similar to your initial solution):

```xquery
//doc[some $doc in .//table/ancestor::doc[1] satisfies $doc is .]
```

**Comment by ChristianGruen** [comment]
> <xsl:value-of select="//doc[.//table except .***@***.***"/>

@davidcarlisle I guess your original XPath expression was distorted, as you added your comment by sending an e-mail. Could you possibly verify the rendering of your comment in the browser?

**Comment by davidcarlisle** [comment]
@ChristianGruen  oops sorry I should know better than to use the email interface for any github comment that has a `@` in it.

I edite the commenst above to refer to the intended construct

```
<xsl:value-of select="//doc[.//table except .//doc//table]/@id"/>
```

**Comment by yamahito** [comment]
If I were to do this as a template match, I might be tempted to use a key:

```
<xsl:key match="table" use="ancestor::doc[1]" name="tablesInDoc"/>
```

I think this can then be used in your match statement:

```
<xsl:template match="doc[key('tablesInDoc', .)]"/>
```

**Comment by mricaud** [comment]
Thanks @ChristianGruen for pointing the rendering problem with @davidcarlisle expression. I can understand it now and yes of course it works fine. It's an elegant solution. 
Your solution works as well @ChristianGruen.

@yamahito, your xslt solution with keys should be quite performant. It gives me only doc1 when I test it, probably because doc1 is the only doc that has a table as direct child. Anyway i'm sure using keys might be a good helper.

Off course one can deal with less or more complex expressions. My point was about:

1. Easy writing especially for more complex cases. You're ideas give me some hints! thanks
2. Performance : looking at ancestors or descendant is really gready especially on big documents. Any of the solutions here are about looking each descendant and filtering afterward. My idea was to avoid such things by "breaking" the axes, i.e stoping iteration when something occurs (encountering a specific element) 
3. Maybe make it easier to deal with such algorithm which would no longer need the developper to thinks globally that means to think about each element conditions to be filtered of not. This is quite common in XSLT, and I find it sometimes difficult where such algorithm could be quite easy with other programming langugages. I'm not sure this is because of functionnal programming, neither rules programming as XSLT is, but rather about how xpath axes are working.

Maybe I close this issue as it didn't really meet other's use-cases? I let it open for now if anyone has other feedbacks, and if I find other more complex cases I'll send it here.

Thanks again all !

**Comment by yamahito** [comment]
> It gives me only doc1 when I test it, probably because doc1 is the only doc that has a table as direct child. 

No, I think it's because you need a `next-match` or `apply-templates` inside of the match template to continue working as descendents, e.g:

```
  
  <xsl:template match="doc[key('tablesInDoc', .)]">
    <xsl:message expand-text="yes">Found key {@id}</xsl:message>
    <xsl:next-match/>
  </xsl:template>
```
Which returns all three relevant docs.

> looking at ancestors or descendant is really gready especially on big documents

Descendant lookups can be really expensive if your processor doesn't use some sort of indexing behind the scenes.  But ancestor lookups are often cheaper; even quite complex documents are rarely as deep as they are wide, if that makes sense?

> Any of the solutions here are about looking each descendant and filtering afterward

Except for the keys based solution :)

Keys FTW! :)

**Comment by mricaud** [comment]
> No, I think it's because you need a next-match or apply-templates inside of the match template to continue working as descendents [...]

All right, I got it ! Works like a charm. Interesting way of linking table and doc in a key. I'm not use to use keys that way.

> Descendant lookups can be really expensive if your processor doesn't use some sort of indexing behind the scenes. But ancestor lookups are often cheaper; even quite complex documents are rarely as deep as they are wide, if that makes sense?

Yes ancestors lookup is cheap but in this issue we are often lead to look each ancestors of each descendant in a way, such lookups are always a bit gready.

Yes index is a solution of course, and keys rocks for this ;) 

But not looking at following nodes (when a stop condition indicates it) should  even be cheaper I guess :)

**Comment by michaelhkay** [comment]
I'm rather bemused by this thread, because the original problem

_get all "doc" elements that have a table as content_

seems to be satisfied by the simple expression 

`//doc[table]`

Now, there certainly are more complex problems that sometimes need to be tackled. But we've got a raft of techniques available including outermost(), innermost(), except, and the proposed "sequence cut-off" functions/operators such as items-until.

For example, if what we want is `//doc[.//table except .//doc//table]`, then we can express it these days using `outermost(//doc)//table`.

If we're going to progress this I think we need some more convincing use cases.

**Comment by yamahito** [comment]
I agree that this isn't a convincing use case, although I think that
`//doc[table]`
won't solve cases where the table is a descendant of the given doc rather than the direct child, which I think is what Matthieu intends, even if that case is not in his example.

**Comment by ChristianGruen** [comment]
@mricaud Do you think we can close the issue?

**Comment by michaelhkay** [comment]
Before we close it, let's try to summarise. Are there use cases here that we could support better?

First, how to cut short a scan of the descendant axis, something like "all the descendant table elements, but not table elements that are within another table element"? We can express that as `//table except //table//table` but that's not easy to optimize. But in 3.1 we can also write `outermost(//table)` which perhaps is easier to optimize (though Saxon could do better here).

Second, how to cut short a scan of the preceding or following axis, e.g. to select preceding nodes within some subtree? We can say `preceding::x intersect ancestor::a//x` but again, it's not easy to optimize. Or you could use a filter: `preceding::x[ancestor::a[1] is $root]`. Again, rather difficult to optimize. Perhaps we could offer a function for this, something like `subtree-selection(preceding::x, ancestor::a[1])` which filters the result of the first argument to select only nodes that are within the subtree rooted at the second argument. That feels easier to optimize. It's a similar design to the XSLT key() function with a third argument to scope the search. If you don't have access to `xsl:number` then it's useful for numbering: `count(subtree-selection(preceding::fig, ancestor::chapter))` counts preceding figures within the current chapter. I think that's worth a proposal.

**Comment by michaelhkay** [comment]
On reflection, I think the second requirement can be met in 4.0 by writing

```
let $root := ancestor::a[1]
return items-before(preceding::x, ->{. << $root})
```

That is, select the nodes on the preceding-axis until the first one that is before `$root` in document order.

**Comment by michaelhkay** [comment]
I think we've established that there's a whole range of tools for handling these requirements including except, outermost, and items-before, and I don't think we've seen any obvious improvements. I'm therefore going to close it with no further action.
