### ISSUE TITLE
Binary map keys

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#886]
We have made `xs:hexBinary` and `xs:base64Binary` comparable and we now allow implicit coercion between the two types.

I've been assuming, though I'm not sure we ever discussed it, that this automatically means that the two types can be "atomic equal" from the point of view of entries in maps: that is, a hexBinary representation of a particular binary value can no longer coexist in a map with a base64Binary representation of the same binary value.

If we were starting from scratch this would clearly make sense, but it has some messy implications:

* It's a backwards incompatibility; in 3.1 you could construct maps that you can no longer construct in 4.0
* It potentially affects interoperability of 3.1 and 4.0 applications. For example, an XQuery 4.0 application invoking an XSLT 3.0 transformation via `fn:transform` might get back a map that's not a valid map in 4.0.

In effect, this is not just a change to the behaviour of one function/operator, it is a data model change, because it changes the value space of the `map(*)` data type.

And more parochially, I freely admit, there's a lot of internal complexity trying to maintain a code base that supports both the 3.1 and 4.0 rules simultaneously.

Is this a feature that benefits users sufficiently to justify the transition complexities? Note that we can still support "eq" between the two data types without supporting `fn:atomic-equal`.

**Comment by michaelhkay** [comment]
>Won't we encounter similar conflicts with xs:string and xs:anyURI? 

No, they already compared equal under the 3.1 op:same-key rules.

**Comment by ndw** [comment]
I'm generally prepared to make implementors work fairly hard, but I think the 3.1 / 4.0 interoperability problem is a pretty compelling argument against this change.

**Comment by ChristianGruen** [comment]
Fixed (see https://github.com/qt4cg/qtspecs/pull/873#issuecomment-1846919967).
