### ISSUE TITLE
Reclassify XPDY0002 as a type error

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#888]
I propose to reclassify XPDY0002 (context item is absent) as a type error rather than a dynamic error.

I don't propose to change the error code.

The only practical distinction is that this will allow the error to be reported statically when it can be detected statically, for example if the user writes something like

```
function($x as node()) {
  starts-with(name(), 'x')
}
```
At present Saxon will give you a compile-time warning for this, followed by a run-time error if the code is actually executed; this is the required behaviour for dynamic errors.

The change does mean that in a case like this example, it will no longer be possible to catch the error using try/catch. However, type errors can only be reported statically if the code is bound to fail at run-time, and catching errors that occur every time is not especially useful.

**Comment by ChristianGruen** [comment]
I wonder if we shouldn’t relax the rules in general, since there are many other cases in which errors can be raised at compile time. Do we have an urgent reason to postpone the error reporting to a later stage?

`XPDY0050` is just one example: It’s easy to detect at compile time that `document { } treat as element(*)` will raise this error. `XQDY0074` is another; I believe there’s no obvious reason why raising an error for `element { ':' } {}` should be delayed until runtime if it’s detected at compile time.

**Comment by benibela** [comment]
>The change does mean that in a case like this example, it will no longer be possible to catch the error using try/catch. 

one could allow try/catch to catch type errors

**Comment by ChristianGruen** [comment]
> one could allow try/catch to catch type errors

I second this. Looking at…

```xquery
(: 1. :) if(true() ) then 'success' else try { 1 + 'a' } catch err:XPTY0004 { 'caught' },
(: 2. :) if(false()) then 'success' else try { 1 + 'a' } catch err:XPTY0004 { 'caught' }
```

…and given that 1. returns `success`, it would certainly be intuitive to get `caught` as a result for 2.

**Comment by michaelhkay** [comment]
Catching type errors is allowed, and makes sense in cases where the processor's type inference isn't strong enough to detect them statically.

The problem with relaxing the rules in general allowing dynamic errors to be reported statically is that it can lead to non-interoperable behaviour. For example, suppose you want to catch data errors in source documents you might write something like

```
try {
  /a/@code cast as xs:integer
} catch x {
  // skip this document and continue with the next one
}
```
Then a processor that uses schema knowledge to detect that the cast will always fail is going to refuse to execute the stylesheet, which isn't helpful because (a) the code as written makes perfect sense, and (b) it will run fine on other processors.

If you allow `element { ':' } {}` to be rejected statically, do you allow `element {$x} {}` to be rejected statically by a processor with smart data flow analysis that can work out that all paths to this code supply invalid values for $x? Even if some of those paths catch the error?

The reason I want to change XPDY0002 is that (a) I think it can very often be detected statically without any smart  data flow analysis, and (b) it's a very common simple typo to write something like `@x` instead of `$input/@x`. Moreover it's detected by the same kinds of mechanisms as type errors: typically type analysis will track the static type of the context item, and one of the possible values for the static type of the context item is "absent".

**Comment by ChristianGruen** [comment]
Thanks for the comprehensive answer. I can see the motivation to change the behavior for `XPDY0002` (and I have no objection against it), but I would be glad if we could look at type errors more generally.

> The problem with relaxing the rules in general allowing dynamic errors to be reported statically is that it can lead to non-interoperable behaviour. 

Isn’t that already the case? For…

```
try { 1 + 'x' } catch * { "caught" }
```

…some processors raise `XPTY0004` and others return `"caught"`. If I read the spec correctly, it’s legal to inline functions statically, so the same applies to code like…

```
try { fn { . + 1 }('x') } catch * { "caught" }
```

…which shouldn’t be treated differently, from a user perspective.

If we think interoperability is an important issue, we should not allow single processors to ignore try/catch. Instead, `1+'x'` could statically be replaced with `error(...)`, and processors with advanced type checks could still statically rewrite `try { error(...) } catch * { "caught" }` to `"caught"`.

If we still want a processor to be able to ignore `try/catch` expressions, it would be intuitive if `if(1) then 1 else 1+'x'` would also raise a static error.

**Comment by michaelhkay** [comment]
This gets back (historically at least) to the topic of strict static typing. Errors are classified as type errors if a processor with strict (i.e. pessimistic) static typing was _required_ to raise the error statically. The theory is that type errors always represent a coding mistake. So although you can catch them with try/catch, it seems that it's bad practice, because type errors should never occur if you write your code properly.

**Comment by michaelhkay** [comment]
On the subject of absent context items, there are a number of test cases like function-lookup-267:

`exists(function-lookup(fn:QName('http://www.w3.org/2005/xpath-functions', 'local-name'), 0))`

and function-literal-267:

`exists(Q{http://www.w3.org/2005/xpath-functions}local-name#0)`

which imply that it is possible to construct a function item that depends on the context item, but in which the bound context item is absent. Such a function item is completely useless because calling it will inevitably fail. Does it really make sense to require the processor to construct a function item whose execution fails, rather than rejecting the attempt to create the function item in the first place?

**Comment by ChristianGruen** [comment]
>

**Comment by ChristianGruen** [comment]
> Does it really make sense to require the processor to construct a function item whose execution fails, rather than rejecting the attempt to create the function item in the first place?

I think this applies to any other construct that will eventually fail if executed, so we shouldn't necessarily relate it to specific errors.

The basic question may be what we believe is more important: Optional checks or interoperability.
