### ISSUE TITLE
Rename "Named Function Reference"

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#889]
The term "named function reference" is used for a construct like `name#1`.

Although we define it as "A named function reference is an expression (written name#arity) which evaluates to a [function item]", the term "named function reference" perpetuates the incorrect assumption that it is some kind of literal or constant denoting a function item.

Of course, in many cases it can be treated as just that. But not when the function is context-dependent, for example name#0 or lang#1.

The term is also questionable because one would assume that a "named function reference" is a reference to a "named function", but there is no such concept as a "named function".

So what might be a better name? What the expression actually does (when evaluated) is to search the static context for a function definition whose name and arity range correspond, and then construct a function item that captures the relevant part of the dynamic context in its closure. It's hard to encapsulate all of that in a simple name for the construct, but I would suggest **named function generator**. This is sufficiently close to the current term to be recognisable, but tries to capture the fact that it's not just a constant or literal, it's an expression that activately does something when evaluated; and it's reasonably accurate in that the result of the evaluation is a function item that has a non-absent name.

**Comment by ChristianGruen** [comment]
+1 for the suggestion to change the name.

Maybe just “function generator” instead of “named function generator”? I never understood what a “named function” was supposed to be, and it’s comforting to hear that there’s no such concept. I assume it was used because `function-name(fn:sum#1)` returns `fn:sum`?

Personally, I’m not so confused about the “reference” part. The term isn’t wrong, it’s just incomplete; and it borrows references from other languages, such as method references in Java. Of course, exactly this could be misleading. I wonder if there are other programming languages that generate context-dependent references?

**Comment by ChristianGruen** [comment]
Another question we could ask: Should the term used describe what the operation **does** or what it **returns**? “Function generator” describes the process of creating the function item; “focus reference” tends to describe the result.

“Partial Function Application” could be discussed as well (for which, by the way, the plural form should be used in the TOC “Partial Function Applications”); “partially applied function” (or even “partial function”) would describe the result and would go hand in hand with, for example, “function call”.

**Comment by dnovatchev** [comment]
> I would suggest **named function generator**. This is sufficiently close to the current term to be recognisable, but tries to capture the fact that it's not just a constant or literal, it's an expression that activately does something when evaluated; and it's reasonably accurate in that the result of the evaluation is a function item that has a non-absent name.

I think that the following would be even more precise:

**named function identifier**

Or why not just:

**function identifier**

Maybe in the future we will have other kinds of function identifiers, too.

**Comment by ChristianGruen** [comment]
> function identifier

I like it.

**Comment by michaelhkay** [comment]
I don't think those terms capture the fact that fn:lang#1, for example, is an expression that needs to be evaluated in the current dynamic context to return a function - it is pretty much equivalent to `fn:lang(?, .)`. It does not identify a function.

**Comment by Arithmeticus** [comment]
How about **function expression**? **Function invocation**?

**Comment by ChristianGruen** [comment]
> How about function expression? Function invocation?

“Function Invocation” could probably be mixed up with “function call” (and the function is not actually invoked by named function references, it’s just wrapped into something that can be invoked/called later on).

We currently have:

Current Name | Example | Alternative Names
--- | --- | ---
Named Function References | `sum#1` | *Named Function Generators*<br/>*Referenced Functions*<br/>*(Enriched) Function References*
Partial Function Applications | `sum(?, -1)` | *Partially Applied Functions*
Inline Function Expressions | `fn($n) { $n + 1 }` | *Inline Functions*
Focus Functions | `fn { . + 1 }` | –

I added *Inline Functions*; otherwise, we should possibly rename *Focus Functions* to *Focus Function Expressions*.

**Comment by dnovatchev** [comment]
I still don't see why "**function identifier**' is considered not suitable.

> I don't think those terms capture the fact that fn:lang#1, for example, is an expression that needs to be evaluated in the current dynamic context to return a function - it is pretty much equivalent to fn:lang(?, .). It does not identify a function.

We don't want to describe in a short name all the actions that take place behind the scenes.

The fact remains is that `fn:someName#simeArity` is the magic value, using which the wanted function is **identified** and located.

**Comment by michaelhkay** [comment]
"Function identifier" has all the problems of "function reference" - we wouldn't call ". + 1" a number identifier or a number reference.

Perhaps "static function lookup expression" fits the bill? It basically does what function-lookup does, only statically.

**Comment by dnovatchev** [comment]
OK, what about:

**function locator**

**Comment by michaelhkay** [comment]
Perhaps **function nominator** since you supply the name, not the location.

**Comment by dnovatchev** [comment]
> Perhaps **function nominator** since you supply the name, not the location.

Regardless of whether we use "function nominator " or "function locator", or any other meaningful phrase, what they still have in common is that the value of this particular non-terminal symbol is what allows us to **_identify_** (meaning select a single one amongst many others) **_the wanted function_**.

Any details of how this is being done behind the scenes are irrelevant to the user, he just provides the string that identifies exactly the function he has in mind.

Thus, once again, all previous comments have strengthened my belief that the most precise term here is **_function-identifier_**.

**Comment by ChristianGruen** [comment]
A criticism about *Function reference* is that it ends with “reference”, with the result not being a reference, but a function. Maybe we should turn the terms around and call it a “Referencing Function”, “Identifying Function” or “Nominating Function”?

I still believe we should have a consistent naming scheme for all expressions that generate functions, and decide whether we want to focus on the process or the result.

**Comment by rhdunn** [comment]
A named function reference `f#n` is equivalent to `f(?, ?, ..., ?)` where `?` occurs n times. So how about something like:
- Complete Function Application
- Full Function Application

for symmetry.

**Comment by ChristianGruen** [comment]
Just for documentation: I learned that a definition for “named function” existed in version 3.1 of XPath: https://www.w3.org/TR/xpath-31/#dt-named-func

**Comment by ChristianGruen** [comment]
Another suggestion: “Named function instance” (but it contains “named” again… It should be read as “instance of a named function”, adhering to the 3.1 definition for named functions).

**Comment by michaelhkay** [comment]
The reason we dropped the term "named function" in 4.0 is because we clarified that the named things in the static context are not functions (function items) but function definitions, each of which corresponds to a family of functions with one name and varying arity. What a "named function reference" actually does is to search the function definitions in the static context for one that has matching name and arity, and then bind the dynamic context as required.

Perhaps "Named Function Binding"?

**Comment by ChristianGruen** [comment]
> Perhaps "Named Function Binding"?

Yes, this sounds good. It seems we won’t get rid of the “named function”, though ;)

**Comment by michaelhkay** [comment]
But you can read it as (Named (Function Binding)).

**Comment by rhdunn** [comment]
So should `f(?, 2)` be considered a function binding as well, instead of a function application?

**Comment by ChristianGruen** [comment]
> So should `f(?, 2)` be considered a function binding as well, instead of a function application?

+1 “Partial function binding” could be a nice fit!

What I also find confusing about “partial function application” is that nothing is actually applied if you use question marks for all arguments (`count(?)` is equivalent to `count#1`).

**Comment by rhdunn** [comment]
How about:
1. `f#2` is a named function binding that is a complete function binding for a function `f` with arity 2, resulting in a dynamic function with arity 2 -- Note: this is equivalent to `f(?, ?)`
2. `f(?, 2)` is a partial function binding for a function `f` with arity 2, resulting in a dynamic function with arity 1
3. `f(?, ?)` is a named function binding that is a complete function binding for a function `f` with arity 2, resulting in a dynamic function with arity 2 -- Note: this is equivalent to `f#2`

We then have a single concept (function binding) that can be complete or partial, and the complete form has a named shorthand.

Note: I'm referencing dynamic functions here to align this with the *Dynamic Function Calls* section of the spec.

**Comment by dnovatchev** [comment]
> How about:
> 
> 1. `f#2` is a named function binding that is a complete function binding for a function `f` with arity 2, resulting in a dynamic function with arity 2 -- Note: this is equivalent to `f(?, ?)`
> 2. `f(?, 2)` is a partial function binding for a function `f` with arity 2, resulting in a dynamic function with arity 1
> 3. `f(?, ?)` is a complete function binding for a function `f` with arity 2, resulting in a dynamic function with arity 2 -- Note: this is equivalent to `f#2`
> 
> We then have a single concept (function binding) that can be complete or partial, and the complete form has a named shorthand.
> 
> Note: I'm referencing dynamic functions here to align this with the _Dynamic Function Calls_ section of the spec.


These are all way worse and completely confusing, than what we have today. 

I as a developer would simply skip over such gibberish wherever I see it.

The original issue as posted by @michaelhkay is about "named function reference" - not about partial application.

I re-read the original issue and it seems that the one and only problem is that at present we don't have a definition for "named function".

If I understand well the problem, I think that most probably what this is equivalent to is: "static (ally defined) -function".
Please, correct me if this is wrong.

**Comment by ChristianGruen** [comment]
> How about:
> 
> 1. `f#2` is a named function binding that is a complete function binding for a function `f` with arity 2, resulting in a dynamic function with arity 2 -- Note: this is equivalent to `f(?, ?)`
> 2. `f(?, 2)` is a partial function binding for a function `f` with arity 2, resulting in a dynamic function with arity 1
> 3. `f(?, ?)` is a complete function binding for a function `f` with arity 2, resulting in a dynamic function with arity 2 -- Note: this is equivalent to `f#2`

Looks good and consistent. Technically, some differences exist between partial function applications and named function references, but from a user perspective, this doesn’t matter, and it would simplify things to present them together.

**Comment by ChristianGruen** [comment]
> I as a developer would simply skip over such gibberish wherever I see it.

I as a reader would simply skip over offensive rhetoric wherever I see it.

**Comment by dnovatchev** [comment]
> How about:
> 
> 1. `f#2` is a named function binding that is a complete function binding for a function `f` with arity 2, resulting in a dynamic function with arity 2 -- Note: this is equivalent to `f(?, ?)`
> 2. `f(?, 2)` is a partial function binding for a function `f` with arity 2, resulting in a dynamic function with arity 1
> 3. `f(?, ?)` is a complete function binding for a function `f` with arity 2, resulting in a dynamic function with arity 2 -- Note: this is equivalent to `f#2`
> 
> We then have a single concept (function binding) that can be complete or partial, and the complete form has a named shorthand.
> 
> Note: I'm referencing dynamic functions here to align this with the _Dynamic Function Calls_ section of the spec.

How would then one call this: **`math:pi#0`**  ?

Do note that **_`math:pi(?)`_** produces an error, because this function accepts no argument.

**Comment by rhdunn** [comment]
> > How about:
> > 
> > 1. `f#2` is a named function binding that is a complete function binding for a function `f` with arity 2, resulting in a dynamic function with arity 2 -- Note: this is equivalent to `f(?, ?)`
> > 2. `f(?, 2)` is a partial function binding for a function `f` with arity 2, resulting in a dynamic function with arity 1
> > 3. `f(?, ?)` is a complete function binding for a function `f` with arity 2, resulting in a dynamic function with arity 2 -- Note: this is equivalent to `f#2`
> > 
> > We then have a single concept (function binding) that can be complete or partial, and the complete form has a named shorthand.
> > Note: I'm referencing dynamic functions here to align this with the _Dynamic Function Calls_ section of the spec.
> 
> How would then one call this: **`math:pi#0`** ?
> 
> Do note that **_`math:pi(?)`_** produces an error, because this function accepts no argument.

- `f#0` is a named function binding that is a complete function binding for a function `f` with arity 0, resulting in a dynamic function with arity 0 -- Note: this has no equivalent using argument placeholders.

Note: This would go between 1 and 2 above.

**Comment by michaelhkay** [comment]
>What I also find confusing about “partial function application” is that nothing is actually applied if you use question marks for all arguments

I can't say that worries me, I'm comfortable with the idea that nothing can be a part of something.

**Comment by michaelhkay** [comment]
I do quite like "partial function binding" as an alternative to "partial function application" because it seems to make it clearer that the result is always a function. I have no problem with the idea that "partial" means any subset of the parameters are bound, which in principle could include none of them or all of them.

**Comment by dnovatchev** [comment]
> A named function reference `f#n` is equivalent to `f(?, ?, ..., ?)` where `?` occurs n times. So how about something like:
> 
> * Complete Function Application
> * Full Function Application
> 
> for symmetry.

Again, this is obviously ambiguous.

If the maximum number of arguments is M and we have   **" `f(?, ?, ..., ?)` where `?` occurs n times"**, there are C(M, N) possible combinations of spreading N '?' (question marks) over M possible places.

And each of these M! / (N! * (M - n)!)  functions is different from the rest.

How can these so many different functions point to just the single function we have in mind?

Please, wake up.

**Comment by rhdunn** [comment]
@dnovatchev  By `f(?, ?, ..., ?)` I meant that as a shorthand for:
1. `f(?)` for an arity 1 function;
2. `f(?, ?)` for an arity 2 function;
3. `f(?, ?, ?)` for an arity 3 function;
4. etc.

I.e. for a named function reference `f#n`, there would be `n` argument placeholders in the partial function application.

Note: Using `...` is a common shorthand in mathematics for enumerating values from 1 to n, e.g. `1, 2, ..., n`.

Please be civil.

**Comment by dnovatchev** [comment]
> @dnovatchev By `f(?, ?, ..., ?)` I meant that as a shorthand for:
> 
> 1. `f(?)` for an arity 1 function;
> 2. `f(?, ?)` for an arity 2 function;
> 3. `f(?, ?, ?)` for an arity 3 function;
> 4. etc.
> 
> I.e. for a named function reference `f#n`, there would be `n` argument placeholders in the partial function application.
> 
> Note: Using `...` is a common shorthand in mathematics for enumerating values from 1 to n, e.g. `1, 2, ..., n`.
> 
> Please be civil.

This cannot cover for overloads that have arguments with different types.

**Comment by ChristianGruen** [comment]
> This cannot cover for overloads that have arguments with different types.

Could you please provide an example?

**Comment by rhdunn** [comment]
See https://qt4cg.org/specifications/xquery-40/xquery-40.html#id-errors:
> __err:XQST0034__
>
> It is a [static error](https://qt4cg.org/specifications/xquery-40/xquery-40.html#dt-static-error) if multiple functions declared or imported by a [module](https://qt4cg.org/specifications/xquery-40/xquery-40.html#dt-module) have the same [expanded QName](https://qt4cg.org/specifications/xquery-40/xquery-40.html#dt-expanded-qname) and overlapping arity ranges (the arity range of a function declaration is M to M+N, where M is the number of required parameters and N is the number of optional parameters).

and https://qt4cg.org/specifications/xquery-40/xquery-40.html#id-user-defined-functions:
> The static context may include more than one declared function with the same name, but their arity ranges must not overlap [[err:XQST0034](https://qt4cg.org/specifications/xquery-40/xquery-40.html#ERRXQST0034)].
>
> __Note:__
>
> A consequence of this rule is that a function declaration must not declare a function that has arity 1 (one) if its name is the same as the name of an imported atomic type, since the name would then clash with the constructor function for that type.

and https://qt4cg.org/specifications/xslt-40/Overview.html#function-overriding-within-package:
> [ERR XTSE0770] It is a [static error](https://qt4cg.org/specifications/xslt-40/Overview.html#dt-static-error) for a [package](https://qt4cg.org/specifications/xslt-40/Overview.html#dt-package) to contain an [xsl:function](https://qt4cg.org/specifications/xslt-40/Overview.html#element-function) declaration F and an [xsl:function](https://qt4cg.org/specifications/xslt-40/Overview.html#element-function) declaration G such that F and G have the same [expanded QName](https://qt4cg.org/specifications/xslt-40/Overview.html#dt-expanded-qname) and the same [import precedence](https://qt4cg.org/specifications/xslt-40/Overview.html#dt-import-precedence), if the [arity ranges](https://qt4cg.org/specifications/xslt-40/Overview.html#dt-arity-range) of F and G overlap in whole or in part, unless F and G are both [eclipsed](https://qt4cg.org/specifications/xslt-40/Overview.html#dt-eclipsed) by another [xsl:function](https://qt4cg.org/specifications/xslt-40/Overview.html#element-function) declaration.

where https://qt4cg.org/specifications/xslt-40/Overview.html#dt-eclipsed:
> [Definition: An [xsl:function](https://qt4cg.org/specifications/xslt-40/Overview.html#element-function) declaration F is said to be eclipsed if the containing package includes an [xsl:function](https://qt4cg.org/specifications/xslt-40/Overview.html#element-function) declaration G such that F and G have the same name, F has lower [import precedence](https://qt4cg.org/specifications/xslt-40/Overview.html#dt-import-precedence) than G, and the [arity range](https://qt4cg.org/specifications/xslt-40/Overview.html#dt-arity-range) of G includes the totality of the arity range of F.]

etc.

**Comment by dnovatchev** [comment]
> > This cannot cover for overloads that have arguments with different types.
> 
> Could you please provide an example?


Here is the simplest possible XSLT example that comes to mind:

```xsl
<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
 xmlns:my="my" xmlns:xs="http://www.w3.org/2001/XMLSchema">
 <xsl:output omit-xml-declaration="yes" indent="yes"/>

  <xsl:template match="/">
    <xsl:sequence select="my:f('Hello', /*)"/>
    <xsl:sequence select="my:f(5)"/>
  </xsl:template>
  
  <xsl:function name="my:f">
   <xsl:param name="p1" as="xs:string"/>
   <xsl:param name="p2" as="node()"/>
   
   <xsl:sequence select="$p1, $p2"/>
  </xsl:function>

  <xsl:function name="my:f">
   <xsl:param name="p1" as="xs:integer"/>
	<xsl:sequence select="2 * $p1"/>
  </xsl:function>
</xsl:stylesheet>
```

Do note that **`my:f#1`** cannot be expressed as a partial application of **`my:f`** (or **`my:f#2`**) because the two overloads of **f** have parameters that are of different types.

Running this transformation with SaxonJ-HE 12.3 on a trivial XML document: `<t/>` produces the correct, expected result:

**`Hello<t/>10`**

Now, trying to express the last overload as a partial application of the 1st overload:

```xsl
<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
 xmlns:my="my" xmlns:xs="http://www.w3.org/2001/XMLSchema">
 <xsl:output omit-xml-declaration="yes" indent="yes"/>

  <xsl:template match="/">
    <xsl:sequence select="my:f('Hello', /*)"/>
    <xsl:sequence select="my:f(5)"/>
    <xsl:sequence select="my:f#2(?, /*)(3)"/>
  </xsl:template>
  
  <xsl:function name="my:f">
   <xsl:param name="p1" as="xs:string"/>
   <xsl:param name="p2" as="node()"/>
   
   <xsl:sequence select="$p1, $p2"/>
  </xsl:function>

  <xsl:function name="my:f">
   <xsl:param name="p1" as="xs:integer"/>
	<xsl:sequence select="2 * $p1"/>
  </xsl:function>
</xsl:stylesheet>
```
Saxon gives us, correctly this error:

"**_Type error on line 5 column 27 of marrowtr.xsl:
  XPTY0004  The required item type of the first argument of partially-applied function
  my:f() is xs:string; the supplied value 3 does not match. The supplied value is of type xs:integer_**"

**Comment by ChristianGruen** [comment]
There must be something you have misunderstood, Dimitre:

> f(?, 2) is a partial function binding for a function f with arity 2, resulting in a dynamic function with arity 1
>
> And as we see from the example above, this isn't at all our `my:f#1` -- it is a completely different function, that has nothing to do with our overload.

That’s correct, you won’t get `my:f#1`. You will get “a dynamic function with arity 1”, just as you’ve quoted.

This has nothing to do with overloading (which exists in other languages, but not in XPath): What you do here is creating a new (partially applied function) that has no relationship to an existing function with a smaller arity. This being said, you can still use partial function applications and named functions references interchangeably:

* `local:f(?, ?)` is the same as `local:f#2`: It uniquely references the 1st function in your XSLT code.
* `local:f(?)` is the same as `local:f#1` (it uniquely references the 2nd function)

Hope this helps.

**Comment by rhdunn** [comment]
In the case where you have `my:f#2(?, /*)`, `my:f#2` is referring to the arity 2 function *not* the arity 1 function.

To break down my:
> f(?, 2) is a partial function binding for a function f with arity 2, resulting in a dynamic function with arity 1

comment...

1. `my:f#2` binds to the arity 2 function:
```xslt
  <xsl:function name="my:f">
   <xsl:param name="p1" as="xs:string"/>
   <xsl:param name="p2" as="node()"/>
   
   <xsl:sequence select="$p1, $p2"/>
  </xsl:function>
```
2. the result is a complete function binding to that function. This result is an arity 2 function item where the arguments map to p1 and p2.
3. the `(?, /*)` partially binds the function item from 2 to create an arity 1 function item, where the first argument (p1) is not specified yet, and p2 is assigned to `/*`. Here, the type of the argument is `xs:string` because the type of `p1` in the arity 2 `my:f` function is `xs:string`.
4. the `(3)` is calling the arity 1 function item with p1 being an `xs:integer` not an `xs:string`, hence the type error. -- This is equivalent to calling `my:f(3, /*)`.

Note that the function application is called currying in Haskell and other computer science literature.

**Comment by dnovatchev** [comment]
> There must be something you have misunderstood, Dimitre:
> 
> > f(?, 2) is a partial function binding for a function f with arity 2, resulting in a dynamic function with arity 1
> > And as we see from the example above, this isn't at all our `my:f#1` -- it is a completely different function, that has nothing to do with our overload.
> 
> That’s correct, you won’t get `my:f#1`. You will get “a dynamic function with arity 1”, just as you’ve quoted.
> 
> This has nothing to do with overloading (which exists in other languages, but not in XPath): What you do here is creating a new (partially applied function) that has no relationship to an existing function with a smaller arity. This being said, you can still use partial function applications and named functions references interchangeably:
> 
> * `local:f(?, ?)` is the same as `local:f#2`: It uniquely references the 1st function in your XSLT code.
> * `local:f(?)` is the same as `local:f#1` (it uniquely references the 2nd function)
> 
> Hope this helps.

I pity the poor user: for a function with 10 arguments, instead of writing just: **f#10**, he will have to write:

**f(?, ?, ?, ?, ?, ?, ?, ?, ?, ?)** and will have to count (maybe 3 times, to be sure) that the number of question marks is really 10.

**Comment by rhdunn** [comment]
You can write either `f#10` *or* `f(?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`. -- There is nothing stopping you in XPath/XQuery 3.1, 4.0, nor what we are proposing from doing either. The changes I wrote were just noting the equivalence in prose. Typically, if you aren't binding any specific parameters you would use `f#10`, but nothing is stopping you from using the other syntax if you wish to.

**Comment by dnovatchev** [comment]
> You can write either `f#10` _or_ `f(?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`. -- There is nothing stopping you in XPath/XQuery 3.1, 4.0, nor what we are proposing from doing either. The changes I wrote were just noting the equivalence in prose. Typically, if you aren't binding any specific parameters you would use `f#10`, but nothing is stopping you from using the other syntax if you wish to.

Surely, but "the other syntax" serves no purpose and has nothing to do with **partial** application because nothing is actually being applied.

But for anyone who really wants to see this done - happy counting of question marks!

**Comment by rhdunn** [comment]
Which is why we are discussing renaming these to all be "function bindings" :),

1. Named Function Reference -> Named Function Binding
2. Partial Function Application -> Partial Function Binding

No need to count question marks! :)

**Comment by dnovatchev** [comment]
> Which is why we are discussing renaming these to all be "function bindings" :),
> 
> 1. Named Function Reference -> Named Function Binding
> 2. Partial Function Application -> Partial Function Binding

**[Partial function application](https://en.wikipedia.org/wiki/Partial_application)** is a well-established concept in functional programming. No attempt to rename it by a small group of people will change this fact.

Such a renaming will need to be reflected in 20 different places in the XPath Spec alone.

Not to speak about the confusion of the user about why the renaming and what caused it. Not to speak about the questions: "why partial function binding" whereas we have actually not a single binding?"

To all such "experimentors": Please, stay clear of renaming well established concepts with very similar and ambiguous phrases, or using very similar phrases for something that is completely different.

To me as a user this would be a totally unexpected, unwarranted and unwanted change. I will be happy living with the term "named function reference" and telling me - the real user, that from now on we will stop calling these "named function references" but will call them "named function bindings" -- **all this has no value at all and only brings questions and confusion**.

It is sad the CG has to spent much of their time on things so unproductive.

**Comment by ChristianGruen** [comment]
> I pity the poor user: for a function with 10 arguments, instead of writing just: f#10, he will have to write: f(?, ?, ?, ?, ?, ?, ?, ?, ?, ?) 

Don't worry, he won't. The syntax doesn't change. One point here is that `sum#1` and `sum(?)` do the same thing, and that there’s no reason to treat them differently.

> It is sad the CG has to spent much of their time on things so unproductive.

It’s a fact of life that members of a group have different priorities; that’s what makes collaboration interesting. If you believe it’s more productive to work on other topics than this one, you are free to push your own GitHub issues forward and trigger new feedback. I’ll be happy to contribute.

**Comment by dnovatchev** [comment]
> Don't worry, he won't. The syntax doesn't change. One point here is that `sum#1` and `sum(?)` do the same thing, and that there’s no reason to treat them differently.

Except for the fact that `sum#1` has (luckily) never before been associated with "binding" but "named function binding" speaks of binding exactly in the case where there is none (no arguments are bound to any values).

**Comment by ChristianGruen** [comment]
> Except for the fact that `sum#1` has (luckily) never before been associated with "binding" but "named function binding" speaks of binding exactly in the case where there is none (no arguments are bound to any values).

Mike has given some reasoning on the name, and how it can be interpreted, further above (https://github.com/qt4cg/qtspecs/issues/889#issuecomment-1860948730 …you'll have read that anyway).

**Comment by dnovatchev** [comment]
> > Except for the fact that `sum#1` has (luckily) never before been associated with "binding" but "named function binding" speaks of binding exactly in the case where there is none (no arguments are bound to any values).
> 
> Mike has given some reasoning on the name, and how it can be interpreted, further above ([#889 (comment)](https://github.com/qt4cg/qtspecs/issues/889#issuecomment-1860948730) …you'll have read that anyway).

As a user of the language I don't care who gave what reasoning, just that this concept is completely unnecessary, brings no value and causes questions/confusion.

**Comment by michaelhkay** [comment]
This simple editorial proposal generated a ridiculous amount of discussion, some of it surprisingly heated. A real bicycle shed issue. Clearly a waste of everyone's time, since the benefits of making the change are very minor. I shall close the issue and try to avoid such things in future.
