### ISSUE TITLE
fn:compare: Support for arbitrary atomic types

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#893]
Inspired by #866:

We should extend `fn:compare` to support arbitrary atomic types. The comparison rules…

* would be unchanged for strings,
* would rely on `fn:numeric-compare` for numbers, and
* would rely on the existing `op:` functions for the remaining types.

For example, the rule for dates would be:

* `0` is returned if `op:date-equal(A, B)` is `true`,
* `-1` is returned if `op:date-less-than(A, B)` is `true`,
* `1` is returned otherwise.

Some types will be rejected (`xs:duration`, `xs:QName`, `xs:NOTATION`, Gregorian types).

In addition, I would vote for making `fn:numeric-compare` and `fn:atomic-equal` private. I don’t see a benefit to expose them; I rather expect people to be confused.

**Comment by michaelhkay** [comment]
We chose to expose `fn:atomic-equal` because it was useful as a callback to functions like `fn:for-each-pair()` and `subsequence-starts-with()` and because the alternatives, like `count(distinct-values($a, $b)) = 1` are horrible.

**Comment by ChristianGruen** [comment]
Accepted and merged (#909).
