### ISSUE TITLE
Errors in forming function items

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#894]
Follow-up to issue #888

There are a number of situations in which error behaviour is insufficiently specified:

- Consider the partial function application `fn:contains(?, 23)`, where the second argument is an integer, not a string. Does the partial application fail, or does it result in a function item that fails when dynamically evaluated? The spec does not say.
- Consider the expression `function-lookup(fn:name, 0`) evaluated when there is no context item in the dynamic context. Does the call on function-lookup fail, or does it return a function item that fails when dynamically evaluated? The spec does not say, though there are numerous test cases in the function-lookup test set that suggest the latter.
- The same is true for the expression `fn:name#0` evaluated when there is no context item in the dynamic context.
- Consider a user-defined function `my:f` with a parameter that has a default value of "."; consider both a function reference `my:f#0` and a partial application `my:f(?)` evaluated when there is no context item. Again, I think the spec is unclear on the error behaviour.

It feels to me that the right thing to do in all these cases is to raise the error early: that is, to fail at the point where a function item is being constructed, not at the point where the function item is subsequently evaluated. However, this disagrees with QT3 expected test results for tests such as `fn-function-lookup-267` and `function-literal-267`.

**Comment by ChristianGruen** [comment]
Minor amendment: It should be `function-lookup(xs:QName('fn:name'), 0)`.

**Comment by ChristianGruen** [comment]
And a possibly minor observation: What about cases in which the context is dynamically supplied?

```
declare context item external;
function-lookup(xs:QName('fn:name'), 0)
```

**Comment by michaelhkay** [comment]
>`function-lookup(xs:QName('fn:name'), 0)`

At the time when `function-lookup()` is evaluated, we know whether there is a context item or not. The question is whether to raise the error then, or to wait until the result returned by `function-lookup()` is evaluated.

**Comment by ChristianGruen** [comment]
> > `function-lookup(xs:QName('fn:name'), 0)`
> 
> At the time when `function-lookup()` is evaluated, we know whether there is a context item or not. The question is whether to raise the error then, or to wait until the result returned by `function-lookup()` is evaluated.

I see; I mixed it up with the suggestion to reclassify `XPDY0002` (which is not discussed here).

Sounds feasible.

**Comment by michaelhkay** [comment]
Reopening to document the consequences: the change is causing a number of tests to fail.

For example, function-literal-001 does

<test>exists(Q{http://www.w3.org/2005/xpath-functions}node-name#0)</test>

and this now fails XPDY0002.

Logically this makes sense. To evaluate the `exists()` function, you have to evaluate its argument, and evaluating the expression `node-name#0` now fails if there is no context item. But it might surprise a few people.

I'm going to propose that we fix the affected tests rather than reverting the change to the spec, but I thought I would reopen the issue to invite review of this decision.

**Comment by michaelhkay** [comment]
Rather than requiring an error or listing alternative results, I've changed the tests so that there is a context item, as I think that reflects the original intent of the tests.

**Comment by ndw** [comment]
The CG agreed to close this issue without further action at [meeting 079](https://qt4cg.org/meeting/minutes/2024/05-28.html).
