### ISSUE TITLE
Parameters with default values: allow empty sequences

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#895]
We need a consistent approach for defining types of optional function arguments. In most current cases, if a function argument is supplied, it must be non-empty:

```xquery
map:get(
  $map       as map(*),
  $key       as xs:anyAtomicType,
  $fallback  as function(xs:anyAtomicType) as item()*  := void#1
) as item()*

fn:starts-with-sequence(
  $input        as item()*,
  $subsequence	as item()*,
  $compare      as function(item(), item()) as xs:boolean  := fn:deep-equal#2
) as xs:boolean
```

In some cases, it’s optional:

```xquery
fn:replace(
  $value        as xs:string?,
  $pattern      as xs:string,
  $replacement  as xs:string?                                                   := (),
  $flags        as xs:string?                                                   := '',
  $action       as (function(xs:untypedAtomic, xs:untypedAtomic*) as item()?)?  := ()
) as xs:string)

(: #874 :)
fn:subsequence(
  $input   as item()*,
  $start   as xs:double?                                     := (),
  $length  as xs:double?                                     := (),
  $from    as (function(item(), xs:integer) as xs:boolean)?  := (),
  $while   as (function(item(), xs:integer) as xs:boolean)?  := (),
  $until   as (function(item(), xs:integer) as xs:boolean)?  := ()
) as item()*
```

As a result, `map:get($map, fallback := ())` is invalid, while `replace($string, $pattern, action := ())`  would be valid.

I think it’s better to enforce non-empty arguments (provided that a single item is expected).

**Comment by michaelhkay** [comment]
It's not just function arguments, it's any argument that can be omitted because there's an explicit or implicit default. For example the `$options` argument of `parse-json()` has a default value of `map{}`, but it doesn't allow an empty sequence to be supplied. The principle should probably be that if an argument can be omitted, then setting it to an empty sequence has the same effect.

**Comment by ChristianGruen** [comment]
> It's not just function arguments, it's any argument that can be omitted because there's an explicit or implicit default. For example the `$options` argument of `parse-json()` has a default value of `map{}`, but it doesn't allow an empty sequence to be supplied. The principle should probably be that if an argument can be omitted, then setting it to an empty sequence has the same effect.

Yes, I only considered function arguments in this issue. The reason was that functions exist (probably not many) that deliver a different result if an empty sequence is provided (see `fn:sum((), ())` vs `fn:sum(())`).

However, we could regard these as exceptions to the principle.
