### ISSUE TITLE
Drop the requirement for document-uri() uniqueness

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#898]
The specification of document-uri() states that the returned URI must be useable as input to the doc() function and that it always round-trips, so `doc(document-uri($X)) is $X` is guaranteed true.

A consequence of this rule is that you can't have two documents in the same execution scope with the same document-uri() property.

Enforcing this rule causes a lot of trouble. For example at the API level, the user can set two stylesheet or query parameters to two different documents that are associated with the same URI. Another example, two XSLT packages in the same stylesheet can call doc() on the same URI and get different documents back because they have set different validation and whitespace-stripping options. Use of `fn:transform()` causes further complications when documents are passed across the boundary (in fact that's where we first encountered the problem). And `collection()` brings further complications.

In order to conform to the rule in the spec, we changed Saxon a while back so the only documents that are guaranteed to have a document-uri() property are those that were read using the doc() function - and even then, things like validation and whitespace variations are troublesome. This causes users much confusion, partly, because of the change from earlier Saxon releases, but more because there are many situations where they would expect document-uri() to give a useful result and it doesn't.

I think we can fix this simply by removing the guarantee. That will cause less inconvenience to users than the current rule. We could perhaps modify it to say that in the case of a document returned from the doc() function, its document-uri() property will be such that a call to doc() with that URI will return the same document, but in the case of documents derived from other sources (for example `collection()`, or a result from `fn:transform`) there is no such guarantee.

**Comment by gimsieke** [comment]
This will indeed be a relief.

**Comment by ChristianGruen** [comment]
Sounds good.

**Comment by ndw** [comment]
I don't know what new problems will arise if we make this change, but I embrace them without reservation. The current situation is awful. In environments like XProc it's damned near paralyzing.

**Comment by michaelhkay** [comment]
Let's look at what we actually say:

> In the case of a document node $D returned by the [fn:doc] function, or a document node at the root of a tree containing a node returned by the [fn:collection] function, it will always be true that either fn:document-uri($D) returns the empty sequence, or that the following expression is true: fn:doc(fn:document-uri($D)) is $D. It is [·implementation-defined·] whether this guarantee also holds for document nodes obtained by other means, for example a document node passed as the initial context node of a query or transformation.
> 
> A consequence of these rules is that it is not possible (within the execution scope of a transformation) for two different documents to have the same value for their document-uri property. This means that in situations where URI stability is not guaranteed (for example, with streamed input documents in XSLT, or for documents returned by [fn:collection] if document stability has been disabled), the document-uri property should be absent, and fn:document-uri should return an empty sequence.

These are notes, so presumably these statements are considered to be consequences of rules stated normatively elsewhere. 

Now, it seems to me that the second paragraph, where it states "A consequence of these rules is that it is not possible (within the execution scope of a transformation) for two different documents to have the same value for their document-uri property." is plain incorrect. This is _not_ a consequence of the rule in the first paragraph (which places no constraints on the URIs of documents other than those returned by `doc()` or `collection()`), nor of any other rules I can find.

What about the first paragraph?

The XDM spec doesn't place any constraints, it merely says:

> The [dm:document-uri] accessor returns the absolute URI of the resource from which the document node was constructed, if the absolute URI is available. If there is no URI available, or if it cannot be made absolute when the document node is constructed, or if it is used on a node other than a document node, the empty sequence is returned.

The XPath spec (§2.2.2, Dynamic Context, Available Documents) makes the following statement:

> If there are one or more URIs in [available documents] that map to a document node D, then the document-uri property of D must either be absent, or must be one of these URIs.

However, this is a statement about the dynamic context, and the dynamic context by definition can vary. In particular, in XSLT, the "mapping from URIs to document nodes" is affected by `<xsl:strip-space>` declarations, which can vary from one package to another, so the result of calling `doc(U)` in one package may be different from the result of the same call in a different package; yet we would expect both documents to have the same document-uri property.

If you call doc(U) in one package that preserves whitespace you will get a document D0 with the whitespace present, and document-uri(D0) will be U. If you call doc(U) in another package that strips whitespace you will get a document D1 with the whitespace absent, and document-uri(D1) will be U. This does not actually violate the constraint stated in §2.2.2. What it does mean is that the statement in the first paragraph of the F+O notes ("the following expression is true: fn:doc(fn:document-uri($D)) is $D") applies only if the call to fn:doc() happens in the same dynamic context as the original call that produced $D in the first place.

So I think we can fix this issue by changing only non-normative text.
