### ISSUE TITLE
name of map:substitute

### ISSUE THREAD

**Issue by benibela** [qt4cg/qtspecs#91]
[map:substitute](https://qt4cg.org/branch/master/xpath-functions-40/Overview-diff.html#func-map-substitute) is a weird name for the function. It sounds as it would change just one value with a new value like map:put

Actually it is mapping all values. `map:map` or `map:map-values` would be more fitting

Or `map:for-each` would have been logical.  Unfortunately it is already taken. `fn:for-each` takes a sequence and returns a sequence, `array:for-each` takes an array and returns an array. `map:for-each` takes a map and returns a ~map~ sequence. makes no sense. Anyways, `map:for-each-value` would also be a good name

[Other languages](https://en.wikipedia.org/wiki/Map_(higher-order_function)#Language_comparison) have other names. It could also be called  `map:transform` like C++, or `map:apply` like pari/gp

**Comment by yamahito** [comment]
I think the danger with map:for-each-value is that confusion may arrive with the ‘value’ of nodes.

Similarly map:transform would be a bit close to comfort to fn:transform.

I like map:apply, but I don’t think any of the others are any better!

_________________
Tomos Hillman
Evolved Binary
+44 7793 242058

**Comment by ChristianGruen** [comment]
I agree with Benito that it’s not obvious what will be substituted in the map. In particular, it may be confusing as the function takes both the key and value of the current entry.

As maps have keys and values, what about `map:replace-values`?

**Comment by benibela** [comment]
> As maps have keys and values, what about `map:replace-values`?


That might be confused with fn:replace

**Comment by ChristianGruen** [comment]
I’ve assigned »Propose for V4.0« for this issues. It seems that `map:substitute` has been added to the spec before the QT4 meetings, so I think we should accept it formally (no matter if we want to keep it this way or another).

**Comment by ChristianGruen** [comment]
I’m closing this in favor of #583.
