### ISSUE TITLE
XQFO: under/unused variable apparatus

### ISSUE THREAD

**Issue by Arithmeticus** [qt4cg/qtspecs#913]
In the preamble of XQFO chap. 13, several paragraphs are spent introducing a tree structure example, defining variables `$po`, `$item1`, `$item2`, and `$item3`. The prose leads the reader to expect frequent invocation of this tree example, but chap. 13 never uses it.  

Chapter 13's tree example is referred to (sans link) and summarized in the preamble of chap. 14. In that chapter it is used only once, in a `fn:count` example that really doesn't rely upon anything special in the tree example.

Variables `$item1` and `$item2` are invoked only once more: in chap. 4, for `fn:number`. It's rather out of the blue, because neither the function definition nor chapter 4's preamble say anything about what the variables mean.

My recommendation is to drop this material all together, and for the functions `fn:count` and `fn:number` replace the examples with simpler examples. 

OTOH, I might have come across an incomplete implementation, and the editors might prefer to make more thorough use of this tree example. I don't know.

**Comment by michaelhkay** [comment]
Indeed, this was already messy in the 2.0 spec; it has been changed since, but not improved.

**Comment by Arithmeticus** [comment]
I neglected to mention another argument in favor of keeping the tree example. Most functions in chapter 13 lack examples, and `$po` could be put to work. Unless we think that the behavior of the functions `fn:name`, `fn:local-name`, `fn:namespace-uri` are patently obvious so as not to need any examples. I don't have druthers, and look to the editors for guidance.
