### ISSUE TITLE
Should predicate callbacks use EBV?

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#919]
Currently predicate callback functions used by things like fn:filter have to return a boolean; they can't rely on EBV semantics. For example you have to write `fn{boolean(self::p)}` rather than `fn{self::p}`.

It's probably with `self` tests that this is most noticeable, because self is so often used in a boolean context.

Of course the current rule gives stricter type-checking which will presumably catch some user errors. But it seems an unnecessary inconsistency.

**Comment by ChristianGruen** [comment]
+1 (I remember suggesting this in the past, but I cannot remember what concerns were raised).

**Comment by ChristianGruen** [comment]
PR #1003 was discarded.
