### ISSUE TITLE
map:values() - Would it be better to return an array?

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#929]
The new function `map:values()` returns the values present in a map, flattened into a sequence.

This loses information if the values are not all singletons.

Would it be better to return an array?

That is, to return `array:build(map:pairs($map), fn{?value}))`

**Comment by ChristianGruen** [comment]
I would prefer to stick with the current result format. The motivation for proposing and adding this function was too have an equivalent solution for the often used, but somewhat cryptic `$input?*` syntax (it was repeatedly requested by users in the past). The same applies to `array:values`.

**Comment by michaelhkay** [comment]
OK, I will drop this.
