### ISSUE TITLE
Remove fn:numeric-compare

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#939]
Related action: [QT4CG-060-04](https://qt4cg.org/meeting/minutes/2024/01-09.html)

@michaelhkay I proposed to merge `fn:numeric-compare` into `fn:compare` in #866; your response was:

> Folding fn:numeric-compare into fn:compare is more feasible, but you've then got one function that does two different jobs; there's no type safety to ensure that the arguments have compatible types, and you need ad-hoc rules to say which combinations of arguments are valid and which aren't. The merit of two separate functions is that each is a total function over the domain implied by its signature.

Do you think the concerns are still relevant, or should we tackle this?

**Comment by michaelhkay** [comment]
If we're having a single compare function that handles all types, then I think there's no merit in having separate functions for different types alongside it.

We can dream about generics allowing us to define signatures more precisely: `filter($x as item<K>*, $predicate as function(K) as boolean) as item<K>*`.
