### ISSUE TITLE
Errors in forming function items (continued)

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#963]
In #894, the following rule was added to the definition of **Named Function References**:

> An error is raised if the identified function depends on components of the static or dynamic context that are not present, or that have unsuitable values. […] `DC0001` is raised for the call `fn:id#1` if the context item is not a node in a tree that is rooted at a document node.

We should be consistent and add this rule to **Partial Function Applications** and **Inline Function Expressions** as well. Perhaps such rules could be defined just once for all affected function item constructors in the parent section?

Also, the error code doesn’t seem to be properly defined in the spec, it shows `[ERROR errorref DC0001 NOT FOUND]` (maybe that’s intentional at this editing stage.)

**Comment by michaelhkay** [comment]
I can't see any situation in which this could arise for inline function expressions.

For partial function applications it's a little harder to find examples. Functions like fn:name are only context dependent in their arity-0 version, and partial application of an arity-0 function is not possible. If we look at fn:id:

* fn:id(?, ?) has no context dependency
* fn:id(?, $node) has no context dependency
* fn:id(?) is bound to the context item, and the rules should be the same as fn:id#1. That's a "partial" application only in name...

I can't find an example of a system function where a "strictly partial" function application (i.e. one that supplies some parameters and not others) can depend on parts of the dynamic context that are absent. But we can add the rule anyway...

What about user functions? A user function can depend on the dynamic context only through default values of parameters. Consider `f(x, y, z:= .)` and the partial application `f(x, ?)`. In this case, I think a context dependency can arise only while evaluating the default value of $z. We say that evaluating the partial function application causes evaluation of the default value expression, and I think it's implicit that if evaluating the default value expression fails, then the PFA itself fails. So I think this case is covered.

**Comment by ChristianGruen** [comment]
> * fn:id(?) is bound to the context item, and the rules should be the same as fn:id#1. That's a "partial" application only in name...

Exactly, that's the case I had in mind (in principle, we could have more in the future). As long as we call this construct “partial function application” (alternatives were discussed in #889), we should probably address this case in the spec.

> I can't see any situation in which this could arise for inline function expressions.

I had thought of queries like `fn() { name() }()`, which are equivalent to `fn:name#0` (if there’s no context value), and which can be rewritten to the same internal representation by a processor.

Maybe we can raise the same error code in both cases, and it can be up to the implementation to decide where/when this error is raised.

**Comment by michaelhkay** [comment]
I had thought of queries like `fn() { name() }()`, which are equivalent to `fn:name#0` (if there’s no context value), and which can be rewritten to the same internal representation by a processor.

I think that one falls within issue #888. Currently the call on `name()` is a dynamic error which can only be raised if the function is actually called; the proposal in #888 is to change it to a type error which can be raised statically if the processor does enough static type checking to work out that there will be no context item here.
