### ISSUE TITLE
fn:reduce (or fn:fold without initial value)

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#983]
Various languages (Kotlin, F#, Haskell, Rust, Scala, others) offer two functions for what we summarize as folds: one that accepts an initial value and another one that consumes the first item of the input as initial value. The first function is usually called `fold`, the latter is called `reduce`, but some languages (like JavaScript) pack the functionality into a single function.

We have the same options:

1. We could tweak `fn:fold-left` and `fn:fold-right` in a way that the `zero` argument is ignored if it’s not explicitly supplied:

```xquery
fold-left(1 to 5, action := op('*'))
```

However, the behavior would then differ from `fold-left(1 to 5, (), action := op('*'))`, which is something we tried to avoid in more recent functions (there are functions like `fn:name`, though, that behave similarly: `fn:name(())` and `fn:name()` does something different).

2. We could also introduce a separate function `fn:reduce` (or 2 variants, resp. 4 if we include arrays):

```xquery
fn:reduce(
  $input   as item()*,
  $action  as function(item()*, item()) as item()*
) as item()*
```

This would allow us to do  `reduce(1 to 5, op('*'))`, and for some people, a reduce function will be more familiar than a fold.

On Wikipedia, there’s a good summary on [folds in various languages](https://en.wikipedia.org/wiki/Fold_(higher-order_function)#In_various_languages).

**Comment by michaelhkay** [comment]
I think that users who are sophisticated enough to be using fold/reduce functions have sufficient brain power to implement this for themselves.

**Comment by ChristianGruen** [comment]
> I think that users who are sophisticated enough to be using fold/reduce functions have sufficient brain power to implement this for themselves.

I’m not so sure about this. I would rather assume that it’s more obvious how to rewrite `reduce` to `fold`. `reduce`  allows you to get rid of special-casing around the initial action (providing an empty sequence, or the identity element – 0 for additions, 1 for multiplications – is not always sufficient). I’m just not sure if it’s a good idea to bloat the spec with 4 new functions for every higher-order feature we add, which can possibly be processed from left-to-right and right-to-left, and run for sequences or arrays.

> I prefer an explicit named fold and reduce...I tend not to like overloaded functions, because typos type check and its a nightmare to find the error.
> …
> What happens if the sequence over which you reduce is empty is the other issue?

Out of interest, as you’re most probably the one among us who’s most proficient in F#, are the following versions for F# correct, or would you write them differently?

```F#
List.fold   (fun acc x -> acc * x) 0 [1..5]
List.reduce (fun acc x -> acc * x) [1..5]
```

In Kotlin, I assume the syntax would be similar:

```Kotlin
(1..5).fold(0) { acc, x -> acc * x }
(1..5).reduce { acc, x -> acc * x }
```

**Comment by MarkNicholls** [comment]
@ChristianGruen 

yes....you would write

`List.fold (*) 1 [1..5]
`
just be be fancy and show off to your C# mates

my kotlins too rusty to comment,

(and to be fair, reduce is pretty obvious to derive from fold...so maybe its gold plating)

**Comment by ChristianGruen** [comment]
> `List.fold (*) 1 [1..5] ` just be be fancy and show off to your C# mates

;-) Thanks. In XPath, we now also have:

```xquery
fold-left(1 to 5, 1, op('*'))
```

**Comment by ndw** [comment]
The CG agreed to close this issue without further action at [meeting 072](https://qt4cg.org/meeting/minutes/2024/04-09.html#close-without-action)
