### ISSUE TITLE
character sequence constructor 'a' to 'z'

### ISSUE THREAD

**Issue by liamquin** [qt4cg/qtspecs#989]
Although you can write 'a' to 'z' as
```xpath
   (string-to-codepoints('a') to string-to-codepoints('z') ! codepoints-to-string()
```
i’m not sure this is easily discoverable.

Note, 'a' to 'z' is obviously dependent on the current collation - if you're using EBCDIC may the dogs help you. I’m assuming, however, any two Unicode characters could appear in the string literals, and it’d be an error to have more than one character in either string.

This means 'ċ' to 'ŗ’ would be an error, not equivalent to 'c' to 'r' (taking the first character of each string), since those are not precomposed forms.

Mostly, i tend to write this because of other languages - e.g. Perl has 'a' .. 'ÿ' or whatever, as does Ruby.

ICU in Python has UnicodeSet('[[:Ll:]&[:Latin:]]') which is powerful but grokhard (& here is intersect i think).

Although 'a' to 'z' is probably what i've seen & used most often, 'a' to 'f' and '0' to '9' are also obvious candidates.

**Comment by Arithmeticus** [comment]
Why not simply 4.0's `fn:characters("abcdefghijklmnopqrstuvwxyz")`? Highly customizable, and transparent.

**Comment by ChristianGruen** [comment]
In addition, we could allow both integers and strings as argument for `fn:char`, to be able to write…

```xquery
 (65 to 90) ! fn:char(.)
```

Otherwise, people may be tempted to write…

```xquery
 (65 to 90) ! fn:char(`#{ . }`)
```

**Comment by michaelhkay** [comment]
Yes, allowing an integer argument to fn:char seems reasonable.

**Comment by dnovatchev** [comment]
Just out of curiosity: Can we cast a string to a sequence (or an array) of single-character strings?

In C# a string is also an array of its characters and one simply writes `myString[3]` without any casts and this produces (a Char) the 4-th character of `myString`.

This is very convenient and it would be great to have something similar in XPath. 

Maybe we could introduce a **`char`** type in XPath?

**Comment by Arithmeticus** [comment]
@dnovatchev see, new in 4.0, [fn:characters](https://qt4cg.org/specifications/xpath-functions-40/Overview.html#func-characters)

**Comment by michaelhkay** [comment]
We introduced the `fn:characters()` function to allow a string to be treated as a sequence of characters. Implicit casting to a sequence wouldn't work because a string is already a sequence of length 1.

**Comment by michaelhkay** [comment]
>i’m not sure this is easily discoverable.

Making features "discoverable" is not something the specifications can do on their own; and there is always a problem that the more features we pack into the language, the harder it is for users to discover that they exist. We can do a fair bit by presenting examples of use cases, but in the end, the languages specs are a specification, not a user guide.

**Comment by dnovatchev** [comment]
> We introduced the `fn:characters()` function to allow a string to be treated as a sequence of characters. Implicit casting to a sequence wouldn't work because a string is already a sequence of length 1.

Yes, but what I am proposing is not "implicit casting to a sequence".

It is implicit **_casting to an array_**.

We could even decide not to define such casting at all, just simply say that:

**`"abcdefgh"[3]`** is a shorthand for:

`subsring("abcdefgh", 3, 1)`

This is extremely nice and convenient - proven by my experience.

**Comment by michaelhkay** [comment]
>"abcdefgh"[3]

This expression, unfortunately, is legal since XPath 2.0, and returns an empty sequence.

**Comment by dnovatchev** [comment]
> > "abcdefgh"[3]
> 
> This expression, unfortunately, is legal since XPath 2.0, and returns an empty sequence.
> 
> A potentially viable alternative is to allow
> 
> ```
> "abcde"[1 ...]
> "abcde"[2 ... 4]
> "abcde"[3 ... 3]
> "abcde"[... 3]
> ```

I think we could do even better:

**"abcd(3)"**

**Comment by ChristianGruen** [comment]
> **"abcd(3)"**

Probably `"abcd"(3)` ?
 
> **`"abcde"[2 ... 4]`**

What would `(1 to 3, "abcde")[2 ... 4]` yield?

**Comment by dnovatchev** [comment]
> > **"abcd(3)"**
> 
> Probably `"abcd"(3)` ?
> 

Yes, thanks for catching this. Corrected in the referred-to comment.

> > **`"abcde"[2 ... 4]`**
> 
> What would `(1 to 3, "abcde")[2 ... 4]` yield?

`2, "abcde"`

**Comment by ChristianGruen** [comment]
> > What would `(1 to 3, "abcde")[2 ... 4]` yield?
> 
> `2, "abcde"`

Thanks. What would be the rules that lead to this result?

**Comment by dnovatchev** [comment]
> > > What would `(1 to 3, "abcde")[2 ... 4]` yield?
> > 
> > 
> > `2, "abcde"`
> 
> Thanks. What would be the rules that lead to this result?

Sorry again. The result should be:

 `2, 3, "abcde"`
 
 The rules are that we have the sequence:
 
 `(1, 2, 3, "abcde")`
 
 And the deconstructor `[2 ... 4]` selects its subsequence starting with the second item and ending at the 4th item.

**Comment by dnovatchev** [comment]
> > And the deconstructor `[2 ... 4]` selects its subsequence starting with the second item and ending at the 4th item.
> 
> Would `("abcde", 1 to 3)[2 ... 4]` return `1, 2, 3` or `"b", "c", "d"`?

`1, 2, 3`

**Comment by michaelhkay** [comment]
Perhaps what we're searching for is a syntax like

`$value[# RANGE #]`

where

(a) If $value is an array, it operates on the array; if it is a string, it operates on the string; if it is a sequence (that is, any other sequence), it operates on the sequence.

(b) The syntax of RANGE allows us to select at least (i) any single item, (ii) any contiguous subsequence, (iii) any set of single items.

**Comment by ChristianGruen** [comment]
```xquery
$value[# RANGE #]
```

I assume it wouldn't be much shorter than

```xquery
items-at($value, RANGE)   (: or :)
RANGE ! get($value, .)
```

Personally, I’d still be in favor of having `$value[RANGE]`.

**Comment by dnovatchev** [comment]
> Perhaps what we're searching for is a syntax like
> 
> `$value[# RANGE #]`

Could be even:

**`   $value # RANGE #`**

or

**`   $value <- RANGE`**

**Comment by michaelhkay** [comment]
This digressed into a discussion of using operators such as [] to slice into a string. That's beyond the scope of the original issue. Having introduced char() taking a numeric argument, I don't think there's any further obvious improvement on the table, so I propose closing the issue with no further action.

**Comment by ndw** [comment]
The CG agreed to close this issue without action at [meeting 065](https://qt4cg.org//meeting/minutes/2024/02-13.html)
