### ISSUE TITLE
Invoking maps & arrays: allow sequences?

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#994]
Can’t we support integer sequences as arguments in dynamic function calls on maps and arrays?

The following query is already valid…

```xquery
[ 3, 4, 5 ] ? (2, 1)
```

…but the number of users who are able to decode this syntax is very limited. It would be easier to allow:

```xquery
[ 3, 4, 5 ](2, 1)
```

I would expect the results to be returned in the supplied order (`4` and `3`).

**Comment by michaelhkay** [comment]
>`[ 3, 4, 5 ](2, 1)`

Did you mean that, or did you mean

`[ 3, 4, 5 ]((2, 1))`

Do you want it to be a variadic function with a variable number of arguments, or a function that takes an integer sequence as a single argument?

**Comment by ChristianGruen** [comment]
Glad you ask this question; it was mine as well:

* From the non-expert user perspective (not knowing the fundamental details between lookups and function calls), the variadic variant would be more intuitive, ideally with a flattened result over the result of all arguments. 
* From the implementor perspective, a single argument would be easier to realize – and it would be less invasive, as it would allow us to introduce additional parameters in the future.

**Comment by michaelhkay** [comment]
In general we made a decision in principle that functions should not do implicit mapping over their arguments. You can argue that `map:get($map, $key)` should do implicit mapping if $key is a sequence of keys, but you can equally argue that it should do implicit mapping if $map is a sequence of maps. So I suggest we don't do this.

As for `$map($key)` if we allow $key to be a sequence here then we have to revise the complex rules for the implicit type of the map as a function and therefore the subsumption rules for maps, which is a swamp I would rather not revisit.

**Comment by ndw** [comment]
The CG agreed to close this issue without action at [meeting 065](https://qt4cg.org//meeting/minutes/2024/02-13.html)
